var topic = "<!-- saved from url=(0024)http://docs.autodesk.com -->\n\
<html>\n\
   <head><script src=\"../scripts/yepnope.1.5.4-min.js\" type=\"text/javascript\"></script><script src=\"../scripts/lib/jquery-1.11.1.min.js\" type=\"text/javascript\"></script><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"><meta name=\"product\" content=\"MOBPRO\"><meta name=\"release\" content=\"2018\"><meta name=\"book\" content=\"GeneralUser\"><meta name=\"created\" content=\"2017-09-08\"><meta name=\"topicid\" content=\"GUID-02FA7DD3-6C7A-4C6A-B7BC-824765AE1CB2\"><meta name=\"topic-type\" content=\"concept\">\n\
      <title>QXmlStreamNotationDeclaration Class Reference</title>\n\
   \n\
\n\
</head>\n\
   <body height=\"100%\"><div class=\"body_content\" id=\"body-content\"><link rel=\"stylesheet\" type=\"text/css\" href=\"cpp_ref/navtree.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"cpp_ref/doxygen.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"cpp_ref/tabs.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"style/adsk.cpm.css\"><script language=\"javascript\">var index = \'index.html\';</script><script>$(document).ready(function() { yepnope.injectJs(\"./scripts/ac_common.js\"); });</script><script type=\"text/javascript\">\n\
var tocSystemNeedsToBeLoaded = typeof(cpp_ref_adsk_ref_toc) == \'undefined\';\n\
var weAreIn21 = $(\'div#main.view-active\').length;\n\
var tocPrefix = \'\';\n\
if (weAreIn21)\n\
{ tocPrefix = \'cpp_ref/\'; }\n\
function cpp_ref_initializeToc(forceTrigger) {\n\
    cpp_ref_adsk_ref_toc.initResizable();\n\
    cpp_ref_adsk_ref_toc.initNavTree(\'class_q_xml_stream_notation_declaration.html\', tocPrefix);\n\
    dQuery(document).trigger(\'toc_initialized\');\n\
}\n\
if (tocSystemNeedsToBeLoaded)\n\
{\n\
	yepnope([{\n\
	load:[tocPrefix + \'json3.min.js\', tocPrefix + \'jquery.js\', tocPrefix + \'ref-toc-controller.js\', tocPrefix + \'dynsections.js\'],\n\
	complete: function() {\n\
	  if (typeof(dQuery) == \'undefined\')\n\
	  {\n\
	    dQuery = jQuery.noConflict(true);\n\
	  }\n\
	  else { jQuery.noConflict(true); }\n\
	  $(document).ready(cpp_ref_initializeToc);\n\
	}\n\
 	}])\n\
}\n\
if (!weAreIn21) { // if in AKN...\n\
$(window).load( function() {\n\
    setTimeout( function() {\n\
        var content = $(\'body > div\').not(\'#body-content\');     // take any divs under body that are not id=body-content\n\
        content.each( function() { \n\
            $(this).css( { \'padding-left\': $(this).css(\'margin-left\') } );       // and if they have any padding-left already, move it to margin-left.\n\
        } );\n\
        var width = cpp_ref_adsk_ref_toc.readFromStorage(\'width\');\n\
        content.css({marginLeft:parseInt(width)+6+\"px\"});\n\
    }, 100);\n\
} ); \n\
}\n\
</script><script>$(\"div#WidgetFloaterPanels,link[href*=\'microsofttranslator.com\'],script[src*=\'microsofttranslator.com\'],script[src*=\'bing.com\']\").remove();</script><script type=\'text/javascript\'>$(\"div#navigation,div#breadcrumbs,div#banner\").attr(\"translate\",\"no\"); var mtLocation = ((location && location.href && location.href.indexOf(\'https\') == 0)?\'https://ssl.microsofttranslator.com\':\'http://www.microsofttranslator.com\')+\'/ajax/v3/WidgetV3.ashx?ctf=True&ui=true&settings=Manual&from=en&hidelanguages=\'; yepnope.injectJs(mtLocation, function() {}, { charset:\'utf-8\', type:\'text/javascript\' } );</script><script>\n\
 if (!tocSystemNeedsToBeLoaded) { cpp_ref_initializeToc(); }\n\
 </script><!-- begin MT -->\n\
            \n\
            <div id=\'MicrosoftTranslatorWidget\' class=\'Dark\' style=\'float:right;z-index:100;color:white;background-color:#bbbbbb;height:58px;overflow:hidden\'></div>\n\
      <div>\n\
         <div class=\"head\">\n\
            <h1>QXmlStreamNotationDeclaration Class Reference</h1>\n\
         </div>\n\
\n\
    <div id=\"top\"><!-- Generated by Doxygen 1.8.10 -->\n\
  <div id=\"navrow1\" class=\"tabs\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./cpp_ref/index.html\"><span>Main&#160;Page</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/pages.html\"><span>Topics</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/modules.html\"><span>Modules</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/namespaces.html\"><span>Namespaces</span></a></li>\n\
      <li class=\"current\"><a href=\"#!/url=./cpp_ref/annotated.html\"><span>Classes</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/files.html\"><span>Files</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/examples.html\"><span>Examples</span></a></li>\n\
    </ul>\n\
  </div>\n\
  <div id=\"navrow2\" class=\"tabs2\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./cpp_ref/annotated.html\"><span>Class&#160;List</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/hierarchy.html\"><span>Class&#160;Hierarchy</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/functions.html\"><span>Class&#160;Members</span></a></li>\n\
    </ul>\n\
  </div>\n\
</div><!-- top -->\n\
<div id=\"side-nav\" class=\"ui-resizable side-nav-resizable\">\n\
  <div id=\"nav-tree\">\n\
    <div id=\"nav-tree-contents\">\n\
      <div id=\"nav-sync\" class=\"sync\"></div>\n\
    </div>\n\
  </div>\n\
  <div id=\"splitbar\" style=\"-moz-user-select:none;\" class=\"ui-resizable-handle\">\n\
  </div>\n\
</div>\n\
\n\
<div id=\"doc-content\">\n\
<div class=\"header\">\n\
  \n\
  <div class=\"headertitle\">\n\
<div class=\"title\">QXmlStreamNotationDeclaration Class Reference</div>  </div>\n\
<div class=\"summary\">\n\
<a href=\"class_q_xml_stream_notation_declaration.html#pub-methods\">Public Member Functions</a> &#124;\n\
<a href=\"class_q_xml_stream_notation_declaration.html#friends\">Friends</a>  </div></div><!--header-->\n\
<div class=\"contents\">\n\
\n\
<p><code>#include &lt;<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_qt_core_2qxmlstream_8h_source.html\">qxmlstream.h</a>&gt;</code></p>\n\
<a name=\"details\" id=\"details\"></a><h2 class=\"groupheader\">Class Description</h2>\n\
<div class=\"textblock\">\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_qt_core_2qxmlstream_8h_source.html#l00227\">227</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_qt_core_2qxmlstream_8h_source.html\">qxmlstream.h</a>.</p>\n\
</div><table class=\"memberdecls\">\n\
<tr class=\"heading\"><td colspan=\"2\"><h2 class=\"groupheader\"><a name=\"pub-methods\"></a>\n\
Public Member Functions</h2></td></tr>\n\
<tr class=\"memitem:a6d8cf4d2a36eb16731ebc700196090d3\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_xml_stream_notation_declaration.html#a6d8cf4d2a36eb16731ebc700196090d3\">QXmlStreamNotationDeclaration</a> ()</td></tr>\n\
<tr class=\"separator:a6d8cf4d2a36eb16731ebc700196090d3\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a161e69b55636182ed2c694f9cbd8002b\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_xml_stream_notation_declaration.html#a161e69b55636182ed2c694f9cbd8002b\">~QXmlStreamNotationDeclaration</a> ()</td></tr>\n\
<tr class=\"separator:a161e69b55636182ed2c694f9cbd8002b\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:aabbd7bda8430fcdc0ba7b271a8eb7b5d\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_xml_stream_notation_declaration.html#aabbd7bda8430fcdc0ba7b271a8eb7b5d\">QXmlStreamNotationDeclaration</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_xml_stream_notation_declaration.html\">QXmlStreamNotationDeclaration</a> &amp;)</td></tr>\n\
<tr class=\"separator:aabbd7bda8430fcdc0ba7b271a8eb7b5d\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a20f1da1eaa129803b9f8f3c92c648edf\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_xml_stream_notation_declaration.html\">QXmlStreamNotationDeclaration</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_xml_stream_notation_declaration.html#a20f1da1eaa129803b9f8f3c92c648edf\">operator=</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_xml_stream_notation_declaration.html\">QXmlStreamNotationDeclaration</a> &amp;)</td></tr>\n\
<tr class=\"separator:a20f1da1eaa129803b9f8f3c92c648edf\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a9595b22dd2ff6a66e1ea7ae6e9e8a8fd\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_string_ref.html\">QStringRef</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_xml_stream_notation_declaration.html#a9595b22dd2ff6a66e1ea7ae6e9e8a8fd\">name</a> () const </td></tr>\n\
<tr class=\"separator:a9595b22dd2ff6a66e1ea7ae6e9e8a8fd\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:aef81695fa6d27cbd89a8a93f18f12fbe\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_string_ref.html\">QStringRef</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_xml_stream_notation_declaration.html#aef81695fa6d27cbd89a8a93f18f12fbe\">systemId</a> () const </td></tr>\n\
<tr class=\"separator:aef81695fa6d27cbd89a8a93f18f12fbe\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ad054ec9131f37faeebaaf0a192e97d97\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_string_ref.html\">QStringRef</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_xml_stream_notation_declaration.html#ad054ec9131f37faeebaaf0a192e97d97\">publicId</a> () const </td></tr>\n\
<tr class=\"separator:ad054ec9131f37faeebaaf0a192e97d97\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a843ff0b146ac95e81a65698f92b37fec\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_xml_stream_notation_declaration.html#a843ff0b146ac95e81a65698f92b37fec\">operator==</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_xml_stream_notation_declaration.html\">QXmlStreamNotationDeclaration</a> &amp;other) const </td></tr>\n\
<tr class=\"separator:a843ff0b146ac95e81a65698f92b37fec\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:abb6186383d5f155f1a5fb562cbe81999\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_xml_stream_notation_declaration.html#abb6186383d5f155f1a5fb562cbe81999\">operator!=</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_xml_stream_notation_declaration.html\">QXmlStreamNotationDeclaration</a> &amp;other) const </td></tr>\n\
<tr class=\"separator:abb6186383d5f155f1a5fb562cbe81999\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
</table><table class=\"memberdecls\">\n\
<tr class=\"heading\"><td colspan=\"2\"><h2 class=\"groupheader\"><a name=\"friends\"></a>\n\
Friends</h2></td></tr>\n\
<tr class=\"memitem:a241ee14062d52cf3248847cc75c9f2d4\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">class&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_xml_stream_notation_declaration.html#a241ee14062d52cf3248847cc75c9f2d4\">QXmlStreamReaderPrivate</a></td></tr>\n\
<tr class=\"separator:a241ee14062d52cf3248847cc75c9f2d4\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
</table>\n\
<h2 class=\"groupheader\">Constructor &amp; Destructor Documentation</h2>\n\
<a class=\"anchor\" id=\"a6d8cf4d2a36eb16731ebc700196090d3\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_xml_stream_notation_declaration.html\">QXmlStreamNotationDeclaration</a> </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a161e69b55636182ed2c694f9cbd8002b\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">~<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_xml_stream_notation_declaration.html\">QXmlStreamNotationDeclaration</a> </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"aabbd7bda8430fcdc0ba7b271a8eb7b5d\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_xml_stream_notation_declaration.html\">QXmlStreamNotationDeclaration</a> </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_xml_stream_notation_declaration.html\">QXmlStreamNotationDeclaration</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
</div>\n\
</div>\n\
<h2 class=\"groupheader\">Member Function Documentation</h2>\n\
<a class=\"anchor\" id=\"a20f1da1eaa129803b9f8f3c92c648edf\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_xml_stream_notation_declaration.html\">QXmlStreamNotationDeclaration</a>&amp; operator= </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_xml_stream_notation_declaration.html\">QXmlStreamNotationDeclaration</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a9595b22dd2ff6a66e1ea7ae6e9e8a8fd\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_string_ref.html\">QStringRef</a> <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#ad977737dfc9a274a62741b9500c49a32\">name</a> </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">inline</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_qt_core_2qxmlstream_8h_source.html#l00237\">237</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_qt_core_2qxmlstream_8h_source.html\">qxmlstream.h</a>.</p>\n\
<div class=\"fragment\"><div class=\"line\"><a name=\"l00237\"></a><span class=\"lineno\">  237</span>&#160;{ <span class=\"keywordflow\">return</span> m_name; }</div>\n\
</div><!-- fragment -->\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"aef81695fa6d27cbd89a8a93f18f12fbe\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_string_ref.html\">QStringRef</a> systemId </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">inline</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_qt_core_2qxmlstream_8h_source.html#l00238\">238</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_qt_core_2qxmlstream_8h_source.html\">qxmlstream.h</a>.</p>\n\
<div class=\"fragment\"><div class=\"line\"><a name=\"l00238\"></a><span class=\"lineno\">  238</span>&#160;{ <span class=\"keywordflow\">return</span> m_systemId; }</div>\n\
</div><!-- fragment -->\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"ad054ec9131f37faeebaaf0a192e97d97\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_string_ref.html\">QStringRef</a> publicId </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">inline</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_qt_core_2qxmlstream_8h_source.html#l00239\">239</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_qt_core_2qxmlstream_8h_source.html\">qxmlstream.h</a>.</p>\n\
<div class=\"fragment\"><div class=\"line\"><a name=\"l00239\"></a><span class=\"lineno\">  239</span>&#160;{ <span class=\"keywordflow\">return</span> m_publicId; }</div>\n\
</div><!-- fragment -->\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a843ff0b146ac95e81a65698f92b37fec\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">bool operator== </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_xml_stream_notation_declaration.html\">QXmlStreamNotationDeclaration</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>other</em></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">inline</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_qt_core_2qxmlstream_8h_source.html#l00240\">240</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_qt_core_2qxmlstream_8h_source.html\">qxmlstream.h</a>.</p>\n\
<div class=\"fragment\"><div class=\"line\"><a name=\"l00240\"></a><span class=\"lineno\">  240</span>&#160;                                                                             {</div>\n\
<div class=\"line\"><a name=\"l00241\"></a><span class=\"lineno\">  241</span>&#160;        <span class=\"keywordflow\">return</span> (<a class=\"code\" href=\"#!/url=./cpp_ref/class_q_xml_stream_notation_declaration.html#a9595b22dd2ff6a66e1ea7ae6e9e8a8fd\">name</a>() == other.<a class=\"code\" href=\"#!/url=./cpp_ref/class_q_xml_stream_notation_declaration.html#a9595b22dd2ff6a66e1ea7ae6e9e8a8fd\">name</a>() &amp;&amp; <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_xml_stream_notation_declaration.html#aef81695fa6d27cbd89a8a93f18f12fbe\">systemId</a>() == other.<a class=\"code\" href=\"#!/url=./cpp_ref/class_q_xml_stream_notation_declaration.html#aef81695fa6d27cbd89a8a93f18f12fbe\">systemId</a>()</div>\n\
<div class=\"line\"><a name=\"l00242\"></a><span class=\"lineno\">  242</span>&#160;                &amp;&amp; <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_xml_stream_notation_declaration.html#ad054ec9131f37faeebaaf0a192e97d97\">publicId</a>() == other.<a class=\"code\" href=\"#!/url=./cpp_ref/class_q_xml_stream_notation_declaration.html#ad054ec9131f37faeebaaf0a192e97d97\">publicId</a>());</div>\n\
<div class=\"line\"><a name=\"l00243\"></a><span class=\"lineno\">  243</span>&#160;    }</div>\n\
<div class=\"ttc\" id=\"class_q_xml_stream_notation_declaration_html_ad054ec9131f37faeebaaf0a192e97d97\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_xml_stream_notation_declaration.html#ad054ec9131f37faeebaaf0a192e97d97\">QXmlStreamNotationDeclaration::publicId</a></div><div class=\"ttdeci\">QStringRef publicId() const </div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/_qt_core_2qxmlstream_8h_source.html#l00239\">qxmlstream.h:239</a></div></div>\n\
<div class=\"ttc\" id=\"class_q_xml_stream_notation_declaration_html_a9595b22dd2ff6a66e1ea7ae6e9e8a8fd\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_xml_stream_notation_declaration.html#a9595b22dd2ff6a66e1ea7ae6e9e8a8fd\">QXmlStreamNotationDeclaration::name</a></div><div class=\"ttdeci\">QStringRef name() const </div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/_qt_core_2qxmlstream_8h_source.html#l00237\">qxmlstream.h:237</a></div></div>\n\
<div class=\"ttc\" id=\"class_q_xml_stream_notation_declaration_html_aef81695fa6d27cbd89a8a93f18f12fbe\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_xml_stream_notation_declaration.html#aef81695fa6d27cbd89a8a93f18f12fbe\">QXmlStreamNotationDeclaration::systemId</a></div><div class=\"ttdeci\">QStringRef systemId() const </div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/_qt_core_2qxmlstream_8h_source.html#l00238\">qxmlstream.h:238</a></div></div>\n\
</div><!-- fragment -->\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"abb6186383d5f155f1a5fb562cbe81999\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">bool operator!= </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_xml_stream_notation_declaration.html\">QXmlStreamNotationDeclaration</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>other</em></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">inline</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_qt_core_2qxmlstream_8h_source.html#l00244\">244</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_qt_core_2qxmlstream_8h_source.html\">qxmlstream.h</a>.</p>\n\
<div class=\"fragment\"><div class=\"line\"><a name=\"l00245\"></a><span class=\"lineno\">  245</span>&#160;        { <span class=\"keywordflow\">return</span> !<a class=\"code\" href=\"#!/url=./cpp_ref/class_q_xml_stream_notation_declaration.html#a843ff0b146ac95e81a65698f92b37fec\">operator==</a>(other); }</div>\n\
<div class=\"ttc\" id=\"class_q_xml_stream_notation_declaration_html_a843ff0b146ac95e81a65698f92b37fec\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_xml_stream_notation_declaration.html#a843ff0b146ac95e81a65698f92b37fec\">QXmlStreamNotationDeclaration::operator==</a></div><div class=\"ttdeci\">bool operator==(const QXmlStreamNotationDeclaration &amp;other) const </div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/_qt_core_2qxmlstream_8h_source.html#l00240\">qxmlstream.h:240</a></div></div>\n\
</div><!-- fragment -->\n\
</div>\n\
</div>\n\
<h2 class=\"groupheader\">Friends And Related Function Documentation</h2>\n\
<a class=\"anchor\" id=\"a241ee14062d52cf3248847cc75c9f2d4\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">friend class QXmlStreamReaderPrivate</td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">friend</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_qt_core_2qxmlstream_8h_source.html#l00231\">231</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_qt_core_2qxmlstream_8h_source.html\">qxmlstream.h</a>.</p>\n\
\n\
</div>\n\
</div>\n\
<hr>The documentation for this class was generated from the following file:<ul>\n\
<li>QtCore/<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_qt_core_2qxmlstream_8h_source.html\">qxmlstream.h</a></li>\n\
</ul>\n\
</div><!-- contents -->\n\
</div><!-- doc-content -->\n\
          <div class=\"footer-block\"><a href=\"../html/ac.cmtdialog.htm\" class=\"comments-anchor\" target=\"_blank\"><span class=\"comments-link\">Please send us your comment about this page</span></a></div></div>\n\
   </div></body>\n\
</html>\n\
";