var topic = "<!-- saved from url=(0024)http://docs.autodesk.com -->\n\
<html>\n\
   <head><script src=\"../scripts/yepnope.1.5.4-min.js\" type=\"text/javascript\"></script><script src=\"../scripts/lib/jquery-1.11.1.min.js\" type=\"text/javascript\"></script><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"><meta name=\"product\" content=\"MOBPRO\"><meta name=\"release\" content=\"2018\"><meta name=\"book\" content=\"GeneralUser\"><meta name=\"created\" content=\"2017-09-08\"><meta name=\"topicid\" content=\"GUID-02FA7DD3-6C7A-4C6A-B7BC-824765AE1CB2\"><meta name=\"topic-type\" content=\"concept\">\n\
      <title>QtGui/qmacdefines_mac.h File Reference</title>\n\
   \n\
\n\
</head>\n\
   <body height=\"100%\"><div class=\"body_content\" id=\"body-content\"><link rel=\"stylesheet\" type=\"text/css\" href=\"cpp_ref/navtree.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"cpp_ref/doxygen.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"cpp_ref/tabs.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"style/adsk.cpm.css\"><script language=\"javascript\">var index = \'index.html\';</script><script>$(document).ready(function() { yepnope.injectJs(\"./scripts/ac_common.js\"); });</script><script type=\"text/javascript\">\n\
var tocSystemNeedsToBeLoaded = typeof(cpp_ref_adsk_ref_toc) == \'undefined\';\n\
var weAreIn21 = $(\'div#main.view-active\').length;\n\
var tocPrefix = \'\';\n\
if (weAreIn21)\n\
{ tocPrefix = \'cpp_ref/\'; }\n\
function cpp_ref_initializeToc(forceTrigger) {\n\
    cpp_ref_adsk_ref_toc.initResizable();\n\
    cpp_ref_adsk_ref_toc.initNavTree(\'qmacdefines__mac_8h.html\', tocPrefix);\n\
    dQuery(document).trigger(\'toc_initialized\');\n\
}\n\
if (tocSystemNeedsToBeLoaded)\n\
{\n\
	yepnope([{\n\
	load:[tocPrefix + \'json3.min.js\', tocPrefix + \'jquery.js\', tocPrefix + \'ref-toc-controller.js\', tocPrefix + \'dynsections.js\'],\n\
	complete: function() {\n\
	  if (typeof(dQuery) == \'undefined\')\n\
	  {\n\
	    dQuery = jQuery.noConflict(true);\n\
	  }\n\
	  else { jQuery.noConflict(true); }\n\
	  $(document).ready(cpp_ref_initializeToc);\n\
	}\n\
 	}])\n\
}\n\
if (!weAreIn21) { // if in AKN...\n\
$(window).load( function() {\n\
    setTimeout( function() {\n\
        var content = $(\'body > div\').not(\'#body-content\');     // take any divs under body that are not id=body-content\n\
        content.each( function() { \n\
            $(this).css( { \'padding-left\': $(this).css(\'margin-left\') } );       // and if they have any padding-left already, move it to margin-left.\n\
        } );\n\
        var width = cpp_ref_adsk_ref_toc.readFromStorage(\'width\');\n\
        content.css({marginLeft:parseInt(width)+6+\"px\"});\n\
    }, 100);\n\
} ); \n\
}\n\
</script><script>$(\"div#WidgetFloaterPanels,link[href*=\'microsofttranslator.com\'],script[src*=\'microsofttranslator.com\'],script[src*=\'bing.com\']\").remove();</script><script type=\'text/javascript\'>$(\"div#navigation,div#breadcrumbs,div#banner\").attr(\"translate\",\"no\"); var mtLocation = ((location && location.href && location.href.indexOf(\'https\') == 0)?\'https://ssl.microsofttranslator.com\':\'http://www.microsofttranslator.com\')+\'/ajax/v3/WidgetV3.ashx?ctf=True&ui=true&settings=Manual&from=en&hidelanguages=\'; yepnope.injectJs(mtLocation, function() {}, { charset:\'utf-8\', type:\'text/javascript\' } );</script><script>\n\
 if (!tocSystemNeedsToBeLoaded) { cpp_ref_initializeToc(); }\n\
 </script><!-- begin MT -->\n\
            \n\
            <div id=\'MicrosoftTranslatorWidget\' class=\'Dark\' style=\'float:right;z-index:100;color:white;background-color:#bbbbbb;height:58px;overflow:hidden\'></div>\n\
      <div>\n\
         <div class=\"head\">\n\
            <h1>QtGui/qmacdefines_mac.h File Reference</h1>\n\
         </div>\n\
\n\
    <div id=\"top\"><!-- Generated by Doxygen 1.8.10 -->\n\
  <div id=\"navrow1\" class=\"tabs\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./cpp_ref/index.html\"><span>Main&#160;Page</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/pages.html\"><span>Topics</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/modules.html\"><span>Modules</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/namespaces.html\"><span>Namespaces</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/annotated.html\"><span>Classes</span></a></li>\n\
      <li class=\"current\"><a href=\"#!/url=./cpp_ref/files.html\"><span>Files</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/examples.html\"><span>Examples</span></a></li>\n\
    </ul>\n\
  </div>\n\
  <div id=\"navrow2\" class=\"tabs2\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./cpp_ref/files.html\"><span>File&#160;List</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/globals.html\"><span>File&#160;Members</span></a></li>\n\
    </ul>\n\
  </div>\n\
</div><!-- top -->\n\
<div id=\"side-nav\" class=\"ui-resizable side-nav-resizable\">\n\
  <div id=\"nav-tree\">\n\
    <div id=\"nav-tree-contents\">\n\
      <div id=\"nav-sync\" class=\"sync\"></div>\n\
    </div>\n\
  </div>\n\
  <div id=\"splitbar\" style=\"-moz-user-select:none;\" class=\"ui-resizable-handle\">\n\
  </div>\n\
</div>\n\
\n\
<div id=\"doc-content\">\n\
<div class=\"header\">\n\
  \n\
  <div class=\"headertitle\">\n\
<div class=\"title\">qmacdefines_mac.h File Reference</div>  </div>\n\
<div class=\"summary\">\n\
<a href=\"qmacdefines__mac_8h.html#typedef-members\">Typedefs</a>  </div></div><!--header-->\n\
<div class=\"contents\">\n\
<div class=\"textblock\"><code>#include &lt;<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qglobal_8h_source.html\">QtCore/qglobal.h</a>&gt;</code><br>\n\
</div><table class=\"memberdecls\">\n\
<tr class=\"heading\"><td colspan=\"2\"><h2 class=\"groupheader\"><a name=\"typedef-members\"></a>\n\
Typedefs</h2></td></tr>\n\
<tr class=\"memitem:a3558682280c7331d128912d3edd21a61\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">typedef signed long&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#a3558682280c7331d128912d3edd21a61\">OSStatus</a></td></tr>\n\
<tr class=\"separator:a3558682280c7331d128912d3edd21a61\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a99dae9b3f18914b7b4cdbd6c22a98a71\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">typedef struct OpaqueEventHandlerCallRef *&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#a99dae9b3f18914b7b4cdbd6c22a98a71\">EventHandlerCallRef</a></td></tr>\n\
<tr class=\"separator:a99dae9b3f18914b7b4cdbd6c22a98a71\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a572a489386d470f4d599ca052b5b189b\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">typedef struct OpaqueEventRef *&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#a572a489386d470f4d599ca052b5b189b\">EventRef</a></td></tr>\n\
<tr class=\"separator:a572a489386d470f4d599ca052b5b189b\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a9eb7e703d944ad4692c51342260524ce\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">typedef struct OpaqueMenuRef *&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#a9eb7e703d944ad4692c51342260524ce\">MenuRef</a></td></tr>\n\
<tr class=\"separator:a9eb7e703d944ad4692c51342260524ce\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:afeb99121ede3c0ba8368d3c211b1a53a\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">typedef struct OpaquePasteboardRef *&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#afeb99121ede3c0ba8368d3c211b1a53a\">PasteboardRef</a></td></tr>\n\
<tr class=\"separator:afeb99121ede3c0ba8368d3c211b1a53a\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ac356933691c5a2aeadf46c14fc5677a6\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">typedef struct OpaqueRgnHandle *&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#ac356933691c5a2aeadf46c14fc5677a6\">RgnHandle</a></td></tr>\n\
<tr class=\"separator:ac356933691c5a2aeadf46c14fc5677a6\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ade43add98032554f7dcb0275b6f2fd8d\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">typedef const struct __HIShape *&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#ade43add98032554f7dcb0275b6f2fd8d\">HIShapeRef</a></td></tr>\n\
<tr class=\"separator:ade43add98032554f7dcb0275b6f2fd8d\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a327dc718639456300ee7f0a19caf5b97\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">typedef struct __HIShape *&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#a327dc718639456300ee7f0a19caf5b97\">HIMutableShapeRef</a></td></tr>\n\
<tr class=\"separator:a327dc718639456300ee7f0a19caf5b97\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a8e9c074e616df46bc46da80c9d4538aa\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">typedef struct <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#a8e9c074e616df46bc46da80c9d4538aa\">CGRect</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#a8e9c074e616df46bc46da80c9d4538aa\">CGRect</a></td></tr>\n\
<tr class=\"separator:a8e9c074e616df46bc46da80c9d4538aa\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a75461eac74c23c49c936eb8811388b88\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">typedef struct CGImage *&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#a75461eac74c23c49c936eb8811388b88\">CGImageRef</a></td></tr>\n\
<tr class=\"separator:a75461eac74c23c49c936eb8811388b88\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:aa24159a5753580ec784c2fd390213c7f\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">typedef struct CGContext *&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#aa24159a5753580ec784c2fd390213c7f\">CGContextRef</a></td></tr>\n\
<tr class=\"separator:aa24159a5753580ec784c2fd390213c7f\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:abae5dc2773814ab19bfe3d8d6f9c0612\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">typedef struct GDevice *&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#abae5dc2773814ab19bfe3d8d6f9c0612\">GDPtr</a></td></tr>\n\
<tr class=\"separator:abae5dc2773814ab19bfe3d8d6f9c0612\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a8c0c534265cb1f49048b16eda52a4663\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">typedef <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#abae5dc2773814ab19bfe3d8d6f9c0612\">GDPtr</a> *&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#a8c0c534265cb1f49048b16eda52a4663\">GDHandle</a></td></tr>\n\
<tr class=\"separator:a8c0c534265cb1f49048b16eda52a4663\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:aba74c21f724151d0738e60efd4947b4f\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">typedef struct OpaqueIconRef *&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#aba74c21f724151d0738e60efd4947b4f\">IconRef</a></td></tr>\n\
<tr class=\"separator:aba74c21f724151d0738e60efd4947b4f\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a018313b70656f253b585c4f89296467f\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">typedef struct OpaqueWindowPtr *&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#a018313b70656f253b585c4f89296467f\">WindowRef</a></td></tr>\n\
<tr class=\"separator:a018313b70656f253b585c4f89296467f\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a1b00029fc61e8014bea2a6d7de5b1512\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">typedef struct OpaqueControlRef *&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#a1b00029fc61e8014bea2a6d7de5b1512\">HIViewRef</a></td></tr>\n\
<tr class=\"separator:a1b00029fc61e8014bea2a6d7de5b1512\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a8965f48887488890d71df88d5ffb561a\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">typedef <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#a018313b70656f253b585c4f89296467f\">WindowRef</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#a8965f48887488890d71df88d5ffb561a\">OSWindowRef</a></td></tr>\n\
<tr class=\"separator:a8965f48887488890d71df88d5ffb561a\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a03940b55aea13049a16793d044d51ddb\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">typedef <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#a1b00029fc61e8014bea2a6d7de5b1512\">HIViewRef</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#a03940b55aea13049a16793d044d51ddb\">OSViewRef</a></td></tr>\n\
<tr class=\"separator:a03940b55aea13049a16793d044d51ddb\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ac776f1ea5eac2429887681cff3d7f430\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">typedef <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#a9eb7e703d944ad4692c51342260524ce\">MenuRef</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#ac776f1ea5eac2429887681cff3d7f430\">OSMenuRef</a></td></tr>\n\
<tr class=\"separator:ac776f1ea5eac2429887681cff3d7f430\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a898305d204f69a36c3f4d979fa1a33b0\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">typedef <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#a572a489386d470f4d599ca052b5b189b\">EventRef</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#a898305d204f69a36c3f4d979fa1a33b0\">OSEventRef</a></td></tr>\n\
<tr class=\"separator:a898305d204f69a36c3f4d979fa1a33b0\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ad6f945998bc5bb127e25f583853cfeed\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">typedef <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#afeb99121ede3c0ba8368d3c211b1a53a\">PasteboardRef</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#ad6f945998bc5bb127e25f583853cfeed\">OSPasteboardRef</a></td></tr>\n\
<tr class=\"separator:ad6f945998bc5bb127e25f583853cfeed\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a17d3971536cafc537339a4daad251d59\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">typedef struct AEDesc&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#a17d3971536cafc537339a4daad251d59\">AEDescList</a></td></tr>\n\
<tr class=\"separator:a17d3971536cafc537339a4daad251d59\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a1abeb2977cb3a5e6fe67ef62a5197b41\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">typedef <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#a17d3971536cafc537339a4daad251d59\">AEDescList</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#a1abeb2977cb3a5e6fe67ef62a5197b41\">AERecord</a></td></tr>\n\
<tr class=\"separator:a1abeb2977cb3a5e6fe67ef62a5197b41\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ab176eaed3a705367d17cb4d3edc9af28\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">typedef <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#a1abeb2977cb3a5e6fe67ef62a5197b41\">AERecord</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#ab176eaed3a705367d17cb4d3edc9af28\">AppleEvent</a></td></tr>\n\
<tr class=\"separator:ab176eaed3a705367d17cb4d3edc9af28\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
</table>\n\
<h2 class=\"groupheader\">Typedef Documentation</h2>\n\
<a class=\"anchor\" id=\"a3558682280c7331d128912d3edd21a61\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">typedef signed long <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#a3558682280c7331d128912d3edd21a61\">OSStatus</a></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h_source.html#l00105\">105</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h_source.html\">qmacdefines_mac.h</a>.</p>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a99dae9b3f18914b7b4cdbd6c22a98a71\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">typedef struct OpaqueEventHandlerCallRef* <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#a99dae9b3f18914b7b4cdbd6c22a98a71\">EventHandlerCallRef</a></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h_source.html#l00146\">146</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h_source.html\">qmacdefines_mac.h</a>.</p>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a572a489386d470f4d599ca052b5b189b\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">typedef struct OpaqueEventRef* <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#a572a489386d470f4d599ca052b5b189b\">EventRef</a></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h_source.html#l00147\">147</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h_source.html\">qmacdefines_mac.h</a>.</p>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a9eb7e703d944ad4692c51342260524ce\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">typedef struct OpaqueMenuRef* <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#a9eb7e703d944ad4692c51342260524ce\">MenuRef</a></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h_source.html#l00148\">148</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h_source.html\">qmacdefines_mac.h</a>.</p>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"afeb99121ede3c0ba8368d3c211b1a53a\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">typedef struct OpaquePasteboardRef* <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#afeb99121ede3c0ba8368d3c211b1a53a\">PasteboardRef</a></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h_source.html#l00149\">149</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h_source.html\">qmacdefines_mac.h</a>.</p>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"ac356933691c5a2aeadf46c14fc5677a6\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">typedef struct OpaqueRgnHandle* <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#ac356933691c5a2aeadf46c14fc5677a6\">RgnHandle</a></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h_source.html#l00150\">150</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h_source.html\">qmacdefines_mac.h</a>.</p>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"ade43add98032554f7dcb0275b6f2fd8d\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">typedef const struct __HIShape* <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#ade43add98032554f7dcb0275b6f2fd8d\">HIShapeRef</a></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h_source.html#l00151\">151</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h_source.html\">qmacdefines_mac.h</a>.</p>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a327dc718639456300ee7f0a19caf5b97\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">typedef struct __HIShape* <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#a327dc718639456300ee7f0a19caf5b97\">HIMutableShapeRef</a></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h_source.html#l00152\">152</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h_source.html\">qmacdefines_mac.h</a>.</p>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a8e9c074e616df46bc46da80c9d4538aa\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">typedef struct <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#a8e9c074e616df46bc46da80c9d4538aa\">CGRect</a> <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#a8e9c074e616df46bc46da80c9d4538aa\">CGRect</a></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h_source.html#l00153\">153</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h_source.html\">qmacdefines_mac.h</a>.</p>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a75461eac74c23c49c936eb8811388b88\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">typedef struct CGImage* <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#a75461eac74c23c49c936eb8811388b88\">CGImageRef</a></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h_source.html#l00154\">154</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h_source.html\">qmacdefines_mac.h</a>.</p>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"aa24159a5753580ec784c2fd390213c7f\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">typedef struct CGContext* <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#aa24159a5753580ec784c2fd390213c7f\">CGContextRef</a></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h_source.html#l00155\">155</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h_source.html\">qmacdefines_mac.h</a>.</p>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"abae5dc2773814ab19bfe3d8d6f9c0612\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">typedef struct GDevice* <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#abae5dc2773814ab19bfe3d8d6f9c0612\">GDPtr</a></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h_source.html#l00156\">156</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h_source.html\">qmacdefines_mac.h</a>.</p>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a8c0c534265cb1f49048b16eda52a4663\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">typedef <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#abae5dc2773814ab19bfe3d8d6f9c0612\">GDPtr</a>* <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#a8c0c534265cb1f49048b16eda52a4663\">GDHandle</a></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h_source.html#l00157\">157</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h_source.html\">qmacdefines_mac.h</a>.</p>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"aba74c21f724151d0738e60efd4947b4f\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">typedef struct OpaqueIconRef* <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#aba74c21f724151d0738e60efd4947b4f\">IconRef</a></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h_source.html#l00158\">158</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h_source.html\">qmacdefines_mac.h</a>.</p>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a018313b70656f253b585c4f89296467f\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">typedef struct OpaqueWindowPtr* <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#a018313b70656f253b585c4f89296467f\">WindowRef</a></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h_source.html#l00159\">159</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h_source.html\">qmacdefines_mac.h</a>.</p>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a1b00029fc61e8014bea2a6d7de5b1512\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">typedef struct OpaqueControlRef* <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#a1b00029fc61e8014bea2a6d7de5b1512\">HIViewRef</a></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h_source.html#l00160\">160</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h_source.html\">qmacdefines_mac.h</a>.</p>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a8965f48887488890d71df88d5ffb561a\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">typedef <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#a018313b70656f253b585c4f89296467f\">WindowRef</a> <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#a8965f48887488890d71df88d5ffb561a\">OSWindowRef</a></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h_source.html#l00161\">161</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h_source.html\">qmacdefines_mac.h</a>.</p>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a03940b55aea13049a16793d044d51ddb\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">typedef <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#a1b00029fc61e8014bea2a6d7de5b1512\">HIViewRef</a> <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#a03940b55aea13049a16793d044d51ddb\">OSViewRef</a></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h_source.html#l00162\">162</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h_source.html\">qmacdefines_mac.h</a>.</p>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"ac776f1ea5eac2429887681cff3d7f430\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">typedef <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#a9eb7e703d944ad4692c51342260524ce\">MenuRef</a> <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#ac776f1ea5eac2429887681cff3d7f430\">OSMenuRef</a></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h_source.html#l00163\">163</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h_source.html\">qmacdefines_mac.h</a>.</p>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a898305d204f69a36c3f4d979fa1a33b0\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">typedef <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#a572a489386d470f4d599ca052b5b189b\">EventRef</a> <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#a898305d204f69a36c3f4d979fa1a33b0\">OSEventRef</a></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h_source.html#l00164\">164</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h_source.html\">qmacdefines_mac.h</a>.</p>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"ad6f945998bc5bb127e25f583853cfeed\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">typedef <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#afeb99121ede3c0ba8368d3c211b1a53a\">PasteboardRef</a> <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#ad6f945998bc5bb127e25f583853cfeed\">OSPasteboardRef</a></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h_source.html#l00167\">167</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h_source.html\">qmacdefines_mac.h</a>.</p>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a17d3971536cafc537339a4daad251d59\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">typedef struct AEDesc <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#a17d3971536cafc537339a4daad251d59\">AEDescList</a></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h_source.html#l00168\">168</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h_source.html\">qmacdefines_mac.h</a>.</p>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a1abeb2977cb3a5e6fe67ef62a5197b41\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">typedef <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#a17d3971536cafc537339a4daad251d59\">AEDescList</a> <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#a1abeb2977cb3a5e6fe67ef62a5197b41\">AERecord</a></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h_source.html#l00169\">169</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h_source.html\">qmacdefines_mac.h</a>.</p>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"ab176eaed3a705367d17cb4d3edc9af28\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">typedef <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#a1abeb2977cb3a5e6fe67ef62a5197b41\">AERecord</a> <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h.html#ab176eaed3a705367d17cb4d3edc9af28\">AppleEvent</a></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h_source.html#l00170\">170</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmacdefines__mac_8h_source.html\">qmacdefines_mac.h</a>.</p>\n\
\n\
</div>\n\
</div>\n\
\n\
<p><a href=\"#!/url=./cpp_ref/qmacdefines__mac_8h_source.html\">Go to the source code of this file.</a></p>\n\
</div><!-- contents -->\n\
</div><!-- doc-content -->\n\
          <div class=\"footer-block\"><a href=\"../html/ac.cmtdialog.htm\" class=\"comments-anchor\" target=\"_blank\"><span class=\"comments-link\">Please send us your comment about this page</span></a></div></div>\n\
   </div></body>\n\
</html>\n\
";