var topic = "<!-- saved from url=(0024)http://docs.autodesk.com -->\n\
<html>\n\
   <head><script src=\"../scripts/yepnope.1.5.4-min.js\" type=\"text/javascript\"></script><script src=\"../scripts/lib/jquery-1.11.1.min.js\" type=\"text/javascript\"></script><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"><meta name=\"product\" content=\"MOBPRO\"><meta name=\"release\" content=\"2018\"><meta name=\"book\" content=\"GeneralUser\"><meta name=\"created\" content=\"2017-09-08\"><meta name=\"topicid\" content=\"GUID-02FA7DD3-6C7A-4C6A-B7BC-824765AE1CB2\"><meta name=\"topic-type\" content=\"concept\">\n\
      <title>QtCore/qmath.h Source File</title>\n\
   \n\
\n\
</head>\n\
   <body height=\"100%\"><div class=\"body_content\" id=\"body-content\"><link rel=\"stylesheet\" type=\"text/css\" href=\"cpp_ref/navtree.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"cpp_ref/doxygen.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"cpp_ref/tabs.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"style/adsk.cpm.css\"><script language=\"javascript\">var index = \'index.html\';</script><script>$(document).ready(function() { yepnope.injectJs(\"./scripts/ac_common.js\"); });</script><script type=\"text/javascript\">\n\
var tocSystemNeedsToBeLoaded = typeof(cpp_ref_adsk_ref_toc) == \'undefined\';\n\
var weAreIn21 = $(\'div#main.view-active\').length;\n\
var tocPrefix = \'\';\n\
if (weAreIn21)\n\
{ tocPrefix = \'cpp_ref/\'; }\n\
function cpp_ref_initializeToc(forceTrigger) {\n\
    cpp_ref_adsk_ref_toc.initResizable();\n\
    cpp_ref_adsk_ref_toc.initNavTree(\'qmath_8h_source.html\', tocPrefix);\n\
    dQuery(document).trigger(\'toc_initialized\');\n\
}\n\
if (tocSystemNeedsToBeLoaded)\n\
{\n\
	yepnope([{\n\
	load:[tocPrefix + \'json3.min.js\', tocPrefix + \'jquery.js\', tocPrefix + \'ref-toc-controller.js\', tocPrefix + \'dynsections.js\'],\n\
	complete: function() {\n\
	  if (typeof(dQuery) == \'undefined\')\n\
	  {\n\
	    dQuery = jQuery.noConflict(true);\n\
	  }\n\
	  else { jQuery.noConflict(true); }\n\
	  $(document).ready(cpp_ref_initializeToc);\n\
	}\n\
 	}])\n\
}\n\
if (!weAreIn21) { // if in AKN...\n\
$(window).load( function() {\n\
    setTimeout( function() {\n\
        var content = $(\'body > div\').not(\'#body-content\');     // take any divs under body that are not id=body-content\n\
        content.each( function() { \n\
            $(this).css( { \'padding-left\': $(this).css(\'margin-left\') } );       // and if they have any padding-left already, move it to margin-left.\n\
        } );\n\
        var width = cpp_ref_adsk_ref_toc.readFromStorage(\'width\');\n\
        content.css({marginLeft:parseInt(width)+6+\"px\"});\n\
    }, 100);\n\
} ); \n\
}\n\
</script><script>$(\"div#WidgetFloaterPanels,link[href*=\'microsofttranslator.com\'],script[src*=\'microsofttranslator.com\'],script[src*=\'bing.com\']\").remove();</script><script type=\'text/javascript\'>$(\"div#navigation,div#breadcrumbs,div#banner\").attr(\"translate\",\"no\"); var mtLocation = ((location && location.href && location.href.indexOf(\'https\') == 0)?\'https://ssl.microsofttranslator.com\':\'http://www.microsofttranslator.com\')+\'/ajax/v3/WidgetV3.ashx?ctf=True&ui=true&settings=Manual&from=en&hidelanguages=\'; yepnope.injectJs(mtLocation, function() {}, { charset:\'utf-8\', type:\'text/javascript\' } );</script><script>\n\
 if (!tocSystemNeedsToBeLoaded) { cpp_ref_initializeToc(); }\n\
 </script><!-- begin MT -->\n\
            \n\
            <div id=\'MicrosoftTranslatorWidget\' class=\'Dark\' style=\'float:right;z-index:100;color:white;background-color:#bbbbbb;height:58px;overflow:hidden\'></div>\n\
      <div>\n\
         <div class=\"head\">\n\
            <h1>QtCore/qmath.h Source File</h1>\n\
         </div>\n\
\n\
    <div id=\"top\"><!-- Generated by Doxygen 1.8.10 -->\n\
  <div id=\"navrow1\" class=\"tabs\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./cpp_ref/index.html\"><span>Main&#160;Page</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/pages.html\"><span>Topics</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/modules.html\"><span>Modules</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/namespaces.html\"><span>Namespaces</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/annotated.html\"><span>Classes</span></a></li>\n\
      <li class=\"current\"><a href=\"#!/url=./cpp_ref/files.html\"><span>Files</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/examples.html\"><span>Examples</span></a></li>\n\
    </ul>\n\
  </div>\n\
  <div id=\"navrow2\" class=\"tabs2\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./cpp_ref/files.html\"><span>File&#160;List</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/globals.html\"><span>File&#160;Members</span></a></li>\n\
    </ul>\n\
  </div>\n\
</div><!-- top -->\n\
<div id=\"side-nav\" class=\"ui-resizable side-nav-resizable\">\n\
  <div id=\"nav-tree\">\n\
    <div id=\"nav-tree-contents\">\n\
      <div id=\"nav-sync\" class=\"sync\"></div>\n\
    </div>\n\
  </div>\n\
  <div id=\"splitbar\" style=\"-moz-user-select:none;\" class=\"ui-resizable-handle\">\n\
  </div>\n\
</div>\n\
\n\
<div id=\"doc-content\">\n\
<div class=\"header\">\n\
  <div class=\"headertitle\">\n\
<div class=\"title\">qmath.h</div>  </div>\n\
</div><!--header-->\n\
<div class=\"contents\">\n\
<a href=\"#!/url=./cpp_ref/qmath_8h.html\">Go to the documentation of this file.</a><div class=\"fragment\"><div class=\"line\"><a name=\"l00001\"></a><span class=\"lineno\">    1</span>&#160;<span class=\"comment\">/****************************************************************************</span></div>\n\
<div class=\"line\"><a name=\"l00002\"></a><span class=\"lineno\">    2</span>&#160;<span class=\"comment\">**</span></div>\n\
<div class=\"line\"><a name=\"l00003\"></a><span class=\"lineno\">    3</span>&#160;<span class=\"comment\">** Copyright (C) 2014 Digia Plc and/or its subsidiary(-ies).</span></div>\n\
<div class=\"line\"><a name=\"l00004\"></a><span class=\"lineno\">    4</span>&#160;<span class=\"comment\">** Contact: http://www.qt-project.org/legal</span></div>\n\
<div class=\"line\"><a name=\"l00005\"></a><span class=\"lineno\">    5</span>&#160;<span class=\"comment\">**</span></div>\n\
<div class=\"line\"><a name=\"l00006\"></a><span class=\"lineno\">    6</span>&#160;<span class=\"comment\">** This file is part of the QtCore module of the Qt Toolkit.</span></div>\n\
<div class=\"line\"><a name=\"l00007\"></a><span class=\"lineno\">    7</span>&#160;<span class=\"comment\">**</span></div>\n\
<div class=\"line\"><a name=\"l00008\"></a><span class=\"lineno\">    8</span>&#160;<span class=\"comment\">** $QT_BEGIN_LICENSE:LGPL$</span></div>\n\
<div class=\"line\"><a name=\"l00009\"></a><span class=\"lineno\">    9</span>&#160;<span class=\"comment\">** Commercial License Usage</span></div>\n\
<div class=\"line\"><a name=\"l00010\"></a><span class=\"lineno\">   10</span>&#160;<span class=\"comment\">** Licensees holding valid commercial Qt licenses may use this file in</span></div>\n\
<div class=\"line\"><a name=\"l00011\"></a><span class=\"lineno\">   11</span>&#160;<span class=\"comment\">** accordance with the commercial license agreement provided with the</span></div>\n\
<div class=\"line\"><a name=\"l00012\"></a><span class=\"lineno\">   12</span>&#160;<span class=\"comment\">** Software or, alternatively, in accordance with the terms contained in</span></div>\n\
<div class=\"line\"><a name=\"l00013\"></a><span class=\"lineno\">   13</span>&#160;<span class=\"comment\">** a written agreement between you and Digia.  For licensing terms and</span></div>\n\
<div class=\"line\"><a name=\"l00014\"></a><span class=\"lineno\">   14</span>&#160;<span class=\"comment\">** conditions see http://qt.digia.com/licensing.  For further information</span></div>\n\
<div class=\"line\"><a name=\"l00015\"></a><span class=\"lineno\">   15</span>&#160;<span class=\"comment\">** use the contact form at http://qt.digia.com/contact-us.</span></div>\n\
<div class=\"line\"><a name=\"l00016\"></a><span class=\"lineno\">   16</span>&#160;<span class=\"comment\">**</span></div>\n\
<div class=\"line\"><a name=\"l00017\"></a><span class=\"lineno\">   17</span>&#160;<span class=\"comment\">** GNU Lesser General Public License Usage</span></div>\n\
<div class=\"line\"><a name=\"l00018\"></a><span class=\"lineno\">   18</span>&#160;<span class=\"comment\">** Alternatively, this file may be used under the terms of the GNU Lesser</span></div>\n\
<div class=\"line\"><a name=\"l00019\"></a><span class=\"lineno\">   19</span>&#160;<span class=\"comment\">** General Public License version 2.1 as published by the Free Software</span></div>\n\
<div class=\"line\"><a name=\"l00020\"></a><span class=\"lineno\">   20</span>&#160;<span class=\"comment\">** Foundation and appearing in the file LICENSE.LGPL included in the</span></div>\n\
<div class=\"line\"><a name=\"l00021\"></a><span class=\"lineno\">   21</span>&#160;<span class=\"comment\">** packaging of this file.  Please review the following information to</span></div>\n\
<div class=\"line\"><a name=\"l00022\"></a><span class=\"lineno\">   22</span>&#160;<span class=\"comment\">** ensure the GNU Lesser General Public License version 2.1 requirements</span></div>\n\
<div class=\"line\"><a name=\"l00023\"></a><span class=\"lineno\">   23</span>&#160;<span class=\"comment\">** will be met: http://www.gnu.org/licenses/old-licenses/lgpl-2.1.html.</span></div>\n\
<div class=\"line\"><a name=\"l00024\"></a><span class=\"lineno\">   24</span>&#160;<span class=\"comment\">**</span></div>\n\
<div class=\"line\"><a name=\"l00025\"></a><span class=\"lineno\">   25</span>&#160;<span class=\"comment\">** In addition, as a special exception, Digia gives you certain additional</span></div>\n\
<div class=\"line\"><a name=\"l00026\"></a><span class=\"lineno\">   26</span>&#160;<span class=\"comment\">** rights.  These rights are described in the Digia Qt LGPL Exception</span></div>\n\
<div class=\"line\"><a name=\"l00027\"></a><span class=\"lineno\">   27</span>&#160;<span class=\"comment\">** version 1.1, included in the file LGPL_EXCEPTION.txt in this package.</span></div>\n\
<div class=\"line\"><a name=\"l00028\"></a><span class=\"lineno\">   28</span>&#160;<span class=\"comment\">**</span></div>\n\
<div class=\"line\"><a name=\"l00029\"></a><span class=\"lineno\">   29</span>&#160;<span class=\"comment\">** GNU General Public License Usage</span></div>\n\
<div class=\"line\"><a name=\"l00030\"></a><span class=\"lineno\">   30</span>&#160;<span class=\"comment\">** Alternatively, this file may be used under the terms of the GNU</span></div>\n\
<div class=\"line\"><a name=\"l00031\"></a><span class=\"lineno\">   31</span>&#160;<span class=\"comment\">** General Public License version 3.0 as published by the Free Software</span></div>\n\
<div class=\"line\"><a name=\"l00032\"></a><span class=\"lineno\">   32</span>&#160;<span class=\"comment\">** Foundation and appearing in the file LICENSE.GPL included in the</span></div>\n\
<div class=\"line\"><a name=\"l00033\"></a><span class=\"lineno\">   33</span>&#160;<span class=\"comment\">** packaging of this file.  Please review the following information to</span></div>\n\
<div class=\"line\"><a name=\"l00034\"></a><span class=\"lineno\">   34</span>&#160;<span class=\"comment\">** ensure the GNU General Public License version 3.0 requirements will be</span></div>\n\
<div class=\"line\"><a name=\"l00035\"></a><span class=\"lineno\">   35</span>&#160;<span class=\"comment\">** met: http://www.gnu.org/copyleft/gpl.html.</span></div>\n\
<div class=\"line\"><a name=\"l00036\"></a><span class=\"lineno\">   36</span>&#160;<span class=\"comment\">**</span></div>\n\
<div class=\"line\"><a name=\"l00037\"></a><span class=\"lineno\">   37</span>&#160;<span class=\"comment\">**</span></div>\n\
<div class=\"line\"><a name=\"l00038\"></a><span class=\"lineno\">   38</span>&#160;<span class=\"comment\">** $QT_END_LICENSE$</span></div>\n\
<div class=\"line\"><a name=\"l00039\"></a><span class=\"lineno\">   39</span>&#160;<span class=\"comment\">**</span></div>\n\
<div class=\"line\"><a name=\"l00040\"></a><span class=\"lineno\">   40</span>&#160;<span class=\"comment\">****************************************************************************/</span></div>\n\
<div class=\"line\"><a name=\"l00041\"></a><span class=\"lineno\">   41</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00042\"></a><span class=\"lineno\">   42</span>&#160;<span class=\"preprocessor\">#ifndef QMATH_H</span></div>\n\
<div class=\"line\"><a name=\"l00043\"></a><span class=\"lineno\">   43</span>&#160;<span class=\"preprocessor\">#define QMATH_H</span></div>\n\
<div class=\"line\"><a name=\"l00044\"></a><span class=\"lineno\">   44</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00045\"></a><span class=\"lineno\">   45</span>&#160;<span class=\"preprocessor\">#include &lt;<a class=\"code\" href=\"#!/url=./cpp_ref/math_8h.html\">math.h</a>&gt;</span></div>\n\
<div class=\"line\"><a name=\"l00046\"></a><span class=\"lineno\">   46</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00047\"></a><span class=\"lineno\">   47</span>&#160;<span class=\"preprocessor\">#include &lt;<a class=\"code\" href=\"#!/url=./cpp_ref/qglobal_8h.html\">QtCore/qglobal.h</a>&gt;</span></div>\n\
<div class=\"line\"><a name=\"l00048\"></a><span class=\"lineno\">   48</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00049\"></a><span class=\"lineno\">   49</span>&#160;<span class=\"preprocessor\">#ifdef Q_OS_SYMBIAN</span></div>\n\
<div class=\"line\"><a name=\"l00050\"></a><span class=\"lineno\">   50</span>&#160;<span class=\"preprocessor\">#    include &lt;e32math.h&gt;</span></div>\n\
<div class=\"line\"><a name=\"l00051\"></a><span class=\"lineno\">   51</span>&#160;<span class=\"preprocessor\">#endif</span></div>\n\
<div class=\"line\"><a name=\"l00052\"></a><span class=\"lineno\">   52</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00053\"></a><span class=\"lineno\">   53</span>&#160;<a class=\"code\" href=\"#!/url=./cpp_ref/qglobal_8h.html#a22466069bc24124bf4d749ca253f5e2b\">QT_BEGIN_HEADER</a></div>\n\
<div class=\"line\"><a name=\"l00054\"></a><span class=\"lineno\">   54</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00055\"></a><span class=\"lineno\">   55</span>&#160;<a class=\"code\" href=\"#!/url=./cpp_ref/qglobal_8h.html#ae7344b820974b9f9f7cfedd5808bd3a0\">QT_BEGIN_NAMESPACE</a></div>\n\
<div class=\"line\"><a name=\"l00056\"></a><span class=\"lineno\">   56</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00057\"></a><span class=\"lineno\">   57</span>&#160;QT_MODULE(Core)</div>\n\
<div class=\"line\"><a name=\"l00058\"></a><span class=\"lineno\">   58</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00059\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./cpp_ref/qmath_8h.html#a1ac42b3a6eddd6a9d82fa4fff0c073f3\">   59</a></span>&#160;<span class=\"preprocessor\">#define QT_SINE_TABLE_SIZE 256</span></div>\n\
<div class=\"line\"><a name=\"l00060\"></a><span class=\"lineno\">   60</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00061\"></a><span class=\"lineno\">   61</span>&#160;<span class=\"keyword\">extern</span> Q_CORE_EXPORT <span class=\"keyword\">const</span> qreal <a class=\"code\" href=\"#!/url=./cpp_ref/qmath_8h.html#a105e697128b5e57f517c3605d5a45847\">qt_sine_table</a>[<a class=\"code\" href=\"#!/url=./cpp_ref/qmath_8h.html#a1ac42b3a6eddd6a9d82fa4fff0c073f3\">QT_SINE_TABLE_SIZE</a>];</div>\n\
<div class=\"line\"><a name=\"l00062\"></a><span class=\"lineno\">   62</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00063\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./cpp_ref/qmath_8h.html#a2de5641ae52db30e76eed8da1cec47c3\">   63</a></span>&#160;<span class=\"keyword\">inline</span> <span class=\"keywordtype\">int</span> <a class=\"code\" href=\"#!/url=./cpp_ref/qmath_8h.html#a2de5641ae52db30e76eed8da1cec47c3\">qCeil</a>(qreal <a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a14cfbe2fc2234f5504618905b69d1e06\">v</a>)</div>\n\
<div class=\"line\"><a name=\"l00064\"></a><span class=\"lineno\">   64</span>&#160;{</div>\n\
<div class=\"line\"><a name=\"l00065\"></a><span class=\"lineno\">   65</span>&#160;<span class=\"preprocessor\">#ifdef QT_USE_MATH_H_FLOATS</span></div>\n\
<div class=\"line\"><a name=\"l00066\"></a><span class=\"lineno\">   66</span>&#160;    <span class=\"keywordflow\">if</span> (<span class=\"keyword\">sizeof</span>(qreal) == <span class=\"keyword\">sizeof</span>(<span class=\"keywordtype\">float</span>))</div>\n\
<div class=\"line\"><a name=\"l00067\"></a><span class=\"lineno\">   67</span>&#160;        <span class=\"keywordflow\">return</span> <a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#aa813ad7a4a00cda401ffd0c336154620\">int</a>(ceilf(<span class=\"keywordtype\">float</span>(v)));</div>\n\
<div class=\"line\"><a name=\"l00068\"></a><span class=\"lineno\">   68</span>&#160;    <span class=\"keywordflow\">else</span></div>\n\
<div class=\"line\"><a name=\"l00069\"></a><span class=\"lineno\">   69</span>&#160;<span class=\"preprocessor\">#endif</span></div>\n\
<div class=\"line\"><a name=\"l00070\"></a><span class=\"lineno\">   70</span>&#160;        <span class=\"keywordflow\">return</span> <a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#aa813ad7a4a00cda401ffd0c336154620\">int</a>(ceil(v));</div>\n\
<div class=\"line\"><a name=\"l00071\"></a><span class=\"lineno\">   71</span>&#160;}</div>\n\
<div class=\"line\"><a name=\"l00072\"></a><span class=\"lineno\">   72</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00073\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./cpp_ref/qmath_8h.html#a90fd634f1cf1c03263337de01372c582\">   73</a></span>&#160;<span class=\"keyword\">inline</span> <span class=\"keywordtype\">int</span> <a class=\"code\" href=\"#!/url=./cpp_ref/qmath_8h.html#a90fd634f1cf1c03263337de01372c582\">qFloor</a>(qreal <a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a14cfbe2fc2234f5504618905b69d1e06\">v</a>)</div>\n\
<div class=\"line\"><a name=\"l00074\"></a><span class=\"lineno\">   74</span>&#160;{</div>\n\
<div class=\"line\"><a name=\"l00075\"></a><span class=\"lineno\">   75</span>&#160;<span class=\"preprocessor\">#ifdef QT_USE_MATH_H_FLOATS</span></div>\n\
<div class=\"line\"><a name=\"l00076\"></a><span class=\"lineno\">   76</span>&#160;    <span class=\"keywordflow\">if</span> (<span class=\"keyword\">sizeof</span>(qreal) == <span class=\"keyword\">sizeof</span>(<span class=\"keywordtype\">float</span>))</div>\n\
<div class=\"line\"><a name=\"l00077\"></a><span class=\"lineno\">   77</span>&#160;        <span class=\"keywordflow\">return</span> <a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#aa813ad7a4a00cda401ffd0c336154620\">int</a>(floorf(<span class=\"keywordtype\">float</span>(v)));</div>\n\
<div class=\"line\"><a name=\"l00078\"></a><span class=\"lineno\">   78</span>&#160;    <span class=\"keywordflow\">else</span></div>\n\
<div class=\"line\"><a name=\"l00079\"></a><span class=\"lineno\">   79</span>&#160;<span class=\"preprocessor\">#endif</span></div>\n\
<div class=\"line\"><a name=\"l00080\"></a><span class=\"lineno\">   80</span>&#160;        <span class=\"keywordflow\">return</span> <a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#aa813ad7a4a00cda401ffd0c336154620\">int</a>(floor(v));</div>\n\
<div class=\"line\"><a name=\"l00081\"></a><span class=\"lineno\">   81</span>&#160;}</div>\n\
<div class=\"line\"><a name=\"l00082\"></a><span class=\"lineno\">   82</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00083\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./cpp_ref/qmath_8h.html#a496bd29bd65dac6b7e5805e08a57c17b\">   83</a></span>&#160;<span class=\"keyword\">inline</span> qreal <a class=\"code\" href=\"#!/url=./cpp_ref/qmath_8h.html#a496bd29bd65dac6b7e5805e08a57c17b\">qFabs</a>(qreal <a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a14cfbe2fc2234f5504618905b69d1e06\">v</a>)</div>\n\
<div class=\"line\"><a name=\"l00084\"></a><span class=\"lineno\">   84</span>&#160;{</div>\n\
<div class=\"line\"><a name=\"l00085\"></a><span class=\"lineno\">   85</span>&#160;<span class=\"preprocessor\">#ifdef QT_USE_MATH_H_FLOATS</span></div>\n\
<div class=\"line\"><a name=\"l00086\"></a><span class=\"lineno\">   86</span>&#160;    <span class=\"keywordflow\">if</span>(<span class=\"keyword\">sizeof</span>(qreal) == <span class=\"keyword\">sizeof</span>(<span class=\"keywordtype\">float</span>))</div>\n\
<div class=\"line\"><a name=\"l00087\"></a><span class=\"lineno\">   87</span>&#160;        <span class=\"keywordflow\">return</span> fabsf(<span class=\"keywordtype\">float</span>(v));</div>\n\
<div class=\"line\"><a name=\"l00088\"></a><span class=\"lineno\">   88</span>&#160;    <span class=\"keywordflow\">else</span></div>\n\
<div class=\"line\"><a name=\"l00089\"></a><span class=\"lineno\">   89</span>&#160;<span class=\"preprocessor\">#endif</span></div>\n\
<div class=\"line\"><a name=\"l00090\"></a><span class=\"lineno\">   90</span>&#160;        <span class=\"keywordflow\">return</span> fabs(v);</div>\n\
<div class=\"line\"><a name=\"l00091\"></a><span class=\"lineno\">   91</span>&#160;}</div>\n\
<div class=\"line\"><a name=\"l00092\"></a><span class=\"lineno\">   92</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00093\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./cpp_ref/qmath_8h.html#abb1f20a4e4f80b3add0c1533bb744921\">   93</a></span>&#160;<span class=\"keyword\">inline</span> qreal <a class=\"code\" href=\"#!/url=./cpp_ref/qmath_8h.html#abb1f20a4e4f80b3add0c1533bb744921\">qSin</a>(qreal <a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a14cfbe2fc2234f5504618905b69d1e06\">v</a>)</div>\n\
<div class=\"line\"><a name=\"l00094\"></a><span class=\"lineno\">   94</span>&#160;{</div>\n\
<div class=\"line\"><a name=\"l00095\"></a><span class=\"lineno\">   95</span>&#160;<span class=\"preprocessor\">#ifdef Q_OS_SYMBIAN</span></div>\n\
<div class=\"line\"><a name=\"l00096\"></a><span class=\"lineno\">   96</span>&#160;    TReal sin_v;</div>\n\
<div class=\"line\"><a name=\"l00097\"></a><span class=\"lineno\">   97</span>&#160;    Math::Sin(sin_v, static_cast&lt;TReal&gt;(v));</div>\n\
<div class=\"line\"><a name=\"l00098\"></a><span class=\"lineno\">   98</span>&#160;    <span class=\"keywordflow\">return</span> <span class=\"keyword\">static_cast&lt;</span>qreal<span class=\"keyword\">&gt;</span>(sin_v);</div>\n\
<div class=\"line\"><a name=\"l00099\"></a><span class=\"lineno\">   99</span>&#160;<span class=\"preprocessor\">#else</span></div>\n\
<div class=\"line\"><a name=\"l00100\"></a><span class=\"lineno\">  100</span>&#160;<span class=\"preprocessor\">#    ifdef QT_USE_MATH_H_FLOATS</span></div>\n\
<div class=\"line\"><a name=\"l00101\"></a><span class=\"lineno\">  101</span>&#160;        <span class=\"keywordflow\">if</span> (<span class=\"keyword\">sizeof</span>(qreal) == <span class=\"keyword\">sizeof</span>(float))</div>\n\
<div class=\"line\"><a name=\"l00102\"></a><span class=\"lineno\">  102</span>&#160;            <span class=\"keywordflow\">return</span> sinf(<span class=\"keywordtype\">float</span>(v));</div>\n\
<div class=\"line\"><a name=\"l00103\"></a><span class=\"lineno\">  103</span>&#160;        <span class=\"keywordflow\">else</span></div>\n\
<div class=\"line\"><a name=\"l00104\"></a><span class=\"lineno\">  104</span>&#160;<span class=\"preprocessor\">#    endif</span></div>\n\
<div class=\"line\"><a name=\"l00105\"></a><span class=\"lineno\">  105</span>&#160;            <span class=\"keywordflow\">return</span> sin(v);</div>\n\
<div class=\"line\"><a name=\"l00106\"></a><span class=\"lineno\">  106</span>&#160;<span class=\"preprocessor\">#endif</span></div>\n\
<div class=\"line\"><a name=\"l00107\"></a><span class=\"lineno\">  107</span>&#160;}</div>\n\
<div class=\"line\"><a name=\"l00108\"></a><span class=\"lineno\">  108</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00109\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./cpp_ref/qmath_8h.html#a4ccb11b3f855f8f7b8bb7a4255ab913e\">  109</a></span>&#160;<span class=\"keyword\">inline</span> qreal <a class=\"code\" href=\"#!/url=./cpp_ref/qmath_8h.html#a4ccb11b3f855f8f7b8bb7a4255ab913e\">qCos</a>(qreal <a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a14cfbe2fc2234f5504618905b69d1e06\">v</a>)</div>\n\
<div class=\"line\"><a name=\"l00110\"></a><span class=\"lineno\">  110</span>&#160;{</div>\n\
<div class=\"line\"><a name=\"l00111\"></a><span class=\"lineno\">  111</span>&#160;<span class=\"preprocessor\">#ifdef Q_OS_SYMBIAN</span></div>\n\
<div class=\"line\"><a name=\"l00112\"></a><span class=\"lineno\">  112</span>&#160;    TReal cos_v;</div>\n\
<div class=\"line\"><a name=\"l00113\"></a><span class=\"lineno\">  113</span>&#160;    Math::Cos(cos_v, static_cast&lt;TReal&gt;(v));</div>\n\
<div class=\"line\"><a name=\"l00114\"></a><span class=\"lineno\">  114</span>&#160;    <span class=\"keywordflow\">return</span> <span class=\"keyword\">static_cast&lt;</span>qreal<span class=\"keyword\">&gt;</span>(cos_v);</div>\n\
<div class=\"line\"><a name=\"l00115\"></a><span class=\"lineno\">  115</span>&#160;<span class=\"preprocessor\">#else</span></div>\n\
<div class=\"line\"><a name=\"l00116\"></a><span class=\"lineno\">  116</span>&#160;<span class=\"preprocessor\">#    ifdef QT_USE_MATH_H_FLOATS</span></div>\n\
<div class=\"line\"><a name=\"l00117\"></a><span class=\"lineno\">  117</span>&#160;        <span class=\"keywordflow\">if</span> (<span class=\"keyword\">sizeof</span>(qreal) == <span class=\"keyword\">sizeof</span>(float))</div>\n\
<div class=\"line\"><a name=\"l00118\"></a><span class=\"lineno\">  118</span>&#160;            <span class=\"keywordflow\">return</span> cosf(<span class=\"keywordtype\">float</span>(v));</div>\n\
<div class=\"line\"><a name=\"l00119\"></a><span class=\"lineno\">  119</span>&#160;        <span class=\"keywordflow\">else</span></div>\n\
<div class=\"line\"><a name=\"l00120\"></a><span class=\"lineno\">  120</span>&#160;<span class=\"preprocessor\">#    endif</span></div>\n\
<div class=\"line\"><a name=\"l00121\"></a><span class=\"lineno\">  121</span>&#160;            <span class=\"keywordflow\">return</span> cos(v);</div>\n\
<div class=\"line\"><a name=\"l00122\"></a><span class=\"lineno\">  122</span>&#160;<span class=\"preprocessor\">#endif</span></div>\n\
<div class=\"line\"><a name=\"l00123\"></a><span class=\"lineno\">  123</span>&#160;}</div>\n\
<div class=\"line\"><a name=\"l00124\"></a><span class=\"lineno\">  124</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00125\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./cpp_ref/qmath_8h.html#a3e43b4c27d11701b766f2797258a2e30\">  125</a></span>&#160;<span class=\"keyword\">inline</span> qreal <a class=\"code\" href=\"#!/url=./cpp_ref/qmath_8h.html#a3e43b4c27d11701b766f2797258a2e30\">qTan</a>(qreal <a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a14cfbe2fc2234f5504618905b69d1e06\">v</a>)</div>\n\
<div class=\"line\"><a name=\"l00126\"></a><span class=\"lineno\">  126</span>&#160;{</div>\n\
<div class=\"line\"><a name=\"l00127\"></a><span class=\"lineno\">  127</span>&#160;<span class=\"preprocessor\">#ifdef Q_OS_SYMBIAN</span></div>\n\
<div class=\"line\"><a name=\"l00128\"></a><span class=\"lineno\">  128</span>&#160;    TReal tan_v;</div>\n\
<div class=\"line\"><a name=\"l00129\"></a><span class=\"lineno\">  129</span>&#160;    Math::Tan(tan_v, static_cast&lt;TReal&gt;(v));</div>\n\
<div class=\"line\"><a name=\"l00130\"></a><span class=\"lineno\">  130</span>&#160;    <span class=\"keywordflow\">return</span> <span class=\"keyword\">static_cast&lt;</span>qreal<span class=\"keyword\">&gt;</span>(tan_v);</div>\n\
<div class=\"line\"><a name=\"l00131\"></a><span class=\"lineno\">  131</span>&#160;<span class=\"preprocessor\">#else</span></div>\n\
<div class=\"line\"><a name=\"l00132\"></a><span class=\"lineno\">  132</span>&#160;<span class=\"preprocessor\">#    ifdef QT_USE_MATH_H_FLOATS</span></div>\n\
<div class=\"line\"><a name=\"l00133\"></a><span class=\"lineno\">  133</span>&#160;        <span class=\"keywordflow\">if</span> (<span class=\"keyword\">sizeof</span>(qreal) == <span class=\"keyword\">sizeof</span>(float))</div>\n\
<div class=\"line\"><a name=\"l00134\"></a><span class=\"lineno\">  134</span>&#160;            <span class=\"keywordflow\">return</span> tanf(<span class=\"keywordtype\">float</span>(v));</div>\n\
<div class=\"line\"><a name=\"l00135\"></a><span class=\"lineno\">  135</span>&#160;        <span class=\"keywordflow\">else</span></div>\n\
<div class=\"line\"><a name=\"l00136\"></a><span class=\"lineno\">  136</span>&#160;<span class=\"preprocessor\">#    endif</span></div>\n\
<div class=\"line\"><a name=\"l00137\"></a><span class=\"lineno\">  137</span>&#160;            <span class=\"keywordflow\">return</span> tan(v);</div>\n\
<div class=\"line\"><a name=\"l00138\"></a><span class=\"lineno\">  138</span>&#160;<span class=\"preprocessor\">#endif</span></div>\n\
<div class=\"line\"><a name=\"l00139\"></a><span class=\"lineno\">  139</span>&#160;}</div>\n\
<div class=\"line\"><a name=\"l00140\"></a><span class=\"lineno\">  140</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00141\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./cpp_ref/qmath_8h.html#a94143b1f9c72a196b1c1e60aab7d63aa\">  141</a></span>&#160;<span class=\"keyword\">inline</span> qreal <a class=\"code\" href=\"#!/url=./cpp_ref/qmath_8h.html#a94143b1f9c72a196b1c1e60aab7d63aa\">qAcos</a>(qreal <a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a14cfbe2fc2234f5504618905b69d1e06\">v</a>)</div>\n\
<div class=\"line\"><a name=\"l00142\"></a><span class=\"lineno\">  142</span>&#160;{</div>\n\
<div class=\"line\"><a name=\"l00143\"></a><span class=\"lineno\">  143</span>&#160;<span class=\"preprocessor\">#ifdef Q_OS_SYMBIAN</span></div>\n\
<div class=\"line\"><a name=\"l00144\"></a><span class=\"lineno\">  144</span>&#160;    TReal acos_v;</div>\n\
<div class=\"line\"><a name=\"l00145\"></a><span class=\"lineno\">  145</span>&#160;    Math::ACos(acos_v, static_cast&lt;TReal&gt;(v));</div>\n\
<div class=\"line\"><a name=\"l00146\"></a><span class=\"lineno\">  146</span>&#160;    <span class=\"keywordflow\">return</span> <span class=\"keyword\">static_cast&lt;</span>qreal<span class=\"keyword\">&gt;</span>(acos_v);</div>\n\
<div class=\"line\"><a name=\"l00147\"></a><span class=\"lineno\">  147</span>&#160;<span class=\"preprocessor\">#else</span></div>\n\
<div class=\"line\"><a name=\"l00148\"></a><span class=\"lineno\">  148</span>&#160;<span class=\"preprocessor\">#    ifdef QT_USE_MATH_H_FLOATS</span></div>\n\
<div class=\"line\"><a name=\"l00149\"></a><span class=\"lineno\">  149</span>&#160;        <span class=\"keywordflow\">if</span> (<span class=\"keyword\">sizeof</span>(qreal) == <span class=\"keyword\">sizeof</span>(float))</div>\n\
<div class=\"line\"><a name=\"l00150\"></a><span class=\"lineno\">  150</span>&#160;            <span class=\"keywordflow\">return</span> acosf(<span class=\"keywordtype\">float</span>(v));</div>\n\
<div class=\"line\"><a name=\"l00151\"></a><span class=\"lineno\">  151</span>&#160;        <span class=\"keywordflow\">else</span></div>\n\
<div class=\"line\"><a name=\"l00152\"></a><span class=\"lineno\">  152</span>&#160;<span class=\"preprocessor\">#    endif</span></div>\n\
<div class=\"line\"><a name=\"l00153\"></a><span class=\"lineno\">  153</span>&#160;           <span class=\"keywordflow\">return</span> acos(v);</div>\n\
<div class=\"line\"><a name=\"l00154\"></a><span class=\"lineno\">  154</span>&#160;<span class=\"preprocessor\">#endif</span></div>\n\
<div class=\"line\"><a name=\"l00155\"></a><span class=\"lineno\">  155</span>&#160;}</div>\n\
<div class=\"line\"><a name=\"l00156\"></a><span class=\"lineno\">  156</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00157\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./cpp_ref/qmath_8h.html#ab9a370ad20b6dcee47de1d14ef2acb85\">  157</a></span>&#160;<span class=\"keyword\">inline</span> qreal <a class=\"code\" href=\"#!/url=./cpp_ref/qmath_8h.html#ab9a370ad20b6dcee47de1d14ef2acb85\">qAsin</a>(qreal <a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a14cfbe2fc2234f5504618905b69d1e06\">v</a>)</div>\n\
<div class=\"line\"><a name=\"l00158\"></a><span class=\"lineno\">  158</span>&#160;{</div>\n\
<div class=\"line\"><a name=\"l00159\"></a><span class=\"lineno\">  159</span>&#160;<span class=\"preprocessor\">#ifdef Q_OS_SYMBIAN</span></div>\n\
<div class=\"line\"><a name=\"l00160\"></a><span class=\"lineno\">  160</span>&#160;    TReal asin_v;</div>\n\
<div class=\"line\"><a name=\"l00161\"></a><span class=\"lineno\">  161</span>&#160;    Math::ASin(asin_v, static_cast&lt;TReal&gt;(v));</div>\n\
<div class=\"line\"><a name=\"l00162\"></a><span class=\"lineno\">  162</span>&#160;    <span class=\"keywordflow\">return</span> <span class=\"keyword\">static_cast&lt;</span>qreal<span class=\"keyword\">&gt;</span>(asin_v);</div>\n\
<div class=\"line\"><a name=\"l00163\"></a><span class=\"lineno\">  163</span>&#160;<span class=\"preprocessor\">#else</span></div>\n\
<div class=\"line\"><a name=\"l00164\"></a><span class=\"lineno\">  164</span>&#160;<span class=\"preprocessor\">#    ifdef QT_USE_MATH_H_FLOATS</span></div>\n\
<div class=\"line\"><a name=\"l00165\"></a><span class=\"lineno\">  165</span>&#160;        <span class=\"keywordflow\">if</span> (<span class=\"keyword\">sizeof</span>(qreal) == <span class=\"keyword\">sizeof</span>(float))</div>\n\
<div class=\"line\"><a name=\"l00166\"></a><span class=\"lineno\">  166</span>&#160;            <span class=\"keywordflow\">return</span> asinf(<span class=\"keywordtype\">float</span>(v));</div>\n\
<div class=\"line\"><a name=\"l00167\"></a><span class=\"lineno\">  167</span>&#160;        <span class=\"keywordflow\">else</span></div>\n\
<div class=\"line\"><a name=\"l00168\"></a><span class=\"lineno\">  168</span>&#160;<span class=\"preprocessor\">#    endif</span></div>\n\
<div class=\"line\"><a name=\"l00169\"></a><span class=\"lineno\">  169</span>&#160;            <span class=\"keywordflow\">return</span> asin(v);</div>\n\
<div class=\"line\"><a name=\"l00170\"></a><span class=\"lineno\">  170</span>&#160;<span class=\"preprocessor\">#endif</span></div>\n\
<div class=\"line\"><a name=\"l00171\"></a><span class=\"lineno\">  171</span>&#160;}</div>\n\
<div class=\"line\"><a name=\"l00172\"></a><span class=\"lineno\">  172</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00173\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./cpp_ref/qmath_8h.html#a49dfe265837a2492d8feca2e20c9cff5\">  173</a></span>&#160;<span class=\"keyword\">inline</span> qreal <a class=\"code\" href=\"#!/url=./cpp_ref/qmath_8h.html#a49dfe265837a2492d8feca2e20c9cff5\">qAtan</a>(qreal <a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a14cfbe2fc2234f5504618905b69d1e06\">v</a>)</div>\n\
<div class=\"line\"><a name=\"l00174\"></a><span class=\"lineno\">  174</span>&#160;{</div>\n\
<div class=\"line\"><a name=\"l00175\"></a><span class=\"lineno\">  175</span>&#160;<span class=\"preprocessor\">#ifdef Q_OS_SYMBIAN</span></div>\n\
<div class=\"line\"><a name=\"l00176\"></a><span class=\"lineno\">  176</span>&#160;    TReal atan_v;</div>\n\
<div class=\"line\"><a name=\"l00177\"></a><span class=\"lineno\">  177</span>&#160;    Math::ATan(atan_v, static_cast&lt;TReal&gt;(v));</div>\n\
<div class=\"line\"><a name=\"l00178\"></a><span class=\"lineno\">  178</span>&#160;    <span class=\"keywordflow\">return</span> <span class=\"keyword\">static_cast&lt;</span>qreal<span class=\"keyword\">&gt;</span>(atan_v);</div>\n\
<div class=\"line\"><a name=\"l00179\"></a><span class=\"lineno\">  179</span>&#160;<span class=\"preprocessor\">#else</span></div>\n\
<div class=\"line\"><a name=\"l00180\"></a><span class=\"lineno\">  180</span>&#160;<span class=\"preprocessor\">#    ifdef QT_USE_MATH_H_FLOATS</span></div>\n\
<div class=\"line\"><a name=\"l00181\"></a><span class=\"lineno\">  181</span>&#160;        <span class=\"keywordflow\">if</span>(<span class=\"keyword\">sizeof</span>(qreal) == <span class=\"keyword\">sizeof</span>(float))</div>\n\
<div class=\"line\"><a name=\"l00182\"></a><span class=\"lineno\">  182</span>&#160;            <span class=\"keywordflow\">return</span> atanf(<span class=\"keywordtype\">float</span>(v));</div>\n\
<div class=\"line\"><a name=\"l00183\"></a><span class=\"lineno\">  183</span>&#160;        <span class=\"keywordflow\">else</span></div>\n\
<div class=\"line\"><a name=\"l00184\"></a><span class=\"lineno\">  184</span>&#160;<span class=\"preprocessor\">#    endif</span></div>\n\
<div class=\"line\"><a name=\"l00185\"></a><span class=\"lineno\">  185</span>&#160;            <span class=\"keywordflow\">return</span> atan(v);</div>\n\
<div class=\"line\"><a name=\"l00186\"></a><span class=\"lineno\">  186</span>&#160;<span class=\"preprocessor\">#endif</span></div>\n\
<div class=\"line\"><a name=\"l00187\"></a><span class=\"lineno\">  187</span>&#160;}</div>\n\
<div class=\"line\"><a name=\"l00188\"></a><span class=\"lineno\">  188</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00189\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./cpp_ref/qmath_8h.html#a4599945d585da9762e4e8a698b036b37\">  189</a></span>&#160;<span class=\"keyword\">inline</span> qreal <a class=\"code\" href=\"#!/url=./cpp_ref/qmath_8h.html#a4599945d585da9762e4e8a698b036b37\">qAtan2</a>(qreal <a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a09b61c9254503800358fe9680a997626\">x</a>, qreal <a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#af21ddfd4e51a5f5a4d8e60f8b9177b98\">y</a>)</div>\n\
<div class=\"line\"><a name=\"l00190\"></a><span class=\"lineno\">  190</span>&#160;{</div>\n\
<div class=\"line\"><a name=\"l00191\"></a><span class=\"lineno\">  191</span>&#160;<span class=\"preprocessor\">#ifdef Q_OS_SYMBIAN</span></div>\n\
<div class=\"line\"><a name=\"l00192\"></a><span class=\"lineno\">  192</span>&#160;    TReal atan2_v;</div>\n\
<div class=\"line\"><a name=\"l00193\"></a><span class=\"lineno\">  193</span>&#160;    Math::ATan(atan2_v, static_cast&lt;TReal&gt;(x), static_cast&lt;TReal&gt;(y));</div>\n\
<div class=\"line\"><a name=\"l00194\"></a><span class=\"lineno\">  194</span>&#160;    <span class=\"keywordflow\">return</span> <span class=\"keyword\">static_cast&lt;</span>qreal<span class=\"keyword\">&gt;</span>(atan2_v);</div>\n\
<div class=\"line\"><a name=\"l00195\"></a><span class=\"lineno\">  195</span>&#160;<span class=\"preprocessor\">#else</span></div>\n\
<div class=\"line\"><a name=\"l00196\"></a><span class=\"lineno\">  196</span>&#160;<span class=\"preprocessor\">#    ifdef QT_USE_MATH_H_FLOATS</span></div>\n\
<div class=\"line\"><a name=\"l00197\"></a><span class=\"lineno\">  197</span>&#160;        <span class=\"keywordflow\">if</span>(<span class=\"keyword\">sizeof</span>(qreal) == <span class=\"keyword\">sizeof</span>(float))</div>\n\
<div class=\"line\"><a name=\"l00198\"></a><span class=\"lineno\">  198</span>&#160;            <span class=\"keywordflow\">return</span> atan2f(<span class=\"keywordtype\">float</span>(x), <span class=\"keywordtype\">float</span>(y));</div>\n\
<div class=\"line\"><a name=\"l00199\"></a><span class=\"lineno\">  199</span>&#160;        <span class=\"keywordflow\">else</span></div>\n\
<div class=\"line\"><a name=\"l00200\"></a><span class=\"lineno\">  200</span>&#160;<span class=\"preprocessor\">#    endif</span></div>\n\
<div class=\"line\"><a name=\"l00201\"></a><span class=\"lineno\">  201</span>&#160;            <span class=\"keywordflow\">return</span> atan2(x, y);</div>\n\
<div class=\"line\"><a name=\"l00202\"></a><span class=\"lineno\">  202</span>&#160;<span class=\"preprocessor\">#endif</span></div>\n\
<div class=\"line\"><a name=\"l00203\"></a><span class=\"lineno\">  203</span>&#160;}</div>\n\
<div class=\"line\"><a name=\"l00204\"></a><span class=\"lineno\">  204</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00205\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./cpp_ref/qmath_8h.html#a43971090fe29537a7c131cea8402964d\">  205</a></span>&#160;<span class=\"keyword\">inline</span> qreal <a class=\"code\" href=\"#!/url=./cpp_ref/qmath_8h.html#a43971090fe29537a7c131cea8402964d\">qSqrt</a>(qreal <a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a14cfbe2fc2234f5504618905b69d1e06\">v</a>)</div>\n\
<div class=\"line\"><a name=\"l00206\"></a><span class=\"lineno\">  206</span>&#160;{</div>\n\
<div class=\"line\"><a name=\"l00207\"></a><span class=\"lineno\">  207</span>&#160;<span class=\"preprocessor\">#ifdef Q_OS_SYMBIAN</span></div>\n\
<div class=\"line\"><a name=\"l00208\"></a><span class=\"lineno\">  208</span>&#160;    TReal sqrt_v;</div>\n\
<div class=\"line\"><a name=\"l00209\"></a><span class=\"lineno\">  209</span>&#160;    Math::Sqrt(sqrt_v, static_cast&lt;TReal&gt;(v));</div>\n\
<div class=\"line\"><a name=\"l00210\"></a><span class=\"lineno\">  210</span>&#160;    <span class=\"keywordflow\">return</span> <span class=\"keyword\">static_cast&lt;</span>qreal<span class=\"keyword\">&gt;</span>(sqrt_v);</div>\n\
<div class=\"line\"><a name=\"l00211\"></a><span class=\"lineno\">  211</span>&#160;<span class=\"preprocessor\">#else</span></div>\n\
<div class=\"line\"><a name=\"l00212\"></a><span class=\"lineno\">  212</span>&#160;<span class=\"preprocessor\">#    ifdef QT_USE_MATH_H_FLOATS</span></div>\n\
<div class=\"line\"><a name=\"l00213\"></a><span class=\"lineno\">  213</span>&#160;        <span class=\"keywordflow\">if</span> (<span class=\"keyword\">sizeof</span>(qreal) == <span class=\"keyword\">sizeof</span>(float))</div>\n\
<div class=\"line\"><a name=\"l00214\"></a><span class=\"lineno\">  214</span>&#160;            <span class=\"keywordflow\">return</span> sqrtf(<span class=\"keywordtype\">float</span>(v));</div>\n\
<div class=\"line\"><a name=\"l00215\"></a><span class=\"lineno\">  215</span>&#160;        <span class=\"keywordflow\">else</span></div>\n\
<div class=\"line\"><a name=\"l00216\"></a><span class=\"lineno\">  216</span>&#160;<span class=\"preprocessor\">#    endif</span></div>\n\
<div class=\"line\"><a name=\"l00217\"></a><span class=\"lineno\">  217</span>&#160;            <span class=\"keywordflow\">return</span> sqrt(v);</div>\n\
<div class=\"line\"><a name=\"l00218\"></a><span class=\"lineno\">  218</span>&#160;<span class=\"preprocessor\">#endif</span></div>\n\
<div class=\"line\"><a name=\"l00219\"></a><span class=\"lineno\">  219</span>&#160;}</div>\n\
<div class=\"line\"><a name=\"l00220\"></a><span class=\"lineno\">  220</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00221\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./cpp_ref/qmath_8h.html#aaedd5c923fc99d95be50ecf97df36e58\">  221</a></span>&#160;<span class=\"keyword\">inline</span> qreal <a class=\"code\" href=\"#!/url=./cpp_ref/qmath_8h.html#aaedd5c923fc99d95be50ecf97df36e58\">qLn</a>(qreal <a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a14cfbe2fc2234f5504618905b69d1e06\">v</a>)</div>\n\
<div class=\"line\"><a name=\"l00222\"></a><span class=\"lineno\">  222</span>&#160;{</div>\n\
<div class=\"line\"><a name=\"l00223\"></a><span class=\"lineno\">  223</span>&#160;<span class=\"preprocessor\">#ifdef QT_USE_MATH_H_FLOATS</span></div>\n\
<div class=\"line\"><a name=\"l00224\"></a><span class=\"lineno\">  224</span>&#160;    <span class=\"keywordflow\">if</span> (<span class=\"keyword\">sizeof</span>(qreal) == <span class=\"keyword\">sizeof</span>(<span class=\"keywordtype\">float</span>))</div>\n\
<div class=\"line\"><a name=\"l00225\"></a><span class=\"lineno\">  225</span>&#160;        <span class=\"keywordflow\">return</span> logf(<span class=\"keywordtype\">float</span>(v));</div>\n\
<div class=\"line\"><a name=\"l00226\"></a><span class=\"lineno\">  226</span>&#160;    <span class=\"keywordflow\">else</span></div>\n\
<div class=\"line\"><a name=\"l00227\"></a><span class=\"lineno\">  227</span>&#160;<span class=\"preprocessor\">#endif</span></div>\n\
<div class=\"line\"><a name=\"l00228\"></a><span class=\"lineno\">  228</span>&#160;        <span class=\"keywordflow\">return</span> log(v);</div>\n\
<div class=\"line\"><a name=\"l00229\"></a><span class=\"lineno\">  229</span>&#160;}</div>\n\
<div class=\"line\"><a name=\"l00230\"></a><span class=\"lineno\">  230</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00231\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./cpp_ref/qmath_8h.html#ac294e301f623bdf87dd083802e9a50d3\">  231</a></span>&#160;<span class=\"keyword\">inline</span> qreal <a class=\"code\" href=\"#!/url=./cpp_ref/qmath_8h.html#ac294e301f623bdf87dd083802e9a50d3\">qExp</a>(qreal <a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a14cfbe2fc2234f5504618905b69d1e06\">v</a>)</div>\n\
<div class=\"line\"><a name=\"l00232\"></a><span class=\"lineno\">  232</span>&#160;{</div>\n\
<div class=\"line\"><a name=\"l00233\"></a><span class=\"lineno\">  233</span>&#160;<span class=\"preprocessor\">#ifdef Q_OS_SYMBIAN</span></div>\n\
<div class=\"line\"><a name=\"l00234\"></a><span class=\"lineno\">  234</span>&#160;    TReal exp_v;</div>\n\
<div class=\"line\"><a name=\"l00235\"></a><span class=\"lineno\">  235</span>&#160;    Math::Exp(exp_v, static_cast&lt;TReal&gt;(v));</div>\n\
<div class=\"line\"><a name=\"l00236\"></a><span class=\"lineno\">  236</span>&#160;    <span class=\"keywordflow\">return</span> <span class=\"keyword\">static_cast&lt;</span>qreal<span class=\"keyword\">&gt;</span>(exp_v);</div>\n\
<div class=\"line\"><a name=\"l00237\"></a><span class=\"lineno\">  237</span>&#160;<span class=\"preprocessor\">#else</span></div>\n\
<div class=\"line\"><a name=\"l00238\"></a><span class=\"lineno\">  238</span>&#160;    <span class=\"comment\">// only one signature</span></div>\n\
<div class=\"line\"><a name=\"l00239\"></a><span class=\"lineno\">  239</span>&#160;    <span class=\"comment\">// exists, exp(double)</span></div>\n\
<div class=\"line\"><a name=\"l00240\"></a><span class=\"lineno\">  240</span>&#160;    <span class=\"keywordflow\">return</span> exp(v);</div>\n\
<div class=\"line\"><a name=\"l00241\"></a><span class=\"lineno\">  241</span>&#160;<span class=\"preprocessor\">#endif</span></div>\n\
<div class=\"line\"><a name=\"l00242\"></a><span class=\"lineno\">  242</span>&#160;}</div>\n\
<div class=\"line\"><a name=\"l00243\"></a><span class=\"lineno\">  243</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00244\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./cpp_ref/qmath_8h.html#adf3b86d06cce7a07bb49c1e06426a202\">  244</a></span>&#160;<span class=\"keyword\">inline</span> qreal <a class=\"code\" href=\"#!/url=./cpp_ref/qmath_8h.html#adf3b86d06cce7a07bb49c1e06426a202\">qPow</a>(qreal <a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a09b61c9254503800358fe9680a997626\">x</a>, qreal <a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#af21ddfd4e51a5f5a4d8e60f8b9177b98\">y</a>)</div>\n\
<div class=\"line\"><a name=\"l00245\"></a><span class=\"lineno\">  245</span>&#160;{</div>\n\
<div class=\"line\"><a name=\"l00246\"></a><span class=\"lineno\">  246</span>&#160;<span class=\"preprocessor\">#ifdef Q_OS_SYMBIAN</span></div>\n\
<div class=\"line\"><a name=\"l00247\"></a><span class=\"lineno\">  247</span>&#160;    TReal pow_v;</div>\n\
<div class=\"line\"><a name=\"l00248\"></a><span class=\"lineno\">  248</span>&#160;    Math::Pow(pow_v, static_cast&lt;TReal&gt;(x), static_cast&lt;TReal&gt;(y));</div>\n\
<div class=\"line\"><a name=\"l00249\"></a><span class=\"lineno\">  249</span>&#160;    <span class=\"keywordflow\">return</span> <span class=\"keyword\">static_cast&lt;</span>qreal<span class=\"keyword\">&gt;</span>(pow_v);</div>\n\
<div class=\"line\"><a name=\"l00250\"></a><span class=\"lineno\">  250</span>&#160;<span class=\"preprocessor\">#else</span></div>\n\
<div class=\"line\"><a name=\"l00251\"></a><span class=\"lineno\">  251</span>&#160;<span class=\"preprocessor\">#    ifdef QT_USE_MATH_H_FLOATS</span></div>\n\
<div class=\"line\"><a name=\"l00252\"></a><span class=\"lineno\">  252</span>&#160;        <span class=\"keywordflow\">if</span> (<span class=\"keyword\">sizeof</span>(qreal) == <span class=\"keyword\">sizeof</span>(float))</div>\n\
<div class=\"line\"><a name=\"l00253\"></a><span class=\"lineno\">  253</span>&#160;            <span class=\"keywordflow\">return</span> powf(<span class=\"keywordtype\">float</span>(x), <span class=\"keywordtype\">float</span>(y));</div>\n\
<div class=\"line\"><a name=\"l00254\"></a><span class=\"lineno\">  254</span>&#160;        <span class=\"keywordflow\">else</span></div>\n\
<div class=\"line\"><a name=\"l00255\"></a><span class=\"lineno\">  255</span>&#160;<span class=\"preprocessor\">#    endif</span></div>\n\
<div class=\"line\"><a name=\"l00256\"></a><span class=\"lineno\">  256</span>&#160;            <span class=\"keywordflow\">return</span> pow(x, y);</div>\n\
<div class=\"line\"><a name=\"l00257\"></a><span class=\"lineno\">  257</span>&#160;<span class=\"preprocessor\">#endif</span></div>\n\
<div class=\"line\"><a name=\"l00258\"></a><span class=\"lineno\">  258</span>&#160;}</div>\n\
<div class=\"line\"><a name=\"l00259\"></a><span class=\"lineno\">  259</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00260\"></a><span class=\"lineno\">  260</span>&#160;<span class=\"preprocessor\">#ifndef M_PI</span></div>\n\
<div class=\"line\"><a name=\"l00261\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./cpp_ref/qmath_8h.html#ae71449b1cc6e6250b91f539153a7a0d3\">  261</a></span>&#160;<span class=\"preprocessor\">#define M_PI (3.14159265358979323846)</span></div>\n\
<div class=\"line\"><a name=\"l00262\"></a><span class=\"lineno\">  262</span>&#160;<span class=\"preprocessor\">#endif</span></div>\n\
<div class=\"line\"><a name=\"l00263\"></a><span class=\"lineno\">  263</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00264\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./cpp_ref/qmath_8h.html#a24691c655fbb7f37b1f544c14e5f47ee\">  264</a></span>&#160;<span class=\"keyword\">inline</span> qreal <a class=\"code\" href=\"#!/url=./cpp_ref/qmath_8h.html#a24691c655fbb7f37b1f544c14e5f47ee\">qFastSin</a>(qreal <a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a09b61c9254503800358fe9680a997626\">x</a>)</div>\n\
<div class=\"line\"><a name=\"l00265\"></a><span class=\"lineno\">  265</span>&#160;{</div>\n\
<div class=\"line\"><a name=\"l00266\"></a><span class=\"lineno\">  266</span>&#160;    <span class=\"keywordtype\">int</span> si = <a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#aa813ad7a4a00cda401ffd0c336154620\">int</a>(x * (0.5 * <a class=\"code\" href=\"#!/url=./cpp_ref/qmath_8h.html#a1ac42b3a6eddd6a9d82fa4fff0c073f3\">QT_SINE_TABLE_SIZE</a> / <a class=\"code\" href=\"#!/url=./cpp_ref/qmath_8h.html#ae71449b1cc6e6250b91f539153a7a0d3\">M_PI</a>)); <span class=\"comment\">// Would be more accurate with qRound, but slower.</span></div>\n\
<div class=\"line\"><a name=\"l00267\"></a><span class=\"lineno\">  267</span>&#160;    qreal d = x - si * (2.0 * <a class=\"code\" href=\"#!/url=./cpp_ref/qmath_8h.html#ae71449b1cc6e6250b91f539153a7a0d3\">M_PI</a> / <a class=\"code\" href=\"#!/url=./cpp_ref/qmath_8h.html#a1ac42b3a6eddd6a9d82fa4fff0c073f3\">QT_SINE_TABLE_SIZE</a>);</div>\n\
<div class=\"line\"><a name=\"l00268\"></a><span class=\"lineno\">  268</span>&#160;    <span class=\"keywordtype\">int</span> ci = si + <a class=\"code\" href=\"#!/url=./cpp_ref/qmath_8h.html#a1ac42b3a6eddd6a9d82fa4fff0c073f3\">QT_SINE_TABLE_SIZE</a> / 4;</div>\n\
<div class=\"line\"><a name=\"l00269\"></a><span class=\"lineno\">  269</span>&#160;    si &amp;= <a class=\"code\" href=\"#!/url=./cpp_ref/qmath_8h.html#a1ac42b3a6eddd6a9d82fa4fff0c073f3\">QT_SINE_TABLE_SIZE</a> - 1;</div>\n\
<div class=\"line\"><a name=\"l00270\"></a><span class=\"lineno\">  270</span>&#160;    ci &amp;= <a class=\"code\" href=\"#!/url=./cpp_ref/qmath_8h.html#a1ac42b3a6eddd6a9d82fa4fff0c073f3\">QT_SINE_TABLE_SIZE</a> - 1;</div>\n\
<div class=\"line\"><a name=\"l00271\"></a><span class=\"lineno\">  271</span>&#160;    <span class=\"keywordflow\">return</span> qt_sine_table[si] + (qt_sine_table[ci] - 0.5 * qt_sine_table[si] * d) * d;</div>\n\
<div class=\"line\"><a name=\"l00272\"></a><span class=\"lineno\">  272</span>&#160;}</div>\n\
<div class=\"line\"><a name=\"l00273\"></a><span class=\"lineno\">  273</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00274\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./cpp_ref/qmath_8h.html#a3c57eb12ea2ed062b4441a95e5e4b50f\">  274</a></span>&#160;<span class=\"keyword\">inline</span> qreal <a class=\"code\" href=\"#!/url=./cpp_ref/qmath_8h.html#a3c57eb12ea2ed062b4441a95e5e4b50f\">qFastCos</a>(qreal <a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a09b61c9254503800358fe9680a997626\">x</a>)</div>\n\
<div class=\"line\"><a name=\"l00275\"></a><span class=\"lineno\">  275</span>&#160;{</div>\n\
<div class=\"line\"><a name=\"l00276\"></a><span class=\"lineno\">  276</span>&#160;    <span class=\"keywordtype\">int</span> ci = <a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#aa813ad7a4a00cda401ffd0c336154620\">int</a>(x * (0.5 * <a class=\"code\" href=\"#!/url=./cpp_ref/qmath_8h.html#a1ac42b3a6eddd6a9d82fa4fff0c073f3\">QT_SINE_TABLE_SIZE</a> / <a class=\"code\" href=\"#!/url=./cpp_ref/qmath_8h.html#ae71449b1cc6e6250b91f539153a7a0d3\">M_PI</a>)); <span class=\"comment\">// Would be more accurate with qRound, but slower.</span></div>\n\
<div class=\"line\"><a name=\"l00277\"></a><span class=\"lineno\">  277</span>&#160;    qreal d = x - ci * (2.0 * <a class=\"code\" href=\"#!/url=./cpp_ref/qmath_8h.html#ae71449b1cc6e6250b91f539153a7a0d3\">M_PI</a> / <a class=\"code\" href=\"#!/url=./cpp_ref/qmath_8h.html#a1ac42b3a6eddd6a9d82fa4fff0c073f3\">QT_SINE_TABLE_SIZE</a>);</div>\n\
<div class=\"line\"><a name=\"l00278\"></a><span class=\"lineno\">  278</span>&#160;    <span class=\"keywordtype\">int</span> si = ci + <a class=\"code\" href=\"#!/url=./cpp_ref/qmath_8h.html#a1ac42b3a6eddd6a9d82fa4fff0c073f3\">QT_SINE_TABLE_SIZE</a> / 4;</div>\n\
<div class=\"line\"><a name=\"l00279\"></a><span class=\"lineno\">  279</span>&#160;    si &amp;= <a class=\"code\" href=\"#!/url=./cpp_ref/qmath_8h.html#a1ac42b3a6eddd6a9d82fa4fff0c073f3\">QT_SINE_TABLE_SIZE</a> - 1;</div>\n\
<div class=\"line\"><a name=\"l00280\"></a><span class=\"lineno\">  280</span>&#160;    ci &amp;= <a class=\"code\" href=\"#!/url=./cpp_ref/qmath_8h.html#a1ac42b3a6eddd6a9d82fa4fff0c073f3\">QT_SINE_TABLE_SIZE</a> - 1;</div>\n\
<div class=\"line\"><a name=\"l00281\"></a><span class=\"lineno\">  281</span>&#160;    <span class=\"keywordflow\">return</span> qt_sine_table[si] - (qt_sine_table[ci] + 0.5 * qt_sine_table[si] * d) * d;</div>\n\
<div class=\"line\"><a name=\"l00282\"></a><span class=\"lineno\">  282</span>&#160;}</div>\n\
<div class=\"line\"><a name=\"l00283\"></a><span class=\"lineno\">  283</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00284\"></a><span class=\"lineno\">  284</span>&#160;<a class=\"code\" href=\"#!/url=./cpp_ref/qglobal_8h.html#af0211888b9fea89f8a616cd6566c521e\">QT_END_NAMESPACE</a></div>\n\
<div class=\"line\"><a name=\"l00285\"></a><span class=\"lineno\">  285</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00286\"></a><span class=\"lineno\">  286</span>&#160;<a class=\"code\" href=\"#!/url=./cpp_ref/qglobal_8h.html#ac10725c642e865540e4faaf733ff95ff\">QT_END_HEADER</a></div>\n\
<div class=\"line\"><a name=\"l00287\"></a><span class=\"lineno\">  287</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00288\"></a><span class=\"lineno\">  288</span>&#160;<span class=\"preprocessor\">#endif // QMATH_H</span></div>\n\
<div class=\"ttc\" id=\"math_8h_html\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/math_8h.html\">math.h</a></div></div>\n\
<div class=\"ttc\" id=\"_g_lee_8h_html_aa813ad7a4a00cda401ffd0c336154620\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/_g_lee_8h.html#aa813ad7a4a00cda401ffd0c336154620\">int</a></div><div class=\"ttdeci\">unsigned int(APIENTRYP PFNGLXGETAGPOFFSETMESAPROC)(const void *pointer)</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/_g_lee_8h_source.html#l10762\">GLee.h:10762</a></div></div>\n\
<div class=\"ttc\" id=\"_g_lee_8h_html_af21ddfd4e51a5f5a4d8e60f8b9177b98\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/_g_lee_8h.html#af21ddfd4e51a5f5a4d8e60f8b9177b98\">y</a></div><div class=\"ttdeci\">GLenum GLint GLint y</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/_g_lee_8h_source.html#l00876\">GLee.h:876</a></div></div>\n\
<div class=\"ttc\" id=\"qglobal_8h_html_af0211888b9fea89f8a616cd6566c521e\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/qglobal_8h.html#af0211888b9fea89f8a616cd6566c521e\">QT_END_NAMESPACE</a></div><div class=\"ttdeci\">#define QT_END_NAMESPACE</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qglobal_8h_source.html#l00128\">qglobal.h:128</a></div></div>\n\
<div class=\"ttc\" id=\"qmath_8h_html_ac294e301f623bdf87dd083802e9a50d3\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/qmath_8h.html#ac294e301f623bdf87dd083802e9a50d3\">qExp</a></div><div class=\"ttdeci\">qreal qExp(qreal v)</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qmath_8h_source.html#l00231\">qmath.h:231</a></div></div>\n\
<div class=\"ttc\" id=\"qmath_8h_html_aaedd5c923fc99d95be50ecf97df36e58\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/qmath_8h.html#aaedd5c923fc99d95be50ecf97df36e58\">qLn</a></div><div class=\"ttdeci\">qreal qLn(qreal v)</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qmath_8h_source.html#l00221\">qmath.h:221</a></div></div>\n\
<div class=\"ttc\" id=\"qmath_8h_html_a2de5641ae52db30e76eed8da1cec47c3\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/qmath_8h.html#a2de5641ae52db30e76eed8da1cec47c3\">qCeil</a></div><div class=\"ttdeci\">int qCeil(qreal v)</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qmath_8h_source.html#l00063\">qmath.h:63</a></div></div>\n\
<div class=\"ttc\" id=\"qglobal_8h_html_a22466069bc24124bf4d749ca253f5e2b\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/qglobal_8h.html#a22466069bc24124bf4d749ca253f5e2b\">QT_BEGIN_HEADER</a></div><div class=\"ttdeci\">#define QT_BEGIN_HEADER</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qglobal_8h_source.html#l00141\">qglobal.h:141</a></div></div>\n\
<div class=\"ttc\" id=\"qmath_8h_html_a90fd634f1cf1c03263337de01372c582\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/qmath_8h.html#a90fd634f1cf1c03263337de01372c582\">qFloor</a></div><div class=\"ttdeci\">int qFloor(qreal v)</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qmath_8h_source.html#l00073\">qmath.h:73</a></div></div>\n\
<div class=\"ttc\" id=\"qmath_8h_html_a24691c655fbb7f37b1f544c14e5f47ee\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/qmath_8h.html#a24691c655fbb7f37b1f544c14e5f47ee\">qFastSin</a></div><div class=\"ttdeci\">qreal qFastSin(qreal x)</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qmath_8h_source.html#l00264\">qmath.h:264</a></div></div>\n\
<div class=\"ttc\" id=\"qmath_8h_html_ae71449b1cc6e6250b91f539153a7a0d3\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/qmath_8h.html#ae71449b1cc6e6250b91f539153a7a0d3\">M_PI</a></div><div class=\"ttdeci\">#define M_PI</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qmath_8h_source.html#l00261\">qmath.h:261</a></div></div>\n\
<div class=\"ttc\" id=\"qglobal_8h_html_ae7344b820974b9f9f7cfedd5808bd3a0\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/qglobal_8h.html#ae7344b820974b9f9f7cfedd5808bd3a0\">QT_BEGIN_NAMESPACE</a></div><div class=\"ttdeci\">#define QT_BEGIN_NAMESPACE</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qglobal_8h_source.html#l00127\">qglobal.h:127</a></div></div>\n\
<div class=\"ttc\" id=\"qglobal_8h_html\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/qglobal_8h.html\">qglobal.h</a></div></div>\n\
<div class=\"ttc\" id=\"qmath_8h_html_abb1f20a4e4f80b3add0c1533bb744921\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/qmath_8h.html#abb1f20a4e4f80b3add0c1533bb744921\">qSin</a></div><div class=\"ttdeci\">qreal qSin(qreal v)</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qmath_8h_source.html#l00093\">qmath.h:93</a></div></div>\n\
<div class=\"ttc\" id=\"qmath_8h_html_ab9a370ad20b6dcee47de1d14ef2acb85\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/qmath_8h.html#ab9a370ad20b6dcee47de1d14ef2acb85\">qAsin</a></div><div class=\"ttdeci\">qreal qAsin(qreal v)</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qmath_8h_source.html#l00157\">qmath.h:157</a></div></div>\n\
<div class=\"ttc\" id=\"qmath_8h_html_a4599945d585da9762e4e8a698b036b37\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/qmath_8h.html#a4599945d585da9762e4e8a698b036b37\">qAtan2</a></div><div class=\"ttdeci\">qreal qAtan2(qreal x, qreal y)</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qmath_8h_source.html#l00189\">qmath.h:189</a></div></div>\n\
<div class=\"ttc\" id=\"_g_lee_8h_html_a09b61c9254503800358fe9680a997626\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/_g_lee_8h.html#a09b61c9254503800358fe9680a997626\">x</a></div><div class=\"ttdeci\">GLenum GLint x</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/_g_lee_8h_source.html#l00876\">GLee.h:876</a></div></div>\n\
<div class=\"ttc\" id=\"qmath_8h_html_adf3b86d06cce7a07bb49c1e06426a202\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/qmath_8h.html#adf3b86d06cce7a07bb49c1e06426a202\">qPow</a></div><div class=\"ttdeci\">qreal qPow(qreal x, qreal y)</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qmath_8h_source.html#l00244\">qmath.h:244</a></div></div>\n\
<div class=\"ttc\" id=\"_g_lee_8h_html_a14cfbe2fc2234f5504618905b69d1e06\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/_g_lee_8h.html#a14cfbe2fc2234f5504618905b69d1e06\">v</a></div><div class=\"ttdeci\">const GLdouble * v</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/_g_lee_8h_source.html#l01174\">GLee.h:1174</a></div></div>\n\
<div class=\"ttc\" id=\"qmath_8h_html_a49dfe265837a2492d8feca2e20c9cff5\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/qmath_8h.html#a49dfe265837a2492d8feca2e20c9cff5\">qAtan</a></div><div class=\"ttdeci\">qreal qAtan(qreal v)</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qmath_8h_source.html#l00173\">qmath.h:173</a></div></div>\n\
<div class=\"ttc\" id=\"qmath_8h_html_a1ac42b3a6eddd6a9d82fa4fff0c073f3\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/qmath_8h.html#a1ac42b3a6eddd6a9d82fa4fff0c073f3\">QT_SINE_TABLE_SIZE</a></div><div class=\"ttdeci\">#define QT_SINE_TABLE_SIZE</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qmath_8h_source.html#l00059\">qmath.h:59</a></div></div>\n\
<div class=\"ttc\" id=\"qmath_8h_html_a94143b1f9c72a196b1c1e60aab7d63aa\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/qmath_8h.html#a94143b1f9c72a196b1c1e60aab7d63aa\">qAcos</a></div><div class=\"ttdeci\">qreal qAcos(qreal v)</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qmath_8h_source.html#l00141\">qmath.h:141</a></div></div>\n\
<div class=\"ttc\" id=\"qmath_8h_html_a3c57eb12ea2ed062b4441a95e5e4b50f\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/qmath_8h.html#a3c57eb12ea2ed062b4441a95e5e4b50f\">qFastCos</a></div><div class=\"ttdeci\">qreal qFastCos(qreal x)</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qmath_8h_source.html#l00274\">qmath.h:274</a></div></div>\n\
<div class=\"ttc\" id=\"qmath_8h_html_a3e43b4c27d11701b766f2797258a2e30\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/qmath_8h.html#a3e43b4c27d11701b766f2797258a2e30\">qTan</a></div><div class=\"ttdeci\">qreal qTan(qreal v)</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qmath_8h_source.html#l00125\">qmath.h:125</a></div></div>\n\
<div class=\"ttc\" id=\"qmath_8h_html_a496bd29bd65dac6b7e5805e08a57c17b\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/qmath_8h.html#a496bd29bd65dac6b7e5805e08a57c17b\">qFabs</a></div><div class=\"ttdeci\">qreal qFabs(qreal v)</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qmath_8h_source.html#l00083\">qmath.h:83</a></div></div>\n\
<div class=\"ttc\" id=\"qmath_8h_html_a105e697128b5e57f517c3605d5a45847\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/qmath_8h.html#a105e697128b5e57f517c3605d5a45847\">qt_sine_table</a></div><div class=\"ttdeci\">Q_CORE_EXPORT const qreal qt_sine_table[QT_SINE_TABLE_SIZE]</div></div>\n\
<div class=\"ttc\" id=\"qglobal_8h_html_ac10725c642e865540e4faaf733ff95ff\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/qglobal_8h.html#ac10725c642e865540e4faaf733ff95ff\">QT_END_HEADER</a></div><div class=\"ttdeci\">#define QT_END_HEADER</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qglobal_8h_source.html#l00142\">qglobal.h:142</a></div></div>\n\
<div class=\"ttc\" id=\"qmath_8h_html_a4ccb11b3f855f8f7b8bb7a4255ab913e\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/qmath_8h.html#a4ccb11b3f855f8f7b8bb7a4255ab913e\">qCos</a></div><div class=\"ttdeci\">qreal qCos(qreal v)</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qmath_8h_source.html#l00109\">qmath.h:109</a></div></div>\n\
<div class=\"ttc\" id=\"qmath_8h_html_a43971090fe29537a7c131cea8402964d\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/qmath_8h.html#a43971090fe29537a7c131cea8402964d\">qSqrt</a></div><div class=\"ttdeci\">qreal qSqrt(qreal v)</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qmath_8h_source.html#l00205\">qmath.h:205</a></div></div>\n\
</div><!-- fragment --></div><!-- contents -->\n\
</div><!-- doc-content -->\n\
          <div class=\"footer-block\"><a href=\"../html/ac.cmtdialog.htm\" class=\"comments-anchor\" target=\"_blank\"><span class=\"comments-link\">Please send us your comment about this page</span></a></div></div>\n\
   </div></body>\n\
</html>\n\
";