var topic = "<!-- saved from url=(0024)http://docs.autodesk.com -->\n\
<html>\n\
   <head><script src=\"../scripts/yepnope.1.5.4-min.js\" type=\"text/javascript\"></script><script src=\"../scripts/lib/jquery-1.11.1.min.js\" type=\"text/javascript\"></script><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"><meta name=\"product\" content=\"MOBPRO\"><meta name=\"release\" content=\"2018\"><meta name=\"book\" content=\"GeneralUser\"><meta name=\"created\" content=\"2017-09-08\"><meta name=\"topicid\" content=\"GUID-02FA7DD3-6C7A-4C6A-B7BC-824765AE1CB2\"><meta name=\"topic-type\" content=\"concept\">\n\
      <title>Vertex Struct Reference</title>\n\
   \n\
\n\
</head>\n\
   <body height=\"100%\"><div class=\"body_content\" id=\"body-content\"><link rel=\"stylesheet\" type=\"text/css\" href=\"cpp_ref/navtree.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"cpp_ref/doxygen.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"cpp_ref/tabs.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"style/adsk.cpm.css\"><script language=\"javascript\">var index = \'index.html\';</script><script>$(document).ready(function() { yepnope.injectJs(\"./scripts/ac_common.js\"); });</script><script type=\"text/javascript\">\n\
var tocSystemNeedsToBeLoaded = typeof(cpp_ref_adsk_ref_toc) == \'undefined\';\n\
var weAreIn21 = $(\'div#main.view-active\').length;\n\
var tocPrefix = \'\';\n\
if (weAreIn21)\n\
{ tocPrefix = \'cpp_ref/\'; }\n\
function cpp_ref_initializeToc(forceTrigger) {\n\
    cpp_ref_adsk_ref_toc.initResizable();\n\
    cpp_ref_adsk_ref_toc.initNavTree(\'structmudbox_1_1_vertex.html\', tocPrefix);\n\
    dQuery(document).trigger(\'toc_initialized\');\n\
}\n\
if (tocSystemNeedsToBeLoaded)\n\
{\n\
	yepnope([{\n\
	load:[tocPrefix + \'json3.min.js\', tocPrefix + \'jquery.js\', tocPrefix + \'ref-toc-controller.js\', tocPrefix + \'dynsections.js\'],\n\
	complete: function() {\n\
	  if (typeof(dQuery) == \'undefined\')\n\
	  {\n\
	    dQuery = jQuery.noConflict(true);\n\
	  }\n\
	  else { jQuery.noConflict(true); }\n\
	  $(document).ready(cpp_ref_initializeToc);\n\
	}\n\
 	}])\n\
}\n\
if (!weAreIn21) { // if in AKN...\n\
$(window).load( function() {\n\
    setTimeout( function() {\n\
        var content = $(\'body > div\').not(\'#body-content\');     // take any divs under body that are not id=body-content\n\
        content.each( function() { \n\
            $(this).css( { \'padding-left\': $(this).css(\'margin-left\') } );       // and if they have any padding-left already, move it to margin-left.\n\
        } );\n\
        var width = cpp_ref_adsk_ref_toc.readFromStorage(\'width\');\n\
        content.css({marginLeft:parseInt(width)+6+\"px\"});\n\
    }, 100);\n\
} ); \n\
}\n\
</script><script>$(\"div#WidgetFloaterPanels,link[href*=\'microsofttranslator.com\'],script[src*=\'microsofttranslator.com\'],script[src*=\'bing.com\']\").remove();</script><script type=\'text/javascript\'>$(\"div#navigation,div#breadcrumbs,div#banner\").attr(\"translate\",\"no\"); var mtLocation = ((location && location.href && location.href.indexOf(\'https\') == 0)?\'https://ssl.microsofttranslator.com\':\'http://www.microsofttranslator.com\')+\'/ajax/v3/WidgetV3.ashx?ctf=True&ui=true&settings=Manual&from=en&hidelanguages=\'; yepnope.injectJs(mtLocation, function() {}, { charset:\'utf-8\', type:\'text/javascript\' } );</script><script>\n\
 if (!tocSystemNeedsToBeLoaded) { cpp_ref_initializeToc(); }\n\
 </script><!-- begin MT -->\n\
            \n\
            <div id=\'MicrosoftTranslatorWidget\' class=\'Dark\' style=\'float:right;z-index:100;color:white;background-color:#bbbbbb;height:58px;overflow:hidden\'></div>\n\
      <div>\n\
         <div class=\"head\">\n\
            <h1>Vertex Struct Reference</h1>\n\
         </div>\n\
\n\
    <div id=\"top\"><!-- Generated by Doxygen 1.8.10 -->\n\
  <div id=\"navrow1\" class=\"tabs\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./cpp_ref/index.html\"><span>Main&#160;Page</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/pages.html\"><span>Topics</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/modules.html\"><span>Modules</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/namespaces.html\"><span>Namespaces</span></a></li>\n\
      <li class=\"current\"><a href=\"#!/url=./cpp_ref/annotated.html\"><span>Classes</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/files.html\"><span>Files</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/examples.html\"><span>Examples</span></a></li>\n\
    </ul>\n\
  </div>\n\
  <div id=\"navrow2\" class=\"tabs2\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./cpp_ref/annotated.html\"><span>Class&#160;List</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/hierarchy.html\"><span>Class&#160;Hierarchy</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/functions.html\"><span>Class&#160;Members</span></a></li>\n\
    </ul>\n\
  </div>\n\
</div><!-- top -->\n\
<div id=\"side-nav\" class=\"ui-resizable side-nav-resizable\">\n\
  <div id=\"nav-tree\">\n\
    <div id=\"nav-tree-contents\">\n\
      <div id=\"nav-sync\" class=\"sync\"></div>\n\
    </div>\n\
  </div>\n\
  <div id=\"splitbar\" style=\"-moz-user-select:none;\" class=\"ui-resizable-handle\">\n\
  </div>\n\
</div>\n\
\n\
<div id=\"doc-content\">\n\
<div class=\"header\">\n\
  \n\
  <div class=\"headertitle\">\n\
<div class=\"title\">Vertex Struct Reference</div>  </div>\n\
<div id=\"OverviewLinksDiv\"><div id=\"dynsection-overview\" onclick=\"return toggleVisibility(this)\" class=\"dynheader closed\" style=\"cursor:pointer;\"><img id=\"dynsection-overview-trigger\" src=\"cpp_ref/closed.png\" alt=\"+\"> Related help topics: </div><div id=\"dynsection-overview-content\" class=\"dyncontent\" style=\"display:none;\"><ul class=\"overviewLinks\">\n\
<li class=\"overviewLink\"><a href=\"#!/url=./files/GUID-AB284533-1D41-4034-A9EC-F34A453FE1EA.htm\">Mesh and Topology</a></li>\n\
</ul></div></div>\n\
<div class=\"summary\">\n\
<a href=\"structmudbox_1_1_vertex.html#pub-methods\">Public Member Functions</a> &#124;\n\
<a href=\"structmudbox_1_1_vertex.html#pub-attribs\">Public Attributes</a>  </div></div><!--header-->\n\
<div class=\"contents\">\n\
\n\
<p><code>#include &lt;<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/mesh_8h_source.html\">mesh.h</a>&gt;</code></p>\n\
<a name=\"details\" id=\"details\"></a><h2 class=\"groupheader\">Class Description</h2>\n\
<div class=\"textblock\"><p>Represents a vertex point on a <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/classmudbox_1_1_mesh.html\" title=\"A Mesh is a collection of vertices organized into faces, and optional Texture Coordinate information...\">Mesh</a> with its associated data. </p>\n\
<p>A <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/structmudbox_1_1_vertex.html\" title=\"Represents a vertex point on a Mesh with its associated data. \">Vertex</a> has an x,y,z position in space, a normal, a \"Freeze\" value between 0.0 and 1.0, and a boolean flag saying whether or not the vertex is currently selected. Each <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/classmudbox_1_1_mesh.html\" title=\"A Mesh is a collection of vertices organized into faces, and optional Texture Coordinate information...\">Mesh</a> object contains a list of <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/structmudbox_1_1_vertex.html\" title=\"Represents a vertex point on a Mesh with its associated data. \">Vertex</a> objects. </p>\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/mesh_8h_source.html#l00056\">56</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/mesh_8h_source.html\">mesh.h</a>.</p>\n\
</div><table class=\"memberdecls\">\n\
<tr class=\"heading\"><td colspan=\"2\"><h2 class=\"groupheader\"><a name=\"pub-methods\"></a>\n\
Public Member Functions</h2></td></tr>\n\
<tr class=\"memitem:aac78269ab31a3881ad087be74c1babaf\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/structmudbox_1_1_vertex.html#aac78269ab31a3881ad087be74c1babaf\">Vertex</a> (<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a>)</td></tr>\n\
<tr class=\"separator:aac78269ab31a3881ad087be74c1babaf\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a2d27f5ef8a94c8d424478c364d3d92fb\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">float&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/structmudbox_1_1_vertex.html#a2d27f5ef8a94c8d424478c364d3d92fb\">Freeze</a> (<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a>) const </td></tr>\n\
<tr class=\"memdesc:a2d27f5ef8a94c8d424478c364d3d92fb\"><td class=\"mdescLeft\">&#160;</td><td class=\"mdescRight\">Returns the Freeze value of the <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/structmudbox_1_1_vertex.html\" title=\"Represents a vertex point on a Mesh with its associated data. \">Vertex</a> (between 0.0 and 1.0, where 0.0 is not frozen)  <a href=\"structmudbox_1_1_vertex.html#a2d27f5ef8a94c8d424478c364d3d92fb\">More...</a><br></td></tr>\n\
<tr class=\"separator:a2d27f5ef8a94c8d424478c364d3d92fb\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a874ca68d5032eba661eaedfc16136284\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/structmudbox_1_1_vertex.html#a874ca68d5032eba661eaedfc16136284\">SetFreeze</a> (float fFreeze)</td></tr>\n\
<tr class=\"memdesc:a874ca68d5032eba661eaedfc16136284\"><td class=\"mdescLeft\">&#160;</td><td class=\"mdescRight\">Sets the Freeze value of the <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/structmudbox_1_1_vertex.html\" title=\"Represents a vertex point on a Mesh with its associated data. \">Vertex</a> (between 0.0 and 1.0, where 0.0 is not frozen)  <a href=\"structmudbox_1_1_vertex.html#a874ca68d5032eba661eaedfc16136284\">More...</a><br></td></tr>\n\
<tr class=\"separator:a874ca68d5032eba661eaedfc16136284\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a7154832a40072405965804abc4ec9cd1\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">float&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/structmudbox_1_1_vertex.html#a7154832a40072405965804abc4ec9cd1\">Mask</a> (<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a>) const </td></tr>\n\
<tr class=\"memdesc:a7154832a40072405965804abc4ec9cd1\"><td class=\"mdescLeft\">&#160;</td><td class=\"mdescRight\">Do not use this method.  <a href=\"structmudbox_1_1_vertex.html#a7154832a40072405965804abc4ec9cd1\">More...</a><br></td></tr>\n\
<tr class=\"separator:a7154832a40072405965804abc4ec9cd1\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:aa7af7a2a7be25f153289aba1a1c1268a\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/structmudbox_1_1_vertex.html#aa7af7a2a7be25f153289aba1a1c1268a\">SetMask</a> (float fMask)</td></tr>\n\
<tr class=\"memdesc:aa7af7a2a7be25f153289aba1a1c1268a\"><td class=\"mdescLeft\">&#160;</td><td class=\"mdescRight\">Do not use this method.  <a href=\"structmudbox_1_1_vertex.html#aa7af7a2a7be25f153289aba1a1c1268a\">More...</a><br></td></tr>\n\
<tr class=\"separator:aa7af7a2a7be25f153289aba1a1c1268a\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a584ab12fc27993f21d31639c6653ab19\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/structmudbox_1_1_vertex.html#a584ab12fc27993f21d31639c6653ab19\">IsSelected</a> (<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a>) const </td></tr>\n\
<tr class=\"memdesc:a584ab12fc27993f21d31639c6653ab19\"><td class=\"mdescLeft\">&#160;</td><td class=\"mdescRight\">Returns the Selected state of the <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/structmudbox_1_1_vertex.html\" title=\"Represents a vertex point on a Mesh with its associated data. \">Vertex</a> (true or false)  <a href=\"structmudbox_1_1_vertex.html#a584ab12fc27993f21d31639c6653ab19\">More...</a><br></td></tr>\n\
<tr class=\"separator:a584ab12fc27993f21d31639c6653ab19\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a320354580ef8105ec229b49300814066\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/structmudbox_1_1_vertex.html#a320354580ef8105ec229b49300814066\">SetSelected</a> (bool bSelected)</td></tr>\n\
<tr class=\"memdesc:a320354580ef8105ec229b49300814066\"><td class=\"mdescLeft\">&#160;</td><td class=\"mdescRight\">Sets the Selected state of the <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/structmudbox_1_1_vertex.html\" title=\"Represents a vertex point on a Mesh with its associated data. \">Vertex</a> (true or false)  <a href=\"structmudbox_1_1_vertex.html#a320354580ef8105ec229b49300814066\">More...</a><br></td></tr>\n\
<tr class=\"separator:a320354580ef8105ec229b49300814066\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
</table><table class=\"memberdecls\">\n\
<tr class=\"heading\"><td colspan=\"2\"><h2 class=\"groupheader\"><a name=\"pub-attribs\"></a>\n\
Public Attributes</h2></td></tr>\n\
<tr class=\"memitem:a8dfc24d64da486c8ca2bd9bf6d743de3\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/classmudbox_1_1_vector.html\">Vector</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/structmudbox_1_1_vertex.html#a8dfc24d64da486c8ca2bd9bf6d743de3\">m_vPos</a></td></tr>\n\
<tr class=\"separator:a8dfc24d64da486c8ca2bd9bf6d743de3\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a2b3c32dc59d4c119314b73ee8bbc8beb\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">unsigned <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a0067a505d12f13572b26d9535c23b671\">int</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/structmudbox_1_1_vertex.html#a2b3c32dc59d4c119314b73ee8bbc8beb\">m_iStrokeID</a></td></tr>\n\
<tr class=\"separator:a2b3c32dc59d4c119314b73ee8bbc8beb\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:abbab52b63f9818cb9b30a0cecc12d99e\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">unsigned short&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/structmudbox_1_1_vertex.html#abbab52b63f9818cb9b30a0cecc12d99e\">m_iStates</a></td></tr>\n\
<tr class=\"separator:abbab52b63f9818cb9b30a0cecc12d99e\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
</table>\n\
<h2 class=\"groupheader\">Constructor &amp; Destructor Documentation</h2>\n\
<a class=\"anchor\" id=\"aac78269ab31a3881ad087be74c1babaf\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/structmudbox_1_1_vertex.html\">Vertex</a> </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a>&#160;</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">inline</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/mesh_8h_source.html#l00058\">58</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/mesh_8h_source.html\">mesh.h</a>.</p>\n\
<div class=\"fragment\"><div class=\"line\"><a name=\"l00058\"></a><span class=\"lineno\">   58</span>&#160;{ <a class=\"code\" href=\"#!/url=./cpp_ref/structmudbox_1_1_vertex.html#a2b3c32dc59d4c119314b73ee8bbc8beb\">m_iStrokeID</a> = 0; <a class=\"code\" href=\"#!/url=./cpp_ref/structmudbox_1_1_vertex.html#abbab52b63f9818cb9b30a0cecc12d99e\">m_iStates</a> = 0; };</div>\n\
<div class=\"ttc\" id=\"structmudbox_1_1_vertex_html_abbab52b63f9818cb9b30a0cecc12d99e\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/structmudbox_1_1_vertex.html#abbab52b63f9818cb9b30a0cecc12d99e\">mudbox::Vertex::m_iStates</a></div><div class=\"ttdeci\">unsigned short m_iStates</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/mesh_8h_source.html#l00068\">mesh.h:68</a></div></div>\n\
<div class=\"ttc\" id=\"structmudbox_1_1_vertex_html_a2b3c32dc59d4c119314b73ee8bbc8beb\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/structmudbox_1_1_vertex.html#a2b3c32dc59d4c119314b73ee8bbc8beb\">mudbox::Vertex::m_iStrokeID</a></div><div class=\"ttdeci\">unsigned int m_iStrokeID</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/mesh_8h_source.html#l00062\">mesh.h:62</a></div></div>\n\
</div><!-- fragment -->\n\
</div>\n\
</div>\n\
<h2 class=\"groupheader\">Member Function Documentation</h2>\n\
<a class=\"anchor\" id=\"a2d27f5ef8a94c8d424478c364d3d92fb\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">float Freeze </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a>&#160;</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">inline</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Returns the Freeze value of the <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/structmudbox_1_1_vertex.html\" title=\"Represents a vertex point on a Mesh with its associated data. \">Vertex</a> (between 0.0 and 1.0, where 0.0 is not frozen) </p>\n\
<p>The freeze value is used to lock parts of the mesh so they are less affected by sculpting brushes. It is the responsibility of every sculpt brush to take into account the Freeze values on vertices it is modifying. </p>\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/mesh_8h_source.html#l00076\">76</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/mesh_8h_source.html\">mesh.h</a>.</p>\n\
<div class=\"fragment\"><div class=\"line\"><a name=\"l00077\"></a><span class=\"lineno\">   77</span>&#160;        { <span class=\"keywordflow\">return</span> ((<span class=\"keywordtype\">float</span>)(<span class=\"keywordtype\">unsigned</span> <span class=\"keywordtype\">char</span>)(<a class=\"code\" href=\"#!/url=./cpp_ref/structmudbox_1_1_vertex.html#abbab52b63f9818cb9b30a0cecc12d99e\">m_iStates</a>&amp;0x7f)) * (1.0f/0x7f); };</div>\n\
<div class=\"ttc\" id=\"structmudbox_1_1_vertex_html_abbab52b63f9818cb9b30a0cecc12d99e\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/structmudbox_1_1_vertex.html#abbab52b63f9818cb9b30a0cecc12d99e\">mudbox::Vertex::m_iStates</a></div><div class=\"ttdeci\">unsigned short m_iStates</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/mesh_8h_source.html#l00068\">mesh.h:68</a></div></div>\n\
</div><!-- fragment -->\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a874ca68d5032eba661eaedfc16136284\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a> SetFreeze </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">float&#160;</td>\n\
          <td class=\"paramname\"><em>fFreeze</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">inline</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Sets the Freeze value of the <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/structmudbox_1_1_vertex.html\" title=\"Represents a vertex point on a Mesh with its associated data. \">Vertex</a> (between 0.0 and 1.0, where 0.0 is not frozen) </p>\n\
<p>The freeze value is used to lock parts of the mesh so they are less affected by sculpting brushes. It is the responsibility of every sculpt brush to take into account the Freeze values on vertices it is modifying. </p>\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/mesh_8h_source.html#l00085\">85</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/mesh_8h_source.html\">mesh.h</a>.</p>\n\
<div class=\"fragment\"><div class=\"line\"><a name=\"l00086\"></a><span class=\"lineno\">   86</span>&#160;        { <a class=\"code\" href=\"#!/url=./cpp_ref/structmudbox_1_1_vertex.html#abbab52b63f9818cb9b30a0cecc12d99e\">m_iStates</a> = (<a class=\"code\" href=\"#!/url=./cpp_ref/structmudbox_1_1_vertex.html#abbab52b63f9818cb9b30a0cecc12d99e\">m_iStates</a>&amp;0xff80)+(<span class=\"keywordtype\">unsigned</span> <span class=\"keywordtype\">int</span>)(0x7f*fFreeze); };</div>\n\
<div class=\"ttc\" id=\"structmudbox_1_1_vertex_html_abbab52b63f9818cb9b30a0cecc12d99e\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/structmudbox_1_1_vertex.html#abbab52b63f9818cb9b30a0cecc12d99e\">mudbox::Vertex::m_iStates</a></div><div class=\"ttdeci\">unsigned short m_iStates</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/mesh_8h_source.html#l00068\">mesh.h:68</a></div></div>\n\
</div><!-- fragment -->\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a7154832a40072405965804abc4ec9cd1\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">float Mask </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a>&#160;</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">inline</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Do not use this method. </p>\n\
<p><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/classmudbox_1_1_layer.html\" title=\"This is the base class for anything which is an element of a list with a fixed order and a transparen...\">Layer</a> masks should be accessed via <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/classmudbox_1_1_layer_mesh_data.html#a2e45c8c378aa12d1293a0dd09e2c85d8\" title=\"Returns the mask of a vertex in the layer. \">LayerMeshData::VertexMask</a>. </p>\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/mesh_8h_source.html#l00090\">90</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/mesh_8h_source.html\">mesh.h</a>.</p>\n\
<div class=\"fragment\"><div class=\"line\"><a name=\"l00091\"></a><span class=\"lineno\">   91</span>&#160;        { <span class=\"keywordflow\">return</span> ((<span class=\"keywordtype\">float</span>)(<span class=\"keywordtype\">unsigned</span> <span class=\"keywordtype\">char</span>)(<a class=\"code\" href=\"#!/url=./cpp_ref/structmudbox_1_1_vertex.html#abbab52b63f9818cb9b30a0cecc12d99e\">m_iStates</a>&gt;&gt;8)) * (1.0f/0xff); };</div>\n\
<div class=\"ttc\" id=\"structmudbox_1_1_vertex_html_abbab52b63f9818cb9b30a0cecc12d99e\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/structmudbox_1_1_vertex.html#abbab52b63f9818cb9b30a0cecc12d99e\">mudbox::Vertex::m_iStates</a></div><div class=\"ttdeci\">unsigned short m_iStates</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/mesh_8h_source.html#l00068\">mesh.h:68</a></div></div>\n\
</div><!-- fragment -->\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"aa7af7a2a7be25f153289aba1a1c1268a\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a> SetMask </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">float&#160;</td>\n\
          <td class=\"paramname\"><em>fMask</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">inline</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Do not use this method. </p>\n\
<p><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/classmudbox_1_1_layer.html\" title=\"This is the base class for anything which is an element of a list with a fixed order and a transparen...\">Layer</a> masks should be accessed via <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/classmudbox_1_1_layer_mesh_data.html#a2e45c8c378aa12d1293a0dd09e2c85d8\" title=\"Returns the mask of a vertex in the layer. \">LayerMeshData::VertexMask</a>. </p>\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/mesh_8h_source.html#l00095\">95</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/mesh_8h_source.html\">mesh.h</a>.</p>\n\
<div class=\"fragment\"><div class=\"line\"><a name=\"l00096\"></a><span class=\"lineno\">   96</span>&#160;        { <a class=\"code\" href=\"#!/url=./cpp_ref/structmudbox_1_1_vertex.html#abbab52b63f9818cb9b30a0cecc12d99e\">m_iStates</a> = (<a class=\"code\" href=\"#!/url=./cpp_ref/structmudbox_1_1_vertex.html#abbab52b63f9818cb9b30a0cecc12d99e\">m_iStates</a>&amp;0xff)+(((<span class=\"keywordtype\">unsigned</span> <span class=\"keywordtype\">int</span>)(0xff*fMask))&lt;&lt;8); };</div>\n\
<div class=\"ttc\" id=\"structmudbox_1_1_vertex_html_abbab52b63f9818cb9b30a0cecc12d99e\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/structmudbox_1_1_vertex.html#abbab52b63f9818cb9b30a0cecc12d99e\">mudbox::Vertex::m_iStates</a></div><div class=\"ttdeci\">unsigned short m_iStates</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/mesh_8h_source.html#l00068\">mesh.h:68</a></div></div>\n\
</div><!-- fragment -->\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a584ab12fc27993f21d31639c6653ab19\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">bool IsSelected </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a>&#160;</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">inline</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Returns the Selected state of the <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/structmudbox_1_1_vertex.html\" title=\"Represents a vertex point on a Mesh with its associated data. \">Vertex</a> (true or false) </p>\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/mesh_8h_source.html#l00099\">99</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/mesh_8h_source.html\">mesh.h</a>.</p>\n\
<div class=\"fragment\"><div class=\"line\"><a name=\"l00099\"></a><span class=\"lineno\">   99</span>&#160;{ <span class=\"keywordflow\">return</span> (<a class=\"code\" href=\"#!/url=./cpp_ref/structmudbox_1_1_vertex.html#abbab52b63f9818cb9b30a0cecc12d99e\">m_iStates</a>&amp;0x80) != 0; };</div>\n\
<div class=\"ttc\" id=\"structmudbox_1_1_vertex_html_abbab52b63f9818cb9b30a0cecc12d99e\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/structmudbox_1_1_vertex.html#abbab52b63f9818cb9b30a0cecc12d99e\">mudbox::Vertex::m_iStates</a></div><div class=\"ttdeci\">unsigned short m_iStates</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/mesh_8h_source.html#l00068\">mesh.h:68</a></div></div>\n\
</div><!-- fragment -->\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a320354580ef8105ec229b49300814066\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a> SetSelected </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">bool&#160;</td>\n\
          <td class=\"paramname\"><em>bSelected</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">inline</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Sets the Selected state of the <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/structmudbox_1_1_vertex.html\" title=\"Represents a vertex point on a Mesh with its associated data. \">Vertex</a> (true or false) </p>\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/mesh_8h_source.html#l00102\">102</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/mesh_8h_source.html\">mesh.h</a>.</p>\n\
<div class=\"fragment\"><div class=\"line\"><a name=\"l00103\"></a><span class=\"lineno\">  103</span>&#160;        { <a class=\"code\" href=\"#!/url=./cpp_ref/structmudbox_1_1_vertex.html#abbab52b63f9818cb9b30a0cecc12d99e\">m_iStates</a> = (<a class=\"code\" href=\"#!/url=./cpp_ref/structmudbox_1_1_vertex.html#abbab52b63f9818cb9b30a0cecc12d99e\">m_iStates</a>&amp;0xff7f)+bSelected*0x80; };</div>\n\
<div class=\"ttc\" id=\"structmudbox_1_1_vertex_html_abbab52b63f9818cb9b30a0cecc12d99e\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/structmudbox_1_1_vertex.html#abbab52b63f9818cb9b30a0cecc12d99e\">mudbox::Vertex::m_iStates</a></div><div class=\"ttdeci\">unsigned short m_iStates</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/mesh_8h_source.html#l00068\">mesh.h:68</a></div></div>\n\
</div><!-- fragment -->\n\
</div>\n\
</div>\n\
<h2 class=\"groupheader\">Member Data Documentation</h2>\n\
<a class=\"anchor\" id=\"a8dfc24d64da486c8ca2bd9bf6d743de3\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/classmudbox_1_1_vector.html\">Vector</a> m_vPos</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/mesh_8h_source.html#l00058\">58</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/mesh_8h_source.html\">mesh.h</a>.</p>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a2b3c32dc59d4c119314b73ee8bbc8beb\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">unsigned <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a0067a505d12f13572b26d9535c23b671\">int</a> m_iStrokeID</td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">mutable</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/mesh_8h_source.html#l00062\">62</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/mesh_8h_source.html\">mesh.h</a>.</p>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"abbab52b63f9818cb9b30a0cecc12d99e\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">unsigned short m_iStates</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/mesh_8h_source.html#l00068\">68</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/mesh_8h_source.html\">mesh.h</a>.</p>\n\
\n\
</div>\n\
</div>\n\
<hr>The documentation for this struct was generated from the following file:<ul>\n\
<li>Mudbox/<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/mesh_8h_source.html\">mesh.h</a></li>\n\
</ul>\n\
</div><!-- contents -->\n\
</div><!-- doc-content -->\n\
          <div class=\"footer-block\"><a href=\"../html/ac.cmtdialog.htm\" class=\"comments-anchor\" target=\"_blank\"><span class=\"comments-link\">Please send us your comment about this page</span></a></div></div>\n\
   </div></body>\n\
</html>\n\
";