var widgets_8h =
[
    [ "MirrorComboBox", "classmudbox_1_1_mirror_combo_box.html", "classmudbox_1_1_mirror_combo_box" ],
    [ "AttributeSign", "classmudbox_1_1_attribute_sign.html", "classmudbox_1_1_attribute_sign" ],
    [ "AttributeWidget", "classmudbox_1_1_attribute_widget.html", "classmudbox_1_1_attribute_widget" ],
    [ "AttributeVectorbox", "classmudbox_1_1_attribute_vectorbox.html", "classmudbox_1_1_attribute_vectorbox" ],
    [ "AttributeVector4box", "classmudbox_1_1_attribute_vector4box.html", "classmudbox_1_1_attribute_vector4box" ],
    [ "AttributeEditbox", "classmudbox_1_1_attribute_editbox.html", "classmudbox_1_1_attribute_editbox" ],
    [ "AttributeImagebox", "classmudbox_1_1_attribute_imagebox.html", "classmudbox_1_1_attribute_imagebox" ],
    [ "AttributeCheckbox", "classmudbox_1_1_attribute_checkbox.html", "classmudbox_1_1_attribute_checkbox" ],
    [ "AttributeColorbox", "classmudbox_1_1_attribute_colorbox.html", "classmudbox_1_1_attribute_colorbox" ],
    [ "AttributeSliderbox", "classmudbox_1_1_attribute_sliderbox.html", "classmudbox_1_1_attribute_sliderbox" ],
    [ "AttributeSpinbox", "classmudbox_1_1_attribute_spinbox.html", "classmudbox_1_1_attribute_spinbox" ],
    [ "AttributeCombobox", "classmudbox_1_1_attribute_combobox.html", "classmudbox_1_1_attribute_combobox" ],
    [ "AttributeComboboxMap", "classmudbox_1_1_attribute_combobox_map.html", "classmudbox_1_1_attribute_combobox_map" ],
    [ "AttributeFilenamebox", "classmudbox_1_1_attribute_filenamebox.html", "classmudbox_1_1_attribute_filenamebox" ],
    [ "AttributeTextureFilenamebox", "classmudbox_1_1_attribute_texture_filenamebox.html", "classmudbox_1_1_attribute_texture_filenamebox" ],
    [ "AttributeEventbox", "classmudbox_1_1_attribute_eventbox.html", "classmudbox_1_1_attribute_eventbox" ],
    [ "AttributePointerbox", "classmudbox_1_1_attribute_pointerbox.html", "classmudbox_1_1_attribute_pointerbox" ],
    [ "AttributeCheckboxCollection", "classmudbox_1_1_attribute_checkbox_collection.html", "classmudbox_1_1_attribute_checkbox_collection" ],
    [ "AttributeSliderWithCheckbox", "classmudbox_1_1_attribute_slider_with_checkbox.html", "classmudbox_1_1_attribute_slider_with_checkbox" ],
    [ "AttributeSliderArrayWithCheckbox", "classmudbox_1_1_attribute_slider_array_with_checkbox.html", "classmudbox_1_1_attribute_slider_array_with_checkbox" ],
    [ "CPBox", "classmudbox_1_1_c_p_box.html", "classmudbox_1_1_c_p_box" ],
    [ "CurveEditor", "classmudbox_1_1_curve_editor.html", "classmudbox_1_1_curve_editor" ],
    [ "AttributeCurveEditor", "classmudbox_1_1_attribute_curve_editor.html", "classmudbox_1_1_attribute_curve_editor" ],
    [ "EnlargedCurveEditor", "classmudbox_1_1_enlarged_curve_editor.html", "classmudbox_1_1_enlarged_curve_editor" ],
    [ "AttributeStampConfigurationWidget", "classmudbox_1_1_attribute_stamp_configuration_widget.html", "classmudbox_1_1_attribute_stamp_configuration_widget" ],
    [ "AttributeMirrorConfigurationWidget", "classmudbox_1_1_attribute_mirror_configuration_widget.html", "classmudbox_1_1_attribute_mirror_configuration_widget" ],
    [ "HelpButton", "classmudbox_1_1_help_button.html", "classmudbox_1_1_help_button" ],
    [ "CPBOX_WIDTH", "widgets_8h.html#a1dec6f1616d097833bb0a64b19607f7c", null ],
    [ "MAX_CURVE_POINTS", "widgets_8h.html#a0a985de0e52c74f66bd6ed9c17a36461", null ]
];