var topic = "<!-- saved from url=(0024)http://docs.autodesk.com -->\n\
<html>\n\
   <head><script src=\"../scripts/yepnope.1.5.4-min.js\" type=\"text/javascript\"></script><script src=\"../scripts/lib/jquery-1.11.1.min.js\" type=\"text/javascript\"></script><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"><meta name=\"product\" content=\"MOBPRO\"><meta name=\"release\" content=\"2018\"><meta name=\"book\" content=\"GeneralUser\"><meta name=\"created\" content=\"2017-09-08\"><meta name=\"topicid\" content=\"GUID-02FA7DD3-6C7A-4C6A-B7BC-824765AE1CB2\"><meta name=\"topic-type\" content=\"concept\">\n\
      <title>QSwipeGesture Class Reference</title>\n\
   \n\
\n\
</head>\n\
   <body height=\"100%\"><div class=\"body_content\" id=\"body-content\"><link rel=\"stylesheet\" type=\"text/css\" href=\"cpp_ref/navtree.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"cpp_ref/doxygen.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"cpp_ref/tabs.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"style/adsk.cpm.css\"><script language=\"javascript\">var index = \'index.html\';</script><script>$(document).ready(function() { yepnope.injectJs(\"./scripts/ac_common.js\"); });</script><script type=\"text/javascript\">\n\
var tocSystemNeedsToBeLoaded = typeof(cpp_ref_adsk_ref_toc) == \'undefined\';\n\
var weAreIn21 = $(\'div#main.view-active\').length;\n\
var tocPrefix = \'\';\n\
if (weAreIn21)\n\
{ tocPrefix = \'cpp_ref/\'; }\n\
function cpp_ref_initializeToc(forceTrigger) {\n\
    cpp_ref_adsk_ref_toc.initResizable();\n\
    cpp_ref_adsk_ref_toc.initNavTree(\'class_q_swipe_gesture.html\', tocPrefix);\n\
    dQuery(document).trigger(\'toc_initialized\');\n\
}\n\
if (tocSystemNeedsToBeLoaded)\n\
{\n\
	yepnope([{\n\
	load:[tocPrefix + \'json3.min.js\', tocPrefix + \'jquery.js\', tocPrefix + \'ref-toc-controller.js\', tocPrefix + \'dynsections.js\'],\n\
	complete: function() {\n\
	  if (typeof(dQuery) == \'undefined\')\n\
	  {\n\
	    dQuery = jQuery.noConflict(true);\n\
	  }\n\
	  else { jQuery.noConflict(true); }\n\
	  $(document).ready(cpp_ref_initializeToc);\n\
	}\n\
 	}])\n\
}\n\
if (!weAreIn21) { // if in AKN...\n\
$(window).load( function() {\n\
    setTimeout( function() {\n\
        var content = $(\'body > div\').not(\'#body-content\');     // take any divs under body that are not id=body-content\n\
        content.each( function() { \n\
            $(this).css( { \'padding-left\': $(this).css(\'margin-left\') } );       // and if they have any padding-left already, move it to margin-left.\n\
        } );\n\
        var width = cpp_ref_adsk_ref_toc.readFromStorage(\'width\');\n\
        content.css({marginLeft:parseInt(width)+6+\"px\"});\n\
    }, 100);\n\
} ); \n\
}\n\
</script><script>$(\"div#WidgetFloaterPanels,link[href*=\'microsofttranslator.com\'],script[src*=\'microsofttranslator.com\'],script[src*=\'bing.com\']\").remove();</script><script type=\'text/javascript\'>$(\"div#navigation,div#breadcrumbs,div#banner\").attr(\"translate\",\"no\"); var mtLocation = ((location && location.href && location.href.indexOf(\'https\') == 0)?\'https://ssl.microsofttranslator.com\':\'http://www.microsofttranslator.com\')+\'/ajax/v3/WidgetV3.ashx?ctf=True&ui=true&settings=Manual&from=en&hidelanguages=\'; yepnope.injectJs(mtLocation, function() {}, { charset:\'utf-8\', type:\'text/javascript\' } );</script><script>\n\
 if (!tocSystemNeedsToBeLoaded) { cpp_ref_initializeToc(); }\n\
 </script><!-- begin MT -->\n\
            \n\
            <div id=\'MicrosoftTranslatorWidget\' class=\'Dark\' style=\'float:right;z-index:100;color:white;background-color:#bbbbbb;height:58px;overflow:hidden\'></div>\n\
      <div>\n\
         <div class=\"head\">\n\
            <h1>QSwipeGesture Class Reference</h1>\n\
         </div>\n\
\n\
    <div id=\"top\"><!-- Generated by Doxygen 1.8.10 -->\n\
  <div id=\"navrow1\" class=\"tabs\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./cpp_ref/index.html\"><span>Main&#160;Page</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/pages.html\"><span>Topics</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/modules.html\"><span>Modules</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/namespaces.html\"><span>Namespaces</span></a></li>\n\
      <li class=\"current\"><a href=\"#!/url=./cpp_ref/annotated.html\"><span>Classes</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/files.html\"><span>Files</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/examples.html\"><span>Examples</span></a></li>\n\
    </ul>\n\
  </div>\n\
  <div id=\"navrow2\" class=\"tabs2\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./cpp_ref/annotated.html\"><span>Class&#160;List</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/hierarchy.html\"><span>Class&#160;Hierarchy</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/functions.html\"><span>Class&#160;Members</span></a></li>\n\
    </ul>\n\
  </div>\n\
</div><!-- top -->\n\
<div id=\"side-nav\" class=\"ui-resizable side-nav-resizable\">\n\
  <div id=\"nav-tree\">\n\
    <div id=\"nav-tree-contents\">\n\
      <div id=\"nav-sync\" class=\"sync\"></div>\n\
    </div>\n\
  </div>\n\
  <div id=\"splitbar\" style=\"-moz-user-select:none;\" class=\"ui-resizable-handle\">\n\
  </div>\n\
</div>\n\
\n\
<div id=\"doc-content\">\n\
<div class=\"header\">\n\
  \n\
  <div class=\"headertitle\">\n\
<div class=\"title\">QSwipeGesture Class Reference</div>  </div>\n\
<div class=\"summary\">\n\
<a href=\"class_q_swipe_gesture.html#pub-types\">Public Types</a> &#124;\n\
<a href=\"class_q_swipe_gesture.html#pub-methods\">Public Member Functions</a> &#124;\n\
<a href=\"class_q_swipe_gesture.html#properties\">Properties</a> &#124;\n\
<a href=\"class_q_swipe_gesture.html#friends\">Friends</a>  </div></div><!--header-->\n\
<div class=\"contents\">\n\
\n\
<p><code>#include &lt;<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qgesture_8h_source.html\">qgesture.h</a>&gt;</code></p>\n\
<a name=\"details\" id=\"details\"></a><h2 class=\"groupheader\">Class Description</h2>\n\
<div class=\"textblock\">\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qgesture_8h_source.html#l00207\">207</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qgesture_8h_source.html\">qgesture.h</a>.</p>\n\
</div><div id=\"dynsection-0\" onclick=\"return toggleVisibility(this)\" class=\"dynheader closed\" style=\"cursor:pointer;\">\n\
  <img id=\"dynsection-0-trigger\" src=\"cpp_ref/closed.png\" alt=\"+\"> Inheritance diagram for QSwipeGesture:</div>\n\
<div id=\"dynsection-0-summary\" class=\"dynsummary\" style=\"display:block;\">\n\
</div>\n\
<div id=\"dynsection-0-content\" class=\"dyncontent\" style=\"display:none;\">\n\
 <div class=\"center\">\n\
  <img src=\"cpp_ref/class_q_swipe_gesture.png\" usemap=\"#QSwipeGesture_map\" alt=\"\">\n\
  <map id=\"QSwipeGesture_map\" name=\"QSwipeGesture_map\">\n\
<area href=\"class_q_gesture.html\" alt=\"QGesture\" shape=\"rect\" coords=\"0,56,100,80\">\n\
<area href=\"class_q_object.html\" alt=\"QObject\" shape=\"rect\" coords=\"0,0,100,24\">\n\
</map>\n\
 </div></div>\n\
<table class=\"memberdecls\">\n\
<tr class=\"heading\"><td colspan=\"2\"><h2 class=\"groupheader\"><a name=\"pub-types\"></a>\n\
Public Types</h2></td></tr>\n\
<tr class=\"memitem:a5f2a0ca7016284497a2768c469290e42\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">enum &#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_swipe_gesture.html#a5f2a0ca7016284497a2768c469290e42\">SwipeDirection</a> { <br>\n\
&#160;&#160;<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_swipe_gesture.html#a5f2a0ca7016284497a2768c469290e42aca3e0efea800bf6b107cc8fa09e4bb06\">NoDirection</a>, \n\
<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_swipe_gesture.html#a5f2a0ca7016284497a2768c469290e42a9d4d8b0b72fc2659da772d761a3c5ecb\">Left</a>, \n\
<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_swipe_gesture.html#a5f2a0ca7016284497a2768c469290e42ad48f7af8c070184f3774c8e85854eb66\">Right</a>, \n\
<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_swipe_gesture.html#a5f2a0ca7016284497a2768c469290e42a57a7edcbc04d6175683383cad5c3e0a2\">Up</a>, \n\
<br>\n\
&#160;&#160;<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_swipe_gesture.html#a5f2a0ca7016284497a2768c469290e42abcf8c79e9a5f5f9d606fb35645a0fb27\">Down</a>\n\
<br>\n\
 }<tr class=\"separator:a5f2a0ca7016284497a2768c469290e42\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
</td></tr>\n\
<tr class=\"inherit_header pub_types_class_q_gesture\"><td colspan=\"2\" onclick=\"javascript:toggleInherit(\'pub_types_class_q_gesture\')\"><img src=\"cpp_ref/closed.png\" alt=\"-\">&#160;Public Types inherited from <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_gesture.html\">QGesture</a></td></tr>\n\
<tr class=\"memitem:a1b2897793a4d2108ee260c1f93027d39 inherit pub_types_class_q_gesture\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">enum &#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_gesture.html#a1b2897793a4d2108ee260c1f93027d39\">GestureCancelPolicy</a> { <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_gesture.html#a1b2897793a4d2108ee260c1f93027d39af27dd4dc967764e2ca44f2a43e8b3fd1\">CancelNone</a> = 0, \n\
<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_gesture.html#a1b2897793a4d2108ee260c1f93027d39a59cba2a2aebb4d124c1d06ab61090ea2\">CancelAllInContext</a>\n\
 }<tr class=\"separator:a1b2897793a4d2108ee260c1f93027d39 inherit pub_types_class_q_gesture\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
</td></tr>\n\
</table><table class=\"memberdecls\">\n\
<tr class=\"heading\"><td colspan=\"2\"><h2 class=\"groupheader\"><a name=\"pub-methods\"></a>\n\
Public Member Functions</h2></td></tr>\n\
<tr class=\"memitem:a047752938e8a9e57f8a10e24c2d4076c\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_swipe_gesture.html#a047752938e8a9e57f8a10e24c2d4076c\">QSwipeGesture</a> (<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html\">QObject</a> *<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html#a5bc37dc360715232180b31f152fe7df6\">parent</a>=0)</td></tr>\n\
<tr class=\"separator:a047752938e8a9e57f8a10e24c2d4076c\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a3c5506175a3a21c7c867efd422553b92\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_swipe_gesture.html#a5f2a0ca7016284497a2768c469290e42\">SwipeDirection</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_swipe_gesture.html#a3c5506175a3a21c7c867efd422553b92\">horizontalDirection</a> () const </td></tr>\n\
<tr class=\"separator:a3c5506175a3a21c7c867efd422553b92\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ad833f8cc0a898c81934009dd5c1d743b\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_swipe_gesture.html#a5f2a0ca7016284497a2768c469290e42\">SwipeDirection</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_swipe_gesture.html#ad833f8cc0a898c81934009dd5c1d743b\">verticalDirection</a> () const </td></tr>\n\
<tr class=\"separator:ad833f8cc0a898c81934009dd5c1d743b\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a1b119db778d3adf4a0e4e9ed41d70338\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">qreal&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_swipe_gesture.html#a1b119db778d3adf4a0e4e9ed41d70338\">swipeAngle</a> () const </td></tr>\n\
<tr class=\"separator:a1b119db778d3adf4a0e4e9ed41d70338\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a7f3f48c8768f199c67d5b874e7ba040d\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_swipe_gesture.html#a7f3f48c8768f199c67d5b874e7ba040d\">setSwipeAngle</a> (qreal <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#aed27f17ebdc1fd207871bc2ed5da0d0f\">value</a>)</td></tr>\n\
<tr class=\"separator:a7f3f48c8768f199c67d5b874e7ba040d\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"inherit_header pub_methods_class_q_gesture\"><td colspan=\"2\" onclick=\"javascript:toggleInherit(\'pub_methods_class_q_gesture\')\"><img src=\"cpp_ref/closed.png\" alt=\"-\">&#160;Public Member Functions inherited from <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_gesture.html\">QGesture</a></td></tr>\n\
<tr class=\"memitem:a505aa0a6ff9742c4026bc0b36ffd04d6 inherit pub_methods_class_q_gesture\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_gesture.html#a505aa0a6ff9742c4026bc0b36ffd04d6\">QGesture</a> (<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html\">QObject</a> *<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html#a5bc37dc360715232180b31f152fe7df6\">parent</a>=0)</td></tr>\n\
<tr class=\"separator:a505aa0a6ff9742c4026bc0b36ffd04d6 inherit pub_methods_class_q_gesture\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a57d61ddebc645b620119b61b43ed43a1 inherit pub_methods_class_q_gesture\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_gesture.html#a57d61ddebc645b620119b61b43ed43a1\">~QGesture</a> ()</td></tr>\n\
<tr class=\"separator:a57d61ddebc645b620119b61b43ed43a1 inherit pub_methods_class_q_gesture\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a7e63700290c4ba6d55c6f7510b6d9753 inherit pub_methods_class_q_gesture\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/namespace_qt.html#a2a0c37051efa1205aa5aade68616c947\">Qt::GestureType</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_gesture.html#a7e63700290c4ba6d55c6f7510b6d9753\">gestureType</a> () const </td></tr>\n\
<tr class=\"separator:a7e63700290c4ba6d55c6f7510b6d9753 inherit pub_methods_class_q_gesture\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a9cc9dd02a2fcd0ef436d6a4326a2b280 inherit pub_methods_class_q_gesture\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/namespace_qt.html#a50af89fcbe8ccc22f6b6ea5f476cfdc9\">Qt::GestureState</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_gesture.html#a9cc9dd02a2fcd0ef436d6a4326a2b280\">state</a> () const </td></tr>\n\
<tr class=\"separator:a9cc9dd02a2fcd0ef436d6a4326a2b280 inherit pub_methods_class_q_gesture\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a3ecaa8831b3e4d26fa7e626133d56454 inherit pub_methods_class_q_gesture\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_point_f.html\">QPointF</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_gesture.html#a3ecaa8831b3e4d26fa7e626133d56454\">hotSpot</a> () const </td></tr>\n\
<tr class=\"separator:a3ecaa8831b3e4d26fa7e626133d56454 inherit pub_methods_class_q_gesture\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:aa75d78c197289233e3b8ed03d843c24a inherit pub_methods_class_q_gesture\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_gesture.html#aa75d78c197289233e3b8ed03d843c24a\">setHotSpot</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_point_f.html\">QPointF</a> &amp;<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#aed27f17ebdc1fd207871bc2ed5da0d0f\">value</a>)</td></tr>\n\
<tr class=\"separator:aa75d78c197289233e3b8ed03d843c24a inherit pub_methods_class_q_gesture\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a79b5ff8666f2c4c6b0977bb71e0c626c inherit pub_methods_class_q_gesture\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_gesture.html#a79b5ff8666f2c4c6b0977bb71e0c626c\">hasHotSpot</a> () const </td></tr>\n\
<tr class=\"separator:a79b5ff8666f2c4c6b0977bb71e0c626c inherit pub_methods_class_q_gesture\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a19de8014d7fccc16f4e63b1fc944cb37 inherit pub_methods_class_q_gesture\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_gesture.html#a19de8014d7fccc16f4e63b1fc944cb37\">unsetHotSpot</a> ()</td></tr>\n\
<tr class=\"separator:a19de8014d7fccc16f4e63b1fc944cb37 inherit pub_methods_class_q_gesture\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a8cbff9f536bec558321acefc92d568c7 inherit pub_methods_class_q_gesture\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_gesture.html#a8cbff9f536bec558321acefc92d568c7\">setGestureCancelPolicy</a> (<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_gesture.html#a1b2897793a4d2108ee260c1f93027d39\">GestureCancelPolicy</a> policy)</td></tr>\n\
<tr class=\"separator:a8cbff9f536bec558321acefc92d568c7 inherit pub_methods_class_q_gesture\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a9ae48982c6f3122ac277cf64bd4c1350 inherit pub_methods_class_q_gesture\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_gesture.html#a1b2897793a4d2108ee260c1f93027d39\">GestureCancelPolicy</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_gesture.html#a9ae48982c6f3122ac277cf64bd4c1350\">gestureCancelPolicy</a> () const </td></tr>\n\
<tr class=\"separator:a9ae48982c6f3122ac277cf64bd4c1350 inherit pub_methods_class_q_gesture\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"inherit_header pub_methods_class_q_object\"><td colspan=\"2\" onclick=\"javascript:toggleInherit(\'pub_methods_class_q_object\')\"><img src=\"cpp_ref/closed.png\" alt=\"-\">&#160;Public Member Functions inherited from <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html\">QObject</a></td></tr>\n\
<tr class=\"memitem:a1a764441bb520104e51138da5dbdfe03 inherit pub_methods_class_q_object\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qobjectdefs_8h.html#a51330077e1b9798935383ee582620d52\">Q_INVOKABLE</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html#a1a764441bb520104e51138da5dbdfe03\">QObject</a> (<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html\">QObject</a> *<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html#a5bc37dc360715232180b31f152fe7df6\">parent</a>=0)</td></tr>\n\
<tr class=\"separator:a1a764441bb520104e51138da5dbdfe03 inherit pub_methods_class_q_object\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a4f69997dd5affef7d1408aada7132bed inherit pub_methods_class_q_object\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">virtual&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html#a4f69997dd5affef7d1408aada7132bed\">~QObject</a> ()</td></tr>\n\
<tr class=\"separator:a4f69997dd5affef7d1408aada7132bed inherit pub_methods_class_q_object\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a4ced595a06a3151cbb53131b2e8c53d8 inherit pub_methods_class_q_object\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">virtual bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html#a4ced595a06a3151cbb53131b2e8c53d8\">event</a> (<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_event.html\">QEvent</a> *)</td></tr>\n\
<tr class=\"separator:a4ced595a06a3151cbb53131b2e8c53d8 inherit pub_methods_class_q_object\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:aad4ff3c29bdb4e0af9880e2e13d554e5 inherit pub_methods_class_q_object\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">virtual bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html#aad4ff3c29bdb4e0af9880e2e13d554e5\">eventFilter</a> (<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html\">QObject</a> *, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_event.html\">QEvent</a> *)</td></tr>\n\
<tr class=\"separator:aad4ff3c29bdb4e0af9880e2e13d554e5 inherit pub_methods_class_q_object\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ad0afbf8902c0d7a9402d9c79bbeec5f3 inherit pub_methods_class_q_object\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_string.html\">QString</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html#ad0afbf8902c0d7a9402d9c79bbeec5f3\">objectName</a> () const </td></tr>\n\
<tr class=\"separator:ad0afbf8902c0d7a9402d9c79bbeec5f3 inherit pub_methods_class_q_object\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a6be8b8d0eb547a8666a3ac6b3d4cac2f inherit pub_methods_class_q_object\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html#a6be8b8d0eb547a8666a3ac6b3d4cac2f\">setObjectName</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_string.html\">QString</a> &amp;<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#ad977737dfc9a274a62741b9500c49a32\">name</a>)</td></tr>\n\
<tr class=\"separator:a6be8b8d0eb547a8666a3ac6b3d4cac2f inherit pub_methods_class_q_object\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a09949b14be8b71147a316bf159815b89 inherit pub_methods_class_q_object\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html#a09949b14be8b71147a316bf159815b89\">isWidgetType</a> () const </td></tr>\n\
<tr class=\"separator:a09949b14be8b71147a316bf159815b89 inherit pub_methods_class_q_object\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a784b2edf96c0ccf6a76b5c8106653acf inherit pub_methods_class_q_object\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html#a784b2edf96c0ccf6a76b5c8106653acf\">signalsBlocked</a> () const </td></tr>\n\
<tr class=\"separator:a784b2edf96c0ccf6a76b5c8106653acf inherit pub_methods_class_q_object\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a606359e3f1fd3067894801994fd3d731 inherit pub_methods_class_q_object\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html#a606359e3f1fd3067894801994fd3d731\">blockSignals</a> (bool <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a08f98740667f706cd68d5e873088ffa6\">b</a>)</td></tr>\n\
<tr class=\"separator:a606359e3f1fd3067894801994fd3d731 inherit pub_methods_class_q_object\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ad337e56f1f9819a21f7dff35358d27bc inherit pub_methods_class_q_object\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_thread.html\">QThread</a> *&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html#ad337e56f1f9819a21f7dff35358d27bc\">thread</a> () const </td></tr>\n\
<tr class=\"separator:ad337e56f1f9819a21f7dff35358d27bc inherit pub_methods_class_q_object\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a4665974ed366ab5016f22cb8ff0d321b inherit pub_methods_class_q_object\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html#a4665974ed366ab5016f22cb8ff0d321b\">moveToThread</a> (<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_thread.html\">QThread</a> *<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html#ad337e56f1f9819a21f7dff35358d27bc\">thread</a>)</td></tr>\n\
<tr class=\"separator:a4665974ed366ab5016f22cb8ff0d321b inherit pub_methods_class_q_object\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a7e4a194e6b6e52921ad355d3a3470947 inherit pub_methods_class_q_object\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a0067a505d12f13572b26d9535c23b671\">int</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html#a7e4a194e6b6e52921ad355d3a3470947\">startTimer</a> (<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a0067a505d12f13572b26d9535c23b671\">int</a> interval)</td></tr>\n\
<tr class=\"separator:a7e4a194e6b6e52921ad355d3a3470947 inherit pub_methods_class_q_object\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:acde424120594a6f47a13cc3e6b85cc58 inherit pub_methods_class_q_object\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html#acde424120594a6f47a13cc3e6b85cc58\">killTimer</a> (<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a0067a505d12f13572b26d9535c23b671\">int</a> <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a58c2a664503e14ffb8f21012aabff3e9\">id</a>)</td></tr>\n\
<tr class=\"separator:acde424120594a6f47a13cc3e6b85cc58 inherit pub_methods_class_q_object\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a304eaec80747a8062d7f693c7374be98 inherit pub_methods_class_q_object\"><td class=\"memTemplParams\" translate=\"no\" colspan=\"2\">template&lt;typename T &gt; </td></tr>\n\
<tr class=\"memitem:a304eaec80747a8062d7f693c7374be98 inherit pub_methods_class_q_object\"><td class=\"memTemplItemLeft\" align=\"right\" valign=\"top\">T&#160;</td><td class=\"memTemplItemRight\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html#a304eaec80747a8062d7f693c7374be98\">findChild</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_string.html\">QString</a> &amp;aName=<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_string.html\">QString</a>()) const </td></tr>\n\
<tr class=\"separator:a304eaec80747a8062d7f693c7374be98 inherit pub_methods_class_q_object\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a6eb46c0d047a453b948965b4b89af6df inherit pub_methods_class_q_object\"><td class=\"memTemplParams\" translate=\"no\" colspan=\"2\">template&lt;typename T &gt; </td></tr>\n\
<tr class=\"memitem:a6eb46c0d047a453b948965b4b89af6df inherit pub_methods_class_q_object\"><td class=\"memTemplItemLeft\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_list.html\">QList</a>&lt; T &gt;&#160;</td><td class=\"memTemplItemRight\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html#a6eb46c0d047a453b948965b4b89af6df\">findChildren</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_string.html\">QString</a> &amp;aName=<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_string.html\">QString</a>()) const </td></tr>\n\
<tr class=\"separator:a6eb46c0d047a453b948965b4b89af6df inherit pub_methods_class_q_object\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a4fb158ee02f2017c14a7a222459062c9 inherit pub_methods_class_q_object\"><td class=\"memTemplParams\" translate=\"no\" colspan=\"2\">template&lt;typename T &gt; </td></tr>\n\
<tr class=\"memitem:a4fb158ee02f2017c14a7a222459062c9 inherit pub_methods_class_q_object\"><td class=\"memTemplItemLeft\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_list.html\">QList</a>&lt; T &gt;&#160;</td><td class=\"memTemplItemRight\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html#a4fb158ee02f2017c14a7a222459062c9\">findChildren</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_reg_exp.html\">QRegExp</a> &amp;re) const </td></tr>\n\
<tr class=\"separator:a4fb158ee02f2017c14a7a222459062c9 inherit pub_methods_class_q_object\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:aa07f2a007283889f08d5b558fc7e5430 inherit pub_methods_class_q_object\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qobject_8h.html#a739945d14d2411c0718094bcbeb557f3\">QObjectList</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html#aa07f2a007283889f08d5b558fc7e5430\">children</a> () const </td></tr>\n\
<tr class=\"separator:aa07f2a007283889f08d5b558fc7e5430 inherit pub_methods_class_q_object\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a4bb4c8bfe77df35fbb93fbe254355ea4 inherit pub_methods_class_q_object\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html#a4bb4c8bfe77df35fbb93fbe254355ea4\">setParent</a> (<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html\">QObject</a> *)</td></tr>\n\
<tr class=\"separator:a4bb4c8bfe77df35fbb93fbe254355ea4 inherit pub_methods_class_q_object\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a9fc0415bcb36622134e63ecaeadc48e0 inherit pub_methods_class_q_object\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html#a9fc0415bcb36622134e63ecaeadc48e0\">installEventFilter</a> (<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html\">QObject</a> *)</td></tr>\n\
<tr class=\"separator:a9fc0415bcb36622134e63ecaeadc48e0 inherit pub_methods_class_q_object\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a9ee13d4b073681e2f2b102e7309518e1 inherit pub_methods_class_q_object\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html#a9ee13d4b073681e2f2b102e7309518e1\">removeEventFilter</a> (<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html\">QObject</a> *)</td></tr>\n\
<tr class=\"separator:a9ee13d4b073681e2f2b102e7309518e1 inherit pub_methods_class_q_object\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:afcc17252fb3afe9a1e27ef73a46666b8 inherit pub_methods_class_q_object\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html#afcc17252fb3afe9a1e27ef73a46666b8\">connect</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html\">QObject</a> *<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html#a0a425b6bb39a29d9777593aa3fb20e1c\">sender</a>, const char *signal, const char *<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#aaf221c4cca848f2b307b3c10dd478d77\">member</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/namespace_qt.html#aa1f0e2efd52935fd01bfece0fbead81f\">Qt::ConnectionType</a> <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a63267399cd2a2ee217572c11d2e54f07\">type</a>=<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/namespace_qt.html#aa1f0e2efd52935fd01bfece0fbead81faa80a2853748720a77e994da0a473f0a9\">Qt::AutoConnection</a>) const </td></tr>\n\
<tr class=\"separator:afcc17252fb3afe9a1e27ef73a46666b8 inherit pub_methods_class_q_object\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a2260c191671eec75549efef224fccaad inherit pub_methods_class_q_object\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html#a2260c191671eec75549efef224fccaad\">disconnect</a> (const char *signal=0, const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html\">QObject</a> *receiver=0, const char *<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#aaf221c4cca848f2b307b3c10dd478d77\">member</a>=0)</td></tr>\n\
<tr class=\"separator:a2260c191671eec75549efef224fccaad inherit pub_methods_class_q_object\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a5963148da1447769681899579629269a inherit pub_methods_class_q_object\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html#a5963148da1447769681899579629269a\">disconnect</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html\">QObject</a> *receiver, const char *<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#aaf221c4cca848f2b307b3c10dd478d77\">member</a>=0)</td></tr>\n\
<tr class=\"separator:a5963148da1447769681899579629269a inherit pub_methods_class_q_object\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a2ea547335b5495aaceb1dc95156242c0 inherit pub_methods_class_q_object\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html#a2ea547335b5495aaceb1dc95156242c0\">dumpObjectTree</a> ()</td></tr>\n\
<tr class=\"separator:a2ea547335b5495aaceb1dc95156242c0 inherit pub_methods_class_q_object\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:aef4f94ba4e8954ed45b9e7a375d371f1 inherit pub_methods_class_q_object\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html#aef4f94ba4e8954ed45b9e7a375d371f1\">dumpObjectInfo</a> ()</td></tr>\n\
<tr class=\"separator:aef4f94ba4e8954ed45b9e7a375d371f1 inherit pub_methods_class_q_object\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a93d2550504a82bd2cbe6f0d7248cf398 inherit pub_methods_class_q_object\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html#a93d2550504a82bd2cbe6f0d7248cf398\">setProperty</a> (const char *<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#ad977737dfc9a274a62741b9500c49a32\">name</a>, const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_variant.html\">QVariant</a> &amp;<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#aed27f17ebdc1fd207871bc2ed5da0d0f\">value</a>)</td></tr>\n\
<tr class=\"separator:a93d2550504a82bd2cbe6f0d7248cf398 inherit pub_methods_class_q_object\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a78b34c11b434ed1e78ce5ad380f8c373 inherit pub_methods_class_q_object\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_variant.html\">QVariant</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html#a78b34c11b434ed1e78ce5ad380f8c373\">property</a> (const char *<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#ad977737dfc9a274a62741b9500c49a32\">name</a>) const </td></tr>\n\
<tr class=\"separator:a78b34c11b434ed1e78ce5ad380f8c373 inherit pub_methods_class_q_object\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a7db0786907c79029fda6b8d4879c8080 inherit pub_methods_class_q_object\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_list.html\">QList</a>&lt; <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_byte_array.html\">QByteArray</a> &gt;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html#a7db0786907c79029fda6b8d4879c8080\">dynamicPropertyNames</a> () const </td></tr>\n\
<tr class=\"separator:a7db0786907c79029fda6b8d4879c8080 inherit pub_methods_class_q_object\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a01b77567d2500d299fc038687a2ad43a inherit pub_methods_class_q_object\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html#a01b77567d2500d299fc038687a2ad43a\">setUserData</a> (uint <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a58c2a664503e14ffb8f21012aabff3e9\">id</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object_user_data.html\">QObjectUserData</a> *<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a2cc7c8468af76cf855e1755c27945693\">data</a>)</td></tr>\n\
<tr class=\"separator:a01b77567d2500d299fc038687a2ad43a inherit pub_methods_class_q_object\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ae6b709217de88bd0ed7a3542f5b00fc5 inherit pub_methods_class_q_object\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object_user_data.html\">QObjectUserData</a> *&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html#ae6b709217de88bd0ed7a3542f5b00fc5\">userData</a> (uint <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a58c2a664503e14ffb8f21012aabff3e9\">id</a>) const </td></tr>\n\
<tr class=\"separator:ae6b709217de88bd0ed7a3542f5b00fc5 inherit pub_methods_class_q_object\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a5bc37dc360715232180b31f152fe7df6 inherit pub_methods_class_q_object\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html\">QObject</a> *&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html#a5bc37dc360715232180b31f152fe7df6\">parent</a> () const </td></tr>\n\
<tr class=\"separator:a5bc37dc360715232180b31f152fe7df6 inherit pub_methods_class_q_object\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ae5dab251f0bb4a0c34f20bf915c6360c inherit pub_methods_class_q_object\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html#ae5dab251f0bb4a0c34f20bf915c6360c\">inherits</a> (const char *classname) const </td></tr>\n\
<tr class=\"separator:ae5dab251f0bb4a0c34f20bf915c6360c inherit pub_methods_class_q_object\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
</table><table class=\"memberdecls\">\n\
<tr class=\"heading\"><td colspan=\"2\"><h2 class=\"groupheader\"><a name=\"properties\"></a>\n\
Properties</h2></td></tr>\n\
<tr class=\"memitem:a7d6d717366533d19ffc93f6d289e1035\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_swipe_gesture.html#a5f2a0ca7016284497a2768c469290e42\">SwipeDirection</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_swipe_gesture.html#a7d6d717366533d19ffc93f6d289e1035\">horizontalDirection</a></td></tr>\n\
<tr class=\"separator:a7d6d717366533d19ffc93f6d289e1035\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a9f2f1336639148b093ddc870858f4dab\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_swipe_gesture.html#a5f2a0ca7016284497a2768c469290e42\">SwipeDirection</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_swipe_gesture.html#a9f2f1336639148b093ddc870858f4dab\">verticalDirection</a></td></tr>\n\
<tr class=\"separator:a9f2f1336639148b093ddc870858f4dab\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a5a56b0a26931c98ed4b9c086ec1ec590\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">qreal&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_swipe_gesture.html#a5a56b0a26931c98ed4b9c086ec1ec590\">swipeAngle</a></td></tr>\n\
<tr class=\"separator:a5a56b0a26931c98ed4b9c086ec1ec590\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"inherit_header properties_class_q_gesture\"><td colspan=\"2\" onclick=\"javascript:toggleInherit(\'properties_class_q_gesture\')\"><img src=\"cpp_ref/closed.png\" alt=\"-\">&#160;Properties inherited from <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_gesture.html\">QGesture</a></td></tr>\n\
<tr class=\"memitem:a392a61858ba83c3b34efa55d51f22ae0 inherit properties_class_q_gesture\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/namespace_qt.html#a50af89fcbe8ccc22f6b6ea5f476cfdc9\">Qt::GestureState</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_gesture.html#a392a61858ba83c3b34efa55d51f22ae0\">state</a></td></tr>\n\
<tr class=\"separator:a392a61858ba83c3b34efa55d51f22ae0 inherit properties_class_q_gesture\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:aaacec42b421f0b596c2637bfd2634eea inherit properties_class_q_gesture\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/namespace_qt.html#a2a0c37051efa1205aa5aade68616c947\">Qt::GestureType</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_gesture.html#aaacec42b421f0b596c2637bfd2634eea\">gestureType</a></td></tr>\n\
<tr class=\"separator:aaacec42b421f0b596c2637bfd2634eea inherit properties_class_q_gesture\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a5062975f890181d7d662017df3d893be inherit properties_class_q_gesture\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_gesture.html#a1b2897793a4d2108ee260c1f93027d39\">QGesture::GestureCancelPolicy</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_gesture.html#a5062975f890181d7d662017df3d893be\">gestureCancelPolicy</a></td></tr>\n\
<tr class=\"separator:a5062975f890181d7d662017df3d893be inherit properties_class_q_gesture\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a1293e86055171925e09a8f27326159a8 inherit properties_class_q_gesture\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_point_f.html\">QPointF</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_gesture.html#a1293e86055171925e09a8f27326159a8\">hotSpot</a></td></tr>\n\
<tr class=\"separator:a1293e86055171925e09a8f27326159a8 inherit properties_class_q_gesture\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a22dc78a6b99e385e8a93c2a7bd0a6365 inherit properties_class_q_gesture\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_gesture.html#a22dc78a6b99e385e8a93c2a7bd0a6365\">hasHotSpot</a></td></tr>\n\
<tr class=\"separator:a22dc78a6b99e385e8a93c2a7bd0a6365 inherit properties_class_q_gesture\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"inherit_header properties_class_q_object\"><td colspan=\"2\" onclick=\"javascript:toggleInherit(\'properties_class_q_object\')\"><img src=\"cpp_ref/closed.png\" alt=\"-\">&#160;Properties inherited from <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html\">QObject</a></td></tr>\n\
<tr class=\"memitem:a631a94066cb7b5d639b2e0b7faae8604 inherit properties_class_q_object\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_string.html\">QString</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html#a631a94066cb7b5d639b2e0b7faae8604\">objectName</a></td></tr>\n\
<tr class=\"separator:a631a94066cb7b5d639b2e0b7faae8604 inherit properties_class_q_object\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
</table><table class=\"memberdecls\">\n\
<tr class=\"heading\"><td colspan=\"2\"><h2 class=\"groupheader\"><a name=\"friends\"></a>\n\
Friends</h2></td></tr>\n\
<tr class=\"memitem:a485ca0babd02f93a21e1be85dc1f9004\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">class&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_swipe_gesture.html#a485ca0babd02f93a21e1be85dc1f9004\">QSwipeGestureRecognizer</a></td></tr>\n\
<tr class=\"separator:a485ca0babd02f93a21e1be85dc1f9004\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
</table><table class=\"memberdecls\">\n\
<tr class=\"heading\"><td colspan=\"2\"><h2 class=\"groupheader\"><a name=\"inherited\"></a>\n\
Additional Inherited Members</h2></td></tr>\n\
<tr class=\"inherit_header pub_slots_class_q_object\"><td colspan=\"2\" onclick=\"javascript:toggleInherit(\'pub_slots_class_q_object\')\"><img src=\"cpp_ref/closed.png\" alt=\"-\">&#160;Public Slots inherited from <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html\">QObject</a></td></tr>\n\
<tr class=\"memitem:ae88f6ec618f65e3a1b410602512e27af inherit pub_slots_class_q_object\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html#ae88f6ec618f65e3a1b410602512e27af\">deleteLater</a> ()</td></tr>\n\
<tr class=\"separator:ae88f6ec618f65e3a1b410602512e27af inherit pub_slots_class_q_object\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"inherit_header signals_class_q_object\"><td colspan=\"2\" onclick=\"javascript:toggleInherit(\'signals_class_q_object\')\"><img src=\"cpp_ref/closed.png\" alt=\"-\">&#160;Signals inherited from <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html\">QObject</a></td></tr>\n\
<tr class=\"memitem:ac8d0c4c93fc174f6ffdf9857a7f60e4c inherit signals_class_q_object\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html#ac8d0c4c93fc174f6ffdf9857a7f60e4c\">destroyed</a> (<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html\">QObject</a> *=0)</td></tr>\n\
<tr class=\"separator:ac8d0c4c93fc174f6ffdf9857a7f60e4c inherit signals_class_q_object\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"inherit_header pub_static_methods_class_q_object\"><td colspan=\"2\" onclick=\"javascript:toggleInherit(\'pub_static_methods_class_q_object\')\"><img src=\"cpp_ref/closed.png\" alt=\"-\">&#160;Static Public Member Functions inherited from <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html\">QObject</a></td></tr>\n\
<tr class=\"memitem:a36adcf1b3cc7e17b84d884d99b5ad748 inherit pub_static_methods_class_q_object\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">static bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html#a36adcf1b3cc7e17b84d884d99b5ad748\">connect</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html\">QObject</a> *<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html#a0a425b6bb39a29d9777593aa3fb20e1c\">sender</a>, const char *signal, const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html\">QObject</a> *receiver, const char *<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#aaf221c4cca848f2b307b3c10dd478d77\">member</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/namespace_qt.html#aa1f0e2efd52935fd01bfece0fbead81f\">Qt::ConnectionType</a>=<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/namespace_qt.html#aa1f0e2efd52935fd01bfece0fbead81faa80a2853748720a77e994da0a473f0a9\">Qt::AutoConnection</a>)</td></tr>\n\
<tr class=\"separator:a36adcf1b3cc7e17b84d884d99b5ad748 inherit pub_static_methods_class_q_object\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a2de3e2c57a8a01286be30bc3b993f829 inherit pub_static_methods_class_q_object\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">static bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html#a2de3e2c57a8a01286be30bc3b993f829\">connect</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html\">QObject</a> *<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html#a0a425b6bb39a29d9777593aa3fb20e1c\">sender</a>, const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_meta_method.html\">QMetaMethod</a> &amp;signal, const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html\">QObject</a> *receiver, const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_meta_method.html\">QMetaMethod</a> &amp;method, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/namespace_qt.html#aa1f0e2efd52935fd01bfece0fbead81f\">Qt::ConnectionType</a> <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a63267399cd2a2ee217572c11d2e54f07\">type</a>=<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/namespace_qt.html#aa1f0e2efd52935fd01bfece0fbead81faa80a2853748720a77e994da0a473f0a9\">Qt::AutoConnection</a>)</td></tr>\n\
<tr class=\"separator:a2de3e2c57a8a01286be30bc3b993f829 inherit pub_static_methods_class_q_object\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:aa074187ef57b708d59f8c82bffc712ee inherit pub_static_methods_class_q_object\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">static bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html#aa074187ef57b708d59f8c82bffc712ee\">disconnect</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html\">QObject</a> *<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html#a0a425b6bb39a29d9777593aa3fb20e1c\">sender</a>, const char *signal, const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html\">QObject</a> *receiver, const char *<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#aaf221c4cca848f2b307b3c10dd478d77\">member</a>)</td></tr>\n\
<tr class=\"separator:aa074187ef57b708d59f8c82bffc712ee inherit pub_static_methods_class_q_object\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a0ccafd34fd6880e8770646d83874a8b5 inherit pub_static_methods_class_q_object\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">static bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html#a0ccafd34fd6880e8770646d83874a8b5\">disconnect</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html\">QObject</a> *<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html#a0a425b6bb39a29d9777593aa3fb20e1c\">sender</a>, const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_meta_method.html\">QMetaMethod</a> &amp;signal, const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html\">QObject</a> *receiver, const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_meta_method.html\">QMetaMethod</a> &amp;<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#aaf221c4cca848f2b307b3c10dd478d77\">member</a>)</td></tr>\n\
<tr class=\"separator:a0ccafd34fd6880e8770646d83874a8b5 inherit pub_static_methods_class_q_object\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:af57704c6dbbcb86e32e871056e338773 inherit pub_static_methods_class_q_object\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">static uint&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html#af57704c6dbbcb86e32e871056e338773\">registerUserData</a> ()</td></tr>\n\
<tr class=\"separator:af57704c6dbbcb86e32e871056e338773 inherit pub_static_methods_class_q_object\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"inherit_header pro_methods_class_q_gesture\"><td colspan=\"2\" onclick=\"javascript:toggleInherit(\'pro_methods_class_q_gesture\')\"><img src=\"cpp_ref/closed.png\" alt=\"-\">&#160;Protected Member Functions inherited from <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_gesture.html\">QGesture</a></td></tr>\n\
<tr class=\"memitem:a341402a33b56ac3258543d33373411c2 inherit pro_methods_class_q_gesture\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_gesture.html#a341402a33b56ac3258543d33373411c2\">QGesture</a> (QGesturePrivate &amp;dd, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html\">QObject</a> *<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html#a5bc37dc360715232180b31f152fe7df6\">parent</a>)</td></tr>\n\
<tr class=\"separator:a341402a33b56ac3258543d33373411c2 inherit pro_methods_class_q_gesture\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"inherit_header pro_methods_class_q_object\"><td colspan=\"2\" onclick=\"javascript:toggleInherit(\'pro_methods_class_q_object\')\"><img src=\"cpp_ref/closed.png\" alt=\"-\">&#160;Protected Member Functions inherited from <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html\">QObject</a></td></tr>\n\
<tr class=\"memitem:a0a425b6bb39a29d9777593aa3fb20e1c inherit pro_methods_class_q_object\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html\">QObject</a> *&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html#a0a425b6bb39a29d9777593aa3fb20e1c\">sender</a> () const </td></tr>\n\
<tr class=\"separator:a0a425b6bb39a29d9777593aa3fb20e1c inherit pro_methods_class_q_object\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a2feb2c5b2ed61e415441dfbb7d423568 inherit pro_methods_class_q_object\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a0067a505d12f13572b26d9535c23b671\">int</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html#a2feb2c5b2ed61e415441dfbb7d423568\">senderSignalIndex</a> () const </td></tr>\n\
<tr class=\"separator:a2feb2c5b2ed61e415441dfbb7d423568 inherit pro_methods_class_q_object\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a49a92d0d2ae12737b0c8656816d6bec6 inherit pro_methods_class_q_object\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a0067a505d12f13572b26d9535c23b671\">int</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html#a49a92d0d2ae12737b0c8656816d6bec6\">receivers</a> (const char *signal) const </td></tr>\n\
<tr class=\"separator:a49a92d0d2ae12737b0c8656816d6bec6 inherit pro_methods_class_q_object\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a390835b6f5cb9ed92e6f92f04f84d902 inherit pro_methods_class_q_object\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">virtual <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html#a390835b6f5cb9ed92e6f92f04f84d902\">timerEvent</a> (<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_timer_event.html\">QTimerEvent</a> *)</td></tr>\n\
<tr class=\"separator:a390835b6f5cb9ed92e6f92f04f84d902 inherit pro_methods_class_q_object\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a6f1d5bdddc57348dc8d2963f6964ef5c inherit pro_methods_class_q_object\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">virtual <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html#a6f1d5bdddc57348dc8d2963f6964ef5c\">childEvent</a> (<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_child_event.html\">QChildEvent</a> *)</td></tr>\n\
<tr class=\"separator:a6f1d5bdddc57348dc8d2963f6964ef5c inherit pro_methods_class_q_object\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:aab44b554f25df4c72798a0a845aace81 inherit pro_methods_class_q_object\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">virtual <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html#aab44b554f25df4c72798a0a845aace81\">customEvent</a> (<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_event.html\">QEvent</a> *)</td></tr>\n\
<tr class=\"separator:aab44b554f25df4c72798a0a845aace81 inherit pro_methods_class_q_object\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ad75854dd4a3c86c761a85e076cdb1243 inherit pro_methods_class_q_object\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">virtual <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html#ad75854dd4a3c86c761a85e076cdb1243\">connectNotify</a> (const char *signal)</td></tr>\n\
<tr class=\"separator:ad75854dd4a3c86c761a85e076cdb1243 inherit pro_methods_class_q_object\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a5210bca8cb0fcc656ecd66550fabbe84 inherit pro_methods_class_q_object\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">virtual <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html#a5210bca8cb0fcc656ecd66550fabbe84\">disconnectNotify</a> (const char *signal)</td></tr>\n\
<tr class=\"separator:a5210bca8cb0fcc656ecd66550fabbe84 inherit pro_methods_class_q_object\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a4f9a5fd4f252905cac4de264d56bab19 inherit pro_methods_class_q_object\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html#a4f9a5fd4f252905cac4de264d56bab19\">QObject</a> (QObjectPrivate &amp;dd, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html\">QObject</a> *<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html#a5bc37dc360715232180b31f152fe7df6\">parent</a>=0)</td></tr>\n\
<tr class=\"separator:a4f9a5fd4f252905cac4de264d56bab19 inherit pro_methods_class_q_object\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"inherit_header pro_attribs_class_q_object\"><td colspan=\"2\" onclick=\"javascript:toggleInherit(\'pro_attribs_class_q_object\')\"><img src=\"cpp_ref/closed.png\" alt=\"-\">&#160;Protected Attributes inherited from <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html\">QObject</a></td></tr>\n\
<tr class=\"memitem:aecb4f08ffa788e1a01a857def619b937 inherit pro_attribs_class_q_object\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_scoped_pointer.html\">QScopedPointer</a>&lt; <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object_data.html\">QObjectData</a> &gt;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html#aecb4f08ffa788e1a01a857def619b937\">d_ptr</a></td></tr>\n\
<tr class=\"separator:aecb4f08ffa788e1a01a857def619b937 inherit pro_attribs_class_q_object\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"inherit_header pro_static_attribs_class_q_object\"><td colspan=\"2\" onclick=\"javascript:toggleInherit(\'pro_static_attribs_class_q_object\')\"><img src=\"cpp_ref/closed.png\" alt=\"-\">&#160;Static Protected Attributes inherited from <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html\">QObject</a></td></tr>\n\
<tr class=\"memitem:a02703652a1697cfbb6b53a4d039b6b73 inherit pro_static_attribs_class_q_object\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">static const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/struct_q_meta_object.html\">QMetaObject</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html#a02703652a1697cfbb6b53a4d039b6b73\">staticQtMetaObject</a></td></tr>\n\
<tr class=\"separator:a02703652a1697cfbb6b53a4d039b6b73 inherit pro_static_attribs_class_q_object\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
</table>\n\
<h2 class=\"groupheader\">Member Enumeration Documentation</h2>\n\
<a class=\"anchor\" id=\"a5f2a0ca7016284497a2768c469290e42\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">enum <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_swipe_gesture.html#a5f2a0ca7016284497a2768c469290e42\">SwipeDirection</a></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<table class=\"fieldtable\">\n\
<tr><th colspan=\"2\">Enumerator</th></tr><tr><td class=\"fieldname\"><a class=\"anchor\" id=\"a5f2a0ca7016284497a2768c469290e42aca3e0efea800bf6b107cc8fa09e4bb06\"></a>NoDirection&#160;</td><td class=\"fielddoc\">\n\
</td></tr>\n\
<tr><td class=\"fieldname\"><a class=\"anchor\" id=\"a5f2a0ca7016284497a2768c469290e42a9d4d8b0b72fc2659da772d761a3c5ecb\"></a>Left&#160;</td><td class=\"fielddoc\">\n\
</td></tr>\n\
<tr><td class=\"fieldname\"><a class=\"anchor\" id=\"a5f2a0ca7016284497a2768c469290e42ad48f7af8c070184f3774c8e85854eb66\"></a>Right&#160;</td><td class=\"fielddoc\">\n\
</td></tr>\n\
<tr><td class=\"fieldname\"><a class=\"anchor\" id=\"a5f2a0ca7016284497a2768c469290e42a57a7edcbc04d6175683383cad5c3e0a2\"></a>Up&#160;</td><td class=\"fielddoc\">\n\
</td></tr>\n\
<tr><td class=\"fieldname\"><a class=\"anchor\" id=\"a5f2a0ca7016284497a2768c469290e42abcf8c79e9a5f5f9d606fb35645a0fb27\"></a>Down&#160;</td><td class=\"fielddoc\">\n\
</td></tr>\n\
</table>\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qgesture_8h_source.html#l00219\">219</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qgesture_8h_source.html\">qgesture.h</a>.</p>\n\
<div class=\"fragment\"><div class=\"line\"><a name=\"l00219\"></a><span class=\"lineno\">  219</span>&#160;{ <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_swipe_gesture.html#a5f2a0ca7016284497a2768c469290e42aca3e0efea800bf6b107cc8fa09e4bb06\">NoDirection</a>, <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_swipe_gesture.html#a5f2a0ca7016284497a2768c469290e42a9d4d8b0b72fc2659da772d761a3c5ecb\">Left</a>, <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_swipe_gesture.html#a5f2a0ca7016284497a2768c469290e42ad48f7af8c070184f3774c8e85854eb66\">Right</a>, <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_swipe_gesture.html#a5f2a0ca7016284497a2768c469290e42a57a7edcbc04d6175683383cad5c3e0a2\">Up</a>, <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_swipe_gesture.html#a5f2a0ca7016284497a2768c469290e42abcf8c79e9a5f5f9d606fb35645a0fb27\">Down</a> };</div>\n\
<div class=\"ttc\" id=\"class_q_swipe_gesture_html_a5f2a0ca7016284497a2768c469290e42abcf8c79e9a5f5f9d606fb35645a0fb27\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_swipe_gesture.html#a5f2a0ca7016284497a2768c469290e42abcf8c79e9a5f5f9d606fb35645a0fb27\">QSwipeGesture::Down</a></div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qgesture_8h_source.html#l00219\">qgesture.h:219</a></div></div>\n\
<div class=\"ttc\" id=\"class_q_swipe_gesture_html_a5f2a0ca7016284497a2768c469290e42a57a7edcbc04d6175683383cad5c3e0a2\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_swipe_gesture.html#a5f2a0ca7016284497a2768c469290e42a57a7edcbc04d6175683383cad5c3e0a2\">QSwipeGesture::Up</a></div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qgesture_8h_source.html#l00219\">qgesture.h:219</a></div></div>\n\
<div class=\"ttc\" id=\"class_q_swipe_gesture_html_a5f2a0ca7016284497a2768c469290e42aca3e0efea800bf6b107cc8fa09e4bb06\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_swipe_gesture.html#a5f2a0ca7016284497a2768c469290e42aca3e0efea800bf6b107cc8fa09e4bb06\">QSwipeGesture::NoDirection</a></div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qgesture_8h_source.html#l00219\">qgesture.h:219</a></div></div>\n\
<div class=\"ttc\" id=\"class_q_swipe_gesture_html_a5f2a0ca7016284497a2768c469290e42ad48f7af8c070184f3774c8e85854eb66\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_swipe_gesture.html#a5f2a0ca7016284497a2768c469290e42ad48f7af8c070184f3774c8e85854eb66\">QSwipeGesture::Right</a></div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qgesture_8h_source.html#l00219\">qgesture.h:219</a></div></div>\n\
<div class=\"ttc\" id=\"class_q_swipe_gesture_html_a5f2a0ca7016284497a2768c469290e42a9d4d8b0b72fc2659da772d761a3c5ecb\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_swipe_gesture.html#a5f2a0ca7016284497a2768c469290e42a9d4d8b0b72fc2659da772d761a3c5ecb\">QSwipeGesture::Left</a></div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qgesture_8h_source.html#l00219\">qgesture.h:219</a></div></div>\n\
</div><!-- fragment -->\n\
</div>\n\
</div>\n\
<h2 class=\"groupheader\">Constructor &amp; Destructor Documentation</h2>\n\
<a class=\"anchor\" id=\"a047752938e8a9e57f8a10e24c2d4076c\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_swipe_gesture.html\">QSwipeGesture</a> </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html\">QObject</a> *&#160;</td>\n\
          <td class=\"paramname\"><em>parent</em> = <code>0</code></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
</div>\n\
</div>\n\
<h2 class=\"groupheader\">Member Function Documentation</h2>\n\
<a class=\"anchor\" id=\"a3c5506175a3a21c7c867efd422553b92\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_swipe_gesture.html#a5f2a0ca7016284497a2768c469290e42\">SwipeDirection</a> horizontalDirection </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"ad833f8cc0a898c81934009dd5c1d743b\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_swipe_gesture.html#a5f2a0ca7016284497a2768c469290e42\">SwipeDirection</a> verticalDirection </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a1b119db778d3adf4a0e4e9ed41d70338\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">qreal swipeAngle </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a7f3f48c8768f199c67d5b874e7ba040d\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a> setSwipeAngle </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">qreal&#160;</td>\n\
          <td class=\"paramname\"><em>value</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
</div>\n\
</div>\n\
<h2 class=\"groupheader\">Friends And Related Function Documentation</h2>\n\
<a class=\"anchor\" id=\"a485ca0babd02f93a21e1be85dc1f9004\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">friend class QSwipeGestureRecognizer</td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">friend</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qgesture_8h_source.html#l00228\">228</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qgesture_8h_source.html\">qgesture.h</a>.</p>\n\
\n\
</div>\n\
</div>\n\
<h2 class=\"groupheader\">Property Documentation</h2>\n\
<a class=\"anchor\" id=\"a7d6d717366533d19ffc93f6d289e1035\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_swipe_gesture.html#a5f2a0ca7016284497a2768c469290e42\">SwipeDirection</a> horizontalDirection</td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">read</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qgesture_8h_source.html#l00213\">213</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qgesture_8h_source.html\">qgesture.h</a>.</p>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a9f2f1336639148b093ddc870858f4dab\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_swipe_gesture.html#a5f2a0ca7016284497a2768c469290e42\">SwipeDirection</a> verticalDirection</td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">read</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qgesture_8h_source.html#l00214\">214</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qgesture_8h_source.html\">qgesture.h</a>.</p>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a5a56b0a26931c98ed4b9c086ec1ec590\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">qreal swipeAngle</td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">read</span><span class=\"mlabel\">write</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qgesture_8h_source.html#l00215\">215</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qgesture_8h_source.html\">qgesture.h</a>.</p>\n\
\n\
</div>\n\
</div>\n\
<hr>The documentation for this class was generated from the following file:<ul>\n\
<li>QtGui/<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qgesture_8h_source.html\">qgesture.h</a></li>\n\
</ul>\n\
</div><!-- contents -->\n\
</div><!-- doc-content -->\n\
          <div class=\"footer-block\"><a href=\"../html/ac.cmtdialog.htm\" class=\"comments-anchor\" target=\"_blank\"><span class=\"comments-link\">Please send us your comment about this page</span></a></div></div>\n\
   </div></body>\n\
</html>\n\
";