var topic = "<!-- saved from url=(0024)http://docs.autodesk.com -->\n\
<html>\n\
   <head><script src=\"../scripts/yepnope.1.5.4-min.js\" type=\"text/javascript\"></script><script src=\"../scripts/lib/jquery-1.11.1.min.js\" type=\"text/javascript\"></script><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"><meta name=\"product\" content=\"MOBPRO\"><meta name=\"release\" content=\"2018\"><meta name=\"book\" content=\"GeneralUser\"><meta name=\"created\" content=\"2017-09-08\"><meta name=\"topicid\" content=\"GUID-02FA7DD3-6C7A-4C6A-B7BC-824765AE1CB2\"><meta name=\"topic-type\" content=\"concept\">\n\
      <title>ThreadEngineBase Class Reference</title>\n\
   \n\
\n\
</head>\n\
   <body height=\"100%\"><div class=\"body_content\" id=\"body-content\"><link rel=\"stylesheet\" type=\"text/css\" href=\"cpp_ref/navtree.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"cpp_ref/doxygen.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"cpp_ref/tabs.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"style/adsk.cpm.css\"><script language=\"javascript\">var index = \'index.html\';</script><script>$(document).ready(function() { yepnope.injectJs(\"./scripts/ac_common.js\"); });</script><script type=\"text/javascript\">\n\
var tocSystemNeedsToBeLoaded = typeof(cpp_ref_adsk_ref_toc) == \'undefined\';\n\
var weAreIn21 = $(\'div#main.view-active\').length;\n\
var tocPrefix = \'\';\n\
if (weAreIn21)\n\
{ tocPrefix = \'cpp_ref/\'; }\n\
function cpp_ref_initializeToc(forceTrigger) {\n\
    cpp_ref_adsk_ref_toc.initResizable();\n\
    cpp_ref_adsk_ref_toc.initNavTree(\'class_qt_concurrent_1_1_thread_engine_base.html\', tocPrefix);\n\
    dQuery(document).trigger(\'toc_initialized\');\n\
}\n\
if (tocSystemNeedsToBeLoaded)\n\
{\n\
	yepnope([{\n\
	load:[tocPrefix + \'json3.min.js\', tocPrefix + \'jquery.js\', tocPrefix + \'ref-toc-controller.js\', tocPrefix + \'dynsections.js\'],\n\
	complete: function() {\n\
	  if (typeof(dQuery) == \'undefined\')\n\
	  {\n\
	    dQuery = jQuery.noConflict(true);\n\
	  }\n\
	  else { jQuery.noConflict(true); }\n\
	  $(document).ready(cpp_ref_initializeToc);\n\
	}\n\
 	}])\n\
}\n\
if (!weAreIn21) { // if in AKN...\n\
$(window).load( function() {\n\
    setTimeout( function() {\n\
        var content = $(\'body > div\').not(\'#body-content\');     // take any divs under body that are not id=body-content\n\
        content.each( function() { \n\
            $(this).css( { \'padding-left\': $(this).css(\'margin-left\') } );       // and if they have any padding-left already, move it to margin-left.\n\
        } );\n\
        var width = cpp_ref_adsk_ref_toc.readFromStorage(\'width\');\n\
        content.css({marginLeft:parseInt(width)+6+\"px\"});\n\
    }, 100);\n\
} ); \n\
}\n\
</script><script>$(\"div#WidgetFloaterPanels,link[href*=\'microsofttranslator.com\'],script[src*=\'microsofttranslator.com\'],script[src*=\'bing.com\']\").remove();</script><script type=\'text/javascript\'>$(\"div#navigation,div#breadcrumbs,div#banner\").attr(\"translate\",\"no\"); var mtLocation = ((location && location.href && location.href.indexOf(\'https\') == 0)?\'https://ssl.microsofttranslator.com\':\'http://www.microsofttranslator.com\')+\'/ajax/v3/WidgetV3.ashx?ctf=True&ui=true&settings=Manual&from=en&hidelanguages=\'; yepnope.injectJs(mtLocation, function() {}, { charset:\'utf-8\', type:\'text/javascript\' } );</script><script>\n\
 if (!tocSystemNeedsToBeLoaded) { cpp_ref_initializeToc(); }\n\
 </script><!-- begin MT -->\n\
            \n\
            <div id=\'MicrosoftTranslatorWidget\' class=\'Dark\' style=\'float:right;z-index:100;color:white;background-color:#bbbbbb;height:58px;overflow:hidden\'></div>\n\
      <div>\n\
         <div class=\"head\">\n\
            <h1>ThreadEngineBase Class Reference</h1>\n\
         </div>\n\
\n\
    <div id=\"top\"><!-- Generated by Doxygen 1.8.10 -->\n\
  <div id=\"navrow1\" class=\"tabs\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./cpp_ref/index.html\"><span>Main&#160;Page</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/pages.html\"><span>Topics</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/modules.html\"><span>Modules</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/namespaces.html\"><span>Namespaces</span></a></li>\n\
      <li class=\"current\"><a href=\"#!/url=./cpp_ref/annotated.html\"><span>Classes</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/files.html\"><span>Files</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/examples.html\"><span>Examples</span></a></li>\n\
    </ul>\n\
  </div>\n\
  <div id=\"navrow2\" class=\"tabs2\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./cpp_ref/annotated.html\"><span>Class&#160;List</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/hierarchy.html\"><span>Class&#160;Hierarchy</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/functions.html\"><span>Class&#160;Members</span></a></li>\n\
    </ul>\n\
  </div>\n\
</div><!-- top -->\n\
<div id=\"side-nav\" class=\"ui-resizable side-nav-resizable\">\n\
  <div id=\"nav-tree\">\n\
    <div id=\"nav-tree-contents\">\n\
      <div id=\"nav-sync\" class=\"sync\"></div>\n\
    </div>\n\
  </div>\n\
  <div id=\"splitbar\" style=\"-moz-user-select:none;\" class=\"ui-resizable-handle\">\n\
  </div>\n\
</div>\n\
\n\
<div id=\"doc-content\">\n\
<div class=\"header\">\n\
  \n\
  <div class=\"headertitle\">\n\
<div class=\"title\">ThreadEngineBase Class Reference<span class=\"mlabels\"><span class=\"mlabel\">abstract</span></span></div>  </div>\n\
<div class=\"summary\">\n\
<a href=\"class_qt_concurrent_1_1_thread_engine_base.html#pub-methods\">Public Member Functions</a> &#124;\n\
<a href=\"class_qt_concurrent_1_1_thread_engine_base.html#pro-methods\">Protected Member Functions</a> &#124;\n\
<a href=\"class_qt_concurrent_1_1_thread_engine_base.html#pro-attribs\">Protected Attributes</a>  </div></div><!--header-->\n\
<div class=\"contents\">\n\
\n\
<p><code>#include &lt;<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qtconcurrentthreadengine_8h_source.html\">qtconcurrentthreadengine.h</a>&gt;</code></p>\n\
<a name=\"details\" id=\"details\"></a><h2 class=\"groupheader\">Class Description</h2>\n\
<div class=\"textblock\">\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qtconcurrentthreadengine_8h_source.html#l00097\">97</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qtconcurrentthreadengine_8h_source.html\">qtconcurrentthreadengine.h</a>.</p>\n\
</div><div id=\"dynsection-0\" onclick=\"return toggleVisibility(this)\" class=\"dynheader closed\" style=\"cursor:pointer;\">\n\
  <img id=\"dynsection-0-trigger\" src=\"cpp_ref/closed.png\" alt=\"+\"> Inheritance diagram for ThreadEngineBase:</div>\n\
<div id=\"dynsection-0-summary\" class=\"dynsummary\" style=\"display:block;\">\n\
</div>\n\
<div id=\"dynsection-0-content\" class=\"dyncontent\" style=\"display:none;\">\n\
 <div class=\"center\">\n\
  <img src=\"cpp_ref/class_qt_concurrent_1_1_thread_engine_base.png\" usemap=\"#ThreadEngineBase_map\" alt=\"\">\n\
  <map id=\"ThreadEngineBase_map\" name=\"ThreadEngineBase_map\">\n\
<area href=\"class_q_runnable.html\" alt=\"QRunnable\" shape=\"rect\" coords=\"1144,0,1706,24\">\n\
<area href=\"class_qt_concurrent_1_1_thread_engine.html\" alt=\"ThreadEngine&lt; T &gt;\" shape=\"rect\" coords=\"0,112,562,136\">\n\
<area href=\"class_qt_concurrent_1_1_thread_engine.html\" alt=\"ThreadEngine&lt; MapFunctor::result_type &gt;\" shape=\"rect\" coords=\"572,112,1134,136\">\n\
<area href=\"class_qt_concurrent_1_1_thread_engine.html\" alt=\"ThreadEngine&lt; qValueType&lt; Iterator &gt;::value_type &gt;\" shape=\"rect\" coords=\"1144,112,1706,136\">\n\
<area href=\"class_qt_concurrent_1_1_thread_engine.html\" alt=\"ThreadEngine&lt; ReducedResultType &gt;\" shape=\"rect\" coords=\"2002,112,2564,136\">\n\
<area href=\"class_qt_concurrent_1_1_thread_engine.html\" alt=\"ThreadEngine&lt; void &gt;\" shape=\"rect\" coords=\"3146,112,3708,136\">\n\
<area href=\"class_qt_concurrent_1_1_iterate_kernel.html\" alt=\"IterateKernel&lt; Iterator, T &gt;\" shape=\"rect\" coords=\"0,168,562,192\">\n\
<area href=\"class_qt_concurrent_1_1_iterate_kernel.html\" alt=\"IterateKernel&lt; Iterator, MapFunctor::result_type &gt;\" shape=\"rect\" coords=\"572,168,1134,192\">\n\
<area href=\"class_qt_concurrent_1_1_iterate_kernel.html\" alt=\"IterateKernel&lt; Iterator, qValueType&lt; Iterator &gt;::value_type &gt;\" shape=\"rect\" coords=\"1144,168,1706,192\">\n\
<area href=\"class_qt_concurrent_1_1_iterate_kernel.html\" alt=\"IterateKernel&lt; Iterator, ReducedResultType &gt;\" shape=\"rect\" coords=\"2002,168,2564,192\">\n\
<area href=\"class_qt_concurrent_1_1_iterate_kernel.html\" alt=\"IterateKernel&lt; Iterator, void &gt;\" shape=\"rect\" coords=\"2860,168,3422,192\">\n\
<area href=\"class_qt_concurrent_1_1_iterate_kernel.html\" alt=\"IterateKernel&lt; Sequence::const_iterator, void &gt;\" shape=\"rect\" coords=\"3432,168,3994,192\">\n\
<area href=\"class_qt_concurrent_1_1_mapped_each_kernel.html\" alt=\"MappedEachKernel&lt; Iterator, MapFunctor &gt;\" shape=\"rect\" coords=\"572,224,1134,248\">\n\
<area href=\"class_qt_concurrent_1_1_filtered_each_kernel.html\" alt=\"FilteredEachKernel&lt; Iterator, KeepFunctor &gt;\" shape=\"rect\" coords=\"1144,224,1706,248\">\n\
<area href=\"class_qt_concurrent_1_1_filtered_reduced_kernel.html\" alt=\"FilteredReducedKernel&lt; ReducedResultType, Iterator, KeepFunctor, ReduceFunctor, Reducer &gt;\" shape=\"rect\" coords=\"1716,224,2278,248\">\n\
<area href=\"class_qt_concurrent_1_1_mapped_reduced_kernel.html\" alt=\"MappedReducedKernel&lt; ReducedResultType, Iterator, MapFunctor, ReduceFunctor, Reducer &gt;\" shape=\"rect\" coords=\"2288,224,2850,248\">\n\
<area href=\"class_qt_concurrent_1_1_map_kernel.html\" alt=\"MapKernel&lt; Iterator, MapFunctor &gt;\" shape=\"rect\" coords=\"2860,224,3422,248\">\n\
<area href=\"class_qt_concurrent_1_1_filter_kernel.html\" alt=\"FilterKernel&lt; Sequence, KeepFunctor, ReduceFunctor &gt;\" shape=\"rect\" coords=\"3432,224,3994,248\">\n\
</map>\n\
 </div></div>\n\
<table class=\"memberdecls\">\n\
<tr class=\"heading\"><td colspan=\"2\"><h2 class=\"groupheader\"><a name=\"pub-methods\"></a>\n\
Public Member Functions</h2></td></tr>\n\
<tr class=\"memitem:a97f3b3abc0f2b2f34f3f2ab4db05d86f\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_thread_engine_base.html#a97f3b3abc0f2b2f34f3f2ab4db05d86f\">ThreadEngineBase</a> ()</td></tr>\n\
<tr class=\"separator:a97f3b3abc0f2b2f34f3f2ab4db05d86f\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ab5d1561a366ea193ead63934d2f5ce27\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">virtual&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_thread_engine_base.html#ab5d1561a366ea193ead63934d2f5ce27\">~ThreadEngineBase</a> ()</td></tr>\n\
<tr class=\"separator:ab5d1561a366ea193ead63934d2f5ce27\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ad4ca948d69d168821335943feaeb102a\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_thread_engine_base.html#ad4ca948d69d168821335943feaeb102a\">startSingleThreaded</a> ()</td></tr>\n\
<tr class=\"separator:ad4ca948d69d168821335943feaeb102a\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ab73427842547954c282c377fc396306a\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_thread_engine_base.html#ab73427842547954c282c377fc396306a\">startBlocking</a> ()</td></tr>\n\
<tr class=\"separator:ab73427842547954c282c377fc396306a\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a97e2ac12bcf73c041e55eb85fbec74c4\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_thread_engine_base.html#a97e2ac12bcf73c041e55eb85fbec74c4\">startThread</a> ()</td></tr>\n\
<tr class=\"separator:a97e2ac12bcf73c041e55eb85fbec74c4\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a7c106eb4e682c11714b8e99036bd6e48\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_thread_engine_base.html#a7c106eb4e682c11714b8e99036bd6e48\">isCanceled</a> ()</td></tr>\n\
<tr class=\"separator:a7c106eb4e682c11714b8e99036bd6e48\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a6cfd97aaf204be66d0c6297e58b5495a\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_thread_engine_base.html#a6cfd97aaf204be66d0c6297e58b5495a\">waitForResume</a> ()</td></tr>\n\
<tr class=\"separator:a6cfd97aaf204be66d0c6297e58b5495a\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a7e7213097e41535c5e2bcde9d438f7a6\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_thread_engine_base.html#a7e7213097e41535c5e2bcde9d438f7a6\">isProgressReportingEnabled</a> ()</td></tr>\n\
<tr class=\"separator:a7e7213097e41535c5e2bcde9d438f7a6\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a7276c56e48caba7bfd2664f812843f7d\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_thread_engine_base.html#a7276c56e48caba7bfd2664f812843f7d\">setProgressValue</a> (<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a0067a505d12f13572b26d9535c23b671\">int</a> progress)</td></tr>\n\
<tr class=\"separator:a7276c56e48caba7bfd2664f812843f7d\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:adfc5e5d29e7702a981515d6450c8fabb\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_thread_engine_base.html#adfc5e5d29e7702a981515d6450c8fabb\">setProgressRange</a> (<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a0067a505d12f13572b26d9535c23b671\">int</a> minimum, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a0067a505d12f13572b26d9535c23b671\">int</a> maximum)</td></tr>\n\
<tr class=\"separator:adfc5e5d29e7702a981515d6450c8fabb\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a29fa4e7c47644330a2baff583f9cdd2a\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_thread_engine_base.html#a29fa4e7c47644330a2baff583f9cdd2a\">acquireBarrierSemaphore</a> ()</td></tr>\n\
<tr class=\"separator:a29fa4e7c47644330a2baff583f9cdd2a\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"inherit_header pub_methods_class_q_runnable\"><td colspan=\"2\" onclick=\"javascript:toggleInherit(\'pub_methods_class_q_runnable\')\"><img src=\"cpp_ref/closed.png\" alt=\"-\">&#160;Public Member Functions inherited from <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_runnable.html\">QRunnable</a></td></tr>\n\
<tr class=\"memitem:acc3822940673c749d982f948f1fedfe7 inherit pub_methods_class_q_runnable\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_runnable.html#acc3822940673c749d982f948f1fedfe7\">QRunnable</a> ()</td></tr>\n\
<tr class=\"separator:acc3822940673c749d982f948f1fedfe7 inherit pub_methods_class_q_runnable\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a5289220d9cad885dcd6ef85dcc3f75f0 inherit pub_methods_class_q_runnable\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">virtual&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_runnable.html#a5289220d9cad885dcd6ef85dcc3f75f0\">~QRunnable</a> ()</td></tr>\n\
<tr class=\"separator:a5289220d9cad885dcd6ef85dcc3f75f0 inherit pub_methods_class_q_runnable\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a64c0f7f7f99c10922f570668b10acb2f inherit pub_methods_class_q_runnable\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_runnable.html#a64c0f7f7f99c10922f570668b10acb2f\">autoDelete</a> () const </td></tr>\n\
<tr class=\"separator:a64c0f7f7f99c10922f570668b10acb2f inherit pub_methods_class_q_runnable\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a1c29746a02a2a798fa378903688df61f inherit pub_methods_class_q_runnable\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_runnable.html#a1c29746a02a2a798fa378903688df61f\">setAutoDelete</a> (bool _autoDelete)</td></tr>\n\
<tr class=\"separator:a1c29746a02a2a798fa378903688df61f inherit pub_methods_class_q_runnable\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
</table><table class=\"memberdecls\">\n\
<tr class=\"heading\"><td colspan=\"2\"><h2 class=\"groupheader\"><a name=\"pro-methods\"></a>\n\
Protected Member Functions</h2></td></tr>\n\
<tr class=\"memitem:a62b63bddf378b0e13a4affa3e8e1bedf\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">virtual <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_thread_engine_base.html#a62b63bddf378b0e13a4affa3e8e1bedf\">start</a> ()</td></tr>\n\
<tr class=\"separator:a62b63bddf378b0e13a4affa3e8e1bedf\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:add480a9cf3f0b32e06ef6e9b87c36b16\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">virtual <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_thread_engine_base.html#add480a9cf3f0b32e06ef6e9b87c36b16\">finish</a> ()</td></tr>\n\
<tr class=\"separator:add480a9cf3f0b32e06ef6e9b87c36b16\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a4e91c107f3578302c37dc577b3b92e11\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">virtual <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/namespace_qt_concurrent.html#a305abcf818c95af6b4ca5a8c3b805874\">ThreadFunctionResult</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_thread_engine_base.html#a4e91c107f3578302c37dc577b3b92e11\">threadFunction</a> ()</td></tr>\n\
<tr class=\"separator:a4e91c107f3578302c37dc577b3b92e11\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:abb78ae19dc9edb1eb4834b0cf47d4980\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">virtual bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_thread_engine_base.html#abb78ae19dc9edb1eb4834b0cf47d4980\">shouldStartThread</a> ()</td></tr>\n\
<tr class=\"separator:abb78ae19dc9edb1eb4834b0cf47d4980\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a61d2f0a45c238719f5b358dc5243aba4\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">virtual bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_thread_engine_base.html#a61d2f0a45c238719f5b358dc5243aba4\">shouldThrottleThread</a> ()</td></tr>\n\
<tr class=\"separator:a61d2f0a45c238719f5b358dc5243aba4\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
</table><table class=\"memberdecls\">\n\
<tr class=\"heading\"><td colspan=\"2\"><h2 class=\"groupheader\"><a name=\"pro-attribs\"></a>\n\
Protected Attributes</h2></td></tr>\n\
<tr class=\"memitem:af5da37966cac83d4904fb091fa62fb9e\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_future_interface_base.html\">QFutureInterfaceBase</a> *&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_thread_engine_base.html#af5da37966cac83d4904fb091fa62fb9e\">futureInterface</a></td></tr>\n\
<tr class=\"separator:af5da37966cac83d4904fb091fa62fb9e\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ad5e9771198144d6dfc215c4024a68f88\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_thread_pool.html\">QThreadPool</a> *&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_thread_engine_base.html#ad5e9771198144d6dfc215c4024a68f88\">threadPool</a></td></tr>\n\
<tr class=\"separator:ad5e9771198144d6dfc215c4024a68f88\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a81312e97c5e51c920b7c4986d5c6b9dc\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_thread_engine_barrier.html\">ThreadEngineBarrier</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_thread_engine_base.html#a81312e97c5e51c920b7c4986d5c6b9dc\">barrier</a></td></tr>\n\
<tr class=\"separator:a81312e97c5e51c920b7c4986d5c6b9dc\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a8f97f458fdee8fc837f2fc7f21a76ea5\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1internal_1_1_exception_store.html\">QtConcurrent::internal::ExceptionStore</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_thread_engine_base.html#a8f97f458fdee8fc837f2fc7f21a76ea5\">exceptionStore</a></td></tr>\n\
<tr class=\"separator:a8f97f458fdee8fc837f2fc7f21a76ea5\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
</table>\n\
<h2 class=\"groupheader\">Constructor &amp; Destructor Documentation</h2>\n\
<a class=\"anchor\" id=\"a97f3b3abc0f2b2f34f3f2ab4db05d86f\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_thread_engine_base.html\">ThreadEngineBase</a> </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"ab5d1561a366ea193ead63934d2f5ce27\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">virtual ~<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_thread_engine_base.html\">ThreadEngineBase</a> </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">virtual</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
\n\
</div>\n\
</div>\n\
<h2 class=\"groupheader\">Member Function Documentation</h2>\n\
<a class=\"anchor\" id=\"ad4ca948d69d168821335943feaeb102a\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a> startSingleThreaded </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"ab73427842547954c282c377fc396306a\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a> startBlocking </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a97e2ac12bcf73c041e55eb85fbec74c4\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a> startThread </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a7c106eb4e682c11714b8e99036bd6e48\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">bool isCanceled </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a6cfd97aaf204be66d0c6297e58b5495a\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a> waitForResume </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a7e7213097e41535c5e2bcde9d438f7a6\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">bool isProgressReportingEnabled </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a7276c56e48caba7bfd2664f812843f7d\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a> setProgressValue </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a0067a505d12f13572b26d9535c23b671\">int</a>&#160;</td>\n\
          <td class=\"paramname\"><em>progress</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"adfc5e5d29e7702a981515d6450c8fabb\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a> setProgressRange </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a0067a505d12f13572b26d9535c23b671\">int</a>&#160;</td>\n\
          <td class=\"paramname\"><em>minimum</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a0067a505d12f13572b26d9535c23b671\">int</a>&#160;</td>\n\
          <td class=\"paramname\"><em>maximum</em>&#160;</td>\n\
        </tr>\n\
        <tr>\n\
          <td></td>\n\
          <td>)</td>\n\
          <td></td><td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a29fa4e7c47644330a2baff583f9cdd2a\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a> acquireBarrierSemaphore </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a62b63bddf378b0e13a4affa3e8e1bedf\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">virtual <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a> <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a13be19455586e95d5a42ed8f054afad2\">start</a> </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">inline</span><span class=\"mlabel\">protected</span><span class=\"mlabel\">virtual</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Reimplemented in <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_filtered_each_kernel.html#a60de64d75454385b23995437f1d72669\">FilteredEachKernel&lt; Iterator, KeepFunctor &gt;</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_iterate_kernel.html#a60de64d75454385b23995437f1d72669\">IterateKernel&lt; Iterator, T &gt;</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_iterate_kernel.html#a60de64d75454385b23995437f1d72669\">IterateKernel&lt; Iterator, void &gt;</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_iterate_kernel.html#a60de64d75454385b23995437f1d72669\">IterateKernel&lt; Iterator, MapFunctor::result_type &gt;</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_iterate_kernel.html#a60de64d75454385b23995437f1d72669\">IterateKernel&lt; Iterator, qValueType&lt; Iterator &gt;::value_type &gt;</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_iterate_kernel.html#a60de64d75454385b23995437f1d72669\">IterateKernel&lt; Sequence::const_iterator, void &gt;</a>, and <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_iterate_kernel.html#a60de64d75454385b23995437f1d72669\">IterateKernel&lt; Iterator, ReducedResultType &gt;</a>.</p>\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qtconcurrentthreadengine_8h_source.html#l00114\">114</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qtconcurrentthreadengine_8h_source.html\">qtconcurrentthreadengine.h</a>.</p>\n\
<div class=\"fragment\"><div class=\"line\"><a name=\"l00114\"></a><span class=\"lineno\">  114</span>&#160;{}</div>\n\
</div><!-- fragment -->\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"add480a9cf3f0b32e06ef6e9b87c36b16\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">virtual <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a> finish </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">inline</span><span class=\"mlabel\">protected</span><span class=\"mlabel\">virtual</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Reimplemented in <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_filtered_reduced_kernel.html#a6dfe1abe0d1eb3ddc1ca081de98b5342\">FilteredReducedKernel&lt; ReducedResultType, Iterator, KeepFunctor, ReduceFunctor, Reducer &gt;</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_mapped_reduced_kernel.html#a6dfe1abe0d1eb3ddc1ca081de98b5342\">MappedReducedKernel&lt; ReducedResultType, Iterator, MapFunctor, ReduceFunctor, Reducer &gt;</a>, and <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_filter_kernel.html#a6dfe1abe0d1eb3ddc1ca081de98b5342\">FilterKernel&lt; Sequence, KeepFunctor, ReduceFunctor &gt;</a>.</p>\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qtconcurrentthreadengine_8h_source.html#l00115\">115</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qtconcurrentthreadengine_8h_source.html\">qtconcurrentthreadengine.h</a>.</p>\n\
<div class=\"fragment\"><div class=\"line\"><a name=\"l00115\"></a><span class=\"lineno\">  115</span>&#160;{}</div>\n\
</div><!-- fragment -->\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a4e91c107f3578302c37dc577b3b92e11\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">virtual <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/namespace_qt_concurrent.html#a305abcf818c95af6b4ca5a8c3b805874\">ThreadFunctionResult</a> threadFunction </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">inline</span><span class=\"mlabel\">protected</span><span class=\"mlabel\">virtual</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Reimplemented in <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_iterate_kernel.html#a6fec2206980791edc00de23cdc788939\">IterateKernel&lt; Iterator, T &gt;</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_iterate_kernel.html#a6fec2206980791edc00de23cdc788939\">IterateKernel&lt; Iterator, void &gt;</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_iterate_kernel.html#a6fec2206980791edc00de23cdc788939\">IterateKernel&lt; Iterator, MapFunctor::result_type &gt;</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_iterate_kernel.html#a6fec2206980791edc00de23cdc788939\">IterateKernel&lt; Iterator, qValueType&lt; Iterator &gt;::value_type &gt;</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_iterate_kernel.html#a6fec2206980791edc00de23cdc788939\">IterateKernel&lt; Sequence::const_iterator, void &gt;</a>, and <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_iterate_kernel.html#a6fec2206980791edc00de23cdc788939\">IterateKernel&lt; Iterator, ReducedResultType &gt;</a>.</p>\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qtconcurrentthreadengine_8h_source.html#l00116\">116</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qtconcurrentthreadengine_8h_source.html\">qtconcurrentthreadengine.h</a>.</p>\n\
<div class=\"fragment\"><div class=\"line\"><a name=\"l00116\"></a><span class=\"lineno\">  116</span>&#160;{ <span class=\"keywordflow\">return</span> <a class=\"code\" href=\"#!/url=./cpp_ref/namespace_qt_concurrent.html#a305abcf818c95af6b4ca5a8c3b805874a08bc03ce784c6a9629efba07a65df531\">ThreadFinished</a>; }</div>\n\
<div class=\"ttc\" id=\"namespace_qt_concurrent_html_a305abcf818c95af6b4ca5a8c3b805874a08bc03ce784c6a9629efba07a65df531\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/namespace_qt_concurrent.html#a305abcf818c95af6b4ca5a8c3b805874a08bc03ce784c6a9629efba07a65df531\">QtConcurrent::ThreadFinished</a></div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qtconcurrentthreadengine_8h_source.html#l00091\">qtconcurrentthreadengine.h:91</a></div></div>\n\
</div><!-- fragment -->\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"abb78ae19dc9edb1eb4834b0cf47d4980\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">virtual bool shouldStartThread </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">inline</span><span class=\"mlabel\">protected</span><span class=\"mlabel\">virtual</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Reimplemented in <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_filtered_reduced_kernel.html#aa590002c60b8f7f08b44b63e7603ba8c\">FilteredReducedKernel&lt; ReducedResultType, Iterator, KeepFunctor, ReduceFunctor, Reducer &gt;</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_iterate_kernel.html#aa590002c60b8f7f08b44b63e7603ba8c\">IterateKernel&lt; Iterator, T &gt;</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_iterate_kernel.html#aa590002c60b8f7f08b44b63e7603ba8c\">IterateKernel&lt; Iterator, void &gt;</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_iterate_kernel.html#aa590002c60b8f7f08b44b63e7603ba8c\">IterateKernel&lt; Iterator, MapFunctor::result_type &gt;</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_iterate_kernel.html#aa590002c60b8f7f08b44b63e7603ba8c\">IterateKernel&lt; Iterator, qValueType&lt; Iterator &gt;::value_type &gt;</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_iterate_kernel.html#aa590002c60b8f7f08b44b63e7603ba8c\">IterateKernel&lt; Sequence::const_iterator, void &gt;</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_iterate_kernel.html#aa590002c60b8f7f08b44b63e7603ba8c\">IterateKernel&lt; Iterator, ReducedResultType &gt;</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_mapped_reduced_kernel.html#aa590002c60b8f7f08b44b63e7603ba8c\">MappedReducedKernel&lt; ReducedResultType, Iterator, MapFunctor, ReduceFunctor, Reducer &gt;</a>, and <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_filter_kernel.html#aa590002c60b8f7f08b44b63e7603ba8c\">FilterKernel&lt; Sequence, KeepFunctor, ReduceFunctor &gt;</a>.</p>\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qtconcurrentthreadengine_8h_source.html#l00117\">117</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qtconcurrentthreadengine_8h_source.html\">qtconcurrentthreadengine.h</a>.</p>\n\
<div class=\"fragment\"><div class=\"line\"><a name=\"l00117\"></a><span class=\"lineno\">  117</span>&#160;{ <span class=\"keywordflow\">return</span> <a class=\"code\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_thread_engine_base.html#af5da37966cac83d4904fb091fa62fb9e\">futureInterface</a> ? !<a class=\"code\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_thread_engine_base.html#af5da37966cac83d4904fb091fa62fb9e\">futureInterface</a>-&gt;<a class=\"code\" href=\"#!/url=./cpp_ref/class_q_future_interface_base.html#a0eaf52e4ed386823bd1051f44d511fe6\">isPaused</a>() : <span class=\"keyword\">true</span>; }</div>\n\
<div class=\"ttc\" id=\"class_qt_concurrent_1_1_thread_engine_base_html_af5da37966cac83d4904fb091fa62fb9e\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_thread_engine_base.html#af5da37966cac83d4904fb091fa62fb9e\">QtConcurrent::ThreadEngineBase::futureInterface</a></div><div class=\"ttdeci\">QFutureInterfaceBase * futureInterface</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qtconcurrentthreadengine_8h_source.html#l00130\">qtconcurrentthreadengine.h:130</a></div></div>\n\
<div class=\"ttc\" id=\"class_q_future_interface_base_html_a0eaf52e4ed386823bd1051f44d511fe6\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_future_interface_base.html#a0eaf52e4ed386823bd1051f44d511fe6\">QFutureInterfaceBase::isPaused</a></div><div class=\"ttdeci\">bool isPaused() const </div></div>\n\
</div><!-- fragment -->\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a61d2f0a45c238719f5b358dc5243aba4\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">virtual bool shouldThrottleThread </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">inline</span><span class=\"mlabel\">protected</span><span class=\"mlabel\">virtual</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Reimplemented in <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_filtered_reduced_kernel.html#a7c4659e51248bc3af274199aff5a60ed\">FilteredReducedKernel&lt; ReducedResultType, Iterator, KeepFunctor, ReduceFunctor, Reducer &gt;</a>, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_mapped_reduced_kernel.html#a7c4659e51248bc3af274199aff5a60ed\">MappedReducedKernel&lt; ReducedResultType, Iterator, MapFunctor, ReduceFunctor, Reducer &gt;</a>, and <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_filter_kernel.html#a7c4659e51248bc3af274199aff5a60ed\">FilterKernel&lt; Sequence, KeepFunctor, ReduceFunctor &gt;</a>.</p>\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qtconcurrentthreadengine_8h_source.html#l00118\">118</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qtconcurrentthreadengine_8h_source.html\">qtconcurrentthreadengine.h</a>.</p>\n\
<div class=\"fragment\"><div class=\"line\"><a name=\"l00118\"></a><span class=\"lineno\">  118</span>&#160;{ <span class=\"keywordflow\">return</span> <a class=\"code\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_thread_engine_base.html#af5da37966cac83d4904fb091fa62fb9e\">futureInterface</a> ? <a class=\"code\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_thread_engine_base.html#af5da37966cac83d4904fb091fa62fb9e\">futureInterface</a>-&gt;<a class=\"code\" href=\"#!/url=./cpp_ref/class_q_future_interface_base.html#a0eaf52e4ed386823bd1051f44d511fe6\">isPaused</a>() : <span class=\"keyword\">false</span>; }</div>\n\
<div class=\"ttc\" id=\"class_qt_concurrent_1_1_thread_engine_base_html_af5da37966cac83d4904fb091fa62fb9e\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_thread_engine_base.html#af5da37966cac83d4904fb091fa62fb9e\">QtConcurrent::ThreadEngineBase::futureInterface</a></div><div class=\"ttdeci\">QFutureInterfaceBase * futureInterface</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qtconcurrentthreadengine_8h_source.html#l00130\">qtconcurrentthreadengine.h:130</a></div></div>\n\
<div class=\"ttc\" id=\"class_q_future_interface_base_html_a0eaf52e4ed386823bd1051f44d511fe6\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_future_interface_base.html#a0eaf52e4ed386823bd1051f44d511fe6\">QFutureInterfaceBase::isPaused</a></div><div class=\"ttdeci\">bool isPaused() const </div></div>\n\
</div><!-- fragment -->\n\
</div>\n\
</div>\n\
<h2 class=\"groupheader\">Member Data Documentation</h2>\n\
<a class=\"anchor\" id=\"af5da37966cac83d4904fb091fa62fb9e\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_future_interface_base.html\">QFutureInterfaceBase</a>* futureInterface</td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">protected</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qtconcurrentthreadengine_8h_source.html#l00130\">130</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qtconcurrentthreadengine_8h_source.html\">qtconcurrentthreadengine.h</a>.</p>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"ad5e9771198144d6dfc215c4024a68f88\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_thread_pool.html\">QThreadPool</a>* threadPool</td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">protected</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qtconcurrentthreadengine_8h_source.html#l00131\">131</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qtconcurrentthreadengine_8h_source.html\">qtconcurrentthreadengine.h</a>.</p>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a81312e97c5e51c920b7c4986d5c6b9dc\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_thread_engine_barrier.html\">ThreadEngineBarrier</a> <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#aa82d0580e15b255ab2f7a5485a27f917\">barrier</a></td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">protected</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qtconcurrentthreadengine_8h_source.html#l00132\">132</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qtconcurrentthreadengine_8h_source.html\">qtconcurrentthreadengine.h</a>.</p>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a8f97f458fdee8fc837f2fc7f21a76ea5\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1internal_1_1_exception_store.html\">QtConcurrent::internal::ExceptionStore</a> exceptionStore</td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">protected</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qtconcurrentthreadengine_8h_source.html#l00133\">133</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qtconcurrentthreadengine_8h_source.html\">qtconcurrentthreadengine.h</a>.</p>\n\
\n\
</div>\n\
</div>\n\
<hr>The documentation for this class was generated from the following file:<ul>\n\
<li>QtCore/<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qtconcurrentthreadengine_8h_source.html\">qtconcurrentthreadengine.h</a></li>\n\
</ul>\n\
</div><!-- contents -->\n\
</div><!-- doc-content -->\n\
          <div class=\"footer-block\"><a href=\"../html/ac.cmtdialog.htm\" class=\"comments-anchor\" target=\"_blank\"><span class=\"comments-link\">Please send us your comment about this page</span></a></div></div>\n\
   </div></body>\n\
</html>\n\
";