var topic = "<!-- saved from url=(0024)http://docs.autodesk.com -->\n\
<html>\n\
   <head><script src=\"../scripts/yepnope.1.5.4-min.js\" type=\"text/javascript\"></script><script src=\"../scripts/lib/jquery-1.11.1.min.js\" type=\"text/javascript\"></script><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"><meta name=\"product\" content=\"MOBPRO\"><meta name=\"release\" content=\"2018\"><meta name=\"book\" content=\"GeneralUser\"><meta name=\"created\" content=\"2017-09-08\"><meta name=\"topicid\" content=\"GUID-02FA7DD3-6C7A-4C6A-B7BC-824765AE1CB2\"><meta name=\"topic-type\" content=\"concept\">\n\
      <title>QWSKeyboardHandler Class Reference</title>\n\
   \n\
\n\
</head>\n\
   <body height=\"100%\"><div class=\"body_content\" id=\"body-content\"><link rel=\"stylesheet\" type=\"text/css\" href=\"cpp_ref/navtree.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"cpp_ref/doxygen.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"cpp_ref/tabs.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"style/adsk.cpm.css\"><script language=\"javascript\">var index = \'index.html\';</script><script>$(document).ready(function() { yepnope.injectJs(\"./scripts/ac_common.js\"); });</script><script type=\"text/javascript\">\n\
var tocSystemNeedsToBeLoaded = typeof(cpp_ref_adsk_ref_toc) == \'undefined\';\n\
var weAreIn21 = $(\'div#main.view-active\').length;\n\
var tocPrefix = \'\';\n\
if (weAreIn21)\n\
{ tocPrefix = \'cpp_ref/\'; }\n\
function cpp_ref_initializeToc(forceTrigger) {\n\
    cpp_ref_adsk_ref_toc.initResizable();\n\
    cpp_ref_adsk_ref_toc.initNavTree(\'class_q_w_s_keyboard_handler.html\', tocPrefix);\n\
    dQuery(document).trigger(\'toc_initialized\');\n\
}\n\
if (tocSystemNeedsToBeLoaded)\n\
{\n\
	yepnope([{\n\
	load:[tocPrefix + \'json3.min.js\', tocPrefix + \'jquery.js\', tocPrefix + \'ref-toc-controller.js\', tocPrefix + \'dynsections.js\'],\n\
	complete: function() {\n\
	  if (typeof(dQuery) == \'undefined\')\n\
	  {\n\
	    dQuery = jQuery.noConflict(true);\n\
	  }\n\
	  else { jQuery.noConflict(true); }\n\
	  $(document).ready(cpp_ref_initializeToc);\n\
	}\n\
 	}])\n\
}\n\
if (!weAreIn21) { // if in AKN...\n\
$(window).load( function() {\n\
    setTimeout( function() {\n\
        var content = $(\'body > div\').not(\'#body-content\');     // take any divs under body that are not id=body-content\n\
        content.each( function() { \n\
            $(this).css( { \'padding-left\': $(this).css(\'margin-left\') } );       // and if they have any padding-left already, move it to margin-left.\n\
        } );\n\
        var width = cpp_ref_adsk_ref_toc.readFromStorage(\'width\');\n\
        content.css({marginLeft:parseInt(width)+6+\"px\"});\n\
    }, 100);\n\
} ); \n\
}\n\
</script><script>$(\"div#WidgetFloaterPanels,link[href*=\'microsofttranslator.com\'],script[src*=\'microsofttranslator.com\'],script[src*=\'bing.com\']\").remove();</script><script type=\'text/javascript\'>$(\"div#navigation,div#breadcrumbs,div#banner\").attr(\"translate\",\"no\"); var mtLocation = ((location && location.href && location.href.indexOf(\'https\') == 0)?\'https://ssl.microsofttranslator.com\':\'http://www.microsofttranslator.com\')+\'/ajax/v3/WidgetV3.ashx?ctf=True&ui=true&settings=Manual&from=en&hidelanguages=\'; yepnope.injectJs(mtLocation, function() {}, { charset:\'utf-8\', type:\'text/javascript\' } );</script><script>\n\
 if (!tocSystemNeedsToBeLoaded) { cpp_ref_initializeToc(); }\n\
 </script><!-- begin MT -->\n\
            \n\
            <div id=\'MicrosoftTranslatorWidget\' class=\'Dark\' style=\'float:right;z-index:100;color:white;background-color:#bbbbbb;height:58px;overflow:hidden\'></div>\n\
      <div>\n\
         <div class=\"head\">\n\
            <h1>QWSKeyboardHandler Class Reference</h1>\n\
         </div>\n\
\n\
    <div id=\"top\"><!-- Generated by Doxygen 1.8.10 -->\n\
  <div id=\"navrow1\" class=\"tabs\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./cpp_ref/index.html\"><span>Main&#160;Page</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/pages.html\"><span>Topics</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/modules.html\"><span>Modules</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/namespaces.html\"><span>Namespaces</span></a></li>\n\
      <li class=\"current\"><a href=\"#!/url=./cpp_ref/annotated.html\"><span>Classes</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/files.html\"><span>Files</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/examples.html\"><span>Examples</span></a></li>\n\
    </ul>\n\
  </div>\n\
  <div id=\"navrow2\" class=\"tabs2\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./cpp_ref/annotated.html\"><span>Class&#160;List</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/hierarchy.html\"><span>Class&#160;Hierarchy</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/functions.html\"><span>Class&#160;Members</span></a></li>\n\
    </ul>\n\
  </div>\n\
</div><!-- top -->\n\
<div id=\"side-nav\" class=\"ui-resizable side-nav-resizable\">\n\
  <div id=\"nav-tree\">\n\
    <div id=\"nav-tree-contents\">\n\
      <div id=\"nav-sync\" class=\"sync\"></div>\n\
    </div>\n\
  </div>\n\
  <div id=\"splitbar\" style=\"-moz-user-select:none;\" class=\"ui-resizable-handle\">\n\
  </div>\n\
</div>\n\
\n\
<div id=\"doc-content\">\n\
<div class=\"header\">\n\
  \n\
  <div class=\"headertitle\">\n\
<div class=\"title\">QWSKeyboardHandler Class Reference</div>  </div>\n\
<div class=\"summary\">\n\
<a href=\"class_q_w_s_keyboard_handler.html#pub-types\">Public Types</a> &#124;\n\
<a href=\"class_q_w_s_keyboard_handler.html#pub-methods\">Public Member Functions</a> &#124;\n\
<a href=\"class_q_w_s_keyboard_handler.html#pro-methods\">Protected Member Functions</a>  </div></div><!--header-->\n\
<div class=\"contents\">\n\
\n\
<p><code>#include &lt;<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qkbd__qws_8h_source.html\">qkbd_qws.h</a>&gt;</code></p>\n\
<a name=\"details\" id=\"details\"></a><h2 class=\"groupheader\">Class Description</h2>\n\
<div class=\"textblock\">\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qkbd__qws_8h_source.html#l00057\">57</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qkbd__qws_8h_source.html\">qkbd_qws.h</a>.</p>\n\
</div><div id=\"dynsection-0\" onclick=\"return toggleVisibility(this)\" class=\"dynheader closed\" style=\"cursor:pointer;\">\n\
  <img id=\"dynsection-0-trigger\" src=\"cpp_ref/closed.png\" alt=\"+\"> Inheritance diagram for QWSKeyboardHandler:</div>\n\
<div id=\"dynsection-0-summary\" class=\"dynsummary\" style=\"display:block;\">\n\
</div>\n\
<div id=\"dynsection-0-content\" class=\"dyncontent\" style=\"display:none;\">\n\
 <div class=\"center\">\n\
  <img src=\"cpp_ref/class_q_w_s_keyboard_handler.png\" usemap=\"#QWSKeyboardHandler_map\" alt=\"\">\n\
  <map id=\"QWSKeyboardHandler_map\" name=\"QWSKeyboardHandler_map\">\n\
<area href=\"class_q_v_fb_keyboard_handler.html\" alt=\"QVFbKeyboardHandler\" shape=\"rect\" coords=\"0,56,198,80\">\n\
<area href=\"class_q_w_s_int_keyboard_handler.html\" alt=\"QWSIntKeyboardHandler\" shape=\"rect\" coords=\"208,56,406,80\">\n\
<area href=\"class_q_w_s_linux_input_keyboard_handler.html\" alt=\"QWSLinuxInputKeyboardHandler\" shape=\"rect\" coords=\"416,56,614,80\">\n\
<area href=\"class_q_w_s_qnx_keyboard_handler.html\" alt=\"QWSQnxKeyboardHandler\" shape=\"rect\" coords=\"624,56,822,80\">\n\
<area href=\"class_q_w_s_tty_keyboard_handler.html\" alt=\"QWSTtyKeyboardHandler\" shape=\"rect\" coords=\"832,56,1030,80\">\n\
<area href=\"class_q_w_s_um_keyboard_handler.html\" alt=\"QWSUmKeyboardHandler\" shape=\"rect\" coords=\"1040,56,1238,80\">\n\
</map>\n\
 </div></div>\n\
<table class=\"memberdecls\">\n\
<tr class=\"heading\"><td colspan=\"2\"><h2 class=\"groupheader\"><a name=\"pub-types\"></a>\n\
Public Types</h2></td></tr>\n\
<tr class=\"memitem:a7c6e4c3a7ea16156ca9632a3dd50cfa7\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">enum &#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_w_s_keyboard_handler.html#a7c6e4c3a7ea16156ca9632a3dd50cfa7\">KeycodeAction</a> { <br>\n\
&#160;&#160;<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_w_s_keyboard_handler.html#a7c6e4c3a7ea16156ca9632a3dd50cfa7ac9d3e887722f2bc482bcca9d41c512af\">None</a> = 0, \n\
<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_w_s_keyboard_handler.html#a7c6e4c3a7ea16156ca9632a3dd50cfa7a2eb71eb4ea5d3bee3e7866f669ae9015\">CapsLockOff</a> = 0x01000000, \n\
<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_w_s_keyboard_handler.html#a7c6e4c3a7ea16156ca9632a3dd50cfa7a03d2e399122b0774ec87fc580b9ac23d\">CapsLockOn</a> = 0x01000001, \n\
<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_w_s_keyboard_handler.html#a7c6e4c3a7ea16156ca9632a3dd50cfa7ad6c21b75e72c2e86024406b036b3a7af\">NumLockOff</a> = 0x02000000, \n\
<br>\n\
&#160;&#160;<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_w_s_keyboard_handler.html#a7c6e4c3a7ea16156ca9632a3dd50cfa7ad30687a48a7675a7c8814cf4ed4ce8bb\">NumLockOn</a> = 0x02000001, \n\
<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_w_s_keyboard_handler.html#a7c6e4c3a7ea16156ca9632a3dd50cfa7ab1b25a2d5c789c7efa9034a5d50b9b30\">ScrollLockOff</a> = 0x03000000, \n\
<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_w_s_keyboard_handler.html#a7c6e4c3a7ea16156ca9632a3dd50cfa7a1ecdea747eef1771190a6ad6464e0b28\">ScrollLockOn</a> = 0x03000001, \n\
<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_w_s_keyboard_handler.html#a7c6e4c3a7ea16156ca9632a3dd50cfa7aa49f6a8953e091ee4209d9b2c4019ff7\">Reboot</a> = 0x04000000, \n\
<br>\n\
&#160;&#160;<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_w_s_keyboard_handler.html#a7c6e4c3a7ea16156ca9632a3dd50cfa7ad022d4c7fe57efe2fcef2549561693c0\">PreviousConsole</a> = 0x05000000, \n\
<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_w_s_keyboard_handler.html#a7c6e4c3a7ea16156ca9632a3dd50cfa7a93da6f98939edd2c5aee8a52a1a9d910\">NextConsole</a> = 0x05000001, \n\
<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_w_s_keyboard_handler.html#a7c6e4c3a7ea16156ca9632a3dd50cfa7a1e7dbeba4a84332666bb952696bbc3e0\">SwitchConsoleFirst</a> = 0x06000000, \n\
<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_w_s_keyboard_handler.html#a7c6e4c3a7ea16156ca9632a3dd50cfa7a939bb1f9a3b99b26b2a67a23241ef5ce\">SwitchConsoleLast</a> = 0x0600007f, \n\
<br>\n\
&#160;&#160;<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_w_s_keyboard_handler.html#a7c6e4c3a7ea16156ca9632a3dd50cfa7aa601a21036022584ed6fbe766d5061d5\">SwitchConsoleMask</a> = 0x0000007f\n\
<br>\n\
 }<tr class=\"separator:a7c6e4c3a7ea16156ca9632a3dd50cfa7\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
</td></tr>\n\
</table><table class=\"memberdecls\">\n\
<tr class=\"heading\"><td colspan=\"2\"><h2 class=\"groupheader\"><a name=\"pub-methods\"></a>\n\
Public Member Functions</h2></td></tr>\n\
<tr class=\"memitem:a1f2829944ff747e636a7f7eabc72b9db\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_w_s_keyboard_handler.html#a1f2829944ff747e636a7f7eabc72b9db\">QWSKeyboardHandler</a> ()</td></tr>\n\
<tr class=\"separator:a1f2829944ff747e636a7f7eabc72b9db\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a8435493f33c0afd9267b51ec8636fa08\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_w_s_keyboard_handler.html#a8435493f33c0afd9267b51ec8636fa08\">QWSKeyboardHandler</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_string.html\">QString</a> &amp;device)</td></tr>\n\
<tr class=\"separator:a8435493f33c0afd9267b51ec8636fa08\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a1c1a3ecc167b21d159b980913670f8dc\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">virtual&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_w_s_keyboard_handler.html#a1c1a3ecc167b21d159b980913670f8dc\">~QWSKeyboardHandler</a> ()</td></tr>\n\
<tr class=\"separator:a1c1a3ecc167b21d159b980913670f8dc\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:ab84558976186aedd2251697c0abffebb\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">virtual <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_w_s_keyboard_handler.html#ab84558976186aedd2251697c0abffebb\">processKeyEvent</a> (<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a0067a505d12f13572b26d9535c23b671\">int</a> unicode, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a0067a505d12f13572b26d9535c23b671\">int</a> keycode, Qt::KeyboardModifiers modifiers, bool isPress, bool autoRepeat)</td></tr>\n\
<tr class=\"separator:ab84558976186aedd2251697c0abffebb\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a54b83aa5f6296d438dea9641a1814309\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_w_s_keyboard_handler.html#a7c6e4c3a7ea16156ca9632a3dd50cfa7\">KeycodeAction</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_w_s_keyboard_handler.html#a54b83aa5f6296d438dea9641a1814309\">processKeycode</a> (<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qglobal_8h.html#a6f3b1e8a589d7539ac4f9592005da8b7\">quint16</a> keycode, bool pressed, bool autorepeat)</td></tr>\n\
<tr class=\"separator:a54b83aa5f6296d438dea9641a1814309\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
</table><table class=\"memberdecls\">\n\
<tr class=\"heading\"><td colspan=\"2\"><h2 class=\"groupheader\"><a name=\"pro-methods\"></a>\n\
Protected Member Functions</h2></td></tr>\n\
<tr class=\"memitem:aca3fe039b79cb430f3f9c1c73e2ef18e\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a0067a505d12f13572b26d9535c23b671\">int</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_w_s_keyboard_handler.html#aca3fe039b79cb430f3f9c1c73e2ef18e\">transformDirKey</a> (<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a0067a505d12f13572b26d9535c23b671\">int</a> key)</td></tr>\n\
<tr class=\"separator:aca3fe039b79cb430f3f9c1c73e2ef18e\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a0fff7ea32fce97eb7c3b2a321f223c6e\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_w_s_keyboard_handler.html#a0fff7ea32fce97eb7c3b2a321f223c6e\">beginAutoRepeat</a> (<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a0067a505d12f13572b26d9535c23b671\">int</a> uni, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a0067a505d12f13572b26d9535c23b671\">int</a> code, Qt::KeyboardModifiers mod)</td></tr>\n\
<tr class=\"separator:a0fff7ea32fce97eb7c3b2a321f223c6e\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:abcc01fa33ed3dbf4074f64ad5c5b1925\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_w_s_keyboard_handler.html#abcc01fa33ed3dbf4074f64ad5c5b1925\">endAutoRepeat</a> ()</td></tr>\n\
<tr class=\"separator:abcc01fa33ed3dbf4074f64ad5c5b1925\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
</table>\n\
<h2 class=\"groupheader\">Member Enumeration Documentation</h2>\n\
<a class=\"anchor\" id=\"a7c6e4c3a7ea16156ca9632a3dd50cfa7\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">enum <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_w_s_keyboard_handler.html#a7c6e4c3a7ea16156ca9632a3dd50cfa7\">KeycodeAction</a></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
<table class=\"fieldtable\">\n\
<tr><th colspan=\"2\">Enumerator</th></tr><tr><td class=\"fieldname\"><a class=\"anchor\" id=\"a7c6e4c3a7ea16156ca9632a3dd50cfa7ac9d3e887722f2bc482bcca9d41c512af\"></a>None&#160;</td><td class=\"fielddoc\">\n\
</td></tr>\n\
<tr><td class=\"fieldname\"><a class=\"anchor\" id=\"a7c6e4c3a7ea16156ca9632a3dd50cfa7a2eb71eb4ea5d3bee3e7866f669ae9015\"></a>CapsLockOff&#160;</td><td class=\"fielddoc\">\n\
</td></tr>\n\
<tr><td class=\"fieldname\"><a class=\"anchor\" id=\"a7c6e4c3a7ea16156ca9632a3dd50cfa7a03d2e399122b0774ec87fc580b9ac23d\"></a>CapsLockOn&#160;</td><td class=\"fielddoc\">\n\
</td></tr>\n\
<tr><td class=\"fieldname\"><a class=\"anchor\" id=\"a7c6e4c3a7ea16156ca9632a3dd50cfa7ad6c21b75e72c2e86024406b036b3a7af\"></a>NumLockOff&#160;</td><td class=\"fielddoc\">\n\
</td></tr>\n\
<tr><td class=\"fieldname\"><a class=\"anchor\" id=\"a7c6e4c3a7ea16156ca9632a3dd50cfa7ad30687a48a7675a7c8814cf4ed4ce8bb\"></a>NumLockOn&#160;</td><td class=\"fielddoc\">\n\
</td></tr>\n\
<tr><td class=\"fieldname\"><a class=\"anchor\" id=\"a7c6e4c3a7ea16156ca9632a3dd50cfa7ab1b25a2d5c789c7efa9034a5d50b9b30\"></a>ScrollLockOff&#160;</td><td class=\"fielddoc\">\n\
</td></tr>\n\
<tr><td class=\"fieldname\"><a class=\"anchor\" id=\"a7c6e4c3a7ea16156ca9632a3dd50cfa7a1ecdea747eef1771190a6ad6464e0b28\"></a>ScrollLockOn&#160;</td><td class=\"fielddoc\">\n\
</td></tr>\n\
<tr><td class=\"fieldname\"><a class=\"anchor\" id=\"a7c6e4c3a7ea16156ca9632a3dd50cfa7aa49f6a8953e091ee4209d9b2c4019ff7\"></a>Reboot&#160;</td><td class=\"fielddoc\">\n\
</td></tr>\n\
<tr><td class=\"fieldname\"><a class=\"anchor\" id=\"a7c6e4c3a7ea16156ca9632a3dd50cfa7ad022d4c7fe57efe2fcef2549561693c0\"></a>PreviousConsole&#160;</td><td class=\"fielddoc\">\n\
</td></tr>\n\
<tr><td class=\"fieldname\"><a class=\"anchor\" id=\"a7c6e4c3a7ea16156ca9632a3dd50cfa7a93da6f98939edd2c5aee8a52a1a9d910\"></a>NextConsole&#160;</td><td class=\"fielddoc\">\n\
</td></tr>\n\
<tr><td class=\"fieldname\"><a class=\"anchor\" id=\"a7c6e4c3a7ea16156ca9632a3dd50cfa7a1e7dbeba4a84332666bb952696bbc3e0\"></a>SwitchConsoleFirst&#160;</td><td class=\"fielddoc\">\n\
</td></tr>\n\
<tr><td class=\"fieldname\"><a class=\"anchor\" id=\"a7c6e4c3a7ea16156ca9632a3dd50cfa7a939bb1f9a3b99b26b2a67a23241ef5ce\"></a>SwitchConsoleLast&#160;</td><td class=\"fielddoc\">\n\
</td></tr>\n\
<tr><td class=\"fieldname\"><a class=\"anchor\" id=\"a7c6e4c3a7ea16156ca9632a3dd50cfa7aa601a21036022584ed6fbe766d5061d5\"></a>SwitchConsoleMask&#160;</td><td class=\"fielddoc\">\n\
</td></tr>\n\
</table>\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qkbd__qws_8h_source.html#l00067\">67</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qkbd__qws_8h_source.html\">qkbd_qws.h</a>.</p>\n\
<div class=\"fragment\"><div class=\"line\"><a name=\"l00067\"></a><span class=\"lineno\">   67</span>&#160;                       {</div>\n\
<div class=\"line\"><a name=\"l00068\"></a><span class=\"lineno\">   68</span>&#160;        <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_w_s_keyboard_handler.html#a7c6e4c3a7ea16156ca9632a3dd50cfa7ac9d3e887722f2bc482bcca9d41c512af\">None</a>               = 0,</div>\n\
<div class=\"line\"><a name=\"l00069\"></a><span class=\"lineno\">   69</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00070\"></a><span class=\"lineno\">   70</span>&#160;        <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_w_s_keyboard_handler.html#a7c6e4c3a7ea16156ca9632a3dd50cfa7a2eb71eb4ea5d3bee3e7866f669ae9015\">CapsLockOff</a>        = 0x01000000,</div>\n\
<div class=\"line\"><a name=\"l00071\"></a><span class=\"lineno\">   71</span>&#160;        <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_w_s_keyboard_handler.html#a7c6e4c3a7ea16156ca9632a3dd50cfa7a03d2e399122b0774ec87fc580b9ac23d\">CapsLockOn</a>         = 0x01000001,</div>\n\
<div class=\"line\"><a name=\"l00072\"></a><span class=\"lineno\">   72</span>&#160;        <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_w_s_keyboard_handler.html#a7c6e4c3a7ea16156ca9632a3dd50cfa7ad6c21b75e72c2e86024406b036b3a7af\">NumLockOff</a>         = 0x02000000,</div>\n\
<div class=\"line\"><a name=\"l00073\"></a><span class=\"lineno\">   73</span>&#160;        <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_w_s_keyboard_handler.html#a7c6e4c3a7ea16156ca9632a3dd50cfa7ad30687a48a7675a7c8814cf4ed4ce8bb\">NumLockOn</a>          = 0x02000001,</div>\n\
<div class=\"line\"><a name=\"l00074\"></a><span class=\"lineno\">   74</span>&#160;        <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_w_s_keyboard_handler.html#a7c6e4c3a7ea16156ca9632a3dd50cfa7ab1b25a2d5c789c7efa9034a5d50b9b30\">ScrollLockOff</a>      = 0x03000000,</div>\n\
<div class=\"line\"><a name=\"l00075\"></a><span class=\"lineno\">   75</span>&#160;        <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_w_s_keyboard_handler.html#a7c6e4c3a7ea16156ca9632a3dd50cfa7a1ecdea747eef1771190a6ad6464e0b28\">ScrollLockOn</a>       = 0x03000001,</div>\n\
<div class=\"line\"><a name=\"l00076\"></a><span class=\"lineno\">   76</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00077\"></a><span class=\"lineno\">   77</span>&#160;        <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_w_s_keyboard_handler.html#a7c6e4c3a7ea16156ca9632a3dd50cfa7aa49f6a8953e091ee4209d9b2c4019ff7\">Reboot</a>             = 0x04000000,</div>\n\
<div class=\"line\"><a name=\"l00078\"></a><span class=\"lineno\">   78</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00079\"></a><span class=\"lineno\">   79</span>&#160;        <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_w_s_keyboard_handler.html#a7c6e4c3a7ea16156ca9632a3dd50cfa7ad022d4c7fe57efe2fcef2549561693c0\">PreviousConsole</a>    = 0x05000000,</div>\n\
<div class=\"line\"><a name=\"l00080\"></a><span class=\"lineno\">   80</span>&#160;        <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_w_s_keyboard_handler.html#a7c6e4c3a7ea16156ca9632a3dd50cfa7a93da6f98939edd2c5aee8a52a1a9d910\">NextConsole</a>        = 0x05000001,</div>\n\
<div class=\"line\"><a name=\"l00081\"></a><span class=\"lineno\">   81</span>&#160;        <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_w_s_keyboard_handler.html#a7c6e4c3a7ea16156ca9632a3dd50cfa7a1e7dbeba4a84332666bb952696bbc3e0\">SwitchConsoleFirst</a> = 0x06000000,</div>\n\
<div class=\"line\"><a name=\"l00082\"></a><span class=\"lineno\">   82</span>&#160;        <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_w_s_keyboard_handler.html#a7c6e4c3a7ea16156ca9632a3dd50cfa7a939bb1f9a3b99b26b2a67a23241ef5ce\">SwitchConsoleLast</a>  = 0x0600007f,</div>\n\
<div class=\"line\"><a name=\"l00083\"></a><span class=\"lineno\">   83</span>&#160;        <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_w_s_keyboard_handler.html#a7c6e4c3a7ea16156ca9632a3dd50cfa7aa601a21036022584ed6fbe766d5061d5\">SwitchConsoleMask</a>  = 0x0000007f,</div>\n\
<div class=\"line\"><a name=\"l00084\"></a><span class=\"lineno\">   84</span>&#160;    };</div>\n\
<div class=\"ttc\" id=\"class_q_w_s_keyboard_handler_html_a7c6e4c3a7ea16156ca9632a3dd50cfa7aa49f6a8953e091ee4209d9b2c4019ff7\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_w_s_keyboard_handler.html#a7c6e4c3a7ea16156ca9632a3dd50cfa7aa49f6a8953e091ee4209d9b2c4019ff7\">QWSKeyboardHandler::Reboot</a></div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qkbd__qws_8h_source.html#l00077\">qkbd_qws.h:77</a></div></div>\n\
<div class=\"ttc\" id=\"class_q_w_s_keyboard_handler_html_a7c6e4c3a7ea16156ca9632a3dd50cfa7a03d2e399122b0774ec87fc580b9ac23d\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_w_s_keyboard_handler.html#a7c6e4c3a7ea16156ca9632a3dd50cfa7a03d2e399122b0774ec87fc580b9ac23d\">QWSKeyboardHandler::CapsLockOn</a></div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qkbd__qws_8h_source.html#l00071\">qkbd_qws.h:71</a></div></div>\n\
<div class=\"ttc\" id=\"class_q_w_s_keyboard_handler_html_a7c6e4c3a7ea16156ca9632a3dd50cfa7a939bb1f9a3b99b26b2a67a23241ef5ce\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_w_s_keyboard_handler.html#a7c6e4c3a7ea16156ca9632a3dd50cfa7a939bb1f9a3b99b26b2a67a23241ef5ce\">QWSKeyboardHandler::SwitchConsoleLast</a></div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qkbd__qws_8h_source.html#l00082\">qkbd_qws.h:82</a></div></div>\n\
<div class=\"ttc\" id=\"class_q_w_s_keyboard_handler_html_a7c6e4c3a7ea16156ca9632a3dd50cfa7aa601a21036022584ed6fbe766d5061d5\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_w_s_keyboard_handler.html#a7c6e4c3a7ea16156ca9632a3dd50cfa7aa601a21036022584ed6fbe766d5061d5\">QWSKeyboardHandler::SwitchConsoleMask</a></div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qkbd__qws_8h_source.html#l00083\">qkbd_qws.h:83</a></div></div>\n\
<div class=\"ttc\" id=\"class_q_w_s_keyboard_handler_html_a7c6e4c3a7ea16156ca9632a3dd50cfa7ad6c21b75e72c2e86024406b036b3a7af\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_w_s_keyboard_handler.html#a7c6e4c3a7ea16156ca9632a3dd50cfa7ad6c21b75e72c2e86024406b036b3a7af\">QWSKeyboardHandler::NumLockOff</a></div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qkbd__qws_8h_source.html#l00072\">qkbd_qws.h:72</a></div></div>\n\
<div class=\"ttc\" id=\"class_q_w_s_keyboard_handler_html_a7c6e4c3a7ea16156ca9632a3dd50cfa7a1ecdea747eef1771190a6ad6464e0b28\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_w_s_keyboard_handler.html#a7c6e4c3a7ea16156ca9632a3dd50cfa7a1ecdea747eef1771190a6ad6464e0b28\">QWSKeyboardHandler::ScrollLockOn</a></div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qkbd__qws_8h_source.html#l00075\">qkbd_qws.h:75</a></div></div>\n\
<div class=\"ttc\" id=\"class_q_w_s_keyboard_handler_html_a7c6e4c3a7ea16156ca9632a3dd50cfa7a2eb71eb4ea5d3bee3e7866f669ae9015\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_w_s_keyboard_handler.html#a7c6e4c3a7ea16156ca9632a3dd50cfa7a2eb71eb4ea5d3bee3e7866f669ae9015\">QWSKeyboardHandler::CapsLockOff</a></div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qkbd__qws_8h_source.html#l00070\">qkbd_qws.h:70</a></div></div>\n\
<div class=\"ttc\" id=\"class_q_w_s_keyboard_handler_html_a7c6e4c3a7ea16156ca9632a3dd50cfa7a93da6f98939edd2c5aee8a52a1a9d910\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_w_s_keyboard_handler.html#a7c6e4c3a7ea16156ca9632a3dd50cfa7a93da6f98939edd2c5aee8a52a1a9d910\">QWSKeyboardHandler::NextConsole</a></div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qkbd__qws_8h_source.html#l00080\">qkbd_qws.h:80</a></div></div>\n\
<div class=\"ttc\" id=\"class_q_w_s_keyboard_handler_html_a7c6e4c3a7ea16156ca9632a3dd50cfa7ab1b25a2d5c789c7efa9034a5d50b9b30\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_w_s_keyboard_handler.html#a7c6e4c3a7ea16156ca9632a3dd50cfa7ab1b25a2d5c789c7efa9034a5d50b9b30\">QWSKeyboardHandler::ScrollLockOff</a></div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qkbd__qws_8h_source.html#l00074\">qkbd_qws.h:74</a></div></div>\n\
<div class=\"ttc\" id=\"class_q_w_s_keyboard_handler_html_a7c6e4c3a7ea16156ca9632a3dd50cfa7ac9d3e887722f2bc482bcca9d41c512af\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_w_s_keyboard_handler.html#a7c6e4c3a7ea16156ca9632a3dd50cfa7ac9d3e887722f2bc482bcca9d41c512af\">QWSKeyboardHandler::None</a></div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qkbd__qws_8h_source.html#l00068\">qkbd_qws.h:68</a></div></div>\n\
<div class=\"ttc\" id=\"class_q_w_s_keyboard_handler_html_a7c6e4c3a7ea16156ca9632a3dd50cfa7ad30687a48a7675a7c8814cf4ed4ce8bb\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_w_s_keyboard_handler.html#a7c6e4c3a7ea16156ca9632a3dd50cfa7ad30687a48a7675a7c8814cf4ed4ce8bb\">QWSKeyboardHandler::NumLockOn</a></div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qkbd__qws_8h_source.html#l00073\">qkbd_qws.h:73</a></div></div>\n\
<div class=\"ttc\" id=\"class_q_w_s_keyboard_handler_html_a7c6e4c3a7ea16156ca9632a3dd50cfa7a1e7dbeba4a84332666bb952696bbc3e0\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_w_s_keyboard_handler.html#a7c6e4c3a7ea16156ca9632a3dd50cfa7a1e7dbeba4a84332666bb952696bbc3e0\">QWSKeyboardHandler::SwitchConsoleFirst</a></div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qkbd__qws_8h_source.html#l00081\">qkbd_qws.h:81</a></div></div>\n\
<div class=\"ttc\" id=\"class_q_w_s_keyboard_handler_html_a7c6e4c3a7ea16156ca9632a3dd50cfa7ad022d4c7fe57efe2fcef2549561693c0\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_w_s_keyboard_handler.html#a7c6e4c3a7ea16156ca9632a3dd50cfa7ad022d4c7fe57efe2fcef2549561693c0\">QWSKeyboardHandler::PreviousConsole</a></div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qkbd__qws_8h_source.html#l00079\">qkbd_qws.h:79</a></div></div>\n\
</div><!-- fragment -->\n\
</div>\n\
</div>\n\
<h2 class=\"groupheader\">Constructor &amp; Destructor Documentation</h2>\n\
<a class=\"anchor\" id=\"a1f2829944ff747e636a7f7eabc72b9db\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_w_s_keyboard_handler.html\">QWSKeyboardHandler</a> </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a8435493f33c0afd9267b51ec8636fa08\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_w_s_keyboard_handler.html\">QWSKeyboardHandler</a> </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_string.html\">QString</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>device</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a1c1a3ecc167b21d159b980913670f8dc\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">virtual ~<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_w_s_keyboard_handler.html\">QWSKeyboardHandler</a> </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">virtual</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
\n\
</div>\n\
</div>\n\
<h2 class=\"groupheader\">Member Function Documentation</h2>\n\
<a class=\"anchor\" id=\"ab84558976186aedd2251697c0abffebb\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">virtual <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a> processKeyEvent </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a0067a505d12f13572b26d9535c23b671\">int</a>&#160;</td>\n\
          <td class=\"paramname\"><em>unicode</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a0067a505d12f13572b26d9535c23b671\">int</a>&#160;</td>\n\
          <td class=\"paramname\"><em>keycode</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">Qt::KeyboardModifiers&#160;</td>\n\
          <td class=\"paramname\"><em>modifiers</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">bool&#160;</td>\n\
          <td class=\"paramname\"><em>isPress</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">bool&#160;</td>\n\
          <td class=\"paramname\"><em>autoRepeat</em>&#160;</td>\n\
        </tr>\n\
        <tr>\n\
          <td></td>\n\
          <td>)</td>\n\
          <td></td><td></td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">virtual</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a54b83aa5f6296d438dea9641a1814309\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_w_s_keyboard_handler.html#a7c6e4c3a7ea16156ca9632a3dd50cfa7\">KeycodeAction</a> processKeycode </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qglobal_8h.html#a6f3b1e8a589d7539ac4f9592005da8b7\">quint16</a>&#160;</td>\n\
          <td class=\"paramname\"><em>keycode</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">bool&#160;</td>\n\
          <td class=\"paramname\"><em>pressed</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">bool&#160;</td>\n\
          <td class=\"paramname\"><em>autorepeat</em>&#160;</td>\n\
        </tr>\n\
        <tr>\n\
          <td></td>\n\
          <td>)</td>\n\
          <td></td><td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"aca3fe039b79cb430f3f9c1c73e2ef18e\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a0067a505d12f13572b26d9535c23b671\">int</a> transformDirKey </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a0067a505d12f13572b26d9535c23b671\">int</a>&#160;</td>\n\
          <td class=\"paramname\"><em>key</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">protected</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a0fff7ea32fce97eb7c3b2a321f223c6e\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a> beginAutoRepeat </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a0067a505d12f13572b26d9535c23b671\">int</a>&#160;</td>\n\
          <td class=\"paramname\"><em>uni</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a0067a505d12f13572b26d9535c23b671\">int</a>&#160;</td>\n\
          <td class=\"paramname\"><em>code</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">Qt::KeyboardModifiers&#160;</td>\n\
          <td class=\"paramname\"><em>mod</em>&#160;</td>\n\
        </tr>\n\
        <tr>\n\
          <td></td>\n\
          <td>)</td>\n\
          <td></td><td></td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">protected</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"abcc01fa33ed3dbf4074f64ad5c5b1925\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a> endAutoRepeat </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">protected</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
\n\
</div>\n\
</div>\n\
<hr>The documentation for this class was generated from the following file:<ul>\n\
<li>QtGui/<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qkbd__qws_8h_source.html\">qkbd_qws.h</a></li>\n\
</ul>\n\
</div><!-- contents -->\n\
</div><!-- doc-content -->\n\
          <div class=\"footer-block\"><a href=\"../html/ac.cmtdialog.htm\" class=\"comments-anchor\" target=\"_blank\"><span class=\"comments-link\">Please send us your comment about this page</span></a></div></div>\n\
   </div></body>\n\
</html>\n\
";