var topic = "<!-- saved from url=(0024)http://docs.autodesk.com -->\n\
<html>\n\
   <head><script src=\"../scripts/yepnope.1.5.4-min.js\" type=\"text/javascript\"></script><script src=\"../scripts/lib/jquery-1.11.1.min.js\" type=\"text/javascript\"></script><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"><meta name=\"product\" content=\"MOBPRO\"><meta name=\"release\" content=\"2018\"><meta name=\"book\" content=\"GeneralUser\"><meta name=\"created\" content=\"2017-09-08\"><meta name=\"topicid\" content=\"GUID-02FA7DD3-6C7A-4C6A-B7BC-824765AE1CB2\"><meta name=\"topic-type\" content=\"concept\">\n\
      <title>CheckableFloat Class Reference</title>\n\
   \n\
\n\
</head>\n\
   <body height=\"100%\"><div class=\"body_content\" id=\"body-content\"><link rel=\"stylesheet\" type=\"text/css\" href=\"cpp_ref/navtree.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"cpp_ref/doxygen.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"cpp_ref/tabs.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"style/adsk.cpm.css\"><script language=\"javascript\">var index = \'index.html\';</script><script>$(document).ready(function() { yepnope.injectJs(\"./scripts/ac_common.js\"); });</script><script type=\"text/javascript\">\n\
var tocSystemNeedsToBeLoaded = typeof(cpp_ref_adsk_ref_toc) == \'undefined\';\n\
var weAreIn21 = $(\'div#main.view-active\').length;\n\
var tocPrefix = \'\';\n\
if (weAreIn21)\n\
{ tocPrefix = \'cpp_ref/\'; }\n\
function cpp_ref_initializeToc(forceTrigger) {\n\
    cpp_ref_adsk_ref_toc.initResizable();\n\
    cpp_ref_adsk_ref_toc.initNavTree(\'classmudbox_1_1_checkable_float.html\', tocPrefix);\n\
    dQuery(document).trigger(\'toc_initialized\');\n\
}\n\
if (tocSystemNeedsToBeLoaded)\n\
{\n\
	yepnope([{\n\
	load:[tocPrefix + \'json3.min.js\', tocPrefix + \'jquery.js\', tocPrefix + \'ref-toc-controller.js\', tocPrefix + \'dynsections.js\'],\n\
	complete: function() {\n\
	  if (typeof(dQuery) == \'undefined\')\n\
	  {\n\
	    dQuery = jQuery.noConflict(true);\n\
	  }\n\
	  else { jQuery.noConflict(true); }\n\
	  $(document).ready(cpp_ref_initializeToc);\n\
	}\n\
 	}])\n\
}\n\
if (!weAreIn21) { // if in AKN...\n\
$(window).load( function() {\n\
    setTimeout( function() {\n\
        var content = $(\'body > div\').not(\'#body-content\');     // take any divs under body that are not id=body-content\n\
        content.each( function() { \n\
            $(this).css( { \'padding-left\': $(this).css(\'margin-left\') } );       // and if they have any padding-left already, move it to margin-left.\n\
        } );\n\
        var width = cpp_ref_adsk_ref_toc.readFromStorage(\'width\');\n\
        content.css({marginLeft:parseInt(width)+6+\"px\"});\n\
    }, 100);\n\
} ); \n\
}\n\
</script><script>$(\"div#WidgetFloaterPanels,link[href*=\'microsofttranslator.com\'],script[src*=\'microsofttranslator.com\'],script[src*=\'bing.com\']\").remove();</script><script type=\'text/javascript\'>$(\"div#navigation,div#breadcrumbs,div#banner\").attr(\"translate\",\"no\"); var mtLocation = ((location && location.href && location.href.indexOf(\'https\') == 0)?\'https://ssl.microsofttranslator.com\':\'http://www.microsofttranslator.com\')+\'/ajax/v3/WidgetV3.ashx?ctf=True&ui=true&settings=Manual&from=en&hidelanguages=\'; yepnope.injectJs(mtLocation, function() {}, { charset:\'utf-8\', type:\'text/javascript\' } );</script><script>\n\
 if (!tocSystemNeedsToBeLoaded) { cpp_ref_initializeToc(); }\n\
 </script><!-- begin MT -->\n\
            \n\
            <div id=\'MicrosoftTranslatorWidget\' class=\'Dark\' style=\'float:right;z-index:100;color:white;background-color:#bbbbbb;height:58px;overflow:hidden\'></div>\n\
      <div>\n\
         <div class=\"head\">\n\
            <h1>CheckableFloat Class Reference</h1>\n\
         </div>\n\
\n\
    <div id=\"top\"><!-- Generated by Doxygen 1.8.10 -->\n\
  <div id=\"navrow1\" class=\"tabs\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./cpp_ref/index.html\"><span>Main&#160;Page</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/pages.html\"><span>Topics</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/modules.html\"><span>Modules</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/namespaces.html\"><span>Namespaces</span></a></li>\n\
      <li class=\"current\"><a href=\"#!/url=./cpp_ref/annotated.html\"><span>Classes</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/files.html\"><span>Files</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/examples.html\"><span>Examples</span></a></li>\n\
    </ul>\n\
  </div>\n\
  <div id=\"navrow2\" class=\"tabs2\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./cpp_ref/annotated.html\"><span>Class&#160;List</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/hierarchy.html\"><span>Class&#160;Hierarchy</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/functions.html\"><span>Class&#160;Members</span></a></li>\n\
    </ul>\n\
  </div>\n\
</div><!-- top -->\n\
<div id=\"side-nav\" class=\"ui-resizable side-nav-resizable\">\n\
  <div id=\"nav-tree\">\n\
    <div id=\"nav-tree-contents\">\n\
      <div id=\"nav-sync\" class=\"sync\"></div>\n\
    </div>\n\
  </div>\n\
  <div id=\"splitbar\" style=\"-moz-user-select:none;\" class=\"ui-resizable-handle\">\n\
  </div>\n\
</div>\n\
\n\
<div id=\"doc-content\">\n\
<div class=\"header\">\n\
  \n\
  <div class=\"headertitle\">\n\
<div class=\"title\">CheckableFloat Class Reference</div>  </div>\n\
<div class=\"summary\">\n\
<a href=\"classmudbox_1_1_checkable_float.html#pub-methods\">Public Member Functions</a> &#124;\n\
<a href=\"classmudbox_1_1_checkable_float.html#pro-attribs\">Protected Attributes</a>  </div></div><!--header-->\n\
<div class=\"contents\">\n\
\n\
<p><code>#include &lt;<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/math_8h_source.html\">math.h</a>&gt;</code></p>\n\
<a name=\"details\" id=\"details\"></a><h2 class=\"groupheader\">Class Description</h2>\n\
<div class=\"textblock\"><p>A container class that holds a boolean and a float value. </p>\n\
<p>Can be used to to enable/disable the usage of the float value. Typically represented by a checkbox and a slider below that where the state of the checkbox enables or disables the slider. </p>\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/math_8h_source.html#l01622\">1622</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/math_8h_source.html\">math.h</a>.</p>\n\
</div><table class=\"memberdecls\">\n\
<tr class=\"heading\"><td colspan=\"2\"><h2 class=\"groupheader\"><a name=\"pub-methods\"></a>\n\
Public Member Functions</h2></td></tr>\n\
<tr class=\"memitem:a148e70afa30510a865d5ec9848f92770\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/classmudbox_1_1_checkable_float.html#a148e70afa30510a865d5ec9848f92770\">CheckableFloat</a> (<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a>)</td></tr>\n\
<tr class=\"separator:a148e70afa30510a865d5ec9848f92770\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a2cb417a0eb751e9778f36e6273de50fa\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/classmudbox_1_1_checkable_float.html#a2cb417a0eb751e9778f36e6273de50fa\">CheckableFloat</a> (bool bState, float fValue)</td></tr>\n\
<tr class=\"separator:a2cb417a0eb751e9778f36e6273de50fa\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a088f953971fe8578b9d6349fec7f1142\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/classmudbox_1_1_checkable_float.html#a088f953971fe8578b9d6349fec7f1142\">SetValue</a> (float <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a691492ec0bd6383f91200e49f6ae40ed\">f</a>)</td></tr>\n\
<tr class=\"memdesc:a088f953971fe8578b9d6349fec7f1142\"><td class=\"mdescLeft\">&#160;</td><td class=\"mdescRight\">Sets the associated float value.  <a href=\"classmudbox_1_1_checkable_float.html#a088f953971fe8578b9d6349fec7f1142\">More...</a><br></td></tr>\n\
<tr class=\"separator:a088f953971fe8578b9d6349fec7f1142\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a3ab9a9fc37706bdfb917edfd86b0e347\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">float&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/classmudbox_1_1_checkable_float.html#a3ab9a9fc37706bdfb917edfd86b0e347\">Value</a> (<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a>) const </td></tr>\n\
<tr class=\"memdesc:a3ab9a9fc37706bdfb917edfd86b0e347\"><td class=\"mdescLeft\">&#160;</td><td class=\"mdescRight\">Retrieves the associated float value.  <a href=\"classmudbox_1_1_checkable_float.html#a3ab9a9fc37706bdfb917edfd86b0e347\">More...</a><br></td></tr>\n\
<tr class=\"separator:a3ab9a9fc37706bdfb917edfd86b0e347\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a4461884eb47b1cce3bacd311ae1190c3\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/classmudbox_1_1_checkable_float.html#a4461884eb47b1cce3bacd311ae1190c3\">SetState</a> (bool <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a08f98740667f706cd68d5e873088ffa6\">b</a>)</td></tr>\n\
<tr class=\"memdesc:a4461884eb47b1cce3bacd311ae1190c3\"><td class=\"mdescLeft\">&#160;</td><td class=\"mdescRight\">Sets the associated boolean value.  <a href=\"classmudbox_1_1_checkable_float.html#a4461884eb47b1cce3bacd311ae1190c3\">More...</a><br></td></tr>\n\
<tr class=\"separator:a4461884eb47b1cce3bacd311ae1190c3\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a5999e0dcb49d4a5b0ed3eec4837bc46b\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/classmudbox_1_1_checkable_float.html#a5999e0dcb49d4a5b0ed3eec4837bc46b\">State</a> (<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a>) const </td></tr>\n\
<tr class=\"memdesc:a5999e0dcb49d4a5b0ed3eec4837bc46b\"><td class=\"mdescLeft\">&#160;</td><td class=\"mdescRight\">Retrieves the associated boolean value.  <a href=\"classmudbox_1_1_checkable_float.html#a5999e0dcb49d4a5b0ed3eec4837bc46b\">More...</a><br></td></tr>\n\
<tr class=\"separator:a5999e0dcb49d4a5b0ed3eec4837bc46b\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a43144ce864c6d18f1597e10deb7a98b7\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/classmudbox_1_1_checkable_float.html#a43144ce864c6d18f1597e10deb7a98b7\">operator==</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/classmudbox_1_1_checkable_float.html\">CheckableFloat</a> &amp;cf) const   throw ()</td></tr>\n\
<tr class=\"separator:a43144ce864c6d18f1597e10deb7a98b7\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a6fc43a2ba354ba521fabd92249a9436e\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/classmudbox_1_1_checkable_float.html#a6fc43a2ba354ba521fabd92249a9436e\">operator!=</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/classmudbox_1_1_checkable_float.html\">CheckableFloat</a> &amp;cf) const   throw ()</td></tr>\n\
<tr class=\"separator:a6fc43a2ba354ba521fabd92249a9436e\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a340d256e1216959e1da19357b687177f\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/classmudbox_1_1_checkable_float.html\">CheckableFloat</a> &amp;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/classmudbox_1_1_checkable_float.html#a340d256e1216959e1da19357b687177f\">operator=</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/classmudbox_1_1_checkable_float.html\">CheckableFloat</a> &amp;cf)</td></tr>\n\
<tr class=\"separator:a340d256e1216959e1da19357b687177f\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a2498295173eb5e339945b7be1297ed9b\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/classmudbox_1_1_checkable_float.html#a2498295173eb5e339945b7be1297ed9b\">Serialize</a> (<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/classmudbox_1_1_stream.html\">Stream</a> &amp;<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#ad585a1393cfa368fa9dc3d8ebff640d5\">s</a>)</td></tr>\n\
<tr class=\"separator:a2498295173eb5e339945b7be1297ed9b\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
</table><table class=\"memberdecls\">\n\
<tr class=\"heading\"><td colspan=\"2\"><h2 class=\"groupheader\"><a name=\"pro-attribs\"></a>\n\
Protected Attributes</h2></td></tr>\n\
<tr class=\"memitem:a07c6160c82cc0c53463459f90b698959\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/classmudbox_1_1_checkable_float.html#a07c6160c82cc0c53463459f90b698959\">m_bState</a></td></tr>\n\
<tr class=\"separator:a07c6160c82cc0c53463459f90b698959\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a3360352ecec61a57e682a3564232041a\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">float&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/classmudbox_1_1_checkable_float.html#a3360352ecec61a57e682a3564232041a\">m_fValue</a></td></tr>\n\
<tr class=\"separator:a3360352ecec61a57e682a3564232041a\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
</table>\n\
<h2 class=\"groupheader\">Constructor &amp; Destructor Documentation</h2>\n\
<a class=\"anchor\" id=\"a148e70afa30510a865d5ec9848f92770\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/classmudbox_1_1_checkable_float.html\">CheckableFloat</a> </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a>&#160;</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">inline</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/math_8h_source.html#l01625\">1625</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/math_8h_source.html\">math.h</a>.</p>\n\
<div class=\"fragment\"><div class=\"line\"><a name=\"l01625\"></a><span class=\"lineno\"> 1625</span>&#160;{ <a class=\"code\" href=\"#!/url=./cpp_ref/classmudbox_1_1_checkable_float.html#a07c6160c82cc0c53463459f90b698959\">m_bState</a> = <span class=\"keyword\">true</span>; <a class=\"code\" href=\"#!/url=./cpp_ref/classmudbox_1_1_checkable_float.html#a3360352ecec61a57e682a3564232041a\">m_fValue</a> = 0.0f; };</div>\n\
<div class=\"ttc\" id=\"classmudbox_1_1_checkable_float_html_a3360352ecec61a57e682a3564232041a\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/classmudbox_1_1_checkable_float.html#a3360352ecec61a57e682a3564232041a\">mudbox::CheckableFloat::m_fValue</a></div><div class=\"ttdeci\">float m_fValue</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/math_8h_source.html#l01652\">math.h:1652</a></div></div>\n\
<div class=\"ttc\" id=\"classmudbox_1_1_checkable_float_html_a07c6160c82cc0c53463459f90b698959\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/classmudbox_1_1_checkable_float.html#a07c6160c82cc0c53463459f90b698959\">mudbox::CheckableFloat::m_bState</a></div><div class=\"ttdeci\">bool m_bState</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/math_8h_source.html#l01647\">math.h:1647</a></div></div>\n\
</div><!-- fragment -->\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a2cb417a0eb751e9778f36e6273de50fa\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/classmudbox_1_1_checkable_float.html\">CheckableFloat</a> </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">bool&#160;</td>\n\
          <td class=\"paramname\"><em>bState</em>, </td>\n\
        </tr>\n\
        <tr>\n\
          <td class=\"paramkey\"></td>\n\
          <td></td>\n\
          <td class=\"paramtype\">float&#160;</td>\n\
          <td class=\"paramname\"><em>fValue</em>&#160;</td>\n\
        </tr>\n\
        <tr>\n\
          <td></td>\n\
          <td>)</td>\n\
          <td></td><td></td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">inline</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/math_8h_source.html#l01626\">1626</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/math_8h_source.html\">math.h</a>.</p>\n\
<div class=\"fragment\"><div class=\"line\"><a name=\"l01626\"></a><span class=\"lineno\"> 1626</span>&#160;{ <a class=\"code\" href=\"#!/url=./cpp_ref/classmudbox_1_1_checkable_float.html#a07c6160c82cc0c53463459f90b698959\">m_bState</a> = bState; <a class=\"code\" href=\"#!/url=./cpp_ref/classmudbox_1_1_checkable_float.html#a3360352ecec61a57e682a3564232041a\">m_fValue</a> = fValue; };</div>\n\
<div class=\"ttc\" id=\"classmudbox_1_1_checkable_float_html_a3360352ecec61a57e682a3564232041a\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/classmudbox_1_1_checkable_float.html#a3360352ecec61a57e682a3564232041a\">mudbox::CheckableFloat::m_fValue</a></div><div class=\"ttdeci\">float m_fValue</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/math_8h_source.html#l01652\">math.h:1652</a></div></div>\n\
<div class=\"ttc\" id=\"classmudbox_1_1_checkable_float_html_a07c6160c82cc0c53463459f90b698959\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/classmudbox_1_1_checkable_float.html#a07c6160c82cc0c53463459f90b698959\">mudbox::CheckableFloat::m_bState</a></div><div class=\"ttdeci\">bool m_bState</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/math_8h_source.html#l01647\">math.h:1647</a></div></div>\n\
</div><!-- fragment -->\n\
</div>\n\
</div>\n\
<h2 class=\"groupheader\">Member Function Documentation</h2>\n\
<a class=\"anchor\" id=\"a088f953971fe8578b9d6349fec7f1142\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a> SetValue </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">float&#160;</td>\n\
          <td class=\"paramname\"><em>f</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">inline</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Sets the associated float value. </p>\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/math_8h_source.html#l01629\">1629</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/math_8h_source.html\">math.h</a>.</p>\n\
<div class=\"fragment\"><div class=\"line\"><a name=\"l01629\"></a><span class=\"lineno\"> 1629</span>&#160;{ <a class=\"code\" href=\"#!/url=./cpp_ref/classmudbox_1_1_checkable_float.html#a3360352ecec61a57e682a3564232041a\">m_fValue</a> = <a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a691492ec0bd6383f91200e49f6ae40ed\">f</a>; };</div>\n\
<div class=\"ttc\" id=\"classmudbox_1_1_checkable_float_html_a3360352ecec61a57e682a3564232041a\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/classmudbox_1_1_checkable_float.html#a3360352ecec61a57e682a3564232041a\">mudbox::CheckableFloat::m_fValue</a></div><div class=\"ttdeci\">float m_fValue</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/math_8h_source.html#l01652\">math.h:1652</a></div></div>\n\
<div class=\"ttc\" id=\"_g_lee_8h_html_a691492ec0bd6383f91200e49f6ae40ed\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/_g_lee_8h.html#a691492ec0bd6383f91200e49f6ae40ed\">f</a></div><div class=\"ttdeci\">GLclampf f</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/_g_lee_8h_source.html#l09303\">GLee.h:9303</a></div></div>\n\
</div><!-- fragment -->\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a3ab9a9fc37706bdfb917edfd86b0e347\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">float Value </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a>&#160;</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">inline</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Retrieves the associated float value. </p>\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/math_8h_source.html#l01632\">1632</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/math_8h_source.html\">math.h</a>.</p>\n\
<div class=\"fragment\"><div class=\"line\"><a name=\"l01632\"></a><span class=\"lineno\"> 1632</span>&#160;{ <span class=\"keywordflow\">return</span> <a class=\"code\" href=\"#!/url=./cpp_ref/classmudbox_1_1_checkable_float.html#a3360352ecec61a57e682a3564232041a\">m_fValue</a>; };</div>\n\
<div class=\"ttc\" id=\"classmudbox_1_1_checkable_float_html_a3360352ecec61a57e682a3564232041a\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/classmudbox_1_1_checkable_float.html#a3360352ecec61a57e682a3564232041a\">mudbox::CheckableFloat::m_fValue</a></div><div class=\"ttdeci\">float m_fValue</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/math_8h_source.html#l01652\">math.h:1652</a></div></div>\n\
</div><!-- fragment -->\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a4461884eb47b1cce3bacd311ae1190c3\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a> SetState </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">bool&#160;</td>\n\
          <td class=\"paramname\"><em>b</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">inline</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Sets the associated boolean value. </p>\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/math_8h_source.html#l01635\">1635</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/math_8h_source.html\">math.h</a>.</p>\n\
<div class=\"fragment\"><div class=\"line\"><a name=\"l01635\"></a><span class=\"lineno\"> 1635</span>&#160;{ <a class=\"code\" href=\"#!/url=./cpp_ref/classmudbox_1_1_checkable_float.html#a07c6160c82cc0c53463459f90b698959\">m_bState</a> = <a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a08f98740667f706cd68d5e873088ffa6\">b</a>; };</div>\n\
<div class=\"ttc\" id=\"_g_lee_8h_html_a08f98740667f706cd68d5e873088ffa6\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/_g_lee_8h.html#a08f98740667f706cd68d5e873088ffa6\">b</a></div><div class=\"ttdeci\">GLubyte GLubyte b</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/_g_lee_8h_source.html#l05404\">GLee.h:5404</a></div></div>\n\
<div class=\"ttc\" id=\"classmudbox_1_1_checkable_float_html_a07c6160c82cc0c53463459f90b698959\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/classmudbox_1_1_checkable_float.html#a07c6160c82cc0c53463459f90b698959\">mudbox::CheckableFloat::m_bState</a></div><div class=\"ttdeci\">bool m_bState</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/math_8h_source.html#l01647\">math.h:1647</a></div></div>\n\
</div><!-- fragment -->\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a5999e0dcb49d4a5b0ed3eec4837bc46b\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">bool State </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a>&#160;</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">inline</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Retrieves the associated boolean value. </p>\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/math_8h_source.html#l01638\">1638</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/math_8h_source.html\">math.h</a>.</p>\n\
<div class=\"fragment\"><div class=\"line\"><a name=\"l01638\"></a><span class=\"lineno\"> 1638</span>&#160;{ <span class=\"keywordflow\">return</span> <a class=\"code\" href=\"#!/url=./cpp_ref/classmudbox_1_1_checkable_float.html#a07c6160c82cc0c53463459f90b698959\">m_bState</a>; };</div>\n\
<div class=\"ttc\" id=\"classmudbox_1_1_checkable_float_html_a07c6160c82cc0c53463459f90b698959\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/classmudbox_1_1_checkable_float.html#a07c6160c82cc0c53463459f90b698959\">mudbox::CheckableFloat::m_bState</a></div><div class=\"ttdeci\">bool m_bState</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/math_8h_source.html#l01647\">math.h:1647</a></div></div>\n\
</div><!-- fragment -->\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a43144ce864c6d18f1597e10deb7a98b7\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">bool operator== </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/classmudbox_1_1_checkable_float.html\">CheckableFloat</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>cf</em></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
        <tr>\n\
          <td align=\"right\">throw </td><td>(</td><td colspan=\"2\"></td>\n\
        </tr>\n\
        <tr>\n\
          <td align=\"right\"></td><td>)</td><td></td><td></td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">inline</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/math_8h_source.html#l01640\">1640</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/math_8h_source.html\">math.h</a>.</p>\n\
<div class=\"fragment\"><div class=\"line\"><a name=\"l01640\"></a><span class=\"lineno\"> 1640</span>&#160;{ <span class=\"keywordflow\">return</span> <a class=\"code\" href=\"#!/url=./cpp_ref/classmudbox_1_1_checkable_float.html#a5999e0dcb49d4a5b0ed3eec4837bc46b\">State</a>() == cf.State() &amp;&amp; <a class=\"code\" href=\"#!/url=./cpp_ref/classmudbox_1_1_checkable_float.html#a3ab9a9fc37706bdfb917edfd86b0e347\">Value</a>() == cf.Value(); };</div>\n\
<div class=\"ttc\" id=\"classmudbox_1_1_checkable_float_html_a3ab9a9fc37706bdfb917edfd86b0e347\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/classmudbox_1_1_checkable_float.html#a3ab9a9fc37706bdfb917edfd86b0e347\">mudbox::CheckableFloat::Value</a></div><div class=\"ttdeci\">float Value(void) const </div><div class=\"ttdoc\">Retrieves the associated float value. </div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/math_8h_source.html#l01632\">math.h:1632</a></div></div>\n\
<div class=\"ttc\" id=\"classmudbox_1_1_checkable_float_html_a5999e0dcb49d4a5b0ed3eec4837bc46b\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/classmudbox_1_1_checkable_float.html#a5999e0dcb49d4a5b0ed3eec4837bc46b\">mudbox::CheckableFloat::State</a></div><div class=\"ttdeci\">bool State(void) const </div><div class=\"ttdoc\">Retrieves the associated boolean value. </div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/math_8h_source.html#l01638\">math.h:1638</a></div></div>\n\
</div><!-- fragment -->\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a6fc43a2ba354ba521fabd92249a9436e\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">bool operator!= </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/classmudbox_1_1_checkable_float.html\">CheckableFloat</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>cf</em></td><td>)</td>\n\
          <td> const</td>\n\
        </tr>\n\
        <tr>\n\
          <td align=\"right\">throw </td><td>(</td><td colspan=\"2\"></td>\n\
        </tr>\n\
        <tr>\n\
          <td align=\"right\"></td><td>)</td><td></td><td></td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">inline</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/math_8h_source.html#l01641\">1641</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/math_8h_source.html\">math.h</a>.</p>\n\
<div class=\"fragment\"><div class=\"line\"><a name=\"l01641\"></a><span class=\"lineno\"> 1641</span>&#160;{ <span class=\"keywordflow\">return</span> !<a class=\"code\" href=\"#!/url=./cpp_ref/classmudbox_1_1_checkable_float.html#a43144ce864c6d18f1597e10deb7a98b7\">operator ==</a>( cf ); };</div>\n\
<div class=\"ttc\" id=\"classmudbox_1_1_checkable_float_html_a43144ce864c6d18f1597e10deb7a98b7\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/classmudbox_1_1_checkable_float.html#a43144ce864c6d18f1597e10deb7a98b7\">mudbox::CheckableFloat::operator==</a></div><div class=\"ttdeci\">bool operator==(const CheckableFloat &amp;cf) const </div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/math_8h_source.html#l01640\">math.h:1640</a></div></div>\n\
</div><!-- fragment -->\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a340d256e1216959e1da19357b687177f\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/classmudbox_1_1_checkable_float.html\">CheckableFloat</a>&amp; operator= </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/classmudbox_1_1_checkable_float.html\">CheckableFloat</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>cf</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">inline</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/math_8h_source.html#l01642\">1642</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/math_8h_source.html\">math.h</a>.</p>\n\
<div class=\"fragment\"><div class=\"line\"><a name=\"l01642\"></a><span class=\"lineno\"> 1642</span>&#160;{ <a class=\"code\" href=\"#!/url=./cpp_ref/classmudbox_1_1_checkable_float.html#a07c6160c82cc0c53463459f90b698959\">m_bState</a> = cf.m_bState; <a class=\"code\" href=\"#!/url=./cpp_ref/classmudbox_1_1_checkable_float.html#a3360352ecec61a57e682a3564232041a\">m_fValue</a> = cf.m_fValue; <span class=\"keywordflow\">return</span> *<span class=\"keyword\">this</span>; };</div>\n\
<div class=\"ttc\" id=\"classmudbox_1_1_checkable_float_html_a3360352ecec61a57e682a3564232041a\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/classmudbox_1_1_checkable_float.html#a3360352ecec61a57e682a3564232041a\">mudbox::CheckableFloat::m_fValue</a></div><div class=\"ttdeci\">float m_fValue</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/math_8h_source.html#l01652\">math.h:1652</a></div></div>\n\
<div class=\"ttc\" id=\"classmudbox_1_1_checkable_float_html_a07c6160c82cc0c53463459f90b698959\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/classmudbox_1_1_checkable_float.html#a07c6160c82cc0c53463459f90b698959\">mudbox::CheckableFloat::m_bState</a></div><div class=\"ttdeci\">bool m_bState</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/math_8h_source.html#l01647\">math.h:1647</a></div></div>\n\
</div><!-- fragment -->\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a2498295173eb5e339945b7be1297ed9b\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a3db05964a3cc4410f35b7ea2b7eb850d\">void</a> Serialize </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/classmudbox_1_1_stream.html\">Stream</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>s</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">inline</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/math_8h_source.html#l01644\">1644</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/math_8h_source.html\">math.h</a>.</p>\n\
<div class=\"fragment\"><div class=\"line\"><a name=\"l01645\"></a><span class=\"lineno\"> 1645</span>&#160;    {</div>\n\
<div class=\"line\"><a name=\"l01646\"></a><span class=\"lineno\"> 1646</span>&#160;        <a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#ad585a1393cfa368fa9dc3d8ebff640d5\">s</a> == <a class=\"code\" href=\"#!/url=./cpp_ref/classmudbox_1_1_checkable_float.html#a07c6160c82cc0c53463459f90b698959\">m_bState</a> == <a class=\"code\" href=\"#!/url=./cpp_ref/classmudbox_1_1_checkable_float.html#a3360352ecec61a57e682a3564232041a\">m_fValue</a>;</div>\n\
<div class=\"line\"><a name=\"l01647\"></a><span class=\"lineno\"> 1647</span>&#160;    };</div>\n\
<div class=\"ttc\" id=\"classmudbox_1_1_checkable_float_html_a3360352ecec61a57e682a3564232041a\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/classmudbox_1_1_checkable_float.html#a3360352ecec61a57e682a3564232041a\">mudbox::CheckableFloat::m_fValue</a></div><div class=\"ttdeci\">float m_fValue</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/math_8h_source.html#l01652\">math.h:1652</a></div></div>\n\
<div class=\"ttc\" id=\"classmudbox_1_1_checkable_float_html_a07c6160c82cc0c53463459f90b698959\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/classmudbox_1_1_checkable_float.html#a07c6160c82cc0c53463459f90b698959\">mudbox::CheckableFloat::m_bState</a></div><div class=\"ttdeci\">bool m_bState</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/math_8h_source.html#l01647\">math.h:1647</a></div></div>\n\
<div class=\"ttc\" id=\"_g_lee_8h_html_ad585a1393cfa368fa9dc3d8ebff640d5\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/_g_lee_8h.html#ad585a1393cfa368fa9dc3d8ebff640d5\">s</a></div><div class=\"ttdeci\">GLdouble s</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/_g_lee_8h_source.html#l01173\">GLee.h:1173</a></div></div>\n\
</div><!-- fragment -->\n\
</div>\n\
</div>\n\
<h2 class=\"groupheader\">Member Data Documentation</h2>\n\
<a class=\"anchor\" id=\"a07c6160c82cc0c53463459f90b698959\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">bool m_bState</td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">protected</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/math_8h_source.html#l01647\">1647</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/math_8h_source.html\">math.h</a>.</p>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a3360352ecec61a57e682a3564232041a\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">float m_fValue</td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">protected</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/math_8h_source.html#l01652\">1652</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/math_8h_source.html\">math.h</a>.</p>\n\
\n\
</div>\n\
</div>\n\
<hr>The documentation for this class was generated from the following file:<ul>\n\
<li>Mudbox/<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/math_8h_source.html\">math.h</a></li>\n\
</ul>\n\
</div><!-- contents -->\n\
</div><!-- doc-content -->\n\
          <div class=\"footer-block\"><a href=\"../html/ac.cmtdialog.htm\" class=\"comments-anchor\" target=\"_blank\"><span class=\"comments-link\">Please send us your comment about this page</span></a></div></div>\n\
   </div></body>\n\
</html>\n\
";