var topic = "<!-- saved from url=(0024)http://docs.autodesk.com -->\n\
<html>\n\
   <head><script src=\"../scripts/yepnope.1.5.4-min.js\" type=\"text/javascript\"></script><script src=\"../scripts/lib/jquery-1.11.1.min.js\" type=\"text/javascript\"></script><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"><meta name=\"product\" content=\"MOBPRO\"><meta name=\"release\" content=\"2018\"><meta name=\"book\" content=\"GeneralUser\"><meta name=\"created\" content=\"2017-09-08\"><meta name=\"topicid\" content=\"GUID-02FA7DD3-6C7A-4C6A-B7BC-824765AE1CB2\"><meta name=\"topic-type\" content=\"concept\">\n\
      <title>Class Members - Typedefs</title>\n\
   \n\
\n\
</head>\n\
   <body height=\"100%\"><div class=\"body_content\" id=\"body-content\"><link rel=\"stylesheet\" type=\"text/css\" href=\"cpp_ref/navtree.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"cpp_ref/doxygen.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"cpp_ref/tabs.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"style/adsk.cpm.css\"><script language=\"javascript\">var index = \'index.html\';</script><script>$(document).ready(function() { yepnope.injectJs(\"./scripts/ac_common.js\"); });</script><script type=\"text/javascript\">\n\
var tocSystemNeedsToBeLoaded = typeof(cpp_ref_adsk_ref_toc) == \'undefined\';\n\
var weAreIn21 = $(\'div#main.view-active\').length;\n\
var tocPrefix = \'\';\n\
if (weAreIn21)\n\
{ tocPrefix = \'cpp_ref/\'; }\n\
function cpp_ref_initializeToc(forceTrigger) {\n\
    cpp_ref_adsk_ref_toc.initResizable();\n\
    cpp_ref_adsk_ref_toc.initNavTree(\'functions_type_r.html\', tocPrefix);\n\
    dQuery(document).trigger(\'toc_initialized\');\n\
}\n\
if (tocSystemNeedsToBeLoaded)\n\
{\n\
	yepnope([{\n\
	load:[tocPrefix + \'json3.min.js\', tocPrefix + \'jquery.js\', tocPrefix + \'ref-toc-controller.js\', tocPrefix + \'dynsections.js\'],\n\
	complete: function() {\n\
	  if (typeof(dQuery) == \'undefined\')\n\
	  {\n\
	    dQuery = jQuery.noConflict(true);\n\
	  }\n\
	  else { jQuery.noConflict(true); }\n\
	  $(document).ready(cpp_ref_initializeToc);\n\
	}\n\
 	}])\n\
}\n\
if (!weAreIn21) { // if in AKN...\n\
$(window).load( function() {\n\
    setTimeout( function() {\n\
        var content = $(\'body > div\').not(\'#body-content\');     // take any divs under body that are not id=body-content\n\
        content.each( function() { \n\
            $(this).css( { \'padding-left\': $(this).css(\'margin-left\') } );       // and if they have any padding-left already, move it to margin-left.\n\
        } );\n\
        var width = cpp_ref_adsk_ref_toc.readFromStorage(\'width\');\n\
        content.css({marginLeft:parseInt(width)+6+\"px\"});\n\
    }, 100);\n\
} ); \n\
}\n\
</script><script>$(\"div#WidgetFloaterPanels,link[href*=\'microsofttranslator.com\'],script[src*=\'microsofttranslator.com\'],script[src*=\'bing.com\']\").remove();</script><script type=\'text/javascript\'>$(\"div#navigation,div#breadcrumbs,div#banner\").attr(\"translate\",\"no\"); var mtLocation = ((location && location.href && location.href.indexOf(\'https\') == 0)?\'https://ssl.microsofttranslator.com\':\'http://www.microsofttranslator.com\')+\'/ajax/v3/WidgetV3.ashx?ctf=True&ui=true&settings=Manual&from=en&hidelanguages=\'; yepnope.injectJs(mtLocation, function() {}, { charset:\'utf-8\', type:\'text/javascript\' } );</script><script>\n\
 if (!tocSystemNeedsToBeLoaded) { cpp_ref_initializeToc(); }\n\
 </script><!-- begin MT -->\n\
            \n\
            <div id=\'MicrosoftTranslatorWidget\' class=\'Dark\' style=\'float:right;z-index:100;color:white;background-color:#bbbbbb;height:58px;overflow:hidden\'></div>\n\
      <div><div class=\"related-links\">\n\
         <div class=\"head\">\n\
            <h1>Class Members - Typedefs</h1>\n\
         </div>\n\
\n\
    <div id=\"top\"><!-- Generated by Doxygen 1.8.10 -->\n\
  <div id=\"navrow1\" class=\"tabs\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./cpp_ref/index.html\"><span>Main&#160;Page</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/pages.html\"><span>Topics</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/modules.html\"><span>Modules</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/namespaces.html\"><span>Namespaces</span></a></li>\n\
      <li class=\"current\"><a href=\"#!/url=./cpp_ref/annotated.html\"><span>Classes</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/files.html\"><span>Files</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/examples.html\"><span>Examples</span></a></li>\n\
    </ul>\n\
  </div>\n\
  <div id=\"navrow2\" class=\"tabs2\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./cpp_ref/annotated.html\"><span>Class&#160;List</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/hierarchy.html\"><span>Class&#160;Hierarchy</span></a></li>\n\
      <li class=\"current\"><a href=\"#!/url=./cpp_ref/functions.html\"><span>Class&#160;Members</span></a></li>\n\
    </ul>\n\
  </div>\n\
  <div id=\"navrow3\" class=\"tabs2\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./cpp_ref/functions.html\"><span>All</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/functions_func.html\"><span>Functions</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/functions_vars.html\"><span>Variables</span></a></li>\n\
      <li class=\"current\"><a href=\"#!/url=./cpp_ref/functions_type.html\"><span>Typedefs</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/functions_enum.html\"><span>Enumerations</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/functions_eval.html\"><span>Enumerator</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/functions_prop.html\"><span>Properties</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/functions_rela.html\"><span>Related&#160;Functions</span></a></li>\n\
    </ul>\n\
  </div>\n\
  <div id=\"navrow4\" class=\"tabs3\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./cpp_ref/functions_type.html#index_a\"><span>a</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/functions_type_b.html#index_b\"><span>b</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/functions_type_c.html#index_c\"><span>c</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/functions_type_d.html#index_d\"><span>d</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/functions_type_e.html#index_e\"><span>e</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/functions_type_f.html#index_f\"><span>f</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/functions_type_i.html#index_i\"><span>i</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/functions_type_k.html#index_k\"><span>k</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/functions_type_l.html#index_l\"><span>l</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/functions_type_m.html#index_m\"><span>m</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/functions_type_p.html#index_p\"><span>p</span></a></li>\n\
      <li class=\"current\"><a href=\"#!/url=./cpp_ref/functions_type_r.html#index_r\"><span>r</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/functions_type_s.html#index_s\"><span>s</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/functions_type_t.html#index_t\"><span>t</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/functions_type_u.html#index_u\"><span>u</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/functions_type_v.html#index_v\"><span>v</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/functions_type_w.html#index_w\"><span>w</span></a></li>\n\
    </ul>\n\
  </div>\n\
</div><!-- top -->\n\
<div id=\"side-nav\" class=\"ui-resizable side-nav-resizable\">\n\
  <div id=\"nav-tree\">\n\
    <div id=\"nav-tree-contents\">\n\
      <div id=\"nav-sync\" class=\"sync\"></div>\n\
    </div>\n\
  </div>\n\
  <div id=\"splitbar\" style=\"-moz-user-select:none;\" class=\"ui-resizable-handle\">\n\
  </div>\n\
</div>\n\
\n\
<div id=\"doc-content\">\n\
<div class=\"contents\">\n\
&#160;\n\
\n\
<h3><a class=\"anchor\" id=\"index_r\"></a>- r -</h3><ul>\n\
<li>RawHeader\n\
: <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_network_cache_meta_data.html#ac1009af450656bc3707915bc691d06ac\">QNetworkCacheMetaData</a>\n\
</li>\n\
<li>RawHeaderList\n\
: <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_network_cache_meta_data.html#acd06d80e7d6f4cde18da21660a742068\">QNetworkCacheMetaData</a>\n\
</li>\n\
<li>RawHeaderPair\n\
: <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_network_reply.html#a6753115dbc00d07b484edaed14898440\">QNetworkReply</a>\n\
</li>\n\
<li>ReadFunc\n\
: <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_settings.html#a6ac2248a1aad810e497d7cbb91a70147\">QSettings</a>\n\
</li>\n\
<li>reference\n\
: <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_byte_array.html#a214162ba1a25a237fbda0ed12656b0fa\">QByteArray</a>\n\
, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_contiguous_cache.html#abe8933d436779a43cb5c1896ff5f2918\">QContiguousCache&lt; T &gt;</a>\n\
, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_future_1_1const__iterator.html#a4fef7a13b0a31eb10c0ae4c731a0e2d3\">QFuture&lt; T &gt;::const_iterator</a>\n\
, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_hash_1_1const__iterator.html#a4fef7a13b0a31eb10c0ae4c731a0e2d3\">QHash&lt; Key, T &gt;::const_iterator</a>\n\
, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_hash_1_1iterator.html#a9b1a63f171d76a7a3995b6858e99f2ea\">QHash&lt; Key, T &gt;::iterator</a>\n\
, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_linked_list_1_1const__iterator.html#a4fef7a13b0a31eb10c0ae4c731a0e2d3\">QLinkedList&lt; T &gt;::const_iterator</a>\n\
, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_linked_list_1_1iterator.html#a9b1a63f171d76a7a3995b6858e99f2ea\">QLinkedList&lt; T &gt;::iterator</a>\n\
, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_linked_list.html#abe8933d436779a43cb5c1896ff5f2918\">QLinkedList&lt; T &gt;</a>\n\
, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_list_1_1const__iterator.html#a4fef7a13b0a31eb10c0ae4c731a0e2d3\">QList&lt; T &gt;::const_iterator</a>\n\
, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_list_1_1iterator.html#a9b1a63f171d76a7a3995b6858e99f2ea\">QList&lt; T &gt;::iterator</a>\n\
, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_list.html#abe8933d436779a43cb5c1896ff5f2918\">QList&lt; T &gt;</a>\n\
, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_map_1_1const__iterator.html#a4fef7a13b0a31eb10c0ae4c731a0e2d3\">QMap&lt; Key, T &gt;::const_iterator</a>\n\
, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_map_1_1iterator.html#a9b1a63f171d76a7a3995b6858e99f2ea\">QMap&lt; Key, T &gt;::iterator</a>\n\
, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_set_1_1const__iterator.html#a4fef7a13b0a31eb10c0ae4c731a0e2d3\">QSet&lt; T &gt;::const_iterator</a>\n\
, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_set_1_1iterator.html#a4fef7a13b0a31eb10c0ae4c731a0e2d3\">QSet&lt; T &gt;::iterator</a>\n\
, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_set.html#abe8933d436779a43cb5c1896ff5f2918\">QSet&lt; T &gt;</a>\n\
, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_string.html#a8b909fac7487a1ec5e240671ea879e50\">QString</a>\n\
, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_shared_pointer_1_1_basic.html#abe8933d436779a43cb5c1896ff5f2918\">Basic&lt; T &gt;</a>\n\
, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_var_length_array.html#abe8933d436779a43cb5c1896ff5f2918\">QVarLengthArray&lt; T, Prealloc &gt;</a>\n\
, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_vector.html#abe8933d436779a43cb5c1896ff5f2918\">QVector&lt; T &gt;</a>\n\
, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_weak_pointer.html#abe8933d436779a43cb5c1896ff5f2918\">QWeakPointer&lt; T &gt;</a>\n\
</li>\n\
<li>RequirementValue\n\
: <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/classmudbox_1_1_view_port_filter.html#a08e0252a0ee2acdf657c8ea09f509f6e\">ViewPortFilter</a>\n\
</li>\n\
<li>result_type\n\
: <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_const_member_function_wrapper.html#ab774fc5d25855517e772c39f7d9d5f09\">ConstMemberFunctionWrapper&lt; T, C &gt;</a>\n\
, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_function_wrapper0.html#ab774fc5d25855517e772c39f7d9d5f09\">FunctionWrapper0&lt; T &gt;</a>\n\
, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_function_wrapper1.html#ab774fc5d25855517e772c39f7d9d5f09\">FunctionWrapper1&lt; T, U &gt;</a>\n\
, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_function_wrapper2.html#ab774fc5d25855517e772c39f7d9d5f09\">FunctionWrapper2&lt; T, U, V &gt;</a>\n\
, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_member_function_wrapper1.html#ab774fc5d25855517e772c39f7d9d5f09\">MemberFunctionWrapper1&lt; T, C, U &gt;</a>\n\
, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_member_function_wrapper.html#ab774fc5d25855517e772c39f7d9d5f09\">MemberFunctionWrapper&lt; T, C &gt;</a>\n\
, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/struct_qt_private_1_1_push_back_wrapper.html#a9362b0e17335e9c13246f970c962d645\">PushBackWrapper</a>\n\
</li>\n\
<li>ResultType\n\
: <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_filtered_each_kernel.html#a13d3ccc8836027e5b399582861553350\">FilteredEachKernel&lt; Iterator, KeepFunctor &gt;</a>\n\
, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_filtered_reduced_kernel.html#ac31d31816fa8af04fab3a129ea6ca3ed\">FilteredReducedKernel&lt; ReducedResultType, Iterator, KeepFunctor, ReduceFunctor, Reducer &gt;</a>\n\
, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_filter_kernel.html#a7f573ccb85146686236d1cc526261d9a\">FilterKernel&lt; Sequence, KeepFunctor, ReduceFunctor &gt;</a>\n\
, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_iterate_kernel.html#a13d3ccc8836027e5b399582861553350\">IterateKernel&lt; Iterator, T &gt;</a>\n\
, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_mapped_each_kernel.html#a13d3ccc8836027e5b399582861553350\">MappedEachKernel&lt; Iterator, MapFunctor &gt;</a>\n\
, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_mapped_reduced_kernel.html#ac31d31816fa8af04fab3a129ea6ca3ed\">MappedReducedKernel&lt; ReducedResultType, Iterator, MapFunctor, ReduceFunctor, Reducer &gt;</a>\n\
, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_thread_engine.html#a13d3ccc8836027e5b399582861553350\">ThreadEngine&lt; T &gt;</a>\n\
, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/struct_qt_private_1_1_map_result_type.html#a975e50ca2381136cfef3eaf213063194\">MapResultType&lt; InputSequence, MapFunctor &gt;</a>\n\
, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/struct_qt_private_1_1_map_result_type_3_01_input_sequence_3_01_t_01_4_00_01_map_functor_01_4.html#ac8805414d1b35c3a4c3200da4571dfeb\">MapResultType&lt; InputSequence&lt; T &gt;, MapFunctor &gt;</a>\n\
, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/struct_qt_private_1_1_map_result_type_3_01_input_sequence_3_01_t_01_4_00_01_u_07_5_08_07_v_08_4.html#a004e6bf1b2694411b23bc426ab98db2d\">MapResultType&lt; InputSequence&lt; T &gt;, U(*)(V)&gt;</a>\n\
, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/struct_qt_private_1_1_map_result_type_3_01_input_sequence_3_01_t_01_4_00_01_u_07_c_1_1_5_08_07_08_01const_01_01_4.html#a004e6bf1b2694411b23bc426ab98db2d\">MapResultType&lt; InputSequence&lt; T &gt;, U(C::*)() const  &gt;</a>\n\
, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/struct_qt_private_1_1_map_result_type_3_01_q_string_list_00_01_map_functor_01_4.html#afc964478dc83ef22124331bfdd96f208\">MapResultType&lt; QStringList, MapFunctor &gt;</a>\n\
, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/struct_qt_private_1_1_map_result_type_3_01_q_string_list_00_01_u_07_5_08_07_v_08_4.html#ac805ce64b579df6e2de146104c7a7e41\">MapResultType&lt; QStringList, U(*)(V)&gt;</a>\n\
, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/struct_qt_private_1_1_map_result_type_3_01_q_string_list_00_01_u_07_c_1_1_5_08_07_08_01const_01_01_4.html#ac805ce64b579df6e2de146104c7a7e41\">MapResultType&lt; QStringList, U(C::*)() const  &gt;</a>\n\
, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/struct_qt_private_1_1_map_result_type_3_01void_00_01_t_07_c_1_1_5_08_07_08_01const_01_01_4.html#a13d3ccc8836027e5b399582861553350\">MapResultType&lt; void, T(C::*)() const  &gt;</a>\n\
, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/struct_qt_private_1_1_map_result_type_3_01void_00_01_u_07_5_08_07_v_08_4.html#a9d309209629f40c96b3f161830042487\">MapResultType&lt; void, U(*)(V)&gt;</a>\n\
, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/struct_qt_private_1_1_reduce_result_type_3_01_t_07_c_1_1_5_08_07_u_08_4.html#a74ebcf0b32d77fdb0469addbfeae49e2\">ReduceResultType&lt; T(C::*)(U)&gt;</a>\n\
, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/struct_qt_private_1_1_reduce_result_type_3_01void_07_5_08_07_u_01_6_00_01_v_08_4.html#a9d309209629f40c96b3f161830042487\">ReduceResultType&lt; void(*)(U &amp;, V)&gt;</a>\n\
</li>\n\
<li>ReturnType\n\
: <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_filtered_each_kernel.html#a033ab452d4be5a0455f4aee5c8646b40\">FilteredEachKernel&lt; Iterator, KeepFunctor &gt;</a>\n\
, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_filtered_reduced_kernel.html#ad8ea22d4292e3a5089b1ffecd2c24b48\">FilteredReducedKernel&lt; ReducedResultType, Iterator, KeepFunctor, ReduceFunctor, Reducer &gt;</a>\n\
, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_filter_kernel.html#ad7d864e3c8fd693987204f120d525b01\">FilterKernel&lt; Sequence, KeepFunctor, ReduceFunctor &gt;</a>\n\
, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_map_kernel.html#ad7d864e3c8fd693987204f120d525b01\">MapKernel&lt; Iterator, MapFunctor &gt;</a>\n\
, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_mapped_each_kernel.html#a033ab452d4be5a0455f4aee5c8646b40\">MappedEachKernel&lt; Iterator, MapFunctor &gt;</a>\n\
, <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_qt_concurrent_1_1_mapped_reduced_kernel.html#ad8ea22d4292e3a5089b1ffecd2c24b48\">MappedReducedKernel&lt; ReducedResultType, Iterator, MapFunctor, ReduceFunctor, Reducer &gt;</a>\n\
</li>\n\
<li>RootObjectHandler\n\
: <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_accessible.html#a3e868797d8937fd0865daddb137336df\">QAccessible</a>\n\
</li>\n\
</ul>\n\
</div><!-- contents -->\n\
</div><!-- doc-content -->\n\
          <div class=\"footer-block\"><a href=\"../html/ac.cmtdialog.htm\" class=\"comments-anchor\" target=\"_blank\"><span class=\"comments-link\">Please send us your comment about this page</span></a></div></div>\n\
   </div></div></body>\n\
</html>\n\
";