var mesh_8h =
[
    [ "Vertex", "structmudbox_1_1_vertex.html", "structmudbox_1_1_vertex" ],
    [ "GenericFace", "structmudbox_1_1_generic_face.html", "structmudbox_1_1_generic_face" ],
    [ "TC", "structmudbox_1_1_t_c.html", "structmudbox_1_1_t_c" ],
    [ "VertexAdjacency", "structmudbox_1_1_vertex_adjacency.html", "structmudbox_1_1_vertex_adjacency" ],
    [ "FaceEnumerator", "classmudbox_1_1_face_enumerator.html", "classmudbox_1_1_face_enumerator" ],
    [ "VertexEnumerator", "classmudbox_1_1_vertex_enumerator.html", "classmudbox_1_1_vertex_enumerator" ],
    [ "AdjacentVertexEnumerator", "classmudbox_1_1_adjacent_vertex_enumerator.html", "classmudbox_1_1_adjacent_vertex_enumerator" ],
    [ "StoredVertexInfo", "structmudbox_1_1_stored_vertex_info.html", "structmudbox_1_1_stored_vertex_info" ],
    [ "SurfacePoint", "structmudbox_1_1_surface_point.html", "structmudbox_1_1_surface_point" ],
    [ "Mesh", "classmudbox_1_1_mesh.html", "classmudbox_1_1_mesh" ],
    [ "MeshFreezer", "classmudbox_1_1_mesh_freezer.html", "classmudbox_1_1_mesh_freezer" ],
    [ "MeshSelector", "classmudbox_1_1_mesh_selector.html", "classmudbox_1_1_mesh_selector" ],
    [ "TangentGenerator", "classmudbox_1_1_tangent_generator.html", "classmudbox_1_1_tangent_generator" ],
    [ "Picker", "classmudbox_1_1_picker.html", "classmudbox_1_1_picker" ],
    [ "ScreenSpacePicker", "classmudbox_1_1_screen_space_picker.html", "classmudbox_1_1_screen_space_picker" ],
    [ "MeshGrid", "classmudbox_1_1_mesh_grid.html", "classmudbox_1_1_mesh_grid" ],
    [ "SpatialGrid", "classmudbox_1_1_spatial_grid.html", "classmudbox_1_1_spatial_grid" ],
    [ "Coord", "structmudbox_1_1_spatial_grid_1_1_coord.html", "structmudbox_1_1_spatial_grid_1_1_coord" ],
    [ "VoxelIterator", "classmudbox_1_1_spatial_grid_1_1_voxel_iterator.html", "classmudbox_1_1_spatial_grid_1_1_voxel_iterator" ],
    [ "SurfaceSmoother", "classmudbox_1_1_surface_smoother.html", "classmudbox_1_1_surface_smoother" ],
    [ "MeshChange", "classmudbox_1_1_mesh_change.html", "classmudbox_1_1_mesh_change" ],
    [ "MeshUnlocker", "classmudbox_1_1_mesh_unlocker.html", "classmudbox_1_1_mesh_unlocker" ],
    [ "MeshPartitioning", "classmudbox_1_1_mesh_partitioning.html", "classmudbox_1_1_mesh_partitioning" ],
    [ "MB_NORMALPRECISION", "mesh_8h.html#a3d82a3323195a3b0a8b6122dff59b066", null ],
    [ "MB_NORMALMAX", "mesh_8h.html#a3085724e01ff9ef04f1210f4a2f1ef44", null ],
    [ "INVALID_ID", "mesh_8h.html#a483b0a38edf0c10ef4a7cb633dc8a9fc", null ]
];