var topic = "<!-- saved from url=(0024)http://docs.autodesk.com -->\n\
<html>\n\
   <head><script src=\"../scripts/yepnope.1.5.4-min.js\" type=\"text/javascript\"></script><script src=\"../scripts/lib/jquery-1.11.1.min.js\" type=\"text/javascript\"></script><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"><meta name=\"product\" content=\"MOBPRO\"><meta name=\"release\" content=\"2018\"><meta name=\"book\" content=\"GeneralUser\"><meta name=\"created\" content=\"2017-09-08\"><meta name=\"topicid\" content=\"GUID-02FA7DD3-6C7A-4C6A-B7BC-824765AE1CB2\"><meta name=\"topic-type\" content=\"concept\">\n\
      <title>Phonon::BackendCapabilities Namespace Reference</title>\n\
   \n\
\n\
</head>\n\
   <body height=\"100%\"><div class=\"body_content\" id=\"body-content\"><link rel=\"stylesheet\" type=\"text/css\" href=\"cpp_ref/navtree.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"cpp_ref/doxygen.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"cpp_ref/tabs.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"style/adsk.cpm.css\"><script language=\"javascript\">var index = \'index.html\';</script><script>$(document).ready(function() { yepnope.injectJs(\"./scripts/ac_common.js\"); });</script><script type=\"text/javascript\">\n\
var tocSystemNeedsToBeLoaded = typeof(cpp_ref_adsk_ref_toc) == \'undefined\';\n\
var weAreIn21 = $(\'div#main.view-active\').length;\n\
var tocPrefix = \'\';\n\
if (weAreIn21)\n\
{ tocPrefix = \'cpp_ref/\'; }\n\
function cpp_ref_initializeToc(forceTrigger) {\n\
    cpp_ref_adsk_ref_toc.initResizable();\n\
    cpp_ref_adsk_ref_toc.initNavTree(\'namespace_phonon_1_1_backend_capabilities.html\', tocPrefix);\n\
    dQuery(document).trigger(\'toc_initialized\');\n\
}\n\
if (tocSystemNeedsToBeLoaded)\n\
{\n\
	yepnope([{\n\
	load:[tocPrefix + \'json3.min.js\', tocPrefix + \'jquery.js\', tocPrefix + \'ref-toc-controller.js\', tocPrefix + \'dynsections.js\'],\n\
	complete: function() {\n\
	  if (typeof(dQuery) == \'undefined\')\n\
	  {\n\
	    dQuery = jQuery.noConflict(true);\n\
	  }\n\
	  else { jQuery.noConflict(true); }\n\
	  $(document).ready(cpp_ref_initializeToc);\n\
	}\n\
 	}])\n\
}\n\
if (!weAreIn21) { // if in AKN...\n\
$(window).load( function() {\n\
    setTimeout( function() {\n\
        var content = $(\'body > div\').not(\'#body-content\');     // take any divs under body that are not id=body-content\n\
        content.each( function() { \n\
            $(this).css( { \'padding-left\': $(this).css(\'margin-left\') } );       // and if they have any padding-left already, move it to margin-left.\n\
        } );\n\
        var width = cpp_ref_adsk_ref_toc.readFromStorage(\'width\');\n\
        content.css({marginLeft:parseInt(width)+6+\"px\"});\n\
    }, 100);\n\
} ); \n\
}\n\
</script><script>$(\"div#WidgetFloaterPanels,link[href*=\'microsofttranslator.com\'],script[src*=\'microsofttranslator.com\'],script[src*=\'bing.com\']\").remove();</script><script type=\'text/javascript\'>$(\"div#navigation,div#breadcrumbs,div#banner\").attr(\"translate\",\"no\"); var mtLocation = ((location && location.href && location.href.indexOf(\'https\') == 0)?\'https://ssl.microsofttranslator.com\':\'http://www.microsofttranslator.com\')+\'/ajax/v3/WidgetV3.ashx?ctf=True&ui=true&settings=Manual&from=en&hidelanguages=\'; yepnope.injectJs(mtLocation, function() {}, { charset:\'utf-8\', type:\'text/javascript\' } );</script><script>\n\
 if (!tocSystemNeedsToBeLoaded) { cpp_ref_initializeToc(); }\n\
 </script><!-- begin MT -->\n\
            \n\
            <div id=\'MicrosoftTranslatorWidget\' class=\'Dark\' style=\'float:right;z-index:100;color:white;background-color:#bbbbbb;height:58px;overflow:hidden\'></div>\n\
      <div>\n\
         <div class=\"head\">\n\
            <h1>Phonon::BackendCapabilities Namespace Reference</h1>\n\
         </div>\n\
\n\
    <div id=\"top\"><!-- Generated by Doxygen 1.8.10 -->\n\
  <div id=\"navrow1\" class=\"tabs\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./cpp_ref/index.html\"><span>Main&#160;Page</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/pages.html\"><span>Topics</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/modules.html\"><span>Modules</span></a></li>\n\
      <li class=\"current\"><a href=\"#!/url=./cpp_ref/namespaces.html\"><span>Namespaces</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/annotated.html\"><span>Classes</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/files.html\"><span>Files</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/examples.html\"><span>Examples</span></a></li>\n\
    </ul>\n\
  </div>\n\
  <div id=\"navrow2\" class=\"tabs2\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./cpp_ref/namespaces.html\"><span>Namespace&#160;List</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/namespacemembers.html\"><span>Namespace&#160;Members</span></a></li>\n\
    </ul>\n\
  </div>\n\
</div><!-- top -->\n\
<div id=\"side-nav\" class=\"ui-resizable side-nav-resizable\">\n\
  <div id=\"nav-tree\">\n\
    <div id=\"nav-tree-contents\">\n\
      <div id=\"nav-sync\" class=\"sync\"></div>\n\
    </div>\n\
  </div>\n\
  <div id=\"splitbar\" style=\"-moz-user-select:none;\" class=\"ui-resizable-handle\">\n\
  </div>\n\
</div>\n\
\n\
<div id=\"doc-content\">\n\
<div class=\"header\">\n\
  \n\
  <div class=\"headertitle\">\n\
<div class=\"title\">Phonon::BackendCapabilities Namespace Reference</div>  </div>\n\
<div class=\"summary\">\n\
<a href=\"namespace_phonon_1_1_backend_capabilities.html#nested-classes\">Classes</a> &#124;\n\
<a href=\"namespace_phonon_1_1_backend_capabilities.html#func-members\">Functions</a>  </div></div><!--header-->\n\
<div class=\"contents\">\n\
<a name=\"details\" id=\"details\"></a><h2 class=\"groupheader\">Namespace description</h2>\n\
<div class=\"textblock\"><p>Collection of functions describing the capabilities of the Backend. </p>\n\
<dl class=\"section author\"><dt>Author</dt><dd>Matthias Kretz <a href=\"#\" onclick=\"location.href=\'#!/url=./cpp_ref/mai/\'+\'lto:\'+\'kre\'+\'tz\'+\'@kd\'+\'e.\'+\'org\'; return false;\">kretz<span style=\"display: none;\">.nosp@m.</span>@kde<span style=\"display: none;\">.nosp@m.</span>.org</a> </dd></dl>\n\
</div><table class=\"memberdecls\">\n\
<tr class=\"heading\"><td colspan=\"2\"><h2 class=\"groupheader\"><a name=\"nested-classes\"></a>\n\
Classes</h2></td></tr>\n\
<tr class=\"memitem:\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">class &#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_phonon_1_1_backend_capabilities_1_1_notifier.html\">Notifier</a></td></tr>\n\
<tr class=\"memdesc:\"><td class=\"mdescLeft\">&#160;</td><td class=\"mdescRight\">Notifications about backend capabilities.  <a href=\"#!/url=./cpp_ref/class_phonon_1_1_backend_capabilities_1_1_notifier.html#details\">More...</a><br></td></tr>\n\
<tr class=\"separator:\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
</table><table class=\"memberdecls\">\n\
<tr class=\"heading\"><td colspan=\"2\"><h2 class=\"groupheader\"><a name=\"func-members\"></a>\n\
Functions</h2></td></tr>\n\
<tr class=\"memitem:a84723110f9fd5e1956bb585bbdd267fa\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/phonon__export_8h.html#a7d358a82612f42a3a3389f13b3a1472d\">PHONON_EXPORT</a> <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_phonon_1_1_backend_capabilities_1_1_notifier.html\">Notifier</a> *&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/namespace_phonon_1_1_backend_capabilities.html#a84723110f9fd5e1956bb585bbdd267fa\">notifier</a> ()</td></tr>\n\
<tr class=\"memdesc:a84723110f9fd5e1956bb585bbdd267fa\"><td class=\"mdescLeft\">&#160;</td><td class=\"mdescRight\">Use this function to get a <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html\">QObject</a> pointer to connect to one of the <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_phonon_1_1_backend_capabilities_1_1_notifier.html\" title=\"Notifications about backend capabilities. \">Notifier</a> signals.  <a href=\"namespace_phonon_1_1_backend_capabilities.html#a84723110f9fd5e1956bb585bbdd267fa\">More...</a><br></td></tr>\n\
<tr class=\"separator:a84723110f9fd5e1956bb585bbdd267fa\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a1408af5994b822f06ddd8229ee6f552b\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/phonon__export_8h.html#a7d358a82612f42a3a3389f13b3a1472d\">PHONON_EXPORT</a> <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_string_list.html\">QStringList</a>&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/namespace_phonon_1_1_backend_capabilities.html#a1408af5994b822f06ddd8229ee6f552b\">availableMimeTypes</a> ()</td></tr>\n\
<tr class=\"memdesc:a1408af5994b822f06ddd8229ee6f552b\"><td class=\"mdescLeft\">&#160;</td><td class=\"mdescRight\">Returns a list of mime types that the Backend can decode.  <a href=\"namespace_phonon_1_1_backend_capabilities.html#a1408af5994b822f06ddd8229ee6f552b\">More...</a><br></td></tr>\n\
<tr class=\"separator:a1408af5994b822f06ddd8229ee6f552b\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a00322470a30f4349a80cc89de93db21f\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/phonon__export_8h.html#a7d358a82612f42a3a3389f13b3a1472d\">PHONON_EXPORT</a> bool&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/namespace_phonon_1_1_backend_capabilities.html#a00322470a30f4349a80cc89de93db21f\">isMimeTypeAvailable</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_string.html\">QString</a> &amp;mimeType)</td></tr>\n\
<tr class=\"memdesc:a00322470a30f4349a80cc89de93db21f\"><td class=\"mdescLeft\">&#160;</td><td class=\"mdescRight\">Often all you want to know is whether one given MIME type can be decoded by the backend.  <a href=\"namespace_phonon_1_1_backend_capabilities.html#a00322470a30f4349a80cc89de93db21f\">More...</a><br></td></tr>\n\
<tr class=\"separator:a00322470a30f4349a80cc89de93db21f\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a4783f1dfc908e62f7640b8ad0722d74c\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/phonon__export_8h.html#a7d358a82612f42a3a3389f13b3a1472d\">PHONON_EXPORT</a> <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_list.html\">QList</a>&lt; <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/namespace_phonon.html#a8f6ea808c0ccaa9c8f495d01574d8b28\">AudioOutputDevice</a> &gt;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/namespace_phonon_1_1_backend_capabilities.html#a4783f1dfc908e62f7640b8ad0722d74c\">availableAudioOutputDevices</a> ()</td></tr>\n\
<tr class=\"memdesc:a4783f1dfc908e62f7640b8ad0722d74c\"><td class=\"mdescLeft\">&#160;</td><td class=\"mdescRight\">Returns the audio output devices the backend supports.  <a href=\"namespace_phonon_1_1_backend_capabilities.html#a4783f1dfc908e62f7640b8ad0722d74c\">More...</a><br></td></tr>\n\
<tr class=\"separator:a4783f1dfc908e62f7640b8ad0722d74c\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a8b464c68c70aeabccaa83a48315a8eaa\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/phonon__export_8h.html#a7d358a82612f42a3a3389f13b3a1472d\">PHONON_EXPORT</a> <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_list.html\">QList</a>&lt; <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/namespace_phonon.html#a1e1cbd441f59d67fb1cb906c07a2490c\">AudioCaptureDevice</a> &gt;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/namespace_phonon_1_1_backend_capabilities.html#a8b464c68c70aeabccaa83a48315a8eaa\">availableAudioCaptureDevices</a> ()</td></tr>\n\
<tr class=\"memdesc:a8b464c68c70aeabccaa83a48315a8eaa\"><td class=\"mdescLeft\">&#160;</td><td class=\"mdescRight\">Returns the audio capture devices the backend supports.  <a href=\"namespace_phonon_1_1_backend_capabilities.html#a8b464c68c70aeabccaa83a48315a8eaa\">More...</a><br></td></tr>\n\
<tr class=\"separator:a8b464c68c70aeabccaa83a48315a8eaa\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a0092522cf9ded156a63531a44f0aa72f\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/phonon__export_8h.html#a7d358a82612f42a3a3389f13b3a1472d\">PHONON_EXPORT</a> <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_list.html\">QList</a>&lt; <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/namespace_phonon.html#a395500a14ead8d9b5b82367c0e4f52fe\">EffectDescription</a> &gt;&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/namespace_phonon_1_1_backend_capabilities.html#a0092522cf9ded156a63531a44f0aa72f\">availableAudioEffects</a> ()</td></tr>\n\
<tr class=\"memdesc:a0092522cf9ded156a63531a44f0aa72f\"><td class=\"mdescLeft\">&#160;</td><td class=\"mdescRight\">Returns the video output devices the backend supports.  <a href=\"namespace_phonon_1_1_backend_capabilities.html#a0092522cf9ded156a63531a44f0aa72f\">More...</a><br></td></tr>\n\
<tr class=\"separator:a0092522cf9ded156a63531a44f0aa72f\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
</table>\n\
<h2 class=\"groupheader\">Function Documentation</h2>\n\
<a class=\"anchor\" id=\"a84723110f9fd5e1956bb585bbdd267fa\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/phonon__export_8h.html#a7d358a82612f42a3a3389f13b3a1472d\">PHONON_EXPORT</a> <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_phonon_1_1_backend_capabilities_1_1_notifier.html\">Notifier</a>* Phonon::BackendCapabilities::notifier </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Use this function to get a <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html\">QObject</a> pointer to connect to one of the <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_phonon_1_1_backend_capabilities_1_1_notifier.html\" title=\"Notifications about backend capabilities. \">Notifier</a> signals. </p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>a pointer to a <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html\">QObject</a>.</dd></dl>\n\
<p>To connect to the signal do the following: </p><div class=\"fragment\"><div class=\"line\"><a class=\"code\" href=\"#!/url=./cpp_ref/class_q_object.html#a36adcf1b3cc7e17b84d884d99b5ad748\">QObject::connect</a>(<a class=\"code\" href=\"#!/url=./cpp_ref/namespace_phonon_1_1_backend_capabilities.html#a84723110f9fd5e1956bb585bbdd267fa\">BackendCapabilities::notifier</a>(), <a class=\"code\" href=\"#!/url=./cpp_ref/qobjectdefs_8h.html#a655037e5154bbbf5c75d419b9d90a156\">SIGNAL</a>(capabilitiesChanged()), ...</div>\n\
</div><!-- fragment --><dl class=\"section see\"><dt>See also</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_phonon_1_1_backend_capabilities_1_1_notifier.html#aa4ec221238cb8b4c80929a8115ac5a98\" title=\"This signal is emitted if the capabilities have changed. \">Notifier::capabilitiesChanged()</a> </dd>\n\
<dd>\n\
<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_phonon_1_1_backend_capabilities_1_1_notifier.html#aae03a67c4e646bc674c311998aec8a31\" title=\"This signal is emitted when audio output devices were plugged or unplugged. \">Notifier::availableAudioOutputDevicesChanged()</a> </dd>\n\
<dd>\n\
<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_phonon_1_1_backend_capabilities_1_1_notifier.html#a510820151208911ef40f6495357de153\" title=\"This signal is emitted when audio capture devices were plugged or unplugged. \">Notifier::availableAudioCaptureDevicesChanged()</a> </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a1408af5994b822f06ddd8229ee6f552b\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/phonon__export_8h.html#a7d358a82612f42a3a3389f13b3a1472d\">PHONON_EXPORT</a> <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_string_list.html\">QStringList</a> Phonon::BackendCapabilities::availableMimeTypes </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Returns a list of mime types that the Backend can decode. </p>\n\
<dl class=\"section see\"><dt>See also</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/namespace_phonon_1_1_backend_capabilities.html#a00322470a30f4349a80cc89de93db21f\" title=\"Often all you want to know is whether one given MIME type can be decoded by the backend. \">isMimeTypeAvailable()</a> </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a00322470a30f4349a80cc89de93db21f\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/phonon__export_8h.html#a7d358a82612f42a3a3389f13b3a1472d\">PHONON_EXPORT</a> bool Phonon::BackendCapabilities::isMimeTypeAvailable </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_string.html\">QString</a> &amp;&#160;</td>\n\
          <td class=\"paramname\"><em>mimeType</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Often all you want to know is whether one given MIME type can be decoded by the backend. </p>\n\
<p>Use this method in favor of <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/namespace_phonon_1_1_backend_capabilities.html#a1408af5994b822f06ddd8229ee6f552b\" title=\"Returns a list of mime types that the Backend can decode. \">availableMimeTypes()</a> as it can give you a negative answer without having a backend loaded.</p>\n\
<dl class=\"section see\"><dt>See also</dt><dd><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/namespace_phonon_1_1_backend_capabilities.html#a1408af5994b822f06ddd8229ee6f552b\" title=\"Returns a list of mime types that the Backend can decode. \">availableMimeTypes()</a>; </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a4783f1dfc908e62f7640b8ad0722d74c\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/phonon__export_8h.html#a7d358a82612f42a3a3389f13b3a1472d\">PHONON_EXPORT</a> <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_list.html\">QList</a>&lt;<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/namespace_phonon.html#a8f6ea808c0ccaa9c8f495d01574d8b28\">AudioOutputDevice</a>&gt; Phonon::BackendCapabilities::availableAudioOutputDevices </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Returns the audio output devices the backend supports. </p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>A list of AudioOutputDevice objects that give a name and description for every supported audio output device. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a8b464c68c70aeabccaa83a48315a8eaa\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/phonon__export_8h.html#a7d358a82612f42a3a3389f13b3a1472d\">PHONON_EXPORT</a> <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_list.html\">QList</a>&lt;<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/namespace_phonon.html#a1e1cbd441f59d67fb1cb906c07a2490c\">AudioCaptureDevice</a>&gt; Phonon::BackendCapabilities::availableAudioCaptureDevices </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Returns the audio capture devices the backend supports. </p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>A list of AudioCaptureDevice objects that give a name and description for every supported audio capture device. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a0092522cf9ded156a63531a44f0aa72f\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/phonon__export_8h.html#a7d358a82612f42a3a3389f13b3a1472d\">PHONON_EXPORT</a> <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_list.html\">QList</a>&lt;<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/namespace_phonon.html#a395500a14ead8d9b5b82367c0e4f52fe\">EffectDescription</a>&gt; Phonon::BackendCapabilities::availableAudioEffects </td>\n\
          <td>(</td>\n\
          <td class=\"paramname\"></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Returns the video output devices the backend supports. </p>\n\
<dl class=\"section return\"><dt>Returns</dt><dd>A list of VideoOutputDevice objects that give a name and description for every supported video output device. Returns the video capture devices the backend supports.</dd>\n\
<dd>\n\
A list of VideoCaptureDevice objects that give a name and description for every supported video capture device. Returns the visualization effects the backend supports.</dd>\n\
<dd>\n\
A list of VisualizationEffect objects that give a name and description for every supported visualization effect. Returns descriptions for the audio effects the backend supports.</dd>\n\
<dd>\n\
A list of AudioEffectDescription objects that give a name and description for every supported audio effect. </dd></dl>\n\
\n\
</div>\n\
</div>\n\
</div><!-- contents -->\n\
</div><!-- doc-content -->\n\
          <div class=\"footer-block\"><a href=\"../html/ac.cmtdialog.htm\" class=\"comments-anchor\" target=\"_blank\"><span class=\"comments-link\">Please send us your comment about this page</span></a></div></div>\n\
   </div></body>\n\
</html>\n\
";