var topic = "<!-- saved from url=(0024)http://docs.autodesk.com -->\n\
<html>\n\
   <head><script src=\"../scripts/yepnope.1.5.4-min.js\" type=\"text/javascript\"></script><script src=\"../scripts/lib/jquery-1.11.1.min.js\" type=\"text/javascript\"></script><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"><meta name=\"product\" content=\"MOBPRO\"><meta name=\"release\" content=\"2018\"><meta name=\"book\" content=\"GeneralUser\"><meta name=\"created\" content=\"2017-09-08\"><meta name=\"topicid\" content=\"GUID-02FA7DD3-6C7A-4C6A-B7BC-824765AE1CB2\"><meta name=\"topic-type\" content=\"concept\">\n\
      <title>QtGui/qfiledialog.h Source File</title>\n\
   \n\
\n\
</head>\n\
   <body height=\"100%\"><div class=\"body_content\" id=\"body-content\"><link rel=\"stylesheet\" type=\"text/css\" href=\"cpp_ref/navtree.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"cpp_ref/doxygen.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"cpp_ref/tabs.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"style/adsk.cpm.css\"><script language=\"javascript\">var index = \'index.html\';</script><script>$(document).ready(function() { yepnope.injectJs(\"./scripts/ac_common.js\"); });</script><script type=\"text/javascript\">\n\
var tocSystemNeedsToBeLoaded = typeof(cpp_ref_adsk_ref_toc) == \'undefined\';\n\
var weAreIn21 = $(\'div#main.view-active\').length;\n\
var tocPrefix = \'\';\n\
if (weAreIn21)\n\
{ tocPrefix = \'cpp_ref/\'; }\n\
function cpp_ref_initializeToc(forceTrigger) {\n\
    cpp_ref_adsk_ref_toc.initResizable();\n\
    cpp_ref_adsk_ref_toc.initNavTree(\'qfiledialog_8h_source.html\', tocPrefix);\n\
    dQuery(document).trigger(\'toc_initialized\');\n\
}\n\
if (tocSystemNeedsToBeLoaded)\n\
{\n\
	yepnope([{\n\
	load:[tocPrefix + \'json3.min.js\', tocPrefix + \'jquery.js\', tocPrefix + \'ref-toc-controller.js\', tocPrefix + \'dynsections.js\'],\n\
	complete: function() {\n\
	  if (typeof(dQuery) == \'undefined\')\n\
	  {\n\
	    dQuery = jQuery.noConflict(true);\n\
	  }\n\
	  else { jQuery.noConflict(true); }\n\
	  $(document).ready(cpp_ref_initializeToc);\n\
	}\n\
 	}])\n\
}\n\
if (!weAreIn21) { // if in AKN...\n\
$(window).load( function() {\n\
    setTimeout( function() {\n\
        var content = $(\'body > div\').not(\'#body-content\');     // take any divs under body that are not id=body-content\n\
        content.each( function() { \n\
            $(this).css( { \'padding-left\': $(this).css(\'margin-left\') } );       // and if they have any padding-left already, move it to margin-left.\n\
        } );\n\
        var width = cpp_ref_adsk_ref_toc.readFromStorage(\'width\');\n\
        content.css({marginLeft:parseInt(width)+6+\"px\"});\n\
    }, 100);\n\
} ); \n\
}\n\
</script><script>$(\"div#WidgetFloaterPanels,link[href*=\'microsofttranslator.com\'],script[src*=\'microsofttranslator.com\'],script[src*=\'bing.com\']\").remove();</script><script type=\'text/javascript\'>$(\"div#navigation,div#breadcrumbs,div#banner\").attr(\"translate\",\"no\"); var mtLocation = ((location && location.href && location.href.indexOf(\'https\') == 0)?\'https://ssl.microsofttranslator.com\':\'http://www.microsofttranslator.com\')+\'/ajax/v3/WidgetV3.ashx?ctf=True&ui=true&settings=Manual&from=en&hidelanguages=\'; yepnope.injectJs(mtLocation, function() {}, { charset:\'utf-8\', type:\'text/javascript\' } );</script><script>\n\
 if (!tocSystemNeedsToBeLoaded) { cpp_ref_initializeToc(); }\n\
 </script><!-- begin MT -->\n\
            \n\
            <div id=\'MicrosoftTranslatorWidget\' class=\'Dark\' style=\'float:right;z-index:100;color:white;background-color:#bbbbbb;height:58px;overflow:hidden\'></div>\n\
      <div>\n\
         <div class=\"head\">\n\
            <h1>QtGui/qfiledialog.h Source File</h1>\n\
         </div>\n\
\n\
    <div id=\"top\"><!-- Generated by Doxygen 1.8.10 -->\n\
  <div id=\"navrow1\" class=\"tabs\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./cpp_ref/index.html\"><span>Main&#160;Page</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/pages.html\"><span>Topics</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/modules.html\"><span>Modules</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/namespaces.html\"><span>Namespaces</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/annotated.html\"><span>Classes</span></a></li>\n\
      <li class=\"current\"><a href=\"#!/url=./cpp_ref/files.html\"><span>Files</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/examples.html\"><span>Examples</span></a></li>\n\
    </ul>\n\
  </div>\n\
  <div id=\"navrow2\" class=\"tabs2\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./cpp_ref/files.html\"><span>File&#160;List</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/globals.html\"><span>File&#160;Members</span></a></li>\n\
    </ul>\n\
  </div>\n\
</div><!-- top -->\n\
<div id=\"side-nav\" class=\"ui-resizable side-nav-resizable\">\n\
  <div id=\"nav-tree\">\n\
    <div id=\"nav-tree-contents\">\n\
      <div id=\"nav-sync\" class=\"sync\"></div>\n\
    </div>\n\
  </div>\n\
  <div id=\"splitbar\" style=\"-moz-user-select:none;\" class=\"ui-resizable-handle\">\n\
  </div>\n\
</div>\n\
\n\
<div id=\"doc-content\">\n\
<div class=\"header\">\n\
  <div class=\"headertitle\">\n\
<div class=\"title\">qfiledialog.h</div>  </div>\n\
</div><!--header-->\n\
<div class=\"contents\">\n\
<a href=\"#!/url=./cpp_ref/qfiledialog_8h.html\">Go to the documentation of this file.</a><div class=\"fragment\"><div class=\"line\"><a name=\"l00001\"></a><span class=\"lineno\">    1</span>&#160;<span class=\"comment\">/****************************************************************************</span></div>\n\
<div class=\"line\"><a name=\"l00002\"></a><span class=\"lineno\">    2</span>&#160;<span class=\"comment\">**</span></div>\n\
<div class=\"line\"><a name=\"l00003\"></a><span class=\"lineno\">    3</span>&#160;<span class=\"comment\">** Copyright (C) 2014 Digia Plc and/or its subsidiary(-ies).</span></div>\n\
<div class=\"line\"><a name=\"l00004\"></a><span class=\"lineno\">    4</span>&#160;<span class=\"comment\">** Contact: http://www.qt-project.org/legal</span></div>\n\
<div class=\"line\"><a name=\"l00005\"></a><span class=\"lineno\">    5</span>&#160;<span class=\"comment\">**</span></div>\n\
<div class=\"line\"><a name=\"l00006\"></a><span class=\"lineno\">    6</span>&#160;<span class=\"comment\">** This file is part of the QtGui module of the Qt Toolkit.</span></div>\n\
<div class=\"line\"><a name=\"l00007\"></a><span class=\"lineno\">    7</span>&#160;<span class=\"comment\">**</span></div>\n\
<div class=\"line\"><a name=\"l00008\"></a><span class=\"lineno\">    8</span>&#160;<span class=\"comment\">** $QT_BEGIN_LICENSE:LGPL$</span></div>\n\
<div class=\"line\"><a name=\"l00009\"></a><span class=\"lineno\">    9</span>&#160;<span class=\"comment\">** Commercial License Usage</span></div>\n\
<div class=\"line\"><a name=\"l00010\"></a><span class=\"lineno\">   10</span>&#160;<span class=\"comment\">** Licensees holding valid commercial Qt licenses may use this file in</span></div>\n\
<div class=\"line\"><a name=\"l00011\"></a><span class=\"lineno\">   11</span>&#160;<span class=\"comment\">** accordance with the commercial license agreement provided with the</span></div>\n\
<div class=\"line\"><a name=\"l00012\"></a><span class=\"lineno\">   12</span>&#160;<span class=\"comment\">** Software or, alternatively, in accordance with the terms contained in</span></div>\n\
<div class=\"line\"><a name=\"l00013\"></a><span class=\"lineno\">   13</span>&#160;<span class=\"comment\">** a written agreement between you and Digia.  For licensing terms and</span></div>\n\
<div class=\"line\"><a name=\"l00014\"></a><span class=\"lineno\">   14</span>&#160;<span class=\"comment\">** conditions see http://qt.digia.com/licensing.  For further information</span></div>\n\
<div class=\"line\"><a name=\"l00015\"></a><span class=\"lineno\">   15</span>&#160;<span class=\"comment\">** use the contact form at http://qt.digia.com/contact-us.</span></div>\n\
<div class=\"line\"><a name=\"l00016\"></a><span class=\"lineno\">   16</span>&#160;<span class=\"comment\">**</span></div>\n\
<div class=\"line\"><a name=\"l00017\"></a><span class=\"lineno\">   17</span>&#160;<span class=\"comment\">** GNU Lesser General Public License Usage</span></div>\n\
<div class=\"line\"><a name=\"l00018\"></a><span class=\"lineno\">   18</span>&#160;<span class=\"comment\">** Alternatively, this file may be used under the terms of the GNU Lesser</span></div>\n\
<div class=\"line\"><a name=\"l00019\"></a><span class=\"lineno\">   19</span>&#160;<span class=\"comment\">** General Public License version 2.1 as published by the Free Software</span></div>\n\
<div class=\"line\"><a name=\"l00020\"></a><span class=\"lineno\">   20</span>&#160;<span class=\"comment\">** Foundation and appearing in the file LICENSE.LGPL included in the</span></div>\n\
<div class=\"line\"><a name=\"l00021\"></a><span class=\"lineno\">   21</span>&#160;<span class=\"comment\">** packaging of this file.  Please review the following information to</span></div>\n\
<div class=\"line\"><a name=\"l00022\"></a><span class=\"lineno\">   22</span>&#160;<span class=\"comment\">** ensure the GNU Lesser General Public License version 2.1 requirements</span></div>\n\
<div class=\"line\"><a name=\"l00023\"></a><span class=\"lineno\">   23</span>&#160;<span class=\"comment\">** will be met: http://www.gnu.org/licenses/old-licenses/lgpl-2.1.html.</span></div>\n\
<div class=\"line\"><a name=\"l00024\"></a><span class=\"lineno\">   24</span>&#160;<span class=\"comment\">**</span></div>\n\
<div class=\"line\"><a name=\"l00025\"></a><span class=\"lineno\">   25</span>&#160;<span class=\"comment\">** In addition, as a special exception, Digia gives you certain additional</span></div>\n\
<div class=\"line\"><a name=\"l00026\"></a><span class=\"lineno\">   26</span>&#160;<span class=\"comment\">** rights.  These rights are described in the Digia Qt LGPL Exception</span></div>\n\
<div class=\"line\"><a name=\"l00027\"></a><span class=\"lineno\">   27</span>&#160;<span class=\"comment\">** version 1.1, included in the file LGPL_EXCEPTION.txt in this package.</span></div>\n\
<div class=\"line\"><a name=\"l00028\"></a><span class=\"lineno\">   28</span>&#160;<span class=\"comment\">**</span></div>\n\
<div class=\"line\"><a name=\"l00029\"></a><span class=\"lineno\">   29</span>&#160;<span class=\"comment\">** GNU General Public License Usage</span></div>\n\
<div class=\"line\"><a name=\"l00030\"></a><span class=\"lineno\">   30</span>&#160;<span class=\"comment\">** Alternatively, this file may be used under the terms of the GNU</span></div>\n\
<div class=\"line\"><a name=\"l00031\"></a><span class=\"lineno\">   31</span>&#160;<span class=\"comment\">** General Public License version 3.0 as published by the Free Software</span></div>\n\
<div class=\"line\"><a name=\"l00032\"></a><span class=\"lineno\">   32</span>&#160;<span class=\"comment\">** Foundation and appearing in the file LICENSE.GPL included in the</span></div>\n\
<div class=\"line\"><a name=\"l00033\"></a><span class=\"lineno\">   33</span>&#160;<span class=\"comment\">** packaging of this file.  Please review the following information to</span></div>\n\
<div class=\"line\"><a name=\"l00034\"></a><span class=\"lineno\">   34</span>&#160;<span class=\"comment\">** ensure the GNU General Public License version 3.0 requirements will be</span></div>\n\
<div class=\"line\"><a name=\"l00035\"></a><span class=\"lineno\">   35</span>&#160;<span class=\"comment\">** met: http://www.gnu.org/copyleft/gpl.html.</span></div>\n\
<div class=\"line\"><a name=\"l00036\"></a><span class=\"lineno\">   36</span>&#160;<span class=\"comment\">**</span></div>\n\
<div class=\"line\"><a name=\"l00037\"></a><span class=\"lineno\">   37</span>&#160;<span class=\"comment\">**</span></div>\n\
<div class=\"line\"><a name=\"l00038\"></a><span class=\"lineno\">   38</span>&#160;<span class=\"comment\">** $QT_END_LICENSE$</span></div>\n\
<div class=\"line\"><a name=\"l00039\"></a><span class=\"lineno\">   39</span>&#160;<span class=\"comment\">**</span></div>\n\
<div class=\"line\"><a name=\"l00040\"></a><span class=\"lineno\">   40</span>&#160;<span class=\"comment\">****************************************************************************/</span></div>\n\
<div class=\"line\"><a name=\"l00041\"></a><span class=\"lineno\">   41</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00042\"></a><span class=\"lineno\">   42</span>&#160;<span class=\"preprocessor\">#ifndef QFILEDIALOG_H</span></div>\n\
<div class=\"line\"><a name=\"l00043\"></a><span class=\"lineno\">   43</span>&#160;<span class=\"preprocessor\">#define QFILEDIALOG_H</span></div>\n\
<div class=\"line\"><a name=\"l00044\"></a><span class=\"lineno\">   44</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00045\"></a><span class=\"lineno\">   45</span>&#160;<span class=\"preprocessor\">#include &lt;<a class=\"code\" href=\"#!/url=./cpp_ref/qdir_8h.html\">QtCore/qdir.h</a>&gt;</span></div>\n\
<div class=\"line\"><a name=\"l00046\"></a><span class=\"lineno\">   46</span>&#160;<span class=\"preprocessor\">#include &lt;<a class=\"code\" href=\"#!/url=./cpp_ref/qstring_8h.html\">QtCore/qstring.h</a>&gt;</span></div>\n\
<div class=\"line\"><a name=\"l00047\"></a><span class=\"lineno\">   47</span>&#160;<span class=\"preprocessor\">#include &lt;<a class=\"code\" href=\"#!/url=./cpp_ref/qdialog_8h.html\">QtGui/qdialog.h</a>&gt;</span></div>\n\
<div class=\"line\"><a name=\"l00048\"></a><span class=\"lineno\">   48</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00049\"></a><span class=\"lineno\">   49</span>&#160;<a class=\"code\" href=\"#!/url=./cpp_ref/qglobal_8h.html#a22466069bc24124bf4d749ca253f5e2b\">QT_BEGIN_HEADER</a></div>\n\
<div class=\"line\"><a name=\"l00050\"></a><span class=\"lineno\">   50</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00051\"></a><span class=\"lineno\">   51</span>&#160;<a class=\"code\" href=\"#!/url=./cpp_ref/qglobal_8h.html#ae7344b820974b9f9f7cfedd5808bd3a0\">QT_BEGIN_NAMESPACE</a></div>\n\
<div class=\"line\"><a name=\"l00052\"></a><span class=\"lineno\">   52</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00053\"></a><span class=\"lineno\">   53</span>&#160;QT_MODULE(Gui)</div>\n\
<div class=\"line\"><a name=\"l00054\"></a><span class=\"lineno\">   54</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00055\"></a><span class=\"lineno\">   55</span>&#160;<span class=\"preprocessor\">#ifndef QT_NO_FILEDIALOG</span></div>\n\
<div class=\"line\"><a name=\"l00056\"></a><span class=\"lineno\">   56</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00057\"></a><span class=\"lineno\">   57</span>&#160;<span class=\"keyword\">class </span><a class=\"code\" href=\"#!/url=./cpp_ref/class_q_model_index.html\">QModelIndex</a>;</div>\n\
<div class=\"line\"><a name=\"l00058\"></a><span class=\"lineno\">   58</span>&#160;<span class=\"keyword\">class </span><a class=\"code\" href=\"#!/url=./cpp_ref/class_q_item_selection.html\">QItemSelection</a>;</div>\n\
<div class=\"line\"><a name=\"l00059\"></a><span class=\"lineno\">   59</span>&#160;<span class=\"keyword\">struct </span>QFileDialogArgs;</div>\n\
<div class=\"line\"><a name=\"l00060\"></a><span class=\"lineno\">   60</span>&#160;<span class=\"keyword\">class </span><a class=\"code\" href=\"#!/url=./cpp_ref/class_q_file_icon_provider.html\">QFileIconProvider</a>;</div>\n\
<div class=\"line\"><a name=\"l00061\"></a><span class=\"lineno\">   61</span>&#160;<span class=\"keyword\">class </span>QFileDialogPrivate;</div>\n\
<div class=\"line\"><a name=\"l00062\"></a><span class=\"lineno\">   62</span>&#160;<span class=\"keyword\">class </span><a class=\"code\" href=\"#!/url=./cpp_ref/class_q_abstract_item_delegate.html\">QAbstractItemDelegate</a>;</div>\n\
<div class=\"line\"><a name=\"l00063\"></a><span class=\"lineno\">   63</span>&#160;<span class=\"keyword\">class </span><a class=\"code\" href=\"#!/url=./cpp_ref/class_q_abstract_proxy_model.html\">QAbstractProxyModel</a>;</div>\n\
<div class=\"line\"><a name=\"l00064\"></a><span class=\"lineno\">   64</span>&#160;<span class=\"keyword\">class </span><a class=\"code\" href=\"#!/url=./cpp_ref/class_q_url.html\">QUrl</a>;</div>\n\
<div class=\"line\"><a name=\"l00065\"></a><span class=\"lineno\">   65</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00066\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./cpp_ref/class_q_file_dialog.html\">   66</a></span>&#160;<span class=\"keyword\">class </span>Q_GUI_EXPORT <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_file_dialog.html\">QFileDialog</a> : <span class=\"keyword\">public</span> <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_dialog.html\">QDialog</a></div>\n\
<div class=\"line\"><a name=\"l00067\"></a><span class=\"lineno\">   67</span>&#160;{</div>\n\
<div class=\"line\"><a name=\"l00068\"></a><span class=\"lineno\">   68</span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/qobjectdefs_8h.html#a28faeb36eee7fb0a64b8081fbab41bcd\">Q_OBJECT</a></div>\n\
<div class=\"line\"><a name=\"l00069\"></a><span class=\"lineno\">   69</span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/qobjectdefs_8h.html#aa4549a75d930e1cb89ab4bdb3f3b2764\">Q_ENUMS</a>(<a class=\"code\" href=\"#!/url=./cpp_ref/class_q_file_dialog.html#a38f29c0359c0338cfd228a7f47175ca9\">ViewMode</a> <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_file_dialog.html#a031770da453a180e21dcbef5cf5aeab6\">FileMode</a> <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_file_dialog.html#a574932d9443c3e4d018b22e1fb61c105\">AcceptMode</a> <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_file_dialog.html#a0e65ad13124ea2cb5e255b640464e35f\">Option</a>)</div>\n\
<div class=\"line\"><a name=\"l00070\"></a><span class=\"lineno\">   70</span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/qobjectdefs_8h.html#a6273b01e702c66df3d67824c8e4eda17\">Q_FLAGS</a>(Options)</div>\n\
<div class=\"line\"><a name=\"l00071\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./cpp_ref/class_q_file_dialog.html#a16e77a8a77b3425f2a323c8bd950c7cf\">   71</a></span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/qobjectdefs_8h.html#ab957fa68243bef7be233542a266be4be\">Q_PROPERTY</a>(<a class=\"code\" href=\"#!/url=./cpp_ref/class_q_file_dialog.html#a38f29c0359c0338cfd228a7f47175ca9\">ViewMode</a> viewMode READ viewMode WRITE setViewMode)</div>\n\
<div class=\"line\"><a name=\"l00072\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./cpp_ref/class_q_file_dialog.html#a3af6607d446eabf3c97e88254de61c4e\">   72</a></span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/qobjectdefs_8h.html#ab957fa68243bef7be233542a266be4be\">Q_PROPERTY</a>(<a class=\"code\" href=\"#!/url=./cpp_ref/class_q_file_dialog.html#a031770da453a180e21dcbef5cf5aeab6\">FileMode</a> fileMode READ fileMode WRITE setFileMode)</div>\n\
<div class=\"line\"><a name=\"l00073\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./cpp_ref/class_q_file_dialog.html#a828351c07edc19cf351d8fd525b17255\">   73</a></span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/qobjectdefs_8h.html#ab957fa68243bef7be233542a266be4be\">Q_PROPERTY</a>(<a class=\"code\" href=\"#!/url=./cpp_ref/class_q_file_dialog.html#a574932d9443c3e4d018b22e1fb61c105\">AcceptMode</a> acceptMode READ acceptMode WRITE setAcceptMode)</div>\n\
<div class=\"line\"><a name=\"l00074\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./cpp_ref/class_q_file_dialog.html#a2661d851ae26aa3aeaac87ebf74c779f\">   74</a></span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/qobjectdefs_8h.html#ab957fa68243bef7be233542a266be4be\">Q_PROPERTY</a>(<span class=\"keywordtype\">bool</span> readOnly READ isReadOnly WRITE setReadOnly DESIGNABLE false)</div>\n\
<div class=\"line\"><a name=\"l00075\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./cpp_ref/class_q_file_dialog.html#a6cb22e08072f17c24b0f681695211c5a\">   75</a></span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/qobjectdefs_8h.html#ab957fa68243bef7be233542a266be4be\">Q_PROPERTY</a>(<span class=\"keywordtype\">bool</span> resolveSymlinks READ resolveSymlinks WRITE setResolveSymlinks DESIGNABLE false)</div>\n\
<div class=\"line\"><a name=\"l00076\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./cpp_ref/class_q_file_dialog.html#a40a58d8e4378ddb9adfe6b4d81bb887b\">   76</a></span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/qobjectdefs_8h.html#ab957fa68243bef7be233542a266be4be\">Q_PROPERTY</a>(<span class=\"keywordtype\">bool</span> confirmOverwrite READ confirmOverwrite WRITE setConfirmOverwrite DESIGNABLE false)</div>\n\
<div class=\"line\"><a name=\"l00077\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./cpp_ref/class_q_file_dialog.html#ade5f35fcba0eb5be2d0f96d13137ab77\">   77</a></span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/qobjectdefs_8h.html#ab957fa68243bef7be233542a266be4be\">Q_PROPERTY</a>(<a class=\"code\" href=\"#!/url=./cpp_ref/class_q_string.html\">QString</a> defaultSuffix READ defaultSuffix WRITE setDefaultSuffix)</div>\n\
<div class=\"line\"><a name=\"l00078\"></a><span class=\"lineno\">   78</span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/qobjectdefs_8h.html#ab957fa68243bef7be233542a266be4be\">Q_PROPERTY</a>(<span class=\"keywordtype\">bool</span> nameFilterDetailsVisible READ isNameFilterDetailsVisible</div>\n\
<div class=\"line\"><a name=\"l00079\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./cpp_ref/class_q_file_dialog.html#a50e9c3c6ac29439656ec9c48117c6544\">   79</a></span>&#160;               WRITE setNameFilterDetailsVisible DESIGNABLE false)</div>\n\
<div class=\"line\"><a name=\"l00080\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./cpp_ref/class_q_file_dialog.html#a4d92a8f5b7d984c1b4ed7b54f347b7a9\">   80</a></span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/qobjectdefs_8h.html#ab957fa68243bef7be233542a266be4be\">Q_PROPERTY</a>(Options options READ options WRITE setOptions)</div>\n\
<div class=\"line\"><a name=\"l00081\"></a><span class=\"lineno\">   81</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00082\"></a><span class=\"lineno\">   82</span>&#160;public:</div>\n\
<div class=\"line\"><a name=\"l00083\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./cpp_ref/class_q_file_dialog.html#a38f29c0359c0338cfd228a7f47175ca9\">   83</a></span>&#160;    enum <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_file_dialog.html#a38f29c0359c0338cfd228a7f47175ca9\">ViewMode</a> { Detail, List };</div>\n\
<div class=\"line\"><a name=\"l00084\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./cpp_ref/class_q_file_dialog.html#a031770da453a180e21dcbef5cf5aeab6\">   84</a></span>&#160;    <span class=\"keyword\">enum</span> <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_file_dialog.html#a031770da453a180e21dcbef5cf5aeab6\">FileMode</a> { AnyFile, ExistingFile, Directory, ExistingFiles, DirectoryOnly };</div>\n\
<div class=\"line\"><a name=\"l00085\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./cpp_ref/class_q_file_dialog.html#a574932d9443c3e4d018b22e1fb61c105af18eed7516a0ab334a2fa9bb1c3bb153\">   85</a></span>&#160;    <span class=\"keyword\">enum</span> <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_file_dialog.html#a574932d9443c3e4d018b22e1fb61c105\">AcceptMode</a> { AcceptOpen, AcceptSave };</div>\n\
<div class=\"line\"><a name=\"l00086\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./cpp_ref/class_q_file_dialog.html#a87d5de54e2b58104be88a72305a60733aac99a1fc7e3ce6e81f55ed902fd6995e\">   86</a></span>&#160;    <span class=\"keyword\">enum</span> <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_file_dialog.html#a87d5de54e2b58104be88a72305a60733\">DialogLabel</a> { LookIn, FileName, FileType, Accept, Reject };</div>\n\
<div class=\"line\"><a name=\"l00087\"></a><span class=\"lineno\">   87</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00088\"></a><span class=\"lineno\">   88</span>&#160;    <span class=\"comment\">// ### Rename to FileDialogOption and FileDialogOptions for Qt 5.0</span></div>\n\
<div class=\"line\"><a name=\"l00089\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./cpp_ref/class_q_file_dialog.html#a0e65ad13124ea2cb5e255b640464e35f\">   89</a></span>&#160;    <span class=\"keyword\">enum</span> <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_file_dialog.html#a0e65ad13124ea2cb5e255b640464e35f\">Option</a></div>\n\
<div class=\"line\"><a name=\"l00090\"></a><span class=\"lineno\">   90</span>&#160;    {</div>\n\
<div class=\"line\"><a name=\"l00091\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./cpp_ref/class_q_file_dialog.html#a0e65ad13124ea2cb5e255b640464e35fa4f57c05bed377c8779ac4c6f6a76f256\">   91</a></span>&#160;        ShowDirsOnly                = 0x00000001,</div>\n\
<div class=\"line\"><a name=\"l00092\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./cpp_ref/class_q_file_dialog.html#a0e65ad13124ea2cb5e255b640464e35fafe68b00d1919d0d788d93bf1be5c8dc9\">   92</a></span>&#160;        DontResolveSymlinks         = 0x00000002,</div>\n\
<div class=\"line\"><a name=\"l00093\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./cpp_ref/class_q_file_dialog.html#a0e65ad13124ea2cb5e255b640464e35fa4d76a7ba000443c71cdad07161f7aafc\">   93</a></span>&#160;        DontConfirmOverwrite        = 0x00000004,</div>\n\
<div class=\"line\"><a name=\"l00094\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./cpp_ref/class_q_file_dialog.html#a0e65ad13124ea2cb5e255b640464e35faa70b92d6e3d5998d4ebe699d519bd1e4\">   94</a></span>&#160;        DontUseSheet                = 0x00000008,</div>\n\
<div class=\"line\"><a name=\"l00095\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./cpp_ref/class_q_file_dialog.html#a0e65ad13124ea2cb5e255b640464e35faaa61ef2a9ef06028aee11e4cff48fb74\">   95</a></span>&#160;        DontUseNativeDialog         = 0x00000010,</div>\n\
<div class=\"line\"><a name=\"l00096\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./cpp_ref/class_q_file_dialog.html#a0e65ad13124ea2cb5e255b640464e35faf1a03d8a79e3c6ef4a82a0ba3fec6e7a\">   96</a></span>&#160;        ReadOnly                    = 0x00000020,</div>\n\
<div class=\"line\"><a name=\"l00097\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./cpp_ref/class_q_file_dialog.html#a0e65ad13124ea2cb5e255b640464e35facf881c08041ee804e2271e5f40c67256\">   97</a></span>&#160;        HideNameFilterDetails       = 0x00000040,</div>\n\
<div class=\"line\"><a name=\"l00098\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./cpp_ref/class_q_file_dialog.html#a0e65ad13124ea2cb5e255b640464e35facc99cce5b1875e39750a74a4ea2ed0ab\">   98</a></span>&#160;        DontUseCustomDirectoryIcons = 0x00000080</div>\n\
<div class=\"line\"><a name=\"l00099\"></a><span class=\"lineno\">   99</span>&#160;    };</div>\n\
<div class=\"line\"><a name=\"l00100\"></a><span class=\"lineno\">  100</span>&#160;    Q_DECLARE_FLAGS(Options, Option)</div>\n\
<div class=\"line\"><a name=\"l00101\"></a><span class=\"lineno\">  101</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00102\"></a><span class=\"lineno\">  102</span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_file_dialog.html\">QFileDialog</a>(<a class=\"code\" href=\"#!/url=./cpp_ref/class_q_widget.html\">QWidget</a> *parent, <a class=\"code\" href=\"#!/url=./cpp_ref/namespace_qt.html\">Qt</a>::WindowFlags <a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a691492ec0bd6383f91200e49f6ae40ed\">f</a>);</div>\n\
<div class=\"line\"><a name=\"l00103\"></a><span class=\"lineno\">  103</span>&#160;    explicit <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_file_dialog.html\">QFileDialog</a>(<a class=\"code\" href=\"#!/url=./cpp_ref/class_q_widget.html\">QWidget</a> *parent = 0,</div>\n\
<div class=\"line\"><a name=\"l00104\"></a><span class=\"lineno\">  104</span>&#160;                         const <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_string.html\">QString</a> &amp;caption = <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_string.html\">QString</a>(),</div>\n\
<div class=\"line\"><a name=\"l00105\"></a><span class=\"lineno\">  105</span>&#160;                         const QString &amp;directory = QString(),</div>\n\
<div class=\"line\"><a name=\"l00106\"></a><span class=\"lineno\">  106</span>&#160;                         const QString &amp;<a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a8bed50656d87c3eeed9d8f5e539c6b3e\">filter</a> = QString());</div>\n\
<div class=\"line\"><a name=\"l00107\"></a><span class=\"lineno\">  107</span>&#160;    ~<a class=\"code\" href=\"#!/url=./cpp_ref/class_q_file_dialog.html\">QFileDialog</a>();</div>\n\
<div class=\"line\"><a name=\"l00108\"></a><span class=\"lineno\">  108</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00109\"></a><span class=\"lineno\">  109</span>&#160;    <span class=\"keywordtype\">void</span> setDirectory(const QString &amp;directory);</div>\n\
<div class=\"line\"><a name=\"l00110\"></a><span class=\"lineno\">  110</span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/image_8h.html#a00d24c7231be28dbaf71f5408f30e44c\">inline</a> <span class=\"keywordtype\">void</span> setDirectory(const <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_dir.html\">QDir</a> &amp;directory);</div>\n\
<div class=\"line\"><a name=\"l00111\"></a><span class=\"lineno\">  111</span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_dir.html\">QDir</a> directory() const;</div>\n\
<div class=\"line\"><a name=\"l00112\"></a><span class=\"lineno\">  112</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00113\"></a><span class=\"lineno\">  113</span>&#160;    <span class=\"keywordtype\">void</span> selectFile(const QString &amp;filename);</div>\n\
<div class=\"line\"><a name=\"l00114\"></a><span class=\"lineno\">  114</span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_string_list.html\">QStringList</a> selectedFiles() const;</div>\n\
<div class=\"line\"><a name=\"l00115\"></a><span class=\"lineno\">  115</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00116\"></a><span class=\"lineno\">  116</span>&#160;<span class=\"preprocessor\">#ifdef QT_DEPRECATED</span></div>\n\
<div class=\"line\"><a name=\"l00117\"></a><span class=\"lineno\">  117</span>&#160;    QT_DEPRECATED <span class=\"keywordtype\">void</span> setFilter(<span class=\"keyword\">const</span> QString &amp;<a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a8bed50656d87c3eeed9d8f5e539c6b3e\">filter</a>);</div>\n\
<div class=\"line\"><a name=\"l00118\"></a><span class=\"lineno\">  118</span>&#160;    QT_DEPRECATED <span class=\"keywordtype\">void</span> setFilters(<span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_string_list.html\">QStringList</a> &amp;filters);</div>\n\
<div class=\"line\"><a name=\"l00119\"></a><span class=\"lineno\">  119</span>&#160;    QT_DEPRECATED <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_string_list.html\">QStringList</a> filters() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00120\"></a><span class=\"lineno\">  120</span>&#160;    QT_DEPRECATED <span class=\"keywordtype\">void</span> selectFilter(<span class=\"keyword\">const</span> QString &amp;<a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a8bed50656d87c3eeed9d8f5e539c6b3e\">filter</a>);</div>\n\
<div class=\"line\"><a name=\"l00121\"></a><span class=\"lineno\">  121</span>&#160;    QT_DEPRECATED QString selectedFilter() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00122\"></a><span class=\"lineno\">  122</span>&#160;<span class=\"preprocessor\">#endif</span></div>\n\
<div class=\"line\"><a name=\"l00123\"></a><span class=\"lineno\">  123</span>&#160;    <span class=\"keywordtype\">void</span> setNameFilterDetailsVisible(<span class=\"keywordtype\">bool</span> enabled);</div>\n\
<div class=\"line\"><a name=\"l00124\"></a><span class=\"lineno\">  124</span>&#160;    <span class=\"keywordtype\">bool</span> isNameFilterDetailsVisible() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00125\"></a><span class=\"lineno\">  125</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00126\"></a><span class=\"lineno\">  126</span>&#160;    <span class=\"keywordtype\">void</span> setNameFilter(<span class=\"keyword\">const</span> QString &amp;<a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a8bed50656d87c3eeed9d8f5e539c6b3e\">filter</a>);</div>\n\
<div class=\"line\"><a name=\"l00127\"></a><span class=\"lineno\">  127</span>&#160;    <span class=\"keywordtype\">void</span> setNameFilters(<span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_string_list.html\">QStringList</a> &amp;filters);</div>\n\
<div class=\"line\"><a name=\"l00128\"></a><span class=\"lineno\">  128</span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_string_list.html\">QStringList</a> nameFilters() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00129\"></a><span class=\"lineno\">  129</span>&#160;    <span class=\"keywordtype\">void</span> selectNameFilter(<span class=\"keyword\">const</span> QString &amp;<a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a8bed50656d87c3eeed9d8f5e539c6b3e\">filter</a>);</div>\n\
<div class=\"line\"><a name=\"l00130\"></a><span class=\"lineno\">  130</span>&#160;    QString selectedNameFilter() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00131\"></a><span class=\"lineno\">  131</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00132\"></a><span class=\"lineno\">  132</span>&#160;    QDir::Filters <a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a8bed50656d87c3eeed9d8f5e539c6b3e\">filter</a>() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00133\"></a><span class=\"lineno\">  133</span>&#160;    <span class=\"keywordtype\">void</span> setFilter(QDir::Filters filters);</div>\n\
<div class=\"line\"><a name=\"l00134\"></a><span class=\"lineno\">  134</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00135\"></a><span class=\"lineno\">  135</span>&#160;    <span class=\"keywordtype\">void</span> setViewMode(ViewMode <a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a1e71d9c196e4683cc06c4b54d53f7ef5\">mode</a>);</div>\n\
<div class=\"line\"><a name=\"l00136\"></a><span class=\"lineno\">  136</span>&#160;    ViewMode viewMode() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00137\"></a><span class=\"lineno\">  137</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00138\"></a><span class=\"lineno\">  138</span>&#160;    <span class=\"keywordtype\">void</span> setFileMode(FileMode <a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a1e71d9c196e4683cc06c4b54d53f7ef5\">mode</a>);</div>\n\
<div class=\"line\"><a name=\"l00139\"></a><span class=\"lineno\">  139</span>&#160;    FileMode fileMode() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00140\"></a><span class=\"lineno\">  140</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00141\"></a><span class=\"lineno\">  141</span>&#160;    <span class=\"keywordtype\">void</span> setAcceptMode(AcceptMode <a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a1e71d9c196e4683cc06c4b54d53f7ef5\">mode</a>);</div>\n\
<div class=\"line\"><a name=\"l00142\"></a><span class=\"lineno\">  142</span>&#160;    AcceptMode acceptMode() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00143\"></a><span class=\"lineno\">  143</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00144\"></a><span class=\"lineno\">  144</span>&#160;    <span class=\"keywordtype\">void</span> setReadOnly(<span class=\"keywordtype\">bool</span> enabled);</div>\n\
<div class=\"line\"><a name=\"l00145\"></a><span class=\"lineno\">  145</span>&#160;    <span class=\"keywordtype\">bool</span> isReadOnly() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00146\"></a><span class=\"lineno\">  146</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00147\"></a><span class=\"lineno\">  147</span>&#160;    <span class=\"keywordtype\">void</span> setResolveSymlinks(<span class=\"keywordtype\">bool</span> enabled);</div>\n\
<div class=\"line\"><a name=\"l00148\"></a><span class=\"lineno\">  148</span>&#160;    <span class=\"keywordtype\">bool</span> resolveSymlinks() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00149\"></a><span class=\"lineno\">  149</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00150\"></a><span class=\"lineno\">  150</span>&#160;    <span class=\"keywordtype\">void</span> setSidebarUrls(<span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_list.html\">QList&lt;QUrl&gt;</a> &amp;urls);</div>\n\
<div class=\"line\"><a name=\"l00151\"></a><span class=\"lineno\">  151</span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_list.html\">QList&lt;QUrl&gt;</a> sidebarUrls() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00152\"></a><span class=\"lineno\">  152</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00153\"></a><span class=\"lineno\">  153</span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_byte_array.html\">QByteArray</a> saveState() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00154\"></a><span class=\"lineno\">  154</span>&#160;    <span class=\"keywordtype\">bool</span> restoreState(<span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_byte_array.html\">QByteArray</a> &amp;state);</div>\n\
<div class=\"line\"><a name=\"l00155\"></a><span class=\"lineno\">  155</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00156\"></a><span class=\"lineno\">  156</span>&#160;    <span class=\"keywordtype\">void</span> setConfirmOverwrite(<span class=\"keywordtype\">bool</span> enabled);</div>\n\
<div class=\"line\"><a name=\"l00157\"></a><span class=\"lineno\">  157</span>&#160;    <span class=\"keywordtype\">bool</span> confirmOverwrite() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00158\"></a><span class=\"lineno\">  158</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00159\"></a><span class=\"lineno\">  159</span>&#160;    <span class=\"keywordtype\">void</span> setDefaultSuffix(<span class=\"keyword\">const</span> QString &amp;suffix);</div>\n\
<div class=\"line\"><a name=\"l00160\"></a><span class=\"lineno\">  160</span>&#160;    QString defaultSuffix() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00161\"></a><span class=\"lineno\">  161</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00162\"></a><span class=\"lineno\">  162</span>&#160;    <span class=\"keywordtype\">void</span> setHistory(<span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_string_list.html\">QStringList</a> &amp;paths);</div>\n\
<div class=\"line\"><a name=\"l00163\"></a><span class=\"lineno\">  163</span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_string_list.html\">QStringList</a> history() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00164\"></a><span class=\"lineno\">  164</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00165\"></a><span class=\"lineno\">  165</span>&#160;    <span class=\"keywordtype\">void</span> setItemDelegate(<a class=\"code\" href=\"#!/url=./cpp_ref/class_q_abstract_item_delegate.html\">QAbstractItemDelegate</a> *delegate);</div>\n\
<div class=\"line\"><a name=\"l00166\"></a><span class=\"lineno\">  166</span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_abstract_item_delegate.html\">QAbstractItemDelegate</a> *itemDelegate() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00167\"></a><span class=\"lineno\">  167</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00168\"></a><span class=\"lineno\">  168</span>&#160;    <span class=\"keywordtype\">void</span> setIconProvider(<a class=\"code\" href=\"#!/url=./cpp_ref/class_q_file_icon_provider.html\">QFileIconProvider</a> *provider);</div>\n\
<div class=\"line\"><a name=\"l00169\"></a><span class=\"lineno\">  169</span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_file_icon_provider.html\">QFileIconProvider</a> *iconProvider() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00170\"></a><span class=\"lineno\">  170</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00171\"></a><span class=\"lineno\">  171</span>&#160;    <span class=\"keywordtype\">void</span> setLabelText(DialogLabel label, <span class=\"keyword\">const</span> QString &amp;text);</div>\n\
<div class=\"line\"><a name=\"l00172\"></a><span class=\"lineno\">  172</span>&#160;    QString labelText(DialogLabel label) <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00173\"></a><span class=\"lineno\">  173</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00174\"></a><span class=\"lineno\">  174</span>&#160;<span class=\"preprocessor\">#ifndef QT_NO_PROXYMODEL</span></div>\n\
<div class=\"line\"><a name=\"l00175\"></a><span class=\"lineno\">  175</span>&#160;    <span class=\"keywordtype\">void</span> setProxyModel(<a class=\"code\" href=\"#!/url=./cpp_ref/class_q_abstract_proxy_model.html\">QAbstractProxyModel</a> *model);</div>\n\
<div class=\"line\"><a name=\"l00176\"></a><span class=\"lineno\">  176</span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_abstract_proxy_model.html\">QAbstractProxyModel</a> *proxyModel() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00177\"></a><span class=\"lineno\">  177</span>&#160;<span class=\"preprocessor\">#endif</span></div>\n\
<div class=\"line\"><a name=\"l00178\"></a><span class=\"lineno\">  178</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00179\"></a><span class=\"lineno\">  179</span>&#160;    <span class=\"keywordtype\">void</span> setOption(Option option, <span class=\"keywordtype\">bool</span> on = <span class=\"keyword\">true</span>);</div>\n\
<div class=\"line\"><a name=\"l00180\"></a><span class=\"lineno\">  180</span>&#160;    <span class=\"keywordtype\">bool</span> testOption(Option option) <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00181\"></a><span class=\"lineno\">  181</span>&#160;    <span class=\"keywordtype\">void</span> setOptions(Options options);</div>\n\
<div class=\"line\"><a name=\"l00182\"></a><span class=\"lineno\">  182</span>&#160;    Options options() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00183\"></a><span class=\"lineno\">  183</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00184\"></a><span class=\"lineno\">  184</span>&#160;<span class=\"preprocessor\">#ifdef Q_NO_USING_KEYWORD</span></div>\n\
<div class=\"line\"><a name=\"l00185\"></a><span class=\"lineno\">  185</span>&#160;<span class=\"preprocessor\">#ifndef Q_QDOC</span></div>\n\
<div class=\"line\"><a name=\"l00186\"></a><span class=\"lineno\">  186</span>&#160;    <span class=\"keywordtype\">void</span> <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_dialog.html#a9e8555112049fc2b4945120b3c45f8ab\">open</a>() { <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_dialog.html#a9e8555112049fc2b4945120b3c45f8ab\">QDialog::open</a>(); }</div>\n\
<div class=\"line\"><a name=\"l00187\"></a><span class=\"lineno\">  187</span>&#160;<span class=\"preprocessor\">#endif</span></div>\n\
<div class=\"line\"><a name=\"l00188\"></a><span class=\"lineno\">  188</span>&#160;<span class=\"preprocessor\">#else</span></div>\n\
<div class=\"line\"><a name=\"l00189\"></a><span class=\"lineno\">  189</span>&#160;    <span class=\"keyword\">using</span> <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_dialog.html#a9e8555112049fc2b4945120b3c45f8ab\">QDialog::open</a>;</div>\n\
<div class=\"line\"><a name=\"l00190\"></a><span class=\"lineno\">  190</span>&#160;<span class=\"preprocessor\">#endif</span></div>\n\
<div class=\"line\"><a name=\"l00191\"></a><span class=\"lineno\">  191</span>&#160;    <span class=\"keywordtype\">void</span> <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_dialog.html#a9e8555112049fc2b4945120b3c45f8ab\">open</a>(<a class=\"code\" href=\"#!/url=./cpp_ref/class_q_object.html\">QObject</a> *receiver, <span class=\"keyword\">const</span> <span class=\"keywordtype\">char</span> *<a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#aaf221c4cca848f2b307b3c10dd478d77\">member</a>);</div>\n\
<div class=\"line\"><a name=\"l00192\"></a><span class=\"lineno\">  192</span>&#160;    <span class=\"keywordtype\">void</span> <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_dialog.html#a18e44e30b31525a243960ca3928125aa\">setVisible</a>(<span class=\"keywordtype\">bool</span> visible);</div>\n\
<div class=\"line\"><a name=\"l00193\"></a><span class=\"lineno\">  193</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00194\"></a><span class=\"lineno\">  194</span>&#160;<a class=\"code\" href=\"#!/url=./cpp_ref/qobjectdefs_8h.html#ab1380971c106b108fd191602b937dc62\">Q_SIGNALS</a>:</div>\n\
<div class=\"line\"><a name=\"l00195\"></a><span class=\"lineno\">  195</span>&#160;    <span class=\"keywordtype\">void</span> fileSelected(<span class=\"keyword\">const</span> QString &amp;file);</div>\n\
<div class=\"line\"><a name=\"l00196\"></a><span class=\"lineno\">  196</span>&#160;    <span class=\"keywordtype\">void</span> filesSelected(<span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_string_list.html\">QStringList</a> &amp;files);</div>\n\
<div class=\"line\"><a name=\"l00197\"></a><span class=\"lineno\">  197</span>&#160;    <span class=\"keywordtype\">void</span> currentChanged(<span class=\"keyword\">const</span> QString &amp;path);</div>\n\
<div class=\"line\"><a name=\"l00198\"></a><span class=\"lineno\">  198</span>&#160;    <span class=\"keywordtype\">void</span> directoryEntered(<span class=\"keyword\">const</span> QString &amp;directory);</div>\n\
<div class=\"line\"><a name=\"l00199\"></a><span class=\"lineno\">  199</span>&#160;    <span class=\"keywordtype\">void</span> filterSelected(<span class=\"keyword\">const</span> QString &amp;<a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a8bed50656d87c3eeed9d8f5e539c6b3e\">filter</a>);</div>\n\
<div class=\"line\"><a name=\"l00200\"></a><span class=\"lineno\">  200</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00201\"></a><span class=\"lineno\">  201</span>&#160;<span class=\"keyword\">public</span>:</div>\n\
<div class=\"line\"><a name=\"l00202\"></a><span class=\"lineno\">  202</span>&#160;<span class=\"preprocessor\">#ifdef QT3_SUPPORT</span></div>\n\
<div class=\"line\"><a name=\"l00203\"></a><span class=\"lineno\">  203</span>&#160;    <span class=\"keyword\">typedef</span> FileMode Mode;</div>\n\
<div class=\"line\"><a name=\"l00204\"></a><span class=\"lineno\">  204</span>&#160;    <span class=\"keyword\">inline</span> QT3_SUPPORT <span class=\"keywordtype\">void</span> setMode(FileMode m) { setFileMode(m); }</div>\n\
<div class=\"line\"><a name=\"l00205\"></a><span class=\"lineno\">  205</span>&#160;    <span class=\"keyword\">inline</span> QT3_SUPPORT FileMode <a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a1e71d9c196e4683cc06c4b54d53f7ef5\">mode</a>()<span class=\"keyword\"> const </span>{ <span class=\"keywordflow\">return</span> fileMode(); }</div>\n\
<div class=\"line\"><a name=\"l00206\"></a><span class=\"lineno\">  206</span>&#160;    <span class=\"keyword\">inline</span> QT3_SUPPORT <span class=\"keywordtype\">void</span> setDir(<span class=\"keyword\">const</span> QString &amp;directory) { setDirectory(directory); }</div>\n\
<div class=\"line\"><a name=\"l00207\"></a><span class=\"lineno\">  207</span>&#160;    <span class=\"keyword\">inline</span> QT3_SUPPORT <span class=\"keywordtype\">void</span> setDir( <span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_dir.html\">QDir</a> &amp;directory ) { setDirectory(directory); }</div>\n\
<div class=\"line\"><a name=\"l00208\"></a><span class=\"lineno\">  208</span>&#160;    QT3_SUPPORT QString selectedFile() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00209\"></a><span class=\"lineno\">  209</span>&#160;<span class=\"preprocessor\">#endif</span></div>\n\
<div class=\"line\"><a name=\"l00210\"></a><span class=\"lineno\">  210</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00211\"></a><span class=\"lineno\">  211</span>&#160;    <span class=\"keyword\">static</span> QString getOpenFileName(<a class=\"code\" href=\"#!/url=./cpp_ref/class_q_widget.html\">QWidget</a> *parent = 0,</div>\n\
<div class=\"line\"><a name=\"l00212\"></a><span class=\"lineno\">  212</span>&#160;                                   <span class=\"keyword\">const</span> QString &amp;caption = QString(),</div>\n\
<div class=\"line\"><a name=\"l00213\"></a><span class=\"lineno\">  213</span>&#160;                                   <span class=\"keyword\">const</span> QString &amp;dir = QString(),</div>\n\
<div class=\"line\"><a name=\"l00214\"></a><span class=\"lineno\">  214</span>&#160;                                   <span class=\"keyword\">const</span> QString &amp;<a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a8bed50656d87c3eeed9d8f5e539c6b3e\">filter</a> = QString(),</div>\n\
<div class=\"line\"><a name=\"l00215\"></a><span class=\"lineno\">  215</span>&#160;                                   QString *selectedFilter = 0,</div>\n\
<div class=\"line\"><a name=\"l00216\"></a><span class=\"lineno\">  216</span>&#160;                                   Options options = 0);</div>\n\
<div class=\"line\"><a name=\"l00217\"></a><span class=\"lineno\">  217</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00218\"></a><span class=\"lineno\">  218</span>&#160;    <span class=\"keyword\">static</span> QString getSaveFileName(<a class=\"code\" href=\"#!/url=./cpp_ref/class_q_widget.html\">QWidget</a> *parent = 0,</div>\n\
<div class=\"line\"><a name=\"l00219\"></a><span class=\"lineno\">  219</span>&#160;                                   <span class=\"keyword\">const</span> QString &amp;caption = QString(),</div>\n\
<div class=\"line\"><a name=\"l00220\"></a><span class=\"lineno\">  220</span>&#160;                                   <span class=\"keyword\">const</span> QString &amp;dir = QString(),</div>\n\
<div class=\"line\"><a name=\"l00221\"></a><span class=\"lineno\">  221</span>&#160;                                   <span class=\"keyword\">const</span> QString &amp;<a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a8bed50656d87c3eeed9d8f5e539c6b3e\">filter</a> = QString(),</div>\n\
<div class=\"line\"><a name=\"l00222\"></a><span class=\"lineno\">  222</span>&#160;                                   QString *selectedFilter = 0,</div>\n\
<div class=\"line\"><a name=\"l00223\"></a><span class=\"lineno\">  223</span>&#160;                                   Options options = 0);</div>\n\
<div class=\"line\"><a name=\"l00224\"></a><span class=\"lineno\">  224</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00225\"></a><span class=\"lineno\">  225</span>&#160;    <span class=\"keyword\">static</span> QString getExistingDirectory(<a class=\"code\" href=\"#!/url=./cpp_ref/class_q_widget.html\">QWidget</a> *parent = 0,</div>\n\
<div class=\"line\"><a name=\"l00226\"></a><span class=\"lineno\">  226</span>&#160;                                        <span class=\"keyword\">const</span> QString &amp;caption = QString(),</div>\n\
<div class=\"line\"><a name=\"l00227\"></a><span class=\"lineno\">  227</span>&#160;                                        <span class=\"keyword\">const</span> QString &amp;dir = QString(),</div>\n\
<div class=\"line\"><a name=\"l00228\"></a><span class=\"lineno\">  228</span>&#160;                                        Options options = ShowDirsOnly);</div>\n\
<div class=\"line\"><a name=\"l00229\"></a><span class=\"lineno\">  229</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00230\"></a><span class=\"lineno\">  230</span>&#160;    <span class=\"keyword\">static</span> <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_string_list.html\">QStringList</a> getOpenFileNames(<a class=\"code\" href=\"#!/url=./cpp_ref/class_q_widget.html\">QWidget</a> *parent = 0,</div>\n\
<div class=\"line\"><a name=\"l00231\"></a><span class=\"lineno\">  231</span>&#160;                                        <span class=\"keyword\">const</span> QString &amp;caption = QString(),</div>\n\
<div class=\"line\"><a name=\"l00232\"></a><span class=\"lineno\">  232</span>&#160;                                        <span class=\"keyword\">const</span> QString &amp;dir = QString(),</div>\n\
<div class=\"line\"><a name=\"l00233\"></a><span class=\"lineno\">  233</span>&#160;                                        <span class=\"keyword\">const</span> QString &amp;<a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a8bed50656d87c3eeed9d8f5e539c6b3e\">filter</a> = QString(),</div>\n\
<div class=\"line\"><a name=\"l00234\"></a><span class=\"lineno\">  234</span>&#160;                                        QString *selectedFilter = 0,</div>\n\
<div class=\"line\"><a name=\"l00235\"></a><span class=\"lineno\">  235</span>&#160;                                        Options options = 0);</div>\n\
<div class=\"line\"><a name=\"l00236\"></a><span class=\"lineno\">  236</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00237\"></a><span class=\"lineno\">  237</span>&#160;<span class=\"preprocessor\">#ifdef QT3_SUPPORT</span></div>\n\
<div class=\"line\"><a name=\"l00238\"></a><span class=\"lineno\">  238</span>&#160;    <span class=\"keyword\">inline</span> <span class=\"keyword\">static</span> QString QT3_SUPPORT getOpenFileName(<span class=\"keyword\">const</span> QString &amp;dir,</div>\n\
<div class=\"line\"><a name=\"l00239\"></a><span class=\"lineno\">  239</span>&#160;                                                    <span class=\"keyword\">const</span> QString &amp;<a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a8bed50656d87c3eeed9d8f5e539c6b3e\">filter</a> = QString(),</div>\n\
<div class=\"line\"><a name=\"l00240\"></a><span class=\"lineno\">  240</span>&#160;                                                    <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_widget.html\">QWidget</a> *parent = 0, <span class=\"keyword\">const</span> <span class=\"keywordtype\">char</span>* <a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#ad977737dfc9a274a62741b9500c49a32\">name</a> = 0,</div>\n\
<div class=\"line\"><a name=\"l00241\"></a><span class=\"lineno\">  241</span>&#160;                                                    <span class=\"keyword\">const</span> QString &amp;caption = QString(),</div>\n\
<div class=\"line\"><a name=\"l00242\"></a><span class=\"lineno\">  242</span>&#160;                                                    QString *selectedFilter = 0,</div>\n\
<div class=\"line\"><a name=\"l00243\"></a><span class=\"lineno\">  243</span>&#160;                                                    <span class=\"keywordtype\">bool</span> resolveSymlinks = <span class=\"keyword\">true</span>)</div>\n\
<div class=\"line\"><a name=\"l00244\"></a><span class=\"lineno\">  244</span>&#160;        { Q_UNUSED(<a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#ad977737dfc9a274a62741b9500c49a32\">name</a>);</div>\n\
<div class=\"line\"><a name=\"l00245\"></a><span class=\"lineno\">  245</span>&#160;          <span class=\"keywordflow\">return</span> getOpenFileName(parent, caption, dir, <a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a8bed50656d87c3eeed9d8f5e539c6b3e\">filter</a>, selectedFilter,</div>\n\
<div class=\"line\"><a name=\"l00246\"></a><span class=\"lineno\">  246</span>&#160;                                 resolveSymlinks ? Option(0) : DontResolveSymlinks); }</div>\n\
<div class=\"line\"><a name=\"l00247\"></a><span class=\"lineno\">  247</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00248\"></a><span class=\"lineno\">  248</span>&#160;    <span class=\"keyword\">inline</span> <span class=\"keyword\">static</span> QString QT3_SUPPORT getSaveFileName(<span class=\"keyword\">const</span> QString &amp;dir,</div>\n\
<div class=\"line\"><a name=\"l00249\"></a><span class=\"lineno\">  249</span>&#160;                                                    <span class=\"keyword\">const</span> QString &amp;<a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a8bed50656d87c3eeed9d8f5e539c6b3e\">filter</a> = QString(),</div>\n\
<div class=\"line\"><a name=\"l00250\"></a><span class=\"lineno\">  250</span>&#160;                                                    <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_widget.html\">QWidget</a> *parent = 0, <span class=\"keyword\">const</span> <span class=\"keywordtype\">char</span>* <a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#ad977737dfc9a274a62741b9500c49a32\">name</a> = 0,</div>\n\
<div class=\"line\"><a name=\"l00251\"></a><span class=\"lineno\">  251</span>&#160;                                                    <span class=\"keyword\">const</span> QString &amp;caption = QString(),</div>\n\
<div class=\"line\"><a name=\"l00252\"></a><span class=\"lineno\">  252</span>&#160;                                                    QString *selectedFilter = 0,</div>\n\
<div class=\"line\"><a name=\"l00253\"></a><span class=\"lineno\">  253</span>&#160;                                                    <span class=\"keywordtype\">bool</span> resolveSymlinks = <span class=\"keyword\">true</span>)</div>\n\
<div class=\"line\"><a name=\"l00254\"></a><span class=\"lineno\">  254</span>&#160;        { Q_UNUSED(<a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#ad977737dfc9a274a62741b9500c49a32\">name</a>);</div>\n\
<div class=\"line\"><a name=\"l00255\"></a><span class=\"lineno\">  255</span>&#160;          <span class=\"keywordflow\">return</span> getSaveFileName(parent, caption, dir, <a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a8bed50656d87c3eeed9d8f5e539c6b3e\">filter</a>, selectedFilter,</div>\n\
<div class=\"line\"><a name=\"l00256\"></a><span class=\"lineno\">  256</span>&#160;                                 resolveSymlinks ? Option(0) : DontResolveSymlinks); }</div>\n\
<div class=\"line\"><a name=\"l00257\"></a><span class=\"lineno\">  257</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00258\"></a><span class=\"lineno\">  258</span>&#160;    <span class=\"keyword\">inline</span> <span class=\"keyword\">static</span> QString QT3_SUPPORT getExistingDirectory(<span class=\"keyword\">const</span> QString &amp;dir,</div>\n\
<div class=\"line\"><a name=\"l00259\"></a><span class=\"lineno\">  259</span>&#160;                                                         <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_widget.html\">QWidget</a> *parent = 0,</div>\n\
<div class=\"line\"><a name=\"l00260\"></a><span class=\"lineno\">  260</span>&#160;                                                         <span class=\"keyword\">const</span> <span class=\"keywordtype\">char</span>* <a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#ad977737dfc9a274a62741b9500c49a32\">name</a> = 0,</div>\n\
<div class=\"line\"><a name=\"l00261\"></a><span class=\"lineno\">  261</span>&#160;                                                         <span class=\"keyword\">const</span> QString &amp;caption = QString(),</div>\n\
<div class=\"line\"><a name=\"l00262\"></a><span class=\"lineno\">  262</span>&#160;                                                         <span class=\"keywordtype\">bool</span> dirOnly = <span class=\"keyword\">true</span>,</div>\n\
<div class=\"line\"><a name=\"l00263\"></a><span class=\"lineno\">  263</span>&#160;                                                         <span class=\"keywordtype\">bool</span> resolveSymlinks = <span class=\"keyword\">true</span>)</div>\n\
<div class=\"line\"><a name=\"l00264\"></a><span class=\"lineno\">  264</span>&#160;        { Q_UNUSED(<a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#ad977737dfc9a274a62741b9500c49a32\">name</a>);</div>\n\
<div class=\"line\"><a name=\"l00265\"></a><span class=\"lineno\">  265</span>&#160;          <span class=\"keywordflow\">return</span> getExistingDirectory(parent, caption, dir,</div>\n\
<div class=\"line\"><a name=\"l00266\"></a><span class=\"lineno\">  266</span>&#160;                                      Options((resolveSymlinks ? Option(0) : DontResolveSymlinks)</div>\n\
<div class=\"line\"><a name=\"l00267\"></a><span class=\"lineno\">  267</span>&#160;                                      | (dirOnly ? ShowDirsOnly : Option(0)))); }</div>\n\
<div class=\"line\"><a name=\"l00268\"></a><span class=\"lineno\">  268</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00269\"></a><span class=\"lineno\">  269</span>&#160;    <span class=\"keyword\">inline</span> <span class=\"keyword\">static</span> <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_string_list.html\">QStringList</a> QT3_SUPPORT getOpenFileNames(<span class=\"keyword\">const</span> QString &amp;<a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a8bed50656d87c3eeed9d8f5e539c6b3e\">filter</a>,</div>\n\
<div class=\"line\"><a name=\"l00270\"></a><span class=\"lineno\">  270</span>&#160;                                                         <span class=\"keyword\">const</span> QString &amp;dir = QString(),</div>\n\
<div class=\"line\"><a name=\"l00271\"></a><span class=\"lineno\">  271</span>&#160;                                                         <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_widget.html\">QWidget</a> *parent = 0,</div>\n\
<div class=\"line\"><a name=\"l00272\"></a><span class=\"lineno\">  272</span>&#160;                                                         <span class=\"keyword\">const</span> <span class=\"keywordtype\">char</span>* <a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#ad977737dfc9a274a62741b9500c49a32\">name</a> = 0,</div>\n\
<div class=\"line\"><a name=\"l00273\"></a><span class=\"lineno\">  273</span>&#160;                                                         <span class=\"keyword\">const</span> QString &amp;caption = QString(),</div>\n\
<div class=\"line\"><a name=\"l00274\"></a><span class=\"lineno\">  274</span>&#160;                                                         QString *selectedFilter = 0,</div>\n\
<div class=\"line\"><a name=\"l00275\"></a><span class=\"lineno\">  275</span>&#160;                                                         <span class=\"keywordtype\">bool</span> resolveSymlinks = <span class=\"keyword\">true</span>)</div>\n\
<div class=\"line\"><a name=\"l00276\"></a><span class=\"lineno\">  276</span>&#160;        { Q_UNUSED(<a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#ad977737dfc9a274a62741b9500c49a32\">name</a>);</div>\n\
<div class=\"line\"><a name=\"l00277\"></a><span class=\"lineno\">  277</span>&#160;          <span class=\"keywordflow\">return</span> getOpenFileNames(parent, caption, dir, filter, selectedFilter,</div>\n\
<div class=\"line\"><a name=\"l00278\"></a><span class=\"lineno\">  278</span>&#160;                                  resolveSymlinks ? Option(0) : DontResolveSymlinks); }</div>\n\
<div class=\"line\"><a name=\"l00279\"></a><span class=\"lineno\">  279</span>&#160;<span class=\"preprocessor\">#endif // QT3_SUPPORT</span></div>\n\
<div class=\"line\"><a name=\"l00280\"></a><span class=\"lineno\">  280</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00281\"></a><span class=\"lineno\">  281</span>&#160;<span class=\"keyword\">protected</span>:</div>\n\
<div class=\"line\"><a name=\"l00282\"></a><span class=\"lineno\">  282</span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_file_dialog.html\">QFileDialog</a>(<span class=\"keyword\">const</span> QFileDialogArgs &amp;args);</div>\n\
<div class=\"line\"><a name=\"l00283\"></a><span class=\"lineno\">  283</span>&#160;    <span class=\"keywordtype\">void</span> <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_dialog.html#abbdb7544c0f1de8836535d8f774d8382\">done</a>(<span class=\"keywordtype\">int</span> result);</div>\n\
<div class=\"line\"><a name=\"l00284\"></a><span class=\"lineno\">  284</span>&#160;    <span class=\"keywordtype\">void</span> <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_dialog.html#ab4f5a198a50e59c790933ed46970fde6\">accept</a>();</div>\n\
<div class=\"line\"><a name=\"l00285\"></a><span class=\"lineno\">  285</span>&#160;    <span class=\"keywordtype\">void</span> <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_widget.html#aa4793783fa9c7196f38e980016657043\">changeEvent</a>(<a class=\"code\" href=\"#!/url=./cpp_ref/class_q_event.html\">QEvent</a> *e);</div>\n\
<div class=\"line\"><a name=\"l00286\"></a><span class=\"lineno\">  286</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00287\"></a><span class=\"lineno\">  287</span>&#160;<span class=\"keyword\">private</span>:</div>\n\
<div class=\"line\"><a name=\"l00288\"></a><span class=\"lineno\">  288</span>&#160;    Q_DECLARE_PRIVATE(<a class=\"code\" href=\"#!/url=./cpp_ref/class_q_file_dialog.html\">QFileDialog</a>)</div>\n\
<div class=\"line\"><a name=\"l00289\"></a><span class=\"lineno\">  289</span>&#160;    Q_DISABLE_COPY(<a class=\"code\" href=\"#!/url=./cpp_ref/class_q_file_dialog.html\">QFileDialog</a>)</div>\n\
<div class=\"line\"><a name=\"l00290\"></a><span class=\"lineno\">  290</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00291\"></a><span class=\"lineno\">  291</span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/qobjectdefs_8h.html#aabd35757898fc6be704d8f574f8e875e\">Q_PRIVATE_SLOT</a>(d_func(), <span class=\"keywordtype\">void</span> _q_pathChanged(const QString &amp;))</div>\n\
<div class=\"line\"><a name=\"l00292\"></a><span class=\"lineno\">  292</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00293\"></a><span class=\"lineno\">  293</span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/qobjectdefs_8h.html#aabd35757898fc6be704d8f574f8e875e\">Q_PRIVATE_SLOT</a>(d_func(), <span class=\"keywordtype\">void</span> _q_navigateBackward())</div>\n\
<div class=\"line\"><a name=\"l00294\"></a><span class=\"lineno\">  294</span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/qobjectdefs_8h.html#aabd35757898fc6be704d8f574f8e875e\">Q_PRIVATE_SLOT</a>(d_func(), <span class=\"keywordtype\">void</span> _q_navigateForward())</div>\n\
<div class=\"line\"><a name=\"l00295\"></a><span class=\"lineno\">  295</span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/qobjectdefs_8h.html#aabd35757898fc6be704d8f574f8e875e\">Q_PRIVATE_SLOT</a>(d_func(), <span class=\"keywordtype\">void</span> _q_navigateToParent())</div>\n\
<div class=\"line\"><a name=\"l00296\"></a><span class=\"lineno\">  296</span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/qobjectdefs_8h.html#aabd35757898fc6be704d8f574f8e875e\">Q_PRIVATE_SLOT</a>(d_func(), <span class=\"keywordtype\">void</span> _q_createDirectory())</div>\n\
<div class=\"line\"><a name=\"l00297\"></a><span class=\"lineno\">  297</span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/qobjectdefs_8h.html#aabd35757898fc6be704d8f574f8e875e\">Q_PRIVATE_SLOT</a>(d_func(), <span class=\"keywordtype\">void</span> _q_showListView())</div>\n\
<div class=\"line\"><a name=\"l00298\"></a><span class=\"lineno\">  298</span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/qobjectdefs_8h.html#aabd35757898fc6be704d8f574f8e875e\">Q_PRIVATE_SLOT</a>(d_func(), <span class=\"keywordtype\">void</span> _q_showDetailsView())</div>\n\
<div class=\"line\"><a name=\"l00299\"></a><span class=\"lineno\">  299</span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/qobjectdefs_8h.html#aabd35757898fc6be704d8f574f8e875e\">Q_PRIVATE_SLOT</a>(d_func(), <span class=\"keywordtype\">void</span> _q_showContextMenu(const <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_point.html\">QPoint</a> &amp;))</div>\n\
<div class=\"line\"><a name=\"l00300\"></a><span class=\"lineno\">  300</span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/qobjectdefs_8h.html#aabd35757898fc6be704d8f574f8e875e\">Q_PRIVATE_SLOT</a>(d_func(), <span class=\"keywordtype\">void</span> _q_renameCurrent())</div>\n\
<div class=\"line\"><a name=\"l00301\"></a><span class=\"lineno\">  301</span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/qobjectdefs_8h.html#aabd35757898fc6be704d8f574f8e875e\">Q_PRIVATE_SLOT</a>(d_func(), <span class=\"keywordtype\">void</span> _q_deleteCurrent())</div>\n\
<div class=\"line\"><a name=\"l00302\"></a><span class=\"lineno\">  302</span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/qobjectdefs_8h.html#aabd35757898fc6be704d8f574f8e875e\">Q_PRIVATE_SLOT</a>(d_func(), <span class=\"keywordtype\">void</span> _q_showHidden())</div>\n\
<div class=\"line\"><a name=\"l00303\"></a><span class=\"lineno\">  303</span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/qobjectdefs_8h.html#aabd35757898fc6be704d8f574f8e875e\">Q_PRIVATE_SLOT</a>(d_func(), <span class=\"keywordtype\">void</span> _q_updateOkButton())</div>\n\
<div class=\"line\"><a name=\"l00304\"></a><span class=\"lineno\">  304</span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/qobjectdefs_8h.html#aabd35757898fc6be704d8f574f8e875e\">Q_PRIVATE_SLOT</a>(d_func(), <span class=\"keywordtype\">void</span> _q_currentChanged(const <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_model_index.html\">QModelIndex</a> &amp;<a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a6468fe3bfff24d7d939eb21863b88268\">index</a>))</div>\n\
<div class=\"line\"><a name=\"l00305\"></a><span class=\"lineno\">  305</span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/qobjectdefs_8h.html#aabd35757898fc6be704d8f574f8e875e\">Q_PRIVATE_SLOT</a>(d_func(), <span class=\"keywordtype\">void</span> _q_enterDirectory(const <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_model_index.html\">QModelIndex</a> &amp;<a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a6468fe3bfff24d7d939eb21863b88268\">index</a>))</div>\n\
<div class=\"line\"><a name=\"l00306\"></a><span class=\"lineno\">  306</span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/qobjectdefs_8h.html#aabd35757898fc6be704d8f574f8e875e\">Q_PRIVATE_SLOT</a>(d_func(), <span class=\"keywordtype\">void</span> _q_goToDirectory(const QString &amp;path))</div>\n\
<div class=\"line\"><a name=\"l00307\"></a><span class=\"lineno\">  307</span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/qobjectdefs_8h.html#aabd35757898fc6be704d8f574f8e875e\">Q_PRIVATE_SLOT</a>(d_func(), <span class=\"keywordtype\">void</span> _q_useNameFilter(<span class=\"keywordtype\">int</span> <a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a6468fe3bfff24d7d939eb21863b88268\">index</a>))</div>\n\
<div class=\"line\"><a name=\"l00308\"></a><span class=\"lineno\">  308</span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/qobjectdefs_8h.html#aabd35757898fc6be704d8f574f8e875e\">Q_PRIVATE_SLOT</a>(d_func(), <span class=\"keywordtype\">void</span> _q_selectionChanged())</div>\n\
<div class=\"line\"><a name=\"l00309\"></a><span class=\"lineno\">  309</span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/qobjectdefs_8h.html#aabd35757898fc6be704d8f574f8e875e\">Q_PRIVATE_SLOT</a>(d_func(), <span class=\"keywordtype\">void</span> _q_goToUrl(const <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_url.html\">QUrl</a> &amp;url))</div>\n\
<div class=\"line\"><a name=\"l00310\"></a><span class=\"lineno\">  310</span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/qobjectdefs_8h.html#aabd35757898fc6be704d8f574f8e875e\">Q_PRIVATE_SLOT</a>(d_func(), <span class=\"keywordtype\">void</span> _q_goHome())</div>\n\
<div class=\"line\"><a name=\"l00311\"></a><span class=\"lineno\">  311</span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/qobjectdefs_8h.html#aabd35757898fc6be704d8f574f8e875e\">Q_PRIVATE_SLOT</a>(d_func(), <span class=\"keywordtype\">void</span> _q_showHeader(<a class=\"code\" href=\"#!/url=./cpp_ref/class_q_action.html\">QAction</a> *))</div>\n\
<div class=\"line\"><a name=\"l00312\"></a><span class=\"lineno\">  312</span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/qobjectdefs_8h.html#aabd35757898fc6be704d8f574f8e875e\">Q_PRIVATE_SLOT</a>(d_func(), <span class=\"keywordtype\">void</span> _q_autoCompleteFileName(const QString &amp;text))</div>\n\
<div class=\"line\"><a name=\"l00313\"></a><span class=\"lineno\">  313</span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/qobjectdefs_8h.html#aabd35757898fc6be704d8f574f8e875e\">Q_PRIVATE_SLOT</a>(d_func(), <span class=\"keywordtype\">void</span> _q_rowsInserted(const <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_model_index.html\">QModelIndex</a> &amp; parent))</div>\n\
<div class=\"line\"><a name=\"l00314\"></a><span class=\"lineno\">  314</span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/qobjectdefs_8h.html#aabd35757898fc6be704d8f574f8e875e\">Q_PRIVATE_SLOT</a>(d_func(), <span class=\"keywordtype\">void</span> _q_fileRenamed(const QString &amp;path,</div>\n\
<div class=\"line\"><a name=\"l00315\"></a><span class=\"lineno\">  315</span>&#160;                const QString oldName, const QString newName))</div>\n\
<div class=\"line\"><a name=\"l00316\"></a><span class=\"lineno\">  316</span>&#160;<span class=\"preprocessor\">#if defined(Q_WS_MAC)</span></div>\n\
<div class=\"line\"><a name=\"l00317\"></a><span class=\"lineno\">  317</span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/qobjectdefs_8h.html#aabd35757898fc6be704d8f574f8e875e\">Q_PRIVATE_SLOT</a>(d_func(), <span class=\"keywordtype\">void</span> _q_macRunNativeAppModalPanel())</div>\n\
<div class=\"line\"><a name=\"l00318\"></a><span class=\"lineno\">  318</span>&#160;<span class=\"preprocessor\">#endif</span></div>\n\
<div class=\"line\"><a name=\"l00319\"></a><span class=\"lineno\">  319</span>&#160;};</div>\n\
<div class=\"line\"><a name=\"l00320\"></a><span class=\"lineno\">  320</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00321\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./cpp_ref/class_q_file_dialog.html#a5359e87cc980e8f7398c9f9cc1d2b5b7\">  321</a></span>&#160;<span class=\"keyword\">inline</span> <span class=\"keywordtype\">void</span> <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_file_dialog.html#a096c5c5ea1c2ea99b821751f4c46235a\">QFileDialog::setDirectory</a>(<span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_dir.html\">QDir</a> &amp;adirectory)</div>\n\
<div class=\"line\"><a name=\"l00322\"></a><span class=\"lineno\">  322</span>&#160;{ <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_file_dialog.html#a096c5c5ea1c2ea99b821751f4c46235a\">setDirectory</a>(adirectory.<a class=\"code\" href=\"#!/url=./cpp_ref/class_q_dir.html#a7d5254e83563d2de29c21ec729372edb\">absolutePath</a>()); }</div>\n\
<div class=\"line\"><a name=\"l00323\"></a><span class=\"lineno\">  323</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00324\"></a><span class=\"lineno\">  324</span>&#160;Q_DECLARE_OPERATORS_FOR_FLAGS(QFileDialog::Options)</div>\n\
<div class=\"line\"><a name=\"l00325\"></a><span class=\"lineno\">  325</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00326\"></a><span class=\"lineno\">  326</span>&#160;<span class=\"preprocessor\">#endif // QT_NO_FILEDIALOG</span></div>\n\
<div class=\"line\"><a name=\"l00327\"></a><span class=\"lineno\">  327</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00328\"></a><span class=\"lineno\">  328</span>&#160;<a class=\"code\" href=\"#!/url=./cpp_ref/qglobal_8h.html#af0211888b9fea89f8a616cd6566c521e\">QT_END_NAMESPACE</a></div>\n\
<div class=\"line\"><a name=\"l00329\"></a><span class=\"lineno\">  329</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00330\"></a><span class=\"lineno\">  330</span>&#160;<a class=\"code\" href=\"#!/url=./cpp_ref/qglobal_8h.html#ac10725c642e865540e4faaf733ff95ff\">QT_END_HEADER</a></div>\n\
<div class=\"line\"><a name=\"l00331\"></a><span class=\"lineno\">  331</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00332\"></a><span class=\"lineno\">  332</span>&#160;<span class=\"preprocessor\">#endif // QFILEDIALOG_H</span></div>\n\
<div class=\"ttc\" id=\"_g_lee_8h_html_a1e71d9c196e4683cc06c4b54d53f7ef5\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/_g_lee_8h.html#a1e71d9c196e4683cc06c4b54d53f7ef5\">mode</a></div><div class=\"ttdeci\">GLint mode</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/_g_lee_8h_source.html#l04479\">GLee.h:4479</a></div></div>\n\
<div class=\"ttc\" id=\"qdialog_8h_html\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/qdialog_8h.html\">qdialog.h</a></div></div>\n\
<div class=\"ttc\" id=\"qglobal_8h_html_af0211888b9fea89f8a616cd6566c521e\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/qglobal_8h.html#af0211888b9fea89f8a616cd6566c521e\">QT_END_NAMESPACE</a></div><div class=\"ttdeci\">#define QT_END_NAMESPACE</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qglobal_8h_source.html#l00128\">qglobal.h:128</a></div></div>\n\
<div class=\"ttc\" id=\"qobjectdefs_8h_html_ab957fa68243bef7be233542a266be4be\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/qobjectdefs_8h.html#ab957fa68243bef7be233542a266be4be\">Q_PROPERTY</a></div><div class=\"ttdeci\">#define Q_PROPERTY(text)</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qobjectdefs_8h_source.html#l00080\">qobjectdefs.h:80</a></div></div>\n\
<div class=\"ttc\" id=\"class_q_file_dialog_html_a38f29c0359c0338cfd228a7f47175ca9\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_file_dialog.html#a38f29c0359c0338cfd228a7f47175ca9\">QFileDialog::ViewMode</a></div><div class=\"ttdeci\">ViewMode</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qfiledialog_8h_source.html#l00083\">qfiledialog.h:83</a></div></div>\n\
<div class=\"ttc\" id=\"class_q_string_list_html\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_string_list.html\">QStringList</a></div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qstringlist_8h_source.html#l00066\">qstringlist.h:66</a></div></div>\n\
<div class=\"ttc\" id=\"qglobal_8h_html_a22466069bc24124bf4d749ca253f5e2b\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/qglobal_8h.html#a22466069bc24124bf4d749ca253f5e2b\">QT_BEGIN_HEADER</a></div><div class=\"ttdeci\">#define QT_BEGIN_HEADER</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qglobal_8h_source.html#l00141\">qglobal.h:141</a></div></div>\n\
<div class=\"ttc\" id=\"class_q_dialog_html_a18e44e30b31525a243960ca3928125aa\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_dialog.html#a18e44e30b31525a243960ca3928125aa\">QDialog::setVisible</a></div><div class=\"ttdeci\">void setVisible(bool visible)</div></div>\n\
<div class=\"ttc\" id=\"class_q_dir_html\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_dir.html\">QDir</a></div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qdir_8h_source.html#l00058\">qdir.h:58</a></div></div>\n\
<div class=\"ttc\" id=\"namespace_qt_html\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/namespace_qt.html\">Qt</a></div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qnamespace_8h_source.html#l00054\">qnamespace.h:54</a></div></div>\n\
<div class=\"ttc\" id=\"_g_lee_8h_html_aaf221c4cca848f2b307b3c10dd478d77\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/_g_lee_8h.html#aaf221c4cca848f2b307b3c10dd478d77\">member</a></div><div class=\"ttdeci\">GLXDrawable GLXDrawable member</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/_g_lee_8h_source.html#l10556\">GLee.h:10556</a></div></div>\n\
<div class=\"ttc\" id=\"qobjectdefs_8h_html_aabd35757898fc6be704d8f574f8e875e\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/qobjectdefs_8h.html#aabd35757898fc6be704d8f574f8e875e\">Q_PRIVATE_SLOT</a></div><div class=\"ttdeci\">#define Q_PRIVATE_SLOT(d, signature)</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qobjectdefs_8h_source.html#l00073\">qobjectdefs.h:73</a></div></div>\n\
<div class=\"ttc\" id=\"class_q_file_dialog_html_a031770da453a180e21dcbef5cf5aeab6\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_file_dialog.html#a031770da453a180e21dcbef5cf5aeab6\">QFileDialog::FileMode</a></div><div class=\"ttdeci\">FileMode</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qfiledialog_8h_source.html#l00084\">qfiledialog.h:84</a></div></div>\n\
<div class=\"ttc\" id=\"image_8h_html_a00d24c7231be28dbaf71f5408f30e44c\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/image_8h.html#a00d24c7231be28dbaf71f5408f30e44c\">inline</a></div><div class=\"ttdeci\">#define inline</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/image_8h_source.html#l02490\">image.h:2490</a></div></div>\n\
<div class=\"ttc\" id=\"qobjectdefs_8h_html_ab1380971c106b108fd191602b937dc62\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/qobjectdefs_8h.html#ab1380971c106b108fd191602b937dc62\">Q_SIGNALS</a></div><div class=\"ttdeci\">#define Q_SIGNALS</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qobjectdefs_8h_source.html#l00072\">qobjectdefs.h:72</a></div></div>\n\
<div class=\"ttc\" id=\"class_q_abstract_item_delegate_html\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_abstract_item_delegate.html\">QAbstractItemDelegate</a></div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qabstractitemdelegate_8h_source.html#l00062\">qabstractitemdelegate.h:62</a></div></div>\n\
<div class=\"ttc\" id=\"qobjectdefs_8h_html_aa4549a75d930e1cb89ab4bdb3f3b2764\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/qobjectdefs_8h.html#aa4549a75d930e1cb89ab4bdb3f3b2764\">Q_ENUMS</a></div><div class=\"ttdeci\">#define Q_ENUMS(x)</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qobjectdefs_8h_source.html#l00084\">qobjectdefs.h:84</a></div></div>\n\
<div class=\"ttc\" id=\"class_q_point_html\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_point.html\">QPoint</a></div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qpoint_8h_source.html#l00053\">qpoint.h:53</a></div></div>\n\
<div class=\"ttc\" id=\"qglobal_8h_html_ae7344b820974b9f9f7cfedd5808bd3a0\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/qglobal_8h.html#ae7344b820974b9f9f7cfedd5808bd3a0\">QT_BEGIN_NAMESPACE</a></div><div class=\"ttdeci\">#define QT_BEGIN_NAMESPACE</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qglobal_8h_source.html#l00127\">qglobal.h:127</a></div></div>\n\
<div class=\"ttc\" id=\"class_q_abstract_proxy_model_html\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_abstract_proxy_model.html\">QAbstractProxyModel</a></div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qabstractproxymodel_8h_source.html#l00058\">qabstractproxymodel.h:58</a></div></div>\n\
<div class=\"ttc\" id=\"class_q_file_dialog_html_a096c5c5ea1c2ea99b821751f4c46235a\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_file_dialog.html#a096c5c5ea1c2ea99b821751f4c46235a\">QFileDialog::setDirectory</a></div><div class=\"ttdeci\">void setDirectory(const QString &amp;directory)</div></div>\n\
<div class=\"ttc\" id=\"qdir_8h_html\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/qdir_8h.html\">qdir.h</a></div></div>\n\
<div class=\"ttc\" id=\"class_q_file_icon_provider_html\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_file_icon_provider.html\">QFileIconProvider</a></div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qfileiconprovider_8h_source.html#l00059\">qfileiconprovider.h:59</a></div></div>\n\
<div class=\"ttc\" id=\"class_q_dir_html_a7d5254e83563d2de29c21ec729372edb\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_dir.html#a7d5254e83563d2de29c21ec729372edb\">QDir::absolutePath</a></div><div class=\"ttdeci\">QString absolutePath() const </div></div>\n\
<div class=\"ttc\" id=\"class_q_file_dialog_html_a0e65ad13124ea2cb5e255b640464e35f\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_file_dialog.html#a0e65ad13124ea2cb5e255b640464e35f\">QFileDialog::Option</a></div><div class=\"ttdeci\">Option</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qfiledialog_8h_source.html#l00089\">qfiledialog.h:89</a></div></div>\n\
<div class=\"ttc\" id=\"class_q_dialog_html_abbdb7544c0f1de8836535d8f774d8382\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_dialog.html#abbdb7544c0f1de8836535d8f774d8382\">QDialog::done</a></div><div class=\"ttdeci\">virtual void done(int)</div></div>\n\
<div class=\"ttc\" id=\"class_q_dialog_html_a9e8555112049fc2b4945120b3c45f8ab\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_dialog.html#a9e8555112049fc2b4945120b3c45f8ab\">QDialog::open</a></div><div class=\"ttdeci\">void open()</div></div>\n\
<div class=\"ttc\" id=\"class_q_dialog_html_ab4f5a198a50e59c790933ed46970fde6\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_dialog.html#ab4f5a198a50e59c790933ed46970fde6\">QDialog::accept</a></div><div class=\"ttdeci\">virtual void accept()</div></div>\n\
<div class=\"ttc\" id=\"qobjectdefs_8h_html_a28faeb36eee7fb0a64b8081fbab41bcd\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/qobjectdefs_8h.html#a28faeb36eee7fb0a64b8081fbab41bcd\">Q_OBJECT</a></div><div class=\"ttdeci\">#define Q_OBJECT</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qobjectdefs_8h_source.html#l00157\">qobjectdefs.h:157</a></div></div>\n\
<div class=\"ttc\" id=\"class_q_item_selection_html\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_item_selection.html\">QItemSelection</a></div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qitemselectionmodel_8h_source.html#l00231\">qitemselectionmodel.h:231</a></div></div>\n\
<div class=\"ttc\" id=\"class_q_event_html\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_event.html\">QEvent</a></div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qcoreevent_8h_source.html#l00056\">qcoreevent.h:56</a></div></div>\n\
<div class=\"ttc\" id=\"class_q_file_dialog_html_a574932d9443c3e4d018b22e1fb61c105\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_file_dialog.html#a574932d9443c3e4d018b22e1fb61c105\">QFileDialog::AcceptMode</a></div><div class=\"ttdeci\">AcceptMode</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qfiledialog_8h_source.html#l00085\">qfiledialog.h:85</a></div></div>\n\
<div class=\"ttc\" id=\"class_q_url_html\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_url.html\">QUrl</a></div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qurl_8h_source.html#l00061\">qurl.h:61</a></div></div>\n\
<div class=\"ttc\" id=\"_g_lee_8h_html_ad977737dfc9a274a62741b9500c49a32\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/_g_lee_8h.html#ad977737dfc9a274a62741b9500c49a32\">name</a></div><div class=\"ttdeci\">GLuint const GLchar * name</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/_g_lee_8h_source.html#l01704\">GLee.h:1704</a></div></div>\n\
<div class=\"ttc\" id=\"qstring_8h_html\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/qstring_8h.html\">qstring.h</a></div></div>\n\
<div class=\"ttc\" id=\"class_q_model_index_html\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_model_index.html\">QModelIndex</a></div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qabstractitemmodel_8h_source.html#l00058\">qabstractitemmodel.h:58</a></div></div>\n\
<div class=\"ttc\" id=\"_g_lee_8h_html_a8bed50656d87c3eeed9d8f5e539c6b3e\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/_g_lee_8h.html#a8bed50656d87c3eeed9d8f5e539c6b3e\">filter</a></div><div class=\"ttdeci\">GLenum filter</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/_g_lee_8h_source.html#l03431\">GLee.h:3431</a></div></div>\n\
<div class=\"ttc\" id=\"class_q_string_html\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_string.html\">QString</a></div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qstring_8h_source.html#l00083\">qstring.h:83</a></div></div>\n\
<div class=\"ttc\" id=\"class_q_list_html\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_list.html\">QList</a></div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/backendcapabilities_8h_source.html#l00040\">backendcapabilities.h:40</a></div></div>\n\
<div class=\"ttc\" id=\"class_q_file_dialog_html_a87d5de54e2b58104be88a72305a60733\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_file_dialog.html#a87d5de54e2b58104be88a72305a60733\">QFileDialog::DialogLabel</a></div><div class=\"ttdeci\">DialogLabel</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qfiledialog_8h_source.html#l00086\">qfiledialog.h:86</a></div></div>\n\
<div class=\"ttc\" id=\"class_q_object_html\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_object.html\">QObject</a></div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qobject_8h_source.html#l00111\">qobject.h:111</a></div></div>\n\
<div class=\"ttc\" id=\"qobjectdefs_8h_html_a6273b01e702c66df3d67824c8e4eda17\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/qobjectdefs_8h.html#a6273b01e702c66df3d67824c8e4eda17\">Q_FLAGS</a></div><div class=\"ttdeci\">#define Q_FLAGS(x)</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qobjectdefs_8h_source.html#l00085\">qobjectdefs.h:85</a></div></div>\n\
<div class=\"ttc\" id=\"class_q_file_dialog_html\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_file_dialog.html\">QFileDialog</a></div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qfiledialog_8h_source.html#l00066\">qfiledialog.h:66</a></div></div>\n\
<div class=\"ttc\" id=\"class_q_action_html\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_action.html\">QAction</a></div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qaction_8h_source.html#l00064\">qaction.h:64</a></div></div>\n\
<div class=\"ttc\" id=\"class_q_dialog_html\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_dialog.html\">QDialog</a></div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qdialog_8h_source.html#l00056\">qdialog.h:56</a></div></div>\n\
<div class=\"ttc\" id=\"class_q_widget_html\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_widget.html\">QWidget</a></div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qwidget_8h_source.html#l00150\">qwidget.h:150</a></div></div>\n\
<div class=\"ttc\" id=\"qglobal_8h_html_ac10725c642e865540e4faaf733ff95ff\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/qglobal_8h.html#ac10725c642e865540e4faaf733ff95ff\">QT_END_HEADER</a></div><div class=\"ttdeci\">#define QT_END_HEADER</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qglobal_8h_source.html#l00142\">qglobal.h:142</a></div></div>\n\
<div class=\"ttc\" id=\"_g_lee_8h_html_a691492ec0bd6383f91200e49f6ae40ed\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/_g_lee_8h.html#a691492ec0bd6383f91200e49f6ae40ed\">f</a></div><div class=\"ttdeci\">GLclampf f</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/_g_lee_8h_source.html#l09303\">GLee.h:9303</a></div></div>\n\
<div class=\"ttc\" id=\"class_q_byte_array_html\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_byte_array.html\">QByteArray</a></div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qbytearray_8h_source.html#l00135\">qbytearray.h:135</a></div></div>\n\
<div class=\"ttc\" id=\"_g_lee_8h_html_a6468fe3bfff24d7d939eb21863b88268\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/_g_lee_8h.html#a6468fe3bfff24d7d939eb21863b88268\">index</a></div><div class=\"ttdeci\">GLuint index</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/_g_lee_8h_source.html#l01704\">GLee.h:1704</a></div></div>\n\
<div class=\"ttc\" id=\"class_q_widget_html_aa4793783fa9c7196f38e980016657043\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_widget.html#aa4793783fa9c7196f38e980016657043\">QWidget::changeEvent</a></div><div class=\"ttdeci\">virtual void changeEvent(QEvent *)</div></div>\n\
</div><!-- fragment --></div><!-- contents -->\n\
</div><!-- doc-content -->\n\
          <div class=\"footer-block\"><a href=\"../html/ac.cmtdialog.htm\" class=\"comments-anchor\" target=\"_blank\"><span class=\"comments-link\">Please send us your comment about this page</span></a></div></div>\n\
   </div></body>\n\
</html>\n\
";