var topic = "<!-- saved from url=(0024)http://docs.autodesk.com -->\n\
<html>\n\
   <head><script src=\"../scripts/yepnope.1.5.4-min.js\" type=\"text/javascript\"></script><script src=\"../scripts/lib/jquery-1.11.1.min.js\" type=\"text/javascript\"></script><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"><meta name=\"product\" content=\"MOBPRO\"><meta name=\"release\" content=\"2018\"><meta name=\"book\" content=\"GeneralUser\"><meta name=\"created\" content=\"2017-09-08\"><meta name=\"topicid\" content=\"GUID-02FA7DD3-6C7A-4C6A-B7BC-824765AE1CB2\"><meta name=\"topic-type\" content=\"concept\">\n\
      <title>QtGui/qformlayout.h Source File</title>\n\
   \n\
\n\
</head>\n\
   <body height=\"100%\"><div class=\"body_content\" id=\"body-content\"><link rel=\"stylesheet\" type=\"text/css\" href=\"cpp_ref/navtree.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"cpp_ref/doxygen.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"cpp_ref/tabs.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"style/adsk.cpm.css\"><script language=\"javascript\">var index = \'index.html\';</script><script>$(document).ready(function() { yepnope.injectJs(\"./scripts/ac_common.js\"); });</script><script type=\"text/javascript\">\n\
var tocSystemNeedsToBeLoaded = typeof(cpp_ref_adsk_ref_toc) == \'undefined\';\n\
var weAreIn21 = $(\'div#main.view-active\').length;\n\
var tocPrefix = \'\';\n\
if (weAreIn21)\n\
{ tocPrefix = \'cpp_ref/\'; }\n\
function cpp_ref_initializeToc(forceTrigger) {\n\
    cpp_ref_adsk_ref_toc.initResizable();\n\
    cpp_ref_adsk_ref_toc.initNavTree(\'qformlayout_8h_source.html\', tocPrefix);\n\
    dQuery(document).trigger(\'toc_initialized\');\n\
}\n\
if (tocSystemNeedsToBeLoaded)\n\
{\n\
	yepnope([{\n\
	load:[tocPrefix + \'json3.min.js\', tocPrefix + \'jquery.js\', tocPrefix + \'ref-toc-controller.js\', tocPrefix + \'dynsections.js\'],\n\
	complete: function() {\n\
	  if (typeof(dQuery) == \'undefined\')\n\
	  {\n\
	    dQuery = jQuery.noConflict(true);\n\
	  }\n\
	  else { jQuery.noConflict(true); }\n\
	  $(document).ready(cpp_ref_initializeToc);\n\
	}\n\
 	}])\n\
}\n\
if (!weAreIn21) { // if in AKN...\n\
$(window).load( function() {\n\
    setTimeout( function() {\n\
        var content = $(\'body > div\').not(\'#body-content\');     // take any divs under body that are not id=body-content\n\
        content.each( function() { \n\
            $(this).css( { \'padding-left\': $(this).css(\'margin-left\') } );       // and if they have any padding-left already, move it to margin-left.\n\
        } );\n\
        var width = cpp_ref_adsk_ref_toc.readFromStorage(\'width\');\n\
        content.css({marginLeft:parseInt(width)+6+\"px\"});\n\
    }, 100);\n\
} ); \n\
}\n\
</script><script>$(\"div#WidgetFloaterPanels,link[href*=\'microsofttranslator.com\'],script[src*=\'microsofttranslator.com\'],script[src*=\'bing.com\']\").remove();</script><script type=\'text/javascript\'>$(\"div#navigation,div#breadcrumbs,div#banner\").attr(\"translate\",\"no\"); var mtLocation = ((location && location.href && location.href.indexOf(\'https\') == 0)?\'https://ssl.microsofttranslator.com\':\'http://www.microsofttranslator.com\')+\'/ajax/v3/WidgetV3.ashx?ctf=True&ui=true&settings=Manual&from=en&hidelanguages=\'; yepnope.injectJs(mtLocation, function() {}, { charset:\'utf-8\', type:\'text/javascript\' } );</script><script>\n\
 if (!tocSystemNeedsToBeLoaded) { cpp_ref_initializeToc(); }\n\
 </script><!-- begin MT -->\n\
            \n\
            <div id=\'MicrosoftTranslatorWidget\' class=\'Dark\' style=\'float:right;z-index:100;color:white;background-color:#bbbbbb;height:58px;overflow:hidden\'></div>\n\
      <div>\n\
         <div class=\"head\">\n\
            <h1>QtGui/qformlayout.h Source File</h1>\n\
         </div>\n\
\n\
    <div id=\"top\"><!-- Generated by Doxygen 1.8.10 -->\n\
  <div id=\"navrow1\" class=\"tabs\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./cpp_ref/index.html\"><span>Main&#160;Page</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/pages.html\"><span>Topics</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/modules.html\"><span>Modules</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/namespaces.html\"><span>Namespaces</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/annotated.html\"><span>Classes</span></a></li>\n\
      <li class=\"current\"><a href=\"#!/url=./cpp_ref/files.html\"><span>Files</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/examples.html\"><span>Examples</span></a></li>\n\
    </ul>\n\
  </div>\n\
  <div id=\"navrow2\" class=\"tabs2\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./cpp_ref/files.html\"><span>File&#160;List</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/globals.html\"><span>File&#160;Members</span></a></li>\n\
    </ul>\n\
  </div>\n\
</div><!-- top -->\n\
<div id=\"side-nav\" class=\"ui-resizable side-nav-resizable\">\n\
  <div id=\"nav-tree\">\n\
    <div id=\"nav-tree-contents\">\n\
      <div id=\"nav-sync\" class=\"sync\"></div>\n\
    </div>\n\
  </div>\n\
  <div id=\"splitbar\" style=\"-moz-user-select:none;\" class=\"ui-resizable-handle\">\n\
  </div>\n\
</div>\n\
\n\
<div id=\"doc-content\">\n\
<div class=\"header\">\n\
  <div class=\"headertitle\">\n\
<div class=\"title\">qformlayout.h</div>  </div>\n\
</div><!--header-->\n\
<div class=\"contents\">\n\
<a href=\"#!/url=./cpp_ref/qformlayout_8h.html\">Go to the documentation of this file.</a><div class=\"fragment\"><div class=\"line\"><a name=\"l00001\"></a><span class=\"lineno\">    1</span>&#160;<span class=\"comment\">/****************************************************************************</span></div>\n\
<div class=\"line\"><a name=\"l00002\"></a><span class=\"lineno\">    2</span>&#160;<span class=\"comment\">**</span></div>\n\
<div class=\"line\"><a name=\"l00003\"></a><span class=\"lineno\">    3</span>&#160;<span class=\"comment\">** Copyright (C) 2014 Digia Plc and/or its subsidiary(-ies).</span></div>\n\
<div class=\"line\"><a name=\"l00004\"></a><span class=\"lineno\">    4</span>&#160;<span class=\"comment\">** Contact: http://www.qt-project.org/legal</span></div>\n\
<div class=\"line\"><a name=\"l00005\"></a><span class=\"lineno\">    5</span>&#160;<span class=\"comment\">**</span></div>\n\
<div class=\"line\"><a name=\"l00006\"></a><span class=\"lineno\">    6</span>&#160;<span class=\"comment\">** This file is part of the QtGui module of the Qt Toolkit.</span></div>\n\
<div class=\"line\"><a name=\"l00007\"></a><span class=\"lineno\">    7</span>&#160;<span class=\"comment\">**</span></div>\n\
<div class=\"line\"><a name=\"l00008\"></a><span class=\"lineno\">    8</span>&#160;<span class=\"comment\">** $QT_BEGIN_LICENSE:LGPL$</span></div>\n\
<div class=\"line\"><a name=\"l00009\"></a><span class=\"lineno\">    9</span>&#160;<span class=\"comment\">** Commercial License Usage</span></div>\n\
<div class=\"line\"><a name=\"l00010\"></a><span class=\"lineno\">   10</span>&#160;<span class=\"comment\">** Licensees holding valid commercial Qt licenses may use this file in</span></div>\n\
<div class=\"line\"><a name=\"l00011\"></a><span class=\"lineno\">   11</span>&#160;<span class=\"comment\">** accordance with the commercial license agreement provided with the</span></div>\n\
<div class=\"line\"><a name=\"l00012\"></a><span class=\"lineno\">   12</span>&#160;<span class=\"comment\">** Software or, alternatively, in accordance with the terms contained in</span></div>\n\
<div class=\"line\"><a name=\"l00013\"></a><span class=\"lineno\">   13</span>&#160;<span class=\"comment\">** a written agreement between you and Digia.  For licensing terms and</span></div>\n\
<div class=\"line\"><a name=\"l00014\"></a><span class=\"lineno\">   14</span>&#160;<span class=\"comment\">** conditions see http://qt.digia.com/licensing.  For further information</span></div>\n\
<div class=\"line\"><a name=\"l00015\"></a><span class=\"lineno\">   15</span>&#160;<span class=\"comment\">** use the contact form at http://qt.digia.com/contact-us.</span></div>\n\
<div class=\"line\"><a name=\"l00016\"></a><span class=\"lineno\">   16</span>&#160;<span class=\"comment\">**</span></div>\n\
<div class=\"line\"><a name=\"l00017\"></a><span class=\"lineno\">   17</span>&#160;<span class=\"comment\">** GNU Lesser General Public License Usage</span></div>\n\
<div class=\"line\"><a name=\"l00018\"></a><span class=\"lineno\">   18</span>&#160;<span class=\"comment\">** Alternatively, this file may be used under the terms of the GNU Lesser</span></div>\n\
<div class=\"line\"><a name=\"l00019\"></a><span class=\"lineno\">   19</span>&#160;<span class=\"comment\">** General Public License version 2.1 as published by the Free Software</span></div>\n\
<div class=\"line\"><a name=\"l00020\"></a><span class=\"lineno\">   20</span>&#160;<span class=\"comment\">** Foundation and appearing in the file LICENSE.LGPL included in the</span></div>\n\
<div class=\"line\"><a name=\"l00021\"></a><span class=\"lineno\">   21</span>&#160;<span class=\"comment\">** packaging of this file.  Please review the following information to</span></div>\n\
<div class=\"line\"><a name=\"l00022\"></a><span class=\"lineno\">   22</span>&#160;<span class=\"comment\">** ensure the GNU Lesser General Public License version 2.1 requirements</span></div>\n\
<div class=\"line\"><a name=\"l00023\"></a><span class=\"lineno\">   23</span>&#160;<span class=\"comment\">** will be met: http://www.gnu.org/licenses/old-licenses/lgpl-2.1.html.</span></div>\n\
<div class=\"line\"><a name=\"l00024\"></a><span class=\"lineno\">   24</span>&#160;<span class=\"comment\">**</span></div>\n\
<div class=\"line\"><a name=\"l00025\"></a><span class=\"lineno\">   25</span>&#160;<span class=\"comment\">** In addition, as a special exception, Digia gives you certain additional</span></div>\n\
<div class=\"line\"><a name=\"l00026\"></a><span class=\"lineno\">   26</span>&#160;<span class=\"comment\">** rights.  These rights are described in the Digia Qt LGPL Exception</span></div>\n\
<div class=\"line\"><a name=\"l00027\"></a><span class=\"lineno\">   27</span>&#160;<span class=\"comment\">** version 1.1, included in the file LGPL_EXCEPTION.txt in this package.</span></div>\n\
<div class=\"line\"><a name=\"l00028\"></a><span class=\"lineno\">   28</span>&#160;<span class=\"comment\">**</span></div>\n\
<div class=\"line\"><a name=\"l00029\"></a><span class=\"lineno\">   29</span>&#160;<span class=\"comment\">** GNU General Public License Usage</span></div>\n\
<div class=\"line\"><a name=\"l00030\"></a><span class=\"lineno\">   30</span>&#160;<span class=\"comment\">** Alternatively, this file may be used under the terms of the GNU</span></div>\n\
<div class=\"line\"><a name=\"l00031\"></a><span class=\"lineno\">   31</span>&#160;<span class=\"comment\">** General Public License version 3.0 as published by the Free Software</span></div>\n\
<div class=\"line\"><a name=\"l00032\"></a><span class=\"lineno\">   32</span>&#160;<span class=\"comment\">** Foundation and appearing in the file LICENSE.GPL included in the</span></div>\n\
<div class=\"line\"><a name=\"l00033\"></a><span class=\"lineno\">   33</span>&#160;<span class=\"comment\">** packaging of this file.  Please review the following information to</span></div>\n\
<div class=\"line\"><a name=\"l00034\"></a><span class=\"lineno\">   34</span>&#160;<span class=\"comment\">** ensure the GNU General Public License version 3.0 requirements will be</span></div>\n\
<div class=\"line\"><a name=\"l00035\"></a><span class=\"lineno\">   35</span>&#160;<span class=\"comment\">** met: http://www.gnu.org/copyleft/gpl.html.</span></div>\n\
<div class=\"line\"><a name=\"l00036\"></a><span class=\"lineno\">   36</span>&#160;<span class=\"comment\">**</span></div>\n\
<div class=\"line\"><a name=\"l00037\"></a><span class=\"lineno\">   37</span>&#160;<span class=\"comment\">**</span></div>\n\
<div class=\"line\"><a name=\"l00038\"></a><span class=\"lineno\">   38</span>&#160;<span class=\"comment\">** $QT_END_LICENSE$</span></div>\n\
<div class=\"line\"><a name=\"l00039\"></a><span class=\"lineno\">   39</span>&#160;<span class=\"comment\">**</span></div>\n\
<div class=\"line\"><a name=\"l00040\"></a><span class=\"lineno\">   40</span>&#160;<span class=\"comment\">****************************************************************************/</span></div>\n\
<div class=\"line\"><a name=\"l00041\"></a><span class=\"lineno\">   41</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00042\"></a><span class=\"lineno\">   42</span>&#160;<span class=\"preprocessor\">#ifndef QFORMLAYOUT_H</span></div>\n\
<div class=\"line\"><a name=\"l00043\"></a><span class=\"lineno\">   43</span>&#160;<span class=\"preprocessor\">#define QFORMLAYOUT_H</span></div>\n\
<div class=\"line\"><a name=\"l00044\"></a><span class=\"lineno\">   44</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00045\"></a><span class=\"lineno\">   45</span>&#160;<span class=\"preprocessor\">#include &lt;QtGui/QLayout&gt;</span></div>\n\
<div class=\"line\"><a name=\"l00046\"></a><span class=\"lineno\">   46</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00047\"></a><span class=\"lineno\">   47</span>&#160;<a class=\"code\" href=\"#!/url=./cpp_ref/qglobal_8h.html#a22466069bc24124bf4d749ca253f5e2b\">QT_BEGIN_HEADER</a></div>\n\
<div class=\"line\"><a name=\"l00048\"></a><span class=\"lineno\">   48</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00049\"></a><span class=\"lineno\">   49</span>&#160;<a class=\"code\" href=\"#!/url=./cpp_ref/qglobal_8h.html#ae7344b820974b9f9f7cfedd5808bd3a0\">QT_BEGIN_NAMESPACE</a></div>\n\
<div class=\"line\"><a name=\"l00050\"></a><span class=\"lineno\">   50</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00051\"></a><span class=\"lineno\">   51</span>&#160;QT_MODULE(Gui)</div>\n\
<div class=\"line\"><a name=\"l00052\"></a><span class=\"lineno\">   52</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00053\"></a><span class=\"lineno\">   53</span>&#160;class QFormLayoutPrivate;</div>\n\
<div class=\"line\"><a name=\"l00054\"></a><span class=\"lineno\">   54</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00055\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./cpp_ref/class_q_form_layout.html\">   55</a></span>&#160;class Q_GUI_EXPORT <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_form_layout.html\">QFormLayout</a> : public <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_layout.html\">QLayout</a></div>\n\
<div class=\"line\"><a name=\"l00056\"></a><span class=\"lineno\">   56</span>&#160;{</div>\n\
<div class=\"line\"><a name=\"l00057\"></a><span class=\"lineno\">   57</span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/qobjectdefs_8h.html#a28faeb36eee7fb0a64b8081fbab41bcd\">Q_OBJECT</a></div>\n\
<div class=\"line\"><a name=\"l00058\"></a><span class=\"lineno\">   58</span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/qobjectdefs_8h.html#aa4549a75d930e1cb89ab4bdb3f3b2764\">Q_ENUMS</a>(FormStyle <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_form_layout.html#a2dc5e1507376ec802dd032e49a62296c\">FieldGrowthPolicy</a> <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_form_layout.html#ac7b6c0f379c60044f740772a175d03ae\">RowWrapPolicy</a> <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_form_layout.html#a9af2e8781b7f12c2c6c241e05473f669\">ItemRole</a>)</div>\n\
<div class=\"line\"><a name=\"l00059\"></a><span class=\"lineno\">   59</span>&#160;    Q_DECLARE_PRIVATE(<a class=\"code\" href=\"#!/url=./cpp_ref/class_q_form_layout.html\">QFormLayout</a>)</div>\n\
<div class=\"line\"><a name=\"l00060\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./cpp_ref/class_q_form_layout.html#a63e942d6561428ab7b2d8fb6467d155b\">   60</a></span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/qobjectdefs_8h.html#ab957fa68243bef7be233542a266be4be\">Q_PROPERTY</a>(<a class=\"code\" href=\"#!/url=./cpp_ref/class_q_form_layout.html#a2dc5e1507376ec802dd032e49a62296c\">FieldGrowthPolicy</a> fieldGrowthPolicy READ fieldGrowthPolicy WRITE setFieldGrowthPolicy RESET resetFieldGrowthPolicy)</div>\n\
<div class=\"line\"><a name=\"l00061\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./cpp_ref/class_q_form_layout.html#ad211edf3d46ecd9cc727eb6f1d6d5b08\">   61</a></span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/qobjectdefs_8h.html#ab957fa68243bef7be233542a266be4be\">Q_PROPERTY</a>(<a class=\"code\" href=\"#!/url=./cpp_ref/class_q_form_layout.html#ac7b6c0f379c60044f740772a175d03ae\">RowWrapPolicy</a> rowWrapPolicy READ rowWrapPolicy WRITE setRowWrapPolicy RESET resetRowWrapPolicy)</div>\n\
<div class=\"line\"><a name=\"l00062\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./cpp_ref/class_q_form_layout.html#af5abb539889625af5561c99aff2de1e8\">   62</a></span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/qobjectdefs_8h.html#ab957fa68243bef7be233542a266be4be\">Q_PROPERTY</a>(<a class=\"code\" href=\"#!/url=./cpp_ref/namespace_qt.html\">Qt</a>::Alignment labelAlignment READ labelAlignment WRITE setLabelAlignment RESET resetLabelAlignment)</div>\n\
<div class=\"line\"><a name=\"l00063\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./cpp_ref/class_q_form_layout.html#a386af539462d83b3461f0ed2c03138dc\">   63</a></span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/qobjectdefs_8h.html#ab957fa68243bef7be233542a266be4be\">Q_PROPERTY</a>(<a class=\"code\" href=\"#!/url=./cpp_ref/namespace_qt.html\">Qt</a>::Alignment formAlignment READ formAlignment WRITE setFormAlignment RESET resetFormAlignment)</div>\n\
<div class=\"line\"><a name=\"l00064\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./cpp_ref/class_q_form_layout.html#a26103bf62dc80bb1df21a096cf15fb83\">   64</a></span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/qobjectdefs_8h.html#ab957fa68243bef7be233542a266be4be\">Q_PROPERTY</a>(<span class=\"keywordtype\">int</span> horizontalSpacing READ horizontalSpacing WRITE setHorizontalSpacing)</div>\n\
<div class=\"line\"><a name=\"l00065\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./cpp_ref/class_q_form_layout.html#a5b467c6a7fff55ceaa2c95a2dce08e9f\">   65</a></span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/qobjectdefs_8h.html#ab957fa68243bef7be233542a266be4be\">Q_PROPERTY</a>(<span class=\"keywordtype\">int</span> verticalSpacing READ verticalSpacing WRITE setVerticalSpacing)</div>\n\
<div class=\"line\"><a name=\"l00066\"></a><span class=\"lineno\">   66</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00067\"></a><span class=\"lineno\">   67</span>&#160;public:</div>\n\
<div class=\"line\"><a name=\"l00068\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./cpp_ref/class_q_form_layout.html#a2dc5e1507376ec802dd032e49a62296c\">   68</a></span>&#160;    enum <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_form_layout.html#a2dc5e1507376ec802dd032e49a62296c\">FieldGrowthPolicy</a> {</div>\n\
<div class=\"line\"><a name=\"l00069\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./cpp_ref/class_q_form_layout.html#a2dc5e1507376ec802dd032e49a62296cab471ddd3f4c08043d2384f5269a59c6f\">   69</a></span>&#160;        <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_form_layout.html#a2dc5e1507376ec802dd032e49a62296cab471ddd3f4c08043d2384f5269a59c6f\">FieldsStayAtSizeHint</a>,</div>\n\
<div class=\"line\"><a name=\"l00070\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./cpp_ref/class_q_form_layout.html#a2dc5e1507376ec802dd032e49a62296ca2f39aaf8f5ea3724eb0adb79afc0ac04\">   70</a></span>&#160;        <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_form_layout.html#a2dc5e1507376ec802dd032e49a62296ca2f39aaf8f5ea3724eb0adb79afc0ac04\">ExpandingFieldsGrow</a>,</div>\n\
<div class=\"line\"><a name=\"l00071\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./cpp_ref/class_q_form_layout.html#a2dc5e1507376ec802dd032e49a62296cac8c7ede586aed561dd789d7e57f776dd\">   71</a></span>&#160;        AllNonFixedFieldsGrow</div>\n\
<div class=\"line\"><a name=\"l00072\"></a><span class=\"lineno\">   72</span>&#160;    };</div>\n\
<div class=\"line\"><a name=\"l00073\"></a><span class=\"lineno\">   73</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00074\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./cpp_ref/class_q_form_layout.html#ac7b6c0f379c60044f740772a175d03ae\">   74</a></span>&#160;    <span class=\"keyword\">enum</span> <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_form_layout.html#ac7b6c0f379c60044f740772a175d03ae\">RowWrapPolicy</a> {</div>\n\
<div class=\"line\"><a name=\"l00075\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./cpp_ref/class_q_form_layout.html#ac7b6c0f379c60044f740772a175d03aea027e3ad68325ae06921fa9b64a5bbb8e\">   75</a></span>&#160;        <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_form_layout.html#ac7b6c0f379c60044f740772a175d03aea027e3ad68325ae06921fa9b64a5bbb8e\">DontWrapRows</a>,</div>\n\
<div class=\"line\"><a name=\"l00076\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./cpp_ref/class_q_form_layout.html#ac7b6c0f379c60044f740772a175d03aea97ef8d6f8056b4328236d232ef61133d\">   76</a></span>&#160;        <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_form_layout.html#ac7b6c0f379c60044f740772a175d03aea97ef8d6f8056b4328236d232ef61133d\">WrapLongRows</a>,</div>\n\
<div class=\"line\"><a name=\"l00077\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./cpp_ref/class_q_form_layout.html#ac7b6c0f379c60044f740772a175d03aeafb9d3130c55990e353b6d00c2c3e5c00\">   77</a></span>&#160;        WrapAllRows</div>\n\
<div class=\"line\"><a name=\"l00078\"></a><span class=\"lineno\">   78</span>&#160;    };</div>\n\
<div class=\"line\"><a name=\"l00079\"></a><span class=\"lineno\">   79</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00080\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./cpp_ref/class_q_form_layout.html#a9af2e8781b7f12c2c6c241e05473f669\">   80</a></span>&#160;    <span class=\"keyword\">enum</span> <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_form_layout.html#a9af2e8781b7f12c2c6c241e05473f669\">ItemRole</a> {</div>\n\
<div class=\"line\"><a name=\"l00081\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./cpp_ref/class_q_form_layout.html#a9af2e8781b7f12c2c6c241e05473f669aebbf0557f932f3e45f6db4956a08198f\">   81</a></span>&#160;        LabelRole = 0,</div>\n\
<div class=\"line\"><a name=\"l00082\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./cpp_ref/class_q_form_layout.html#a9af2e8781b7f12c2c6c241e05473f669ac82e9d96bd1fcde48567504bd886e215\">   82</a></span>&#160;        FieldRole = 1,</div>\n\
<div class=\"line\"><a name=\"l00083\"></a><span class=\"lineno\"><a class=\"line\" href=\"#!/url=./cpp_ref/class_q_form_layout.html#a9af2e8781b7f12c2c6c241e05473f669ab98d2591362cf7bc0e20e9af013f2ab4\">   83</a></span>&#160;        SpanningRole = 2</div>\n\
<div class=\"line\"><a name=\"l00084\"></a><span class=\"lineno\">   84</span>&#160;    };</div>\n\
<div class=\"line\"><a name=\"l00085\"></a><span class=\"lineno\">   85</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00086\"></a><span class=\"lineno\">   86</span>&#160;    <span class=\"keyword\">explicit</span> <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_form_layout.html\">QFormLayout</a>(<a class=\"code\" href=\"#!/url=./cpp_ref/class_q_widget.html\">QWidget</a> *parent = 0);</div>\n\
<div class=\"line\"><a name=\"l00087\"></a><span class=\"lineno\">   87</span>&#160;    ~<a class=\"code\" href=\"#!/url=./cpp_ref/class_q_form_layout.html\">QFormLayout</a>();</div>\n\
<div class=\"line\"><a name=\"l00088\"></a><span class=\"lineno\">   88</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00089\"></a><span class=\"lineno\">   89</span>&#160;    <span class=\"keywordtype\">void</span> setFieldGrowthPolicy(FieldGrowthPolicy policy);</div>\n\
<div class=\"line\"><a name=\"l00090\"></a><span class=\"lineno\">   90</span>&#160;    FieldGrowthPolicy fieldGrowthPolicy() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00091\"></a><span class=\"lineno\">   91</span>&#160;    <span class=\"keywordtype\">void</span> setRowWrapPolicy(RowWrapPolicy policy);</div>\n\
<div class=\"line\"><a name=\"l00092\"></a><span class=\"lineno\">   92</span>&#160;    RowWrapPolicy rowWrapPolicy() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00093\"></a><span class=\"lineno\">   93</span>&#160;    <span class=\"keywordtype\">void</span> setLabelAlignment(Qt::Alignment alignment);</div>\n\
<div class=\"line\"><a name=\"l00094\"></a><span class=\"lineno\">   94</span>&#160;    Qt::Alignment labelAlignment() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00095\"></a><span class=\"lineno\">   95</span>&#160;    <span class=\"keywordtype\">void</span> setFormAlignment(Qt::Alignment alignment);</div>\n\
<div class=\"line\"><a name=\"l00096\"></a><span class=\"lineno\">   96</span>&#160;    Qt::Alignment formAlignment() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00097\"></a><span class=\"lineno\">   97</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00098\"></a><span class=\"lineno\">   98</span>&#160;    <span class=\"keywordtype\">void</span> setHorizontalSpacing(<span class=\"keywordtype\">int</span> spacing);</div>\n\
<div class=\"line\"><a name=\"l00099\"></a><span class=\"lineno\">   99</span>&#160;    <span class=\"keywordtype\">int</span> horizontalSpacing() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00100\"></a><span class=\"lineno\">  100</span>&#160;    <span class=\"keywordtype\">void</span> setVerticalSpacing(<span class=\"keywordtype\">int</span> spacing);</div>\n\
<div class=\"line\"><a name=\"l00101\"></a><span class=\"lineno\">  101</span>&#160;    <span class=\"keywordtype\">int</span> verticalSpacing() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00102\"></a><span class=\"lineno\">  102</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00103\"></a><span class=\"lineno\">  103</span>&#160;    <span class=\"keywordtype\">int</span> spacing() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00104\"></a><span class=\"lineno\">  104</span>&#160;    <span class=\"keywordtype\">void</span> setSpacing(<span class=\"keywordtype\">int</span>);</div>\n\
<div class=\"line\"><a name=\"l00105\"></a><span class=\"lineno\">  105</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00106\"></a><span class=\"lineno\">  106</span>&#160;    <span class=\"keywordtype\">void</span> addRow(<a class=\"code\" href=\"#!/url=./cpp_ref/class_q_widget.html\">QWidget</a> *label, <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_widget.html\">QWidget</a> *field);</div>\n\
<div class=\"line\"><a name=\"l00107\"></a><span class=\"lineno\">  107</span>&#160;    <span class=\"keywordtype\">void</span> addRow(<a class=\"code\" href=\"#!/url=./cpp_ref/class_q_widget.html\">QWidget</a> *label, <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_layout.html\">QLayout</a> *field);</div>\n\
<div class=\"line\"><a name=\"l00108\"></a><span class=\"lineno\">  108</span>&#160;    <span class=\"keywordtype\">void</span> addRow(<span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_string.html\">QString</a> &amp;labelText, <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_widget.html\">QWidget</a> *field);</div>\n\
<div class=\"line\"><a name=\"l00109\"></a><span class=\"lineno\">  109</span>&#160;    <span class=\"keywordtype\">void</span> addRow(<span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_string.html\">QString</a> &amp;labelText, <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_layout.html\">QLayout</a> *field);</div>\n\
<div class=\"line\"><a name=\"l00110\"></a><span class=\"lineno\">  110</span>&#160;    <span class=\"keywordtype\">void</span> addRow(<a class=\"code\" href=\"#!/url=./cpp_ref/class_q_widget.html\">QWidget</a> *widget);</div>\n\
<div class=\"line\"><a name=\"l00111\"></a><span class=\"lineno\">  111</span>&#160;    <span class=\"keywordtype\">void</span> addRow(<a class=\"code\" href=\"#!/url=./cpp_ref/class_q_layout.html\">QLayout</a> *layout);</div>\n\
<div class=\"line\"><a name=\"l00112\"></a><span class=\"lineno\">  112</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00113\"></a><span class=\"lineno\">  113</span>&#160;    <span class=\"keywordtype\">void</span> insertRow(<span class=\"keywordtype\">int</span> <a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a11b277b422822f784ee248b43eee3e1e\">row</a>, <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_widget.html\">QWidget</a> *label, <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_widget.html\">QWidget</a> *field);</div>\n\
<div class=\"line\"><a name=\"l00114\"></a><span class=\"lineno\">  114</span>&#160;    <span class=\"keywordtype\">void</span> insertRow(<span class=\"keywordtype\">int</span> <a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a11b277b422822f784ee248b43eee3e1e\">row</a>, <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_widget.html\">QWidget</a> *label, <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_layout.html\">QLayout</a> *field);</div>\n\
<div class=\"line\"><a name=\"l00115\"></a><span class=\"lineno\">  115</span>&#160;    <span class=\"keywordtype\">void</span> insertRow(<span class=\"keywordtype\">int</span> <a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a11b277b422822f784ee248b43eee3e1e\">row</a>, <span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_string.html\">QString</a> &amp;labelText, <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_widget.html\">QWidget</a> *field);</div>\n\
<div class=\"line\"><a name=\"l00116\"></a><span class=\"lineno\">  116</span>&#160;    <span class=\"keywordtype\">void</span> insertRow(<span class=\"keywordtype\">int</span> <a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a11b277b422822f784ee248b43eee3e1e\">row</a>, <span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_string.html\">QString</a> &amp;labelText, <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_layout.html\">QLayout</a> *field);</div>\n\
<div class=\"line\"><a name=\"l00117\"></a><span class=\"lineno\">  117</span>&#160;    <span class=\"keywordtype\">void</span> insertRow(<span class=\"keywordtype\">int</span> <a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a11b277b422822f784ee248b43eee3e1e\">row</a>, <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_widget.html\">QWidget</a> *widget);</div>\n\
<div class=\"line\"><a name=\"l00118\"></a><span class=\"lineno\">  118</span>&#160;    <span class=\"keywordtype\">void</span> insertRow(<span class=\"keywordtype\">int</span> <a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a11b277b422822f784ee248b43eee3e1e\">row</a>, <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_layout.html\">QLayout</a> *layout);</div>\n\
<div class=\"line\"><a name=\"l00119\"></a><span class=\"lineno\">  119</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00120\"></a><span class=\"lineno\">  120</span>&#160;    <span class=\"keywordtype\">void</span> setItem(<span class=\"keywordtype\">int</span> <a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a11b277b422822f784ee248b43eee3e1e\">row</a>, ItemRole role, <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_layout_item.html\">QLayoutItem</a> *item);</div>\n\
<div class=\"line\"><a name=\"l00121\"></a><span class=\"lineno\">  121</span>&#160;    <span class=\"keywordtype\">void</span> setWidget(<span class=\"keywordtype\">int</span> <a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a11b277b422822f784ee248b43eee3e1e\">row</a>, ItemRole role, <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_widget.html\">QWidget</a> *widget);</div>\n\
<div class=\"line\"><a name=\"l00122\"></a><span class=\"lineno\">  122</span>&#160;    <span class=\"keywordtype\">void</span> setLayout(<span class=\"keywordtype\">int</span> <a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a11b277b422822f784ee248b43eee3e1e\">row</a>, ItemRole role, <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_layout.html\">QLayout</a> *layout);</div>\n\
<div class=\"line\"><a name=\"l00123\"></a><span class=\"lineno\">  123</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00124\"></a><span class=\"lineno\">  124</span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_layout_item.html\">QLayoutItem</a> *itemAt(<span class=\"keywordtype\">int</span> <a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a11b277b422822f784ee248b43eee3e1e\">row</a>, ItemRole role) <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00125\"></a><span class=\"lineno\">  125</span>&#160;    <span class=\"keywordtype\">void</span> getItemPosition(<span class=\"keywordtype\">int</span> <a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a6468fe3bfff24d7d939eb21863b88268\">index</a>, <span class=\"keywordtype\">int</span> *rowPtr, ItemRole *rolePtr) <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00126\"></a><span class=\"lineno\">  126</span>&#160;    <span class=\"keywordtype\">void</span> getWidgetPosition(<a class=\"code\" href=\"#!/url=./cpp_ref/class_q_widget.html\">QWidget</a> *widget, <span class=\"keywordtype\">int</span> *rowPtr, ItemRole *rolePtr) <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00127\"></a><span class=\"lineno\">  127</span>&#160;    <span class=\"keywordtype\">void</span> getLayoutPosition(<a class=\"code\" href=\"#!/url=./cpp_ref/class_q_layout.html\">QLayout</a> *layout, <span class=\"keywordtype\">int</span> *rowPtr, ItemRole *rolePtr) <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00128\"></a><span class=\"lineno\">  128</span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_widget.html\">QWidget</a> *labelForField(<a class=\"code\" href=\"#!/url=./cpp_ref/class_q_widget.html\">QWidget</a> *field) <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00129\"></a><span class=\"lineno\">  129</span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_widget.html\">QWidget</a> *labelForField(<a class=\"code\" href=\"#!/url=./cpp_ref/class_q_layout.html\">QLayout</a> *field) <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00130\"></a><span class=\"lineno\">  130</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00131\"></a><span class=\"lineno\">  131</span>&#160;    <span class=\"comment\">// reimplemented from QLayout</span></div>\n\
<div class=\"line\"><a name=\"l00132\"></a><span class=\"lineno\">  132</span>&#160;    <span class=\"keywordtype\">void</span> addItem(<a class=\"code\" href=\"#!/url=./cpp_ref/class_q_layout_item.html\">QLayoutItem</a> *item);</div>\n\
<div class=\"line\"><a name=\"l00133\"></a><span class=\"lineno\">  133</span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_layout_item.html\">QLayoutItem</a> *itemAt(<span class=\"keywordtype\">int</span> <a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a6468fe3bfff24d7d939eb21863b88268\">index</a>) <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00134\"></a><span class=\"lineno\">  134</span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_layout_item.html\">QLayoutItem</a> *takeAt(<span class=\"keywordtype\">int</span> <a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a6468fe3bfff24d7d939eb21863b88268\">index</a>);</div>\n\
<div class=\"line\"><a name=\"l00135\"></a><span class=\"lineno\">  135</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00136\"></a><span class=\"lineno\">  136</span>&#160;    <span class=\"keywordtype\">void</span> setGeometry(<span class=\"keyword\">const</span> <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_rect.html\">QRect</a> &amp;rect);</div>\n\
<div class=\"line\"><a name=\"l00137\"></a><span class=\"lineno\">  137</span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_size.html\">QSize</a> minimumSize() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00138\"></a><span class=\"lineno\">  138</span>&#160;    <a class=\"code\" href=\"#!/url=./cpp_ref/class_q_size.html\">QSize</a> sizeHint() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00139\"></a><span class=\"lineno\">  139</span>&#160;    <span class=\"keywordtype\">void</span> invalidate();</div>\n\
<div class=\"line\"><a name=\"l00140\"></a><span class=\"lineno\">  140</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00141\"></a><span class=\"lineno\">  141</span>&#160;    <span class=\"keywordtype\">bool</span> hasHeightForWidth() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00142\"></a><span class=\"lineno\">  142</span>&#160;    <span class=\"keywordtype\">int</span> heightForWidth(<span class=\"keywordtype\">int</span> <a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#ac112eef468530a44b7a653ddac190a22\">width</a>) <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00143\"></a><span class=\"lineno\">  143</span>&#160;    Qt::Orientations expandingDirections() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00144\"></a><span class=\"lineno\">  144</span>&#160;    <span class=\"keywordtype\">int</span> <a class=\"code\" href=\"#!/url=./cpp_ref/_g_lee_8h.html#a9274fa62feb8371797c4c0312446e333\">count</a>() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00145\"></a><span class=\"lineno\">  145</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00146\"></a><span class=\"lineno\">  146</span>&#160;    <span class=\"keywordtype\">int</span> rowCount() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00147\"></a><span class=\"lineno\">  147</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00148\"></a><span class=\"lineno\">  148</span>&#160;<span class=\"preprocessor\">#if 0</span></div>\n\
<div class=\"line\"><a name=\"l00149\"></a><span class=\"lineno\">  149</span>&#160;    <span class=\"keywordtype\">void</span> dump() <span class=\"keyword\">const</span>;</div>\n\
<div class=\"line\"><a name=\"l00150\"></a><span class=\"lineno\">  150</span>&#160;<span class=\"preprocessor\">#endif</span></div>\n\
<div class=\"line\"><a name=\"l00151\"></a><span class=\"lineno\">  151</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00152\"></a><span class=\"lineno\">  152</span>&#160;<span class=\"keyword\">private</span>:</div>\n\
<div class=\"line\"><a name=\"l00153\"></a><span class=\"lineno\">  153</span>&#160;    <span class=\"keywordtype\">void</span> resetFieldGrowthPolicy();</div>\n\
<div class=\"line\"><a name=\"l00154\"></a><span class=\"lineno\">  154</span>&#160;    <span class=\"keywordtype\">void</span> resetRowWrapPolicy();</div>\n\
<div class=\"line\"><a name=\"l00155\"></a><span class=\"lineno\">  155</span>&#160;    <span class=\"keywordtype\">void</span> resetLabelAlignment();</div>\n\
<div class=\"line\"><a name=\"l00156\"></a><span class=\"lineno\">  156</span>&#160;    <span class=\"keywordtype\">void</span> resetFormAlignment();</div>\n\
<div class=\"line\"><a name=\"l00157\"></a><span class=\"lineno\">  157</span>&#160;};</div>\n\
<div class=\"line\"><a name=\"l00158\"></a><span class=\"lineno\">  158</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00159\"></a><span class=\"lineno\">  159</span>&#160;<a class=\"code\" href=\"#!/url=./cpp_ref/qglobal_8h.html#af0211888b9fea89f8a616cd6566c521e\">QT_END_NAMESPACE</a></div>\n\
<div class=\"line\"><a name=\"l00160\"></a><span class=\"lineno\">  160</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00161\"></a><span class=\"lineno\">  161</span>&#160;<a class=\"code\" href=\"#!/url=./cpp_ref/qglobal_8h.html#ac10725c642e865540e4faaf733ff95ff\">QT_END_HEADER</a></div>\n\
<div class=\"line\"><a name=\"l00162\"></a><span class=\"lineno\">  162</span>&#160;</div>\n\
<div class=\"line\"><a name=\"l00163\"></a><span class=\"lineno\">  163</span>&#160;<span class=\"preprocessor\">#endif</span></div>\n\
<div class=\"ttc\" id=\"class_q_form_layout_html_a2dc5e1507376ec802dd032e49a62296c\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_form_layout.html#a2dc5e1507376ec802dd032e49a62296c\">QFormLayout::FieldGrowthPolicy</a></div><div class=\"ttdeci\">FieldGrowthPolicy</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qformlayout_8h_source.html#l00068\">qformlayout.h:68</a></div></div>\n\
<div class=\"ttc\" id=\"class_q_layout_html\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_layout.html\">QLayout</a></div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qlayout_8h_source.html#l00090\">qlayout.h:90</a></div></div>\n\
<div class=\"ttc\" id=\"qglobal_8h_html_af0211888b9fea89f8a616cd6566c521e\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/qglobal_8h.html#af0211888b9fea89f8a616cd6566c521e\">QT_END_NAMESPACE</a></div><div class=\"ttdeci\">#define QT_END_NAMESPACE</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qglobal_8h_source.html#l00128\">qglobal.h:128</a></div></div>\n\
<div class=\"ttc\" id=\"qobjectdefs_8h_html_ab957fa68243bef7be233542a266be4be\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/qobjectdefs_8h.html#ab957fa68243bef7be233542a266be4be\">Q_PROPERTY</a></div><div class=\"ttdeci\">#define Q_PROPERTY(text)</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qobjectdefs_8h_source.html#l00080\">qobjectdefs.h:80</a></div></div>\n\
<div class=\"ttc\" id=\"qglobal_8h_html_a22466069bc24124bf4d749ca253f5e2b\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/qglobal_8h.html#a22466069bc24124bf4d749ca253f5e2b\">QT_BEGIN_HEADER</a></div><div class=\"ttdeci\">#define QT_BEGIN_HEADER</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qglobal_8h_source.html#l00141\">qglobal.h:141</a></div></div>\n\
<div class=\"ttc\" id=\"class_q_form_layout_html_ac7b6c0f379c60044f740772a175d03aea027e3ad68325ae06921fa9b64a5bbb8e\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_form_layout.html#ac7b6c0f379c60044f740772a175d03aea027e3ad68325ae06921fa9b64a5bbb8e\">QFormLayout::DontWrapRows</a></div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qformlayout_8h_source.html#l00075\">qformlayout.h:75</a></div></div>\n\
<div class=\"ttc\" id=\"_g_lee_8h_html_ac112eef468530a44b7a653ddac190a22\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/_g_lee_8h.html#ac112eef468530a44b7a653ddac190a22\">width</a></div><div class=\"ttdeci\">GLenum GLsizei width</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/_g_lee_8h_source.html#l00873\">GLee.h:873</a></div></div>\n\
<div class=\"ttc\" id=\"class_q_form_layout_html\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_form_layout.html\">QFormLayout</a></div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qformlayout_8h_source.html#l00055\">qformlayout.h:55</a></div></div>\n\
<div class=\"ttc\" id=\"namespace_qt_html\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/namespace_qt.html\">Qt</a></div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qnamespace_8h_source.html#l00054\">qnamespace.h:54</a></div></div>\n\
<div class=\"ttc\" id=\"class_q_form_layout_html_a2dc5e1507376ec802dd032e49a62296ca2f39aaf8f5ea3724eb0adb79afc0ac04\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_form_layout.html#a2dc5e1507376ec802dd032e49a62296ca2f39aaf8f5ea3724eb0adb79afc0ac04\">QFormLayout::ExpandingFieldsGrow</a></div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qformlayout_8h_source.html#l00070\">qformlayout.h:70</a></div></div>\n\
<div class=\"ttc\" id=\"class_q_form_layout_html_ac7b6c0f379c60044f740772a175d03ae\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_form_layout.html#ac7b6c0f379c60044f740772a175d03ae\">QFormLayout::RowWrapPolicy</a></div><div class=\"ttdeci\">RowWrapPolicy</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qformlayout_8h_source.html#l00074\">qformlayout.h:74</a></div></div>\n\
<div class=\"ttc\" id=\"qobjectdefs_8h_html_aa4549a75d930e1cb89ab4bdb3f3b2764\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/qobjectdefs_8h.html#aa4549a75d930e1cb89ab4bdb3f3b2764\">Q_ENUMS</a></div><div class=\"ttdeci\">#define Q_ENUMS(x)</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qobjectdefs_8h_source.html#l00084\">qobjectdefs.h:84</a></div></div>\n\
<div class=\"ttc\" id=\"_g_lee_8h_html_a11b277b422822f784ee248b43eee3e1e\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/_g_lee_8h.html#a11b277b422822f784ee248b43eee3e1e\">row</a></div><div class=\"ttdeci\">GLenum GLenum GLvoid * row</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/_g_lee_8h_source.html#l00893\">GLee.h:893</a></div></div>\n\
<div class=\"ttc\" id=\"class_q_form_layout_html_a2dc5e1507376ec802dd032e49a62296cab471ddd3f4c08043d2384f5269a59c6f\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_form_layout.html#a2dc5e1507376ec802dd032e49a62296cab471ddd3f4c08043d2384f5269a59c6f\">QFormLayout::FieldsStayAtSizeHint</a></div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qformlayout_8h_source.html#l00069\">qformlayout.h:69</a></div></div>\n\
<div class=\"ttc\" id=\"qglobal_8h_html_ae7344b820974b9f9f7cfedd5808bd3a0\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/qglobal_8h.html#ae7344b820974b9f9f7cfedd5808bd3a0\">QT_BEGIN_NAMESPACE</a></div><div class=\"ttdeci\">#define QT_BEGIN_NAMESPACE</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qglobal_8h_source.html#l00127\">qglobal.h:127</a></div></div>\n\
<div class=\"ttc\" id=\"class_q_layout_item_html\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_layout_item.html\">QLayoutItem</a></div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qlayoutitem_8h_source.html#l00064\">qlayoutitem.h:64</a></div></div>\n\
<div class=\"ttc\" id=\"_g_lee_8h_html_a9274fa62feb8371797c4c0312446e333\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/_g_lee_8h.html#a9274fa62feb8371797c4c0312446e333\">count</a></div><div class=\"ttdeci\">GLuint GLuint GLsizei count</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/_g_lee_8h_source.html#l00872\">GLee.h:872</a></div></div>\n\
<div class=\"ttc\" id=\"qobjectdefs_8h_html_a28faeb36eee7fb0a64b8081fbab41bcd\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/qobjectdefs_8h.html#a28faeb36eee7fb0a64b8081fbab41bcd\">Q_OBJECT</a></div><div class=\"ttdeci\">#define Q_OBJECT</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qobjectdefs_8h_source.html#l00157\">qobjectdefs.h:157</a></div></div>\n\
<div class=\"ttc\" id=\"class_q_rect_html\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_rect.html\">QRect</a></div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qrect_8h_source.html#l00058\">qrect.h:58</a></div></div>\n\
<div class=\"ttc\" id=\"class_q_size_html\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_size.html\">QSize</a></div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qsize_8h_source.html#l00053\">qsize.h:53</a></div></div>\n\
<div class=\"ttc\" id=\"class_q_form_layout_html_a9af2e8781b7f12c2c6c241e05473f669\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_form_layout.html#a9af2e8781b7f12c2c6c241e05473f669\">QFormLayout::ItemRole</a></div><div class=\"ttdeci\">ItemRole</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qformlayout_8h_source.html#l00080\">qformlayout.h:80</a></div></div>\n\
<div class=\"ttc\" id=\"class_q_string_html\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_string.html\">QString</a></div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qstring_8h_source.html#l00083\">qstring.h:83</a></div></div>\n\
<div class=\"ttc\" id=\"class_q_widget_html\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_widget.html\">QWidget</a></div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qwidget_8h_source.html#l00150\">qwidget.h:150</a></div></div>\n\
<div class=\"ttc\" id=\"qglobal_8h_html_ac10725c642e865540e4faaf733ff95ff\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/qglobal_8h.html#ac10725c642e865540e4faaf733ff95ff\">QT_END_HEADER</a></div><div class=\"ttdeci\">#define QT_END_HEADER</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qglobal_8h_source.html#l00142\">qglobal.h:142</a></div></div>\n\
<div class=\"ttc\" id=\"class_q_form_layout_html_ac7b6c0f379c60044f740772a175d03aea97ef8d6f8056b4328236d232ef61133d\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_form_layout.html#ac7b6c0f379c60044f740772a175d03aea97ef8d6f8056b4328236d232ef61133d\">QFormLayout::WrapLongRows</a></div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qformlayout_8h_source.html#l00076\">qformlayout.h:76</a></div></div>\n\
<div class=\"ttc\" id=\"_g_lee_8h_html_a6468fe3bfff24d7d939eb21863b88268\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/_g_lee_8h.html#a6468fe3bfff24d7d939eb21863b88268\">index</a></div><div class=\"ttdeci\">GLuint index</div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/_g_lee_8h_source.html#l01704\">GLee.h:1704</a></div></div>\n\
</div><!-- fragment --></div><!-- contents -->\n\
</div><!-- doc-content -->\n\
          <div class=\"footer-block\"><a href=\"../html/ac.cmtdialog.htm\" class=\"comments-anchor\" target=\"_blank\"><span class=\"comments-link\">Please send us your comment about this page</span></a></div></div>\n\
   </div></body>\n\
</html>\n\
";