var topic = "<!-- saved from url=(0024)http://docs.autodesk.com -->\n\
<html>\n\
   <head><script src=\"../scripts/yepnope.1.5.4-min.js\" type=\"text/javascript\"></script><script src=\"../scripts/lib/jquery-1.11.1.min.js\" type=\"text/javascript\"></script><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"><meta name=\"product\" content=\"MOBPRO\"><meta name=\"release\" content=\"2018\"><meta name=\"book\" content=\"GeneralUser\"><meta name=\"created\" content=\"2017-09-08\"><meta name=\"topicid\" content=\"GUID-02FA7DD3-6C7A-4C6A-B7BC-824765AE1CB2\"><meta name=\"topic-type\" content=\"concept\">\n\
      <title>QtGui/qwidget.h File Reference</title>\n\
   \n\
\n\
</head>\n\
   <body height=\"100%\"><div class=\"body_content\" id=\"body-content\"><link rel=\"stylesheet\" type=\"text/css\" href=\"cpp_ref/navtree.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"cpp_ref/doxygen.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"cpp_ref/tabs.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"style/adsk.cpm.css\"><script language=\"javascript\">var index = \'index.html\';</script><script>$(document).ready(function() { yepnope.injectJs(\"./scripts/ac_common.js\"); });</script><script type=\"text/javascript\">\n\
var tocSystemNeedsToBeLoaded = typeof(cpp_ref_adsk_ref_toc) == \'undefined\';\n\
var weAreIn21 = $(\'div#main.view-active\').length;\n\
var tocPrefix = \'\';\n\
if (weAreIn21)\n\
{ tocPrefix = \'cpp_ref/\'; }\n\
function cpp_ref_initializeToc(forceTrigger) {\n\
    cpp_ref_adsk_ref_toc.initResizable();\n\
    cpp_ref_adsk_ref_toc.initNavTree(\'qwidget_8h.html\', tocPrefix);\n\
    dQuery(document).trigger(\'toc_initialized\');\n\
}\n\
if (tocSystemNeedsToBeLoaded)\n\
{\n\
	yepnope([{\n\
	load:[tocPrefix + \'json3.min.js\', tocPrefix + \'jquery.js\', tocPrefix + \'ref-toc-controller.js\', tocPrefix + \'dynsections.js\'],\n\
	complete: function() {\n\
	  if (typeof(dQuery) == \'undefined\')\n\
	  {\n\
	    dQuery = jQuery.noConflict(true);\n\
	  }\n\
	  else { jQuery.noConflict(true); }\n\
	  $(document).ready(cpp_ref_initializeToc);\n\
	}\n\
 	}])\n\
}\n\
if (!weAreIn21) { // if in AKN...\n\
$(window).load( function() {\n\
    setTimeout( function() {\n\
        var content = $(\'body > div\').not(\'#body-content\');     // take any divs under body that are not id=body-content\n\
        content.each( function() { \n\
            $(this).css( { \'padding-left\': $(this).css(\'margin-left\') } );       // and if they have any padding-left already, move it to margin-left.\n\
        } );\n\
        var width = cpp_ref_adsk_ref_toc.readFromStorage(\'width\');\n\
        content.css({marginLeft:parseInt(width)+6+\"px\"});\n\
    }, 100);\n\
} ); \n\
}\n\
</script><script>$(\"div#WidgetFloaterPanels,link[href*=\'microsofttranslator.com\'],script[src*=\'microsofttranslator.com\'],script[src*=\'bing.com\']\").remove();</script><script type=\'text/javascript\'>$(\"div#navigation,div#breadcrumbs,div#banner\").attr(\"translate\",\"no\"); var mtLocation = ((location && location.href && location.href.indexOf(\'https\') == 0)?\'https://ssl.microsofttranslator.com\':\'http://www.microsofttranslator.com\')+\'/ajax/v3/WidgetV3.ashx?ctf=True&ui=true&settings=Manual&from=en&hidelanguages=\'; yepnope.injectJs(mtLocation, function() {}, { charset:\'utf-8\', type:\'text/javascript\' } );</script><script>\n\
 if (!tocSystemNeedsToBeLoaded) { cpp_ref_initializeToc(); }\n\
 </script><!-- begin MT -->\n\
            \n\
            <div id=\'MicrosoftTranslatorWidget\' class=\'Dark\' style=\'float:right;z-index:100;color:white;background-color:#bbbbbb;height:58px;overflow:hidden\'></div>\n\
      <div>\n\
         <div class=\"head\">\n\
            <h1>QtGui/qwidget.h File Reference</h1>\n\
         </div>\n\
\n\
    <div id=\"top\"><!-- Generated by Doxygen 1.8.10 -->\n\
  <div id=\"navrow1\" class=\"tabs\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./cpp_ref/index.html\"><span>Main&#160;Page</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/pages.html\"><span>Topics</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/modules.html\"><span>Modules</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/namespaces.html\"><span>Namespaces</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/annotated.html\"><span>Classes</span></a></li>\n\
      <li class=\"current\"><a href=\"#!/url=./cpp_ref/files.html\"><span>Files</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/examples.html\"><span>Examples</span></a></li>\n\
    </ul>\n\
  </div>\n\
  <div id=\"navrow2\" class=\"tabs2\">\n\
    <ul class=\"tablist\">\n\
      <li><a href=\"#!/url=./cpp_ref/files.html\"><span>File&#160;List</span></a></li>\n\
      <li><a href=\"#!/url=./cpp_ref/globals.html\"><span>File&#160;Members</span></a></li>\n\
    </ul>\n\
  </div>\n\
</div><!-- top -->\n\
<div id=\"side-nav\" class=\"ui-resizable side-nav-resizable\">\n\
  <div id=\"nav-tree\">\n\
    <div id=\"nav-tree-contents\">\n\
      <div id=\"nav-sync\" class=\"sync\"></div>\n\
    </div>\n\
  </div>\n\
  <div id=\"splitbar\" style=\"-moz-user-select:none;\" class=\"ui-resizable-handle\">\n\
  </div>\n\
</div>\n\
\n\
<div id=\"doc-content\">\n\
<div class=\"header\">\n\
  \n\
  <div class=\"headertitle\">\n\
<div class=\"title\">qwidget.h File Reference</div>  </div>\n\
<div class=\"summary\">\n\
<a href=\"qwidget_8h.html#nested-classes\">Classes</a> &#124;\n\
<a href=\"qwidget_8h.html#define-members\">Macros</a> &#124;\n\
<a href=\"qwidget_8h.html#func-members\">Functions</a>  </div></div><!--header-->\n\
<div class=\"contents\">\n\
<div class=\"textblock\"><code>#include &lt;<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qconfig_8h_source.html\">QtCore/qconfig.h</a>&gt;</code><br>\n\
<code>#include &lt;<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qwindowdefs_8h_source.html\">QtGui/qwindowdefs.h</a>&gt;</code><br>\n\
<code>#include &lt;<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qobject_8h_source.html\">QtCore/qobject.h</a>&gt;</code><br>\n\
<code>#include &lt;<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qmargins_8h_source.html\">QtCore/qmargins.h</a>&gt;</code><br>\n\
<code>#include &lt;<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qpaintdevice_8h_source.html\">QtGui/qpaintdevice.h</a>&gt;</code><br>\n\
<code>#include &lt;<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qpalette_8h_source.html\">QtGui/qpalette.h</a>&gt;</code><br>\n\
<code>#include &lt;<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qfont_8h_source.html\">QtGui/qfont.h</a>&gt;</code><br>\n\
<code>#include &lt;<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qfontmetrics_8h_source.html\">QtGui/qfontmetrics.h</a>&gt;</code><br>\n\
<code>#include &lt;<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qfontinfo_8h_source.html\">QtGui/qfontinfo.h</a>&gt;</code><br>\n\
<code>#include &lt;<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qsizepolicy_8h_source.html\">QtGui/qsizepolicy.h</a>&gt;</code><br>\n\
<code>#include &lt;<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qregion_8h_source.html\">QtGui/qregion.h</a>&gt;</code><br>\n\
<code>#include &lt;<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qbrush_8h_source.html\">QtGui/qbrush.h</a>&gt;</code><br>\n\
<code>#include &lt;<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qcursor_8h_source.html\">QtGui/qcursor.h</a>&gt;</code><br>\n\
<code>#include &lt;<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qkeysequence_8h_source.html\">QtGui/qkeysequence.h</a>&gt;</code><br>\n\
</div><table class=\"memberdecls\">\n\
<tr class=\"heading\"><td colspan=\"2\"><h2 class=\"groupheader\"><a name=\"nested-classes\"></a>\n\
Classes</h2></td></tr>\n\
<tr class=\"memitem:\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">class &#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_widget_data.html\">QWidgetData</a></td></tr>\n\
<tr class=\"separator:\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">class &#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_widget.html\">QWidget</a></td></tr>\n\
<tr class=\"separator:\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
</table><table class=\"memberdecls\">\n\
<tr class=\"heading\"><td colspan=\"2\"><h2 class=\"groupheader\"><a name=\"define-members\"></a>\n\
Macros</h2></td></tr>\n\
<tr class=\"memitem:a0f9f3def9c1847f7e8f5db552d1ddcbd\"><td class=\"memItemLeft\" translate=\"no\" align=\"right\" valign=\"top\">#define&#160;</td><td class=\"memItemRight\" translate=\"no\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qwidget_8h.html#a0f9f3def9c1847f7e8f5db552d1ddcbd\">QWIDGETSIZE_MAX</a>&#160;&#160;&#160;((1&lt;&lt;24)-1)</td></tr>\n\
<tr class=\"separator:a0f9f3def9c1847f7e8f5db552d1ddcbd\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
</table><table class=\"memberdecls\">\n\
<tr class=\"heading\"><td colspan=\"2\"><h2 class=\"groupheader\"><a name=\"func-members\"></a>\n\
Functions</h2></td></tr>\n\
<tr class=\"memitem:a2ecd5248624b8d38debba930e3305c3a\"><td class=\"memTemplParams\" translate=\"no\" colspan=\"2\">template&lt;&gt; </td></tr>\n\
<tr class=\"memitem:a2ecd5248624b8d38debba930e3305c3a\"><td class=\"memTemplItemLeft\" align=\"right\" valign=\"top\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_widget.html\">QWidget</a> *&#160;</td><td class=\"memTemplItemRight\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qwidget_8h.html#a2ecd5248624b8d38debba930e3305c3a\">qobject_cast&lt; QWidget * &gt;</a> (<a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html\">QObject</a> *o)</td></tr>\n\
<tr class=\"separator:a2ecd5248624b8d38debba930e3305c3a\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
<tr class=\"memitem:a53cdca59294eaf2a4907495503299f92\"><td class=\"memTemplParams\" translate=\"no\" colspan=\"2\">template&lt;&gt; </td></tr>\n\
<tr class=\"memitem:a53cdca59294eaf2a4907495503299f92\"><td class=\"memTemplItemLeft\" align=\"right\" valign=\"top\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_widget.html\">QWidget</a> *&#160;</td><td class=\"memTemplItemRight\" valign=\"bottom\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qwidget_8h.html#a53cdca59294eaf2a4907495503299f92\">qobject_cast&lt; const QWidget * &gt;</a> (const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html\">QObject</a> *o)</td></tr>\n\
<tr class=\"separator:a53cdca59294eaf2a4907495503299f92\"><td class=\"memSeparator\" colspan=\"2\">&#160;</td></tr>\n\
</table>\n\
<h2 class=\"groupheader\">Macro Definition Documentation</h2>\n\
<a class=\"anchor\" id=\"a0f9f3def9c1847f7e8f5db552d1ddcbd\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">#define QWIDGETSIZE_MAX&#160;&#160;&#160;((1&lt;&lt;24)-1)</td>\n\
        </tr>\n\
      </table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qwidget_8h_source.html#l01087\">1087</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qwidget_8h_source.html\">qwidget.h</a>.</p>\n\
\n\
</div>\n\
</div>\n\
<h2 class=\"groupheader\">Function Documentation</h2>\n\
<a class=\"anchor\" id=\"a2ecd5248624b8d38debba930e3305c3a\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_widget.html\">QWidget</a>* <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qsharedpointer__impl_8h.html#a3f9c5cc44dc9410d863cdca11f36fdab\">qobject_cast</a>&lt; <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_widget.html\">QWidget</a> * &gt; </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\"><a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html\">QObject</a> *&#160;</td>\n\
          <td class=\"paramname\"><em>o</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">inline</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qwidget_8h_source.html#l00923\">923</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qwidget_8h_source.html\">qwidget.h</a>.</p>\n\
<div class=\"fragment\"><div class=\"line\"><a name=\"l00924\"></a><span class=\"lineno\">  924</span>&#160;{</div>\n\
<div class=\"line\"><a name=\"l00925\"></a><span class=\"lineno\">  925</span>&#160;    <span class=\"keywordflow\">if</span> (!o || !o-&gt;<a class=\"code\" href=\"#!/url=./cpp_ref/class_q_object.html#a09949b14be8b71147a316bf159815b89\">isWidgetType</a>()) <span class=\"keywordflow\">return</span> 0;</div>\n\
<div class=\"line\"><a name=\"l00926\"></a><span class=\"lineno\">  926</span>&#160;    <span class=\"keywordflow\">return</span> <span class=\"keyword\">static_cast&lt;</span><a class=\"code\" href=\"#!/url=./cpp_ref/class_q_widget.html\">QWidget</a>*<span class=\"keyword\">&gt;</span>(o);</div>\n\
<div class=\"line\"><a name=\"l00927\"></a><span class=\"lineno\">  927</span>&#160;}</div>\n\
<div class=\"ttc\" id=\"class_q_object_html_a09949b14be8b71147a316bf159815b89\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_object.html#a09949b14be8b71147a316bf159815b89\">QObject::isWidgetType</a></div><div class=\"ttdeci\">bool isWidgetType() const </div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qobject_8h_source.html#l00146\">qobject.h:146</a></div></div>\n\
<div class=\"ttc\" id=\"class_q_widget_html\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_widget.html\">QWidget</a></div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qwidget_8h_source.html#l00150\">qwidget.h:150</a></div></div>\n\
</div><!-- fragment -->\n\
</div>\n\
</div>\n\
<a class=\"anchor\" id=\"a53cdca59294eaf2a4907495503299f92\"></a>\n\
<div class=\"memitem\">\n\
<div class=\"memproto\">\n\
<table class=\"mlabels\">\n\
  <tr>\n\
  <td class=\"mlabels-left\">\n\
      <table class=\"memname\">\n\
        <tr>\n\
          <td class=\"memname\" translate=\"no\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_widget.html\">QWidget</a>* <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qsharedpointer__impl_8h.html#a3f9c5cc44dc9410d863cdca11f36fdab\">qobject_cast</a>&lt; const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_widget.html\">QWidget</a> * &gt; </td>\n\
          <td>(</td>\n\
          <td class=\"paramtype\">const <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/class_q_object.html\">QObject</a> *&#160;</td>\n\
          <td class=\"paramname\"><em>o</em></td><td>)</td>\n\
          <td></td>\n\
        </tr>\n\
      </table>\n\
  </td>\n\
  <td class=\"mlabels-right\">\n\
<span class=\"mlabels\"><span class=\"mlabel\">inline</span></span>  </td>\n\
  </tr>\n\
</table>\n\
</div><div class=\"memdoc\">\n\
\n\
<p>Definition at line <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qwidget_8h_source.html#l00928\">928</a> of file <a class=\"el\" translate=\"no\" href=\"#!/url=./cpp_ref/qwidget_8h_source.html\">qwidget.h</a>.</p>\n\
<div class=\"fragment\"><div class=\"line\"><a name=\"l00929\"></a><span class=\"lineno\">  929</span>&#160;{</div>\n\
<div class=\"line\"><a name=\"l00930\"></a><span class=\"lineno\">  930</span>&#160;    <span class=\"keywordflow\">if</span> (!o || !o-&gt;<a class=\"code\" href=\"#!/url=./cpp_ref/class_q_object.html#a09949b14be8b71147a316bf159815b89\">isWidgetType</a>()) <span class=\"keywordflow\">return</span> 0;</div>\n\
<div class=\"line\"><a name=\"l00931\"></a><span class=\"lineno\">  931</span>&#160;    <span class=\"keywordflow\">return</span> <span class=\"keyword\">static_cast&lt;</span><span class=\"keyword\">const </span><a class=\"code\" href=\"#!/url=./cpp_ref/class_q_widget.html\">QWidget</a>*<span class=\"keyword\">&gt;</span>(o);</div>\n\
<div class=\"line\"><a name=\"l00932\"></a><span class=\"lineno\">  932</span>&#160;}</div>\n\
<div class=\"ttc\" id=\"class_q_object_html_a09949b14be8b71147a316bf159815b89\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_object.html#a09949b14be8b71147a316bf159815b89\">QObject::isWidgetType</a></div><div class=\"ttdeci\">bool isWidgetType() const </div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qobject_8h_source.html#l00146\">qobject.h:146</a></div></div>\n\
<div class=\"ttc\" id=\"class_q_widget_html\"><div class=\"ttname\"><a href=\"#!/url=./cpp_ref/class_q_widget.html\">QWidget</a></div><div class=\"ttdef\"><b>Definition:</b> <a href=\"#!/url=./cpp_ref/qwidget_8h_source.html#l00150\">qwidget.h:150</a></div></div>\n\
</div><!-- fragment -->\n\
</div>\n\
</div>\n\
\n\
<p><a href=\"#!/url=./cpp_ref/qwidget_8h_source.html\">Go to the source code of this file.</a></p>\n\
</div><!-- contents -->\n\
</div><!-- doc-content -->\n\
          <div class=\"footer-block\"><a href=\"../html/ac.cmtdialog.htm\" class=\"comments-anchor\" target=\"_blank\"><span class=\"comments-link\">Please send us your comment about this page</span></a></div></div>\n\
   </div></body>\n\
</html>\n\
";